// Generated by ZYANG
#ifndef INCLUDED_CCS_DUT_WRAPPER_H
#define INCLUDED_CCS_DUT_WRAPPER_H

#ifndef SC_USE_STD_STRING
#define SC_USE_STD_STRING
#endif

#include <systemc.h>
#include <mc_simulator_extensions.h>

#ifdef CCS_SYSC
namespace HDL {
#endif
#if defined(CCS_DUT_SYSC)
// alias ccs_DUT_wrapper to namespace enclosure of either cycle or RTL SystemC netlist
namespace
    ccs_design {
#if defined(CCS_DUT_CYCLE)
#include "cycle.cxx"
#else
#if defined(CCS_DUT_RTL)
#include "rtl.cxx"
#endif
#endif
}
typedef
    ccs_design::HDL::test ccs_DUT_wrapper;

#else

// Create a foreign module wrapper around the HDL
#ifdef VCS_SYSTEMC
// VCS support - ccs_DUT_wrapper is derived from VCS-generated SystemC wrapper around HDL code
class ccs_DUT_wrapper : public TOP_HDL_ENTITY
{
public:
  ccs_DUT_wrapper(const sc_module_name& nm, const char *hdl_name)
  : TOP_HDL_ENTITY(nm)
  {
  // elaborate_foreign_module(hdl_name);
  }

  ~ccs_DUT_wrapper() {}
};

#else
// non VCS simulators - ccs_DUT_wrapper is derived from mc_foreign_module (adding 2nd ctor arg)
class ccs_DUT_wrapper: public mc_foreign_module
{
public:
  // Interface Ports
  sc_in<bool> clk;
  sc_in<sc_logic> rst;
  sc_in<sc_lv<10> > data_in_rsc_dat;
  sc_in<sc_logic> data_in_rsc_vld;
  sc_out<sc_logic> data_in_rsc_rdy;
  sc_out<sc_lv<5> > coeffs_rsc_0_0_adr;
  sc_out<sc_lv<7> > coeffs_rsc_0_0_d;
  sc_out<sc_logic> coeffs_rsc_0_0_we;
  sc_in<sc_lv<7> > coeffs_rsc_0_0_q;
  sc_out<sc_logic> coeffs_rsc_triosy_0_0_lz;
  sc_out<sc_lv<5> > coeffs_rsc_0_1_adr;
  sc_out<sc_lv<7> > coeffs_rsc_0_1_d;
  sc_out<sc_logic> coeffs_rsc_0_1_we;
  sc_in<sc_lv<7> > coeffs_rsc_0_1_q;
  sc_out<sc_logic> coeffs_rsc_triosy_0_1_lz;
  sc_out<sc_lv<5> > coeffs_rsc_0_2_adr;
  sc_out<sc_lv<7> > coeffs_rsc_0_2_d;
  sc_out<sc_logic> coeffs_rsc_0_2_we;
  sc_in<sc_lv<7> > coeffs_rsc_0_2_q;
  sc_out<sc_logic> coeffs_rsc_triosy_0_2_lz;
  sc_out<sc_lv<5> > coeffs_rsc_0_3_adr;
  sc_out<sc_lv<7> > coeffs_rsc_0_3_d;
  sc_out<sc_logic> coeffs_rsc_0_3_we;
  sc_in<sc_lv<7> > coeffs_rsc_0_3_q;
  sc_out<sc_logic> coeffs_rsc_triosy_0_3_lz;
  sc_in<sc_lv<5> > coeff_addr_rsc_dat;
  sc_in<sc_logic> coeff_addr_rsc_vld;
  sc_out<sc_logic> coeff_addr_rsc_rdy;
  sc_out<sc_lv<19> > result_rsc_dat;
  sc_out<sc_logic> result_rsc_vld;
  sc_in<sc_logic> result_rsc_rdy;
public:
  ccs_DUT_wrapper(const sc_module_name& nm, const char *hdl_name)
  :
    mc_foreign_module(nm, hdl_name), 
    clk("clk"), 
    rst("rst"), 
    data_in_rsc_dat("data_in_rsc_dat"), 
    data_in_rsc_vld("data_in_rsc_vld"), 
    data_in_rsc_rdy("data_in_rsc_rdy"), 
    coeffs_rsc_0_0_adr("coeffs_rsc_0_0_adr"), 
    coeffs_rsc_0_0_d("coeffs_rsc_0_0_d"), 
    coeffs_rsc_0_0_we("coeffs_rsc_0_0_we"), 
    coeffs_rsc_0_0_q("coeffs_rsc_0_0_q"), 
    coeffs_rsc_triosy_0_0_lz("coeffs_rsc_triosy_0_0_lz"), 
    coeffs_rsc_0_1_adr("coeffs_rsc_0_1_adr"), 
    coeffs_rsc_0_1_d("coeffs_rsc_0_1_d"), 
    coeffs_rsc_0_1_we("coeffs_rsc_0_1_we"), 
    coeffs_rsc_0_1_q("coeffs_rsc_0_1_q"), 
    coeffs_rsc_triosy_0_1_lz("coeffs_rsc_triosy_0_1_lz"), 
    coeffs_rsc_0_2_adr("coeffs_rsc_0_2_adr"), 
    coeffs_rsc_0_2_d("coeffs_rsc_0_2_d"), 
    coeffs_rsc_0_2_we("coeffs_rsc_0_2_we"), 
    coeffs_rsc_0_2_q("coeffs_rsc_0_2_q"), 
    coeffs_rsc_triosy_0_2_lz("coeffs_rsc_triosy_0_2_lz"), 
    coeffs_rsc_0_3_adr("coeffs_rsc_0_3_adr"), 
    coeffs_rsc_0_3_d("coeffs_rsc_0_3_d"), 
    coeffs_rsc_0_3_we("coeffs_rsc_0_3_we"), 
    coeffs_rsc_0_3_q("coeffs_rsc_0_3_q"), 
    coeffs_rsc_triosy_0_3_lz("coeffs_rsc_triosy_0_3_lz"), 
    coeff_addr_rsc_dat("coeff_addr_rsc_dat"), 
    coeff_addr_rsc_vld("coeff_addr_rsc_vld"), 
    coeff_addr_rsc_rdy("coeff_addr_rsc_rdy"), 
    result_rsc_dat("result_rsc_dat"), 
    result_rsc_vld("result_rsc_vld"), 
    result_rsc_rdy("result_rsc_rdy")
  {
    elaborate_foreign_module(hdl_name);
  }

  ~ccs_DUT_wrapper() {}
};
#endif

#endif

#ifdef CCS_SYSC
} // end namespace HDL
#endif
#endif


