
//------> /vol/mentor/Catapult_Synthesis_10.4a/Mgc_home/pkgs/siflibs/ccs_in_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module ccs_in_v1 (idat, dat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output [width-1:0] idat;
  input  [width-1:0] dat;

  wire   [width-1:0] idat;

  assign idat = dat;

endmodule


//------> /vol/mentor/Catapult_Synthesis_10.4a/Mgc_home/pkgs/siflibs/ccs_out_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2015 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------

module ccs_out_v1 (dat, idat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output   [width-1:0] dat;
  input    [width-1:0] idat;

  wire     [width-1:0] dat;

  assign dat = idat;

endmodule




//------> /vol/mentor/Catapult_Synthesis_10.4a/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module mgc_io_sync_v2 (ld, lz);
    parameter valid = 0;

    input  ld;
    output lz;

    wire   lz;

    assign lz = ld;

endmodule


//------> ./rtl.v 
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4a/835166 Production Release
//  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
// 
//  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
//  Generated date: Mon Dec  1 01:43:55 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    conv_fixed_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module conv_fixed_core_core_fsm (
  clk, rst, fsm_output, sum_C_0_tr0
);
  input clk;
  input rst;
  output [6:0] fsm_output;
  reg [6:0] fsm_output;
  input sum_C_0_tr0;


  // FSM State Type Declaration for conv_fixed_core_core_fsm_1
  parameter
    main_C_0 = 3'd0,
    sum_C_0 = 3'd1,
    main_C_1 = 3'd2,
    main_C_2 = 3'd3,
    main_C_3 = 3'd4,
    main_C_4 = 3'd5,
    main_C_5 = 3'd6;

  reg [2:0] state_var;
  reg [2:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : conv_fixed_core_core_fsm_1
    case (state_var)
      sum_C_0 : begin
        fsm_output = 7'b0000010;
        if ( sum_C_0_tr0 ) begin
          state_var_NS = main_C_1;
        end
        else begin
          state_var_NS = sum_C_0;
        end
      end
      main_C_1 : begin
        fsm_output = 7'b0000100;
        state_var_NS = main_C_2;
      end
      main_C_2 : begin
        fsm_output = 7'b0001000;
        state_var_NS = main_C_3;
      end
      main_C_3 : begin
        fsm_output = 7'b0010000;
        state_var_NS = main_C_4;
      end
      main_C_4 : begin
        fsm_output = 7'b0100000;
        state_var_NS = main_C_5;
      end
      main_C_5 : begin
        fsm_output = 7'b1000000;
        state_var_NS = main_C_0;
      end
      // main_C_0
      default : begin
        fsm_output = 7'b0000001;
        state_var_NS = sum_C_0;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( rst ) begin
      state_var <= main_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    conv_fixed_core
// ------------------------------------------------------------------


module conv_fixed_core (
  clk, rst, input_rsc_dat, input_rsc_triosy_lz, output_rsc_dat, output_rsc_triosy_lz,
      filter_rsc_dat, filter_rsc_triosy_lz
);
  input clk;
  input rst;
  input [143:0] input_rsc_dat;
  output input_rsc_triosy_lz;
  output [15:0] output_rsc_dat;
  output output_rsc_triosy_lz;
  input [143:0] filter_rsc_dat;
  output filter_rsc_triosy_lz;


  // Interconnect Declarations
  wire [143:0] input_rsci_idat;
  reg [15:0] output_rsci_idat;
  wire [143:0] filter_rsci_idat;
  reg output_rsc_triosy_obj_ld;
  wire [6:0] fsm_output;
  wire [3:0] sum_acc_tmp;
  wire [4:0] nl_sum_acc_tmp;
  wire or_dcpl;
  wire or_dcpl_1;
  wire or_dcpl_3;
  wire or_dcpl_4;
  wire or_dcpl_6;
  wire or_dcpl_8;
  wire or_dcpl_16;
  wire or_dcpl_17;
  wire or_dcpl_19;
  wire or_dcpl_21;
  wire or_dcpl_22;
  wire or_dcpl_24;
  reg [3:0] sum_i_3_0_sva;
  reg reg_filter_rsc_triosy_obj_ld_cse;
  wire and_2_cse;
  wire [15:0] z_out;
  wire [16:0] nl_z_out;
  wire [15:0] z_out_1;
  wire [16:0] nl_z_out_1;
  reg [15:0] temp_4_sva_1;
  reg [15:0] temp_3_sva_1;
  reg [15:0] temp_5_sva_1;
  reg [15:0] temp_2_sva_1;
  reg [15:0] temp_6_sva_1;
  reg [15:0] temp_1_sva_1;
  reg [15:0] temp_7_sva_1;
  reg [15:0] temp_0_sva_1;
  reg [15:0] acc_8_itm;
  reg [15:0] acc_11_itm;
  reg [15:0] acc_10_itm;
  reg [15:0] acc_13_itm;
  wire [15:0] sum_mul_itm_23_8;

  wire[15:0] acc_10_nl;
  wire[16:0] nl_acc_10_nl;
  wire[15:0] acc_9_nl;
  wire[16:0] nl_acc_9_nl;
  wire[23:0] sum_mul_nl;
  wire signed [31:0] nl_sum_mul_nl;
  wire[15:0] sum_mux_9_nl;
  wire[15:0] sum_mux_10_nl;
  wire[15:0] mux_8_nl;
  wire[15:0] mux_9_nl;
  wire[15:0] mux_10_nl;
  wire[15:0] mux_11_nl;
  wire[0:0] or_60_nl;

  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd144)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd16)) output_rsci (
      .idat(output_rsci_idat),
      .dat(output_rsc_dat)
    );
  ccs_in_v1 #(.rscid(32'sd3),
  .width(32'sd144)) filter_rsci (
      .dat(filter_rsc_dat),
      .idat(filter_rsci_idat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_rsc_triosy_obj (
      .ld(reg_filter_rsc_triosy_obj_ld_cse),
      .lz(input_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) output_rsc_triosy_obj (
      .ld(output_rsc_triosy_obj_ld),
      .lz(output_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) filter_rsc_triosy_obj (
      .ld(reg_filter_rsc_triosy_obj_ld_cse),
      .lz(filter_rsc_triosy_lz)
    );
  conv_fixed_core_core_fsm conv_fixed_core_core_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output),
      .sum_C_0_tr0(and_2_cse)
    );
  assign and_2_cse = (sum_acc_tmp==4'b1001);
  assign nl_sum_acc_tmp = sum_i_3_0_sva + 4'b0001;
  assign sum_acc_tmp = nl_sum_acc_tmp[3:0];
  assign sum_mux_9_nl = MUX_v_16_9_2((filter_rsci_idat[15:0]), (filter_rsci_idat[31:16]),
      (filter_rsci_idat[47:32]), (filter_rsci_idat[63:48]), (filter_rsci_idat[79:64]),
      (filter_rsci_idat[95:80]), (filter_rsci_idat[111:96]), (filter_rsci_idat[127:112]),
      (filter_rsci_idat[143:128]), sum_i_3_0_sva);
  assign sum_mux_10_nl = MUX_v_16_9_2((input_rsci_idat[15:0]), (input_rsci_idat[31:16]),
      (input_rsci_idat[47:32]), (input_rsci_idat[63:48]), (input_rsci_idat[79:64]),
      (input_rsci_idat[95:80]), (input_rsci_idat[111:96]), (input_rsci_idat[127:112]),
      (input_rsci_idat[143:128]), sum_i_3_0_sva);
  assign nl_sum_mul_nl = $signed((sum_mux_9_nl)) * $signed((sum_mux_10_nl));
  assign sum_mul_nl = nl_sum_mul_nl[23:0];
  assign sum_mul_itm_23_8 = readslicef_24_16_8((sum_mul_nl));
  assign or_dcpl = (sum_acc_tmp[1:0]!=2'b00);
  assign or_dcpl_1 = (sum_acc_tmp[3:2]!=2'b00);
  assign or_dcpl_3 = (sum_acc_tmp[1:0]!=2'b01);
  assign or_dcpl_4 = (sum_acc_tmp[3:2]!=2'b01);
  assign or_dcpl_6 = (sum_acc_tmp[1:0]!=2'b10);
  assign or_dcpl_8 = ~((sum_acc_tmp[1:0]==2'b11));
  assign or_dcpl_16 = (sum_i_3_0_sva[0]) | (sum_i_3_0_sva[2]);
  assign or_dcpl_17 = (sum_i_3_0_sva[1]) | (sum_i_3_0_sva[3]);
  assign or_dcpl_19 = ~((sum_i_3_0_sva[0]) & (sum_i_3_0_sva[2]));
  assign or_dcpl_21 = (sum_i_3_0_sva[0]) | (~ (sum_i_3_0_sva[2]));
  assign or_dcpl_22 = (~ (sum_i_3_0_sva[1])) | (sum_i_3_0_sva[3]);
  assign or_dcpl_24 = (~ (sum_i_3_0_sva[0])) | (sum_i_3_0_sva[2]);
  always @(posedge clk) begin
    if ( rst ) begin
      output_rsci_idat <= 16'b0000000000000000;
    end
    else if ( fsm_output[5] ) begin
      output_rsci_idat <= z_out_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_0_sva_1 <= 16'b0000000000000000;
    end
    else if ( (fsm_output[1]) & (or_dcpl_1 | or_dcpl) & (~(or_dcpl_17 | or_dcpl_16))
        ) begin
      temp_0_sva_1 <= sum_mul_itm_23_8;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_5_sva_1 <= 16'b0000000000000000;
    end
    else if ( (fsm_output[1]) & (or_dcpl_4 | or_dcpl_3) & (~(or_dcpl_17 | or_dcpl_19))
        ) begin
      temp_5_sva_1 <= sum_mul_itm_23_8;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_6_sva_1 <= 16'b0000000000000000;
    end
    else if ( (fsm_output[1]) & (or_dcpl_4 | or_dcpl_6) & (~(or_dcpl_22 | or_dcpl_21))
        ) begin
      temp_6_sva_1 <= sum_mul_itm_23_8;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_3_sva_1 <= 16'b0000000000000000;
    end
    else if ( (fsm_output[1]) & (or_dcpl_1 | or_dcpl_8) & (~(or_dcpl_22 | or_dcpl_24))
        ) begin
      temp_3_sva_1 <= sum_mul_itm_23_8;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_4_sva_1 <= 16'b0000000000000000;
    end
    else if ( (fsm_output[1]) & (or_dcpl_4 | or_dcpl) & (~(or_dcpl_17 | or_dcpl_21))
        ) begin
      temp_4_sva_1 <= sum_mul_itm_23_8;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_1_sva_1 <= 16'b0000000000000000;
    end
    else if ( (fsm_output[1]) & (or_dcpl_1 | or_dcpl_3) & (~(or_dcpl_17 | or_dcpl_24))
        ) begin
      temp_1_sva_1 <= sum_mul_itm_23_8;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_2_sva_1 <= 16'b0000000000000000;
    end
    else if ( (fsm_output[1]) & (or_dcpl_1 | or_dcpl_6) & (~(or_dcpl_22 | or_dcpl_16))
        ) begin
      temp_2_sva_1 <= sum_mul_itm_23_8;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_7_sva_1 <= 16'b0000000000000000;
    end
    else if ( (fsm_output[1]) & (or_dcpl_4 | or_dcpl_8) & (~(or_dcpl_22 | or_dcpl_19))
        ) begin
      temp_7_sva_1 <= sum_mul_itm_23_8;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      sum_i_3_0_sva <= 4'b0000;
      reg_filter_rsc_triosy_obj_ld_cse <= 1'b0;
      output_rsc_triosy_obj_ld <= 1'b0;
      acc_10_itm <= 16'b0000000000000000;
      acc_8_itm <= 16'b0000000000000000;
    end
    else begin
      sum_i_3_0_sva <= MUX_v_4_2_2(4'b0000, sum_acc_tmp, (fsm_output[1]));
      reg_filter_rsc_triosy_obj_ld_cse <= and_2_cse & (fsm_output[1]);
      output_rsc_triosy_obj_ld <= fsm_output[5];
      acc_10_itm <= MUX1HOT_v_16_3_2((acc_10_nl), z_out, z_out_1, {(fsm_output[2])
          , (fsm_output[3]) , (fsm_output[4])});
      acc_8_itm <= z_out_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      acc_11_itm <= 16'b0000000000000000;
    end
    else if ( (fsm_output[2:1]!=2'b00) ) begin
      acc_11_itm <= MUX_v_16_2_2(sum_mul_itm_23_8, z_out, fsm_output[2]);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      acc_13_itm <= 16'b0000000000000000;
    end
    else if ( (fsm_output[3:2]!=2'b00) ) begin
      acc_13_itm <= MUX_v_16_2_2((acc_9_nl), z_out_1, fsm_output[3]);
    end
  end
  assign nl_acc_10_nl = temp_3_sva_1 + temp_4_sva_1;
  assign acc_10_nl = nl_acc_10_nl[15:0];
  assign nl_acc_9_nl = temp_5_sva_1 + temp_6_sva_1;
  assign acc_9_nl = nl_acc_9_nl[15:0];
  assign mux_8_nl = MUX_v_16_2_2(temp_1_sva_1, acc_8_itm, fsm_output[3]);
  assign mux_9_nl = MUX_v_16_2_2(temp_2_sva_1, temp_0_sva_1, fsm_output[3]);
  assign nl_z_out = (mux_8_nl) + (mux_9_nl);
  assign z_out = nl_z_out[15:0];
  assign mux_10_nl = MUX_v_16_2_2(acc_10_itm, temp_7_sva_1, fsm_output[2]);
  assign or_60_nl = (fsm_output[3]) | (fsm_output[5]);
  assign mux_11_nl = MUX_v_16_2_2(acc_11_itm, acc_13_itm, or_60_nl);
  assign nl_z_out_1 = (mux_10_nl) + (mux_11_nl);
  assign z_out_1 = nl_z_out_1[15:0];

  function automatic [15:0] MUX1HOT_v_16_3_2;
    input [15:0] input_2;
    input [15:0] input_1;
    input [15:0] input_0;
    input [2:0] sel;
    reg [15:0] result;
  begin
    result = input_0 & {16{sel[0]}};
    result = result | ( input_1 & {16{sel[1]}});
    result = result | ( input_2 & {16{sel[2]}});
    MUX1HOT_v_16_3_2 = result;
  end
  endfunction


  function automatic [15:0] MUX_v_16_2_2;
    input [15:0] input_0;
    input [15:0] input_1;
    input [0:0] sel;
    reg [15:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_16_2_2 = result;
  end
  endfunction


  function automatic [15:0] MUX_v_16_9_2;
    input [15:0] input_0;
    input [15:0] input_1;
    input [15:0] input_2;
    input [15:0] input_3;
    input [15:0] input_4;
    input [15:0] input_5;
    input [15:0] input_6;
    input [15:0] input_7;
    input [15:0] input_8;
    input [3:0] sel;
    reg [15:0] result;
  begin
    case (sel)
      4'b0000 : begin
        result = input_0;
      end
      4'b0001 : begin
        result = input_1;
      end
      4'b0010 : begin
        result = input_2;
      end
      4'b0011 : begin
        result = input_3;
      end
      4'b0100 : begin
        result = input_4;
      end
      4'b0101 : begin
        result = input_5;
      end
      4'b0110 : begin
        result = input_6;
      end
      4'b0111 : begin
        result = input_7;
      end
      default : begin
        result = input_8;
      end
    endcase
    MUX_v_16_9_2 = result;
  end
  endfunction


  function automatic [3:0] MUX_v_4_2_2;
    input [3:0] input_0;
    input [3:0] input_1;
    input [0:0] sel;
    reg [3:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_4_2_2 = result;
  end
  endfunction


  function automatic [15:0] readslicef_24_16_8;
    input [23:0] vector;
    reg [23:0] tmp;
  begin
    tmp = vector >> 8;
    readslicef_24_16_8 = tmp[15:0];
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    conv_fixed
// ------------------------------------------------------------------


module conv_fixed (
  clk, rst, input_rsc_dat, input_rsc_triosy_lz, output_rsc_dat, output_rsc_triosy_lz,
      filter_rsc_dat, filter_rsc_triosy_lz
);
  input clk;
  input rst;
  input [143:0] input_rsc_dat;
  output input_rsc_triosy_lz;
  output [15:0] output_rsc_dat;
  output output_rsc_triosy_lz;
  input [143:0] filter_rsc_dat;
  output filter_rsc_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  conv_fixed_core conv_fixed_core_inst (
      .clk(clk),
      .rst(rst),
      .input_rsc_dat(input_rsc_dat),
      .input_rsc_triosy_lz(input_rsc_triosy_lz),
      .output_rsc_dat(output_rsc_dat),
      .output_rsc_triosy_lz(output_rsc_triosy_lz),
      .filter_rsc_dat(filter_rsc_dat),
      .filter_rsc_triosy_lz(filter_rsc_triosy_lz)
    );
endmodule



