
--------> /vol/mentor/Catapult_Synthesis_10.4a/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.vhd 
--------------------------------------------------------------------------------
-- Catapult Synthesis - Sample I/O Port Library
--
-- Copyright (c) 2003-2017 Mentor Graphics Corp.
--       All Rights Reserved
--
-- This document may be used and distributed without restriction provided that
-- this copyright statement is not removed from the file and that any derivative
-- work contains this copyright notice.
--
-- The design information contained in this file is intended to be an example
-- of the functionality which the end user may study in preparation for creating
-- their own custom interfaces. This design does not necessarily present a 
-- complete implementation of the named protocol or standard.
--
--------------------------------------------------------------------------------

LIBRARY ieee;

USE ieee.std_logic_1164.all;
PACKAGE mgc_io_sync_pkg_v2 IS

COMPONENT mgc_io_sync_v2
  GENERIC (
    valid    : INTEGER RANGE 0 TO 1
  );
  PORT (
    ld       : IN    std_logic;
    lz       : OUT   std_logic
  );
END COMPONENT;

END mgc_io_sync_pkg_v2;

LIBRARY ieee;

USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all; -- Prevent STARC 2.1.1.2 violation

ENTITY mgc_io_sync_v2 IS
  GENERIC (
    valid    : INTEGER RANGE 0 TO 1
  );
  PORT (
    ld       : IN    std_logic;
    lz       : OUT   std_logic
  );
END mgc_io_sync_v2;

ARCHITECTURE beh OF mgc_io_sync_v2 IS
BEGIN

  lz <= ld;

END beh;


--------> ./rtl.vhdl 
-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    10.4a/835166 Production Release
--  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
-- 
--  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
--  Generated date: Tue Dec  2 09:18:12 2025
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen;

ARCHITECTURE v3 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v3;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen;

ARCHITECTURE v3 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v3;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen;

ARCHITECTURE v3 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v3;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_core_core_fsm
--  FSM Module
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_core_core_fsm IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    fsm_output : OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
  );
END matrix_mul_core_core_fsm;

ARCHITECTURE v3 OF matrix_mul_core_core_fsm IS
  -- Default Constants

  -- FSM State Type Declaration for matrix_mul_core_core_fsm_1
  TYPE matrix_mul_core_core_fsm_1_ST IS (core_rlp_C_0, main_C_0);

  SIGNAL state_var : matrix_mul_core_core_fsm_1_ST;
  SIGNAL state_var_NS : matrix_mul_core_core_fsm_1_ST;

BEGIN
  matrix_mul_core_core_fsm_1 : PROCESS (state_var)
  BEGIN
    CASE state_var IS
      WHEN main_C_0 =>
        fsm_output <= STD_LOGIC_VECTOR'( "10");
        state_var_NS <= main_C_0;
      -- core_rlp_C_0
      WHEN OTHERS =>
        fsm_output <= STD_LOGIC_VECTOR'( "01");
        state_var_NS <= main_C_0;
    END CASE;
  END PROCESS matrix_mul_core_core_fsm_1;

  matrix_mul_core_core_fsm_1_REG : PROCESS (clk)
  BEGIN
    IF clk'event AND ( clk = '1' ) THEN
      IF ( rst = '1' ) THEN
        state_var <= core_rlp_C_0;
      ELSE
        state_var <= state_var_NS;
      END IF;
    END IF;
  END PROCESS matrix_mul_core_core_fsm_1_REG;

END v3;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_core
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_triosy_lz : OUT STD_LOGIC;
    B_rsc_triosy_lz : OUT STD_LOGIC;
    C_rsc_triosy_lz : OUT STD_LOGIC;
    A_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    A_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    B_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    C_rsci_d_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff : OUT STD_LOGIC;
    C_rsci_we_d_pff : OUT STD_LOGIC
  );
END matrix_mul_core;

ARCHITECTURE v3 OF matrix_mul_core IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL C_rsc_triosy_obj_ld : STD_LOGIC;
  SIGNAL fsm_output : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL main_1_for_acc_1_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL main_1_for_for_acc_2_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL main_1_for_for_for_acc_4_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL main_2_for_acc_1_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL main_2_for_for_acc_2_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL main_2_for_for_for_acc_4_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL or_tmp : STD_LOGIC;
  SIGNAL or_tmp_1 : STD_LOGIC;
  SIGNAL mux_tmp : STD_LOGIC;
  SIGNAL or_tmp_2 : STD_LOGIC;
  SIGNAL and_tmp : STD_LOGIC;
  SIGNAL mux_tmp_1 : STD_LOGIC;
  SIGNAL not_tmp_4 : STD_LOGIC;
  SIGNAL or_dcpl_4 : STD_LOGIC;
  SIGNAL and_dcpl_8 : STD_LOGIC;
  SIGNAL exit_main_1_for_for_lpi_1_dfm_3 : STD_LOGIC;
  SIGNAL lfst_exit_main_1_for_for_1_lpi_1 : STD_LOGIC;
  SIGNAL for_unequal_tmp_1 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_lpi_1_dfm_1_1 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_lpi_1_dfm_0_1 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_lpi_1_dfm_3_1 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_lpi_1_dfm_3_0 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_for_1_lpi_1 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_lpi_1_dfm_3_1_mx0w0 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_lpi_1_dfm_3_0_mx0w0 : STD_LOGIC;
  SIGNAL exit_main_2_for_lpi_1_dfm_1_mx0w1 : STD_LOGIC;
  SIGNAL for_equal_tmp_4 : STD_LOGIC;
  SIGNAL for_and_ssc_1 : STD_LOGIC;
  SIGNAL for_and_1_ssc_1 : STD_LOGIC;
  SIGNAL for_equal_tmp_3 : STD_LOGIC;
  SIGNAL exit_main_1_for_lpi_1_dfm_2_mx0w0 : STD_LOGIC;
  SIGNAL for_or_tmp_1 : STD_LOGIC;
  SIGNAL for_equal_tmp_1_1 : STD_LOGIC;
  SIGNAL for_equal_tmp_2_1 : STD_LOGIC;
  SIGNAL exitL_exit_main_2_for_sva : STD_LOGIC;
  SIGNAL main_stage_0_2 : STD_LOGIC;
  SIGNAL exit_main_1_for_lpi_1_dfm_2_st_1 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_lpi_1_dfm_st_1_0 : STD_LOGIC;
  SIGNAL lfst_exit_main_2_for_lpi_1_dfm_st_1_1 : STD_LOGIC;
  SIGNAL main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 : STD_LOGIC;
  SIGNAL nand_2_tmp : STD_LOGIC;
  SIGNAL reg_B_rsc_triosy_obj_ld_cse : STD_LOGIC;
  SIGNAL for_for_j_and_2_cse : STD_LOGIC;
  SIGNAL for_for_j_mux_cse : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_i_mux_cse : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL and_2_cse : STD_LOGIC;
  SIGNAL B_mux_rmff : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL main_1_for_i_slc_for_i_5_0_4_0_1_itm_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL main_1_for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 : STD_LOGIC_VECTOR (4 DOWNTO
      0);
  SIGNAL for_for_sum_1_sva_2 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_for_j_slc_for_for_j_5_0_1_5_2_itm_1 : STD_LOGIC;
  SIGNAL mux_21_tmp : STD_LOGIC;
  SIGNAL lfst_exit_main_1_for_for_1_lpi_1_dfm_1 : STD_LOGIC;
  SIGNAL for_for_for_for_and_4_itm_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_i_5_0_1_lpi_1_4_0 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_j_5_0_1_lpi_1_4_0 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_for_k_5_0_1_lpi_1_4_0 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_i_5_0_1_lpi_1_dfm_4_0_mx0w0 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_for_acc_7_psp_1_sva_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_for_for_mul_sdt_1_sva_1 : STD_LOGIC_VECTOR (45 DOWNTO 0);
  SIGNAL for_for_for_k_5_0_1_lpi_1_dfm_4_0_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_for_k_5_0_lpi_1_dfm_4_0_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL or_tmp_20 : STD_LOGIC;
  SIGNAL and_38_cse : STD_LOGIC;
  SIGNAL and_37_cse : STD_LOGIC;
  SIGNAL nand_1_cse : STD_LOGIC;
  SIGNAL mux_tmp_24 : STD_LOGIC;

  SIGNAL mux_16_nl : STD_LOGIC;
  SIGNAL and_6_nl : STD_LOGIC;
  SIGNAL mux_15_nl : STD_LOGIC;
  SIGNAL nor_6_nl : STD_LOGIC;
  SIGNAL mux_14_nl : STD_LOGIC;
  SIGNAL mux_13_nl : STD_LOGIC;
  SIGNAL nor_7_nl : STD_LOGIC;
  SIGNAL and_28_nl : STD_LOGIC;
  SIGNAL mux_31_nl : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL and_32_nl : STD_LOGIC;
  SIGNAL mux_20_nl : STD_LOGIC;
  SIGNAL nor_14_nl : STD_LOGIC;
  SIGNAL nor_15_nl : STD_LOGIC;
  SIGNAL and_33_nl : STD_LOGIC;
  SIGNAL mux_23_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL and_35_nl : STD_LOGIC;
  SIGNAL not_64_nl : STD_LOGIC;
  SIGNAL for_for_j_and_nl : STD_LOGIC;
  SIGNAL for_for_j_and_1_nl : STD_LOGIC;
  SIGNAL for_and_16_nl : STD_LOGIC;
  SIGNAL for_for_j_and_4_nl : STD_LOGIC;
  SIGNAL mux_28_nl : STD_LOGIC;
  SIGNAL mux_27_nl : STD_LOGIC;
  SIGNAL mux_26_nl : STD_LOGIC;
  SIGNAL mux_25_nl : STD_LOGIC;
  SIGNAL and_39_nl : STD_LOGIC;
  SIGNAL for_for_and_9_nl : STD_LOGIC;
  SIGNAL for_and_3_nl : STD_LOGIC;
  SIGNAL mux_30_nl : STD_LOGIC;
  SIGNAL or_32_nl : STD_LOGIC;
  SIGNAL mux_29_nl : STD_LOGIC;
  SIGNAL or_31_nl : STD_LOGIC;
  SIGNAL mux_11_nl : STD_LOGIC;
  SIGNAL nor_2_nl : STD_LOGIC;
  SIGNAL nor_8_nl : STD_LOGIC;
  SIGNAL for_not_27_nl : STD_LOGIC;
  SIGNAL for_mux_13_nl : STD_LOGIC;
  SIGNAL main_1_for_for_for_and_1_nl : STD_LOGIC;
  SIGNAL or_25_nl : STD_LOGIC;
  SIGNAL mux_9_nl : STD_LOGIC;
  SIGNAL mux_8_nl : STD_LOGIC;
  SIGNAL nor_10_nl : STD_LOGIC;
  SIGNAL and_42_nl : STD_LOGIC;
  SIGNAL and_41_nl : STD_LOGIC;
  COMPONENT matrix_mul_core_core_fsm
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      fsm_output : OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL matrix_mul_core_core_fsm_inst_fsm_output : STD_LOGIC_VECTOR (1 DOWNTO 0);

  FUNCTION CONV_SL_1_1(input:BOOLEAN)
  RETURN STD_LOGIC IS
  BEGIN
    IF input THEN RETURN '1';ELSE RETURN '0';END IF;
  END;

  FUNCTION MUX1HOT_v_5_4_2(input_3 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_2 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC_VECTOR(3 DOWNTO 0))
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);
    VARIABLE tmp : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      tmp := (OTHERS=>sel(0));
      result := input_0 and tmp;
      tmp := (OTHERS=>sel( 1));
      result := result or ( input_1 and tmp);
      tmp := (OTHERS=>sel( 2));
      result := result or ( input_2 and tmp);
      tmp := (OTHERS=>sel( 3));
      result := result or ( input_3 and tmp);
    RETURN result;
  END;

  FUNCTION MUX1HOT_v_5_6_2(input_5 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_4 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_3 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_2 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC_VECTOR(5 DOWNTO 0))
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);
    VARIABLE tmp : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      tmp := (OTHERS=>sel(0));
      result := input_0 and tmp;
      tmp := (OTHERS=>sel( 1));
      result := result or ( input_1 and tmp);
      tmp := (OTHERS=>sel( 2));
      result := result or ( input_2 and tmp);
      tmp := (OTHERS=>sel( 3));
      result := result or ( input_3 and tmp);
      tmp := (OTHERS=>sel( 4));
      result := result or ( input_4 and tmp);
      tmp := (OTHERS=>sel( 5));
      result := result or ( input_5 and tmp);
    RETURN result;
  END;

  FUNCTION MUX_s_1_2_2(input_0 : STD_LOGIC;
  input_1 : STD_LOGIC;
  sel : STD_LOGIC)
  RETURN STD_LOGIC IS
    VARIABLE result : STD_LOGIC;

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

  FUNCTION MUX_v_32_2_2(input_0 : STD_LOGIC_VECTOR(31 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(31 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(31 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

  FUNCTION MUX_v_5_2_2(input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

BEGIN
  A_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_B_rsc_triosy_obj_ld_cse,
      lz => A_rsc_triosy_lz
    );
  B_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_B_rsc_triosy_obj_ld_cse,
      lz => B_rsc_triosy_lz
    );
  C_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => C_rsc_triosy_obj_ld,
      lz => C_rsc_triosy_lz
    );
  matrix_mul_core_core_fsm_inst : matrix_mul_core_core_fsm
    PORT MAP(
      clk => clk,
      rst => rst,
      fsm_output => matrix_mul_core_core_fsm_inst_fsm_output
    );
  fsm_output <= matrix_mul_core_core_fsm_inst_fsm_output;

  for_i_mux_cse <= MUX_v_5_2_2(for_i_5_0_1_lpi_1_dfm_4_0_mx0w0, for_i_5_0_1_lpi_1_4_0,
      lfst_exit_main_2_for_lpi_1_dfm_1_1);
  for_for_j_mux_cse <= MUX_v_5_2_2(for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0, for_for_j_5_0_1_lpi_1_4_0,
      lfst_exit_main_2_for_lpi_1_dfm_1_1);
  and_33_nl <= (main_2_for_for_for_acc_4_tmp(5)) AND for_equal_tmp_3;
  mux_21_tmp <= MUX_s_1_2_2((main_1_for_for_for_acc_4_tmp(5)), and_33_nl, lfst_exit_main_2_for_lpi_1_dfm_1_1);
  for_for_j_and_2_cse <= for_or_tmp_1 AND (((main_1_for_for_for_acc_4_tmp(5)) AND
      (main_1_for_for_acc_2_tmp(5)) AND (main_1_for_acc_1_tmp(5))) OR lfst_exit_main_2_for_lpi_1_dfm_1_1);
  and_38_cse <= (main_2_for_for_acc_2_tmp(5)) AND (main_2_for_acc_1_tmp(5));
  and_37_cse <= (main_2_for_for_for_acc_4_tmp(5)) AND (main_2_for_for_acc_2_tmp(5));
  nand_1_cse <= NOT((main_1_for_for_for_acc_4_tmp(5)) AND (main_1_for_for_acc_2_tmp(5)));
  and_2_cse <= or_tmp_2 AND nand_1_cse;
  for_not_27_nl <= NOT exitL_exit_main_2_for_sva;
  for_i_5_0_1_lpi_1_dfm_4_0_mx0w0 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), for_i_5_0_1_lpi_1_4_0,
      for_not_27_nl);
  for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"),
      for_for_j_5_0_1_lpi_1_4_0, for_unequal_tmp_1);
  exit_main_1_for_lpi_1_dfm_2_mx0w0 <= (main_1_for_acc_1_tmp(5)) AND exit_main_1_for_for_lpi_1_dfm_3;
  exit_main_2_for_lpi_1_dfm_1_mx0w1 <= (main_2_for_acc_1_tmp(5)) AND and_37_cse;
  lfst_exit_main_2_for_lpi_1_dfm_1_1 <= lfst_exit_main_2_for_lpi_1_dfm_3_1 AND (NOT
      exitL_exit_main_2_for_sva);
  lfst_exit_main_2_for_lpi_1_dfm_0_1 <= lfst_exit_main_2_for_lpi_1_dfm_3_0 AND (NOT
      exitL_exit_main_2_for_sva);
  for_mux_13_nl <= MUX_s_1_2_2((NOT exit_main_2_for_lpi_1_dfm_1_mx0w1), lfst_exit_main_2_for_lpi_1_dfm_1_1,
      for_equal_tmp_4);
  lfst_exit_main_2_for_lpi_1_dfm_3_1_mx0w0 <= (for_mux_13_nl AND (NOT for_and_ssc_1))
      OR for_and_1_ssc_1;
  lfst_exit_main_2_for_lpi_1_dfm_3_0_mx0w0 <= (lfst_exit_main_2_for_lpi_1_dfm_0_1
      AND (NOT(for_and_1_ssc_1 OR for_equal_tmp_3))) OR for_and_ssc_1;
  main_1_for_for_for_and_1_nl <= (for_for_for_mul_sdt_1_sva_1(13)) AND (CONV_SL_1_1(for_for_for_mul_sdt_1_sva_1(12
      DOWNTO 0)/=STD_LOGIC_VECTOR'("0000000000000")) OR (for_for_for_acc_7_psp_1_sva_1(0)));
  for_for_sum_1_sva_2 <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(for_for_for_acc_7_psp_1_sva_1)
      + CONV_SIGNED(CONV_UNSIGNED(main_1_for_for_for_and_1_nl, 1), 32), 32));
  for_equal_tmp_3 <= lfst_exit_main_2_for_lpi_1_dfm_1_1 AND (NOT lfst_exit_main_2_for_lpi_1_dfm_0_1);
  for_equal_tmp_4 <= lfst_exit_main_2_for_lpi_1_dfm_1_1 AND lfst_exit_main_2_for_lpi_1_dfm_0_1;
  for_for_for_acc_7_psp_1_sva_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(for_for_for_for_and_4_itm_1)
      + UNSIGNED(for_for_for_mul_sdt_1_sva_1(45 DOWNTO 14)), 32));
  for_for_for_mul_sdt_1_sva_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(SIGNED'( SIGNED(A_rsci_q_d)
      * SIGNED(B_rsci_q_d)), 46));
  main_1_for_acc_1_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_i_5_0_1_lpi_1_dfm_4_0_mx0w0),
      5), 6) + SIGNED'( "000001"), 6));
  main_1_for_for_acc_2_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0),
      5), 6) + SIGNED'( "000001"), 6));
  exit_main_1_for_for_lpi_1_dfm_3 <= (main_1_for_for_acc_2_tmp(5)) AND (main_1_for_for_for_acc_4_tmp(5));
  main_1_for_for_for_acc_4_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_for_for_k_5_0_1_lpi_1_dfm_4_0_1),
      5), 6) + SIGNED'( "000001"), 6));
  for_for_for_k_5_0_1_lpi_1_dfm_4_0_1 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"),
      for_for_for_k_5_0_1_lpi_1_4_0, lfst_exit_main_1_for_for_1_lpi_1_dfm_1);
  lfst_exit_main_1_for_for_1_lpi_1_dfm_1 <= lfst_exit_main_1_for_for_1_lpi_1 AND
      for_unequal_tmp_1;
  for_unequal_tmp_1 <= lfst_exit_main_2_for_lpi_1_dfm_1_1 OR lfst_exit_main_2_for_lpi_1_dfm_0_1;
  main_2_for_acc_1_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_i_5_0_1_lpi_1_4_0),
      5), 6) + SIGNED'( "000001"), 6));
  main_2_for_for_acc_2_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_for_j_5_0_1_lpi_1_4_0),
      5), 6) + SIGNED'( "000001"), 6));
  main_2_for_for_for_acc_4_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_for_for_k_5_0_lpi_1_dfm_4_0_1),
      5), 6) + SIGNED'( "000001"), 6));
  for_for_for_k_5_0_lpi_1_dfm_4_0_1 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), for_for_for_k_5_0_1_lpi_1_4_0,
      lfst_exit_main_2_for_for_1_lpi_1);
  for_or_tmp_1 <= (lfst_exit_main_2_for_lpi_1_dfm_0_1 AND (NOT lfst_exit_main_2_for_lpi_1_dfm_1_1))
      OR (NOT(lfst_exit_main_2_for_lpi_1_dfm_1_1 OR lfst_exit_main_2_for_lpi_1_dfm_0_1));
  for_and_ssc_1 <= (NOT exit_main_1_for_lpi_1_dfm_2_mx0w0) AND for_or_tmp_1;
  for_and_1_ssc_1 <= exit_main_1_for_lpi_1_dfm_2_mx0w0 AND for_or_tmp_1;
  or_tmp <= (NOT lfst_exit_main_2_for_lpi_1_dfm_3_0) OR (NOT lfst_exit_main_2_for_lpi_1_dfm_3_1)
      OR exitL_exit_main_2_for_sva;
  or_tmp_1 <= lfst_exit_main_2_for_lpi_1_dfm_3_0 OR (NOT lfst_exit_main_2_for_lpi_1_dfm_3_1)
      OR exitL_exit_main_2_for_sva;
  mux_tmp <= MUX_s_1_2_2((NOT or_tmp_1), or_tmp, main_1_for_for_for_acc_4_tmp(5));
  or_tmp_2 <= (NOT lfst_exit_main_2_for_lpi_1_dfm_3_1) OR exitL_exit_main_2_for_sva;
  and_tmp <= (main_1_for_for_for_acc_4_tmp(5)) AND or_tmp_2;
  mux_tmp_1 <= MUX_s_1_2_2(and_tmp, mux_tmp, main_2_for_for_for_acc_4_tmp(5));
  or_25_nl <= (NOT(and_37_cse OR lfst_exit_main_2_for_lpi_1_dfm_3_0)) OR (NOT lfst_exit_main_2_for_lpi_1_dfm_3_1)
      OR exitL_exit_main_2_for_sva;
  mux_8_nl <= MUX_s_1_2_2(or_tmp, (NOT or_tmp_1), main_1_for_for_for_acc_4_tmp(5));
  nor_10_nl <= NOT((main_1_for_for_for_acc_4_tmp(5)) OR (NOT or_tmp_2));
  mux_9_nl <= MUX_s_1_2_2(mux_8_nl, nor_10_nl, and_37_cse);
  not_tmp_4 <= MUX_s_1_2_2(or_25_nl, mux_9_nl, main_1_for_for_acc_2_tmp(5));
  or_dcpl_4 <= NOT(lfst_exit_main_2_for_lpi_1_dfm_st_1_1 AND lfst_exit_main_2_for_lpi_1_dfm_st_1_0);
  and_dcpl_8 <= and_tmp AND (main_1_for_for_acc_2_tmp(5)) AND (NOT (main_1_for_acc_1_tmp(5)));
  B_mux_rmff <= MUX_v_5_2_2(for_for_for_k_5_0_1_lpi_1_dfm_4_0_1, for_for_for_k_5_0_lpi_1_dfm_4_0_1,
      lfst_exit_main_2_for_lpi_1_dfm_1_1);
  nand_2_tmp <= NOT((main_2_for_for_for_acc_4_tmp(5)) AND (main_2_for_for_acc_2_tmp(5)));
  A_rsci_adr_d <= for_i_mux_cse & B_mux_rmff;
  A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff <= or_tmp AND (fsm_output(1));
  B_rsci_adr_d <= B_mux_rmff & for_for_j_mux_cse;
  C_rsci_adr_d <= main_1_for_i_slc_for_i_5_0_4_0_1_itm_1 & main_1_for_for_j_slc_for_for_j_5_0_4_0_1_itm_1;
  C_rsci_d_d <= for_for_sum_1_sva_2;
  C_rsci_we_d_pff <= or_dcpl_4 AND main_stage_0_2 AND main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
  or_tmp_20 <= lfst_exit_main_2_for_lpi_1_dfm_3_0 OR lfst_exit_main_2_for_lpi_1_dfm_3_1;
  and_42_nl <= lfst_exit_main_2_for_for_1_lpi_1 AND ((NOT for_equal_tmp_1_1) OR (NOT
      main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1) OR for_for_j_slc_for_for_j_5_0_1_5_2_itm_1);
  and_41_nl <= lfst_exit_main_1_for_for_1_lpi_1_dfm_1 AND (for_equal_tmp_2_1 OR for_equal_tmp_1_1
      OR (NOT main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1) OR for_for_j_slc_for_for_j_5_0_1_5_2_itm_1);
  mux_tmp_24 <= MUX_s_1_2_2(and_42_nl, and_41_nl, or_tmp_2);
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        C_rsc_triosy_obj_ld <= '0';
        reg_B_rsc_triosy_obj_ld_cse <= '0';
        lfst_exit_main_2_for_lpi_1_dfm_st_1_1 <= '0';
        lfst_exit_main_2_for_lpi_1_dfm_st_1_0 <= '0';
        main_stage_0_2 <= '0';
      ELSE
        C_rsc_triosy_obj_ld <= or_dcpl_4 AND main_stage_0_2 AND exit_main_1_for_lpi_1_dfm_2_st_1;
        reg_B_rsc_triosy_obj_ld_cse <= mux_16_nl AND (fsm_output(1));
        lfst_exit_main_2_for_lpi_1_dfm_st_1_1 <= lfst_exit_main_2_for_lpi_1_dfm_1_1;
        lfst_exit_main_2_for_lpi_1_dfm_st_1_0 <= lfst_exit_main_2_for_lpi_1_dfm_0_1;
        main_stage_0_2 <= fsm_output(1);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        main_1_for_i_slc_for_i_5_0_4_0_1_itm_1 <= STD_LOGIC_VECTOR'( "00000");
        main_1_for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( mux_tmp_1 = '1' ) THEN
        main_1_for_i_slc_for_i_5_0_4_0_1_itm_1 <= for_i_mux_cse;
        main_1_for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 <= for_for_j_mux_cse;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        exit_main_1_for_lpi_1_dfm_2_st_1 <= '0';
        main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 <= '0';
        for_for_for_for_and_4_itm_1 <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
        lfst_exit_main_2_for_for_1_lpi_1 <= '0';
      ELSIF ( or_tmp = '1' ) THEN
        exit_main_1_for_lpi_1_dfm_2_st_1 <= MUX_s_1_2_2(exit_main_1_for_lpi_1_dfm_2_mx0w0,
            exit_main_2_for_lpi_1_dfm_1_mx0w1, lfst_exit_main_2_for_lpi_1_dfm_1_1);
        main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 <= MUX_s_1_2_2((main_1_for_for_for_acc_4_tmp(5)),
            (main_2_for_for_for_acc_4_tmp(5)), lfst_exit_main_2_for_lpi_1_dfm_1_1);
        for_for_for_for_and_4_itm_1 <= MUX_v_32_2_2(STD_LOGIC_VECTOR'("00000000000000000000000000000000"),
            mux_31_nl, mux_tmp_24);
        lfst_exit_main_2_for_for_1_lpi_1 <= MUX_s_1_2_2(for_for_and_9_nl, (NOT and_37_cse),
            for_equal_tmp_3);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_k_5_0_1_lpi_1_4_0 <= STD_LOGIC_VECTOR'( "00000");
        for_equal_tmp_1_1 <= '0';
      ELSIF ( not_tmp_4 = '1' ) THEN
        for_for_for_k_5_0_1_lpi_1_4_0 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"),
            mux_23_nl, not_64_nl);
        for_equal_tmp_1_1 <= for_equal_tmp_3;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        lfst_exit_main_1_for_for_1_lpi_1 <= '0';
      ELSIF ( lfst_exit_main_2_for_lpi_1_dfm_1_1 = '0' ) THEN
        lfst_exit_main_1_for_for_1_lpi_1 <= NOT exit_main_1_for_for_lpi_1_dfm_3;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_5_0_1_lpi_1_4_0 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( ((NOT mux_28_nl) OR exitL_exit_main_2_for_sva) = '1' ) THEN
        for_for_j_5_0_1_lpi_1_4_0 <= MUX1HOT_v_5_6_2(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(main_1_for_acc_1_tmp(5),
            1),5)), for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0, (main_1_for_for_acc_2_tmp(4
            DOWNTO 0)), STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT exit_main_1_for_lpi_1_dfm_2_mx0w0,
            1),5)), STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(main_2_for_acc_1_tmp(5),
            1),5)), (main_2_for_for_acc_2_tmp(4 DOWNTO 0)), STD_LOGIC_VECTOR'( and_dcpl_8
            & for_for_j_and_nl & for_for_j_and_1_nl & for_for_j_and_2_cse & for_and_16_nl
            & for_for_j_and_4_nl));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        lfst_exit_main_2_for_lpi_1_dfm_3_1 <= '0';
      ELSIF ( (fsm_output(0)) = '0' ) THEN
        lfst_exit_main_2_for_lpi_1_dfm_3_1 <= lfst_exit_main_2_for_lpi_1_dfm_3_1_mx0w0;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        exitL_exit_main_2_for_sva <= '1';
      ELSIF ( (fsm_output(0)) = '0' ) THEN
        exitL_exit_main_2_for_sva <= NOT(lfst_exit_main_2_for_lpi_1_dfm_3_1_mx0w0
            OR lfst_exit_main_2_for_lpi_1_dfm_3_0_mx0w0);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        lfst_exit_main_2_for_lpi_1_dfm_3_0 <= '0';
      ELSIF ( (fsm_output(0)) = '0' ) THEN
        lfst_exit_main_2_for_lpi_1_dfm_3_0 <= lfst_exit_main_2_for_lpi_1_dfm_3_0_mx0w0;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_i_5_0_1_lpi_1_4_0 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( ((NOT mux_30_nl) OR exitL_exit_main_2_for_sva) = '1' ) THEN
        for_i_5_0_1_lpi_1_4_0 <= MUX1HOT_v_5_4_2(for_i_5_0_1_lpi_1_dfm_4_0_mx0w0,
            (main_1_for_acc_1_tmp(4 DOWNTO 0)), STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            exit_main_1_for_lpi_1_dfm_2_mx0w0, 1),5)), (main_2_for_acc_1_tmp(4 DOWNTO
            0)), STD_LOGIC_VECTOR'( and_2_cse & and_dcpl_8 & for_for_j_and_2_cse
            & for_and_3_nl));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_slc_for_for_j_5_0_1_5_2_itm_1 <= '0';
      ELSIF ( (MUX_s_1_2_2(mux_11_nl, nor_8_nl, main_1_for_for_acc_2_tmp(5))) = '1'
          ) THEN
        for_for_j_slc_for_for_j_5_0_1_5_2_itm_1 <= MUX_s_1_2_2((main_1_for_for_acc_2_tmp(5)),
            (main_2_for_for_acc_2_tmp(5)), lfst_exit_main_2_for_lpi_1_dfm_1_1);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_equal_tmp_2_1 <= '0';
      ELSIF ( and_2_cse = '1' ) THEN
        for_equal_tmp_2_1 <= for_equal_tmp_4;
      END IF;
    END IF;
  END PROCESS;
  and_6_nl <= (main_1_for_acc_1_tmp(5)) AND (main_1_for_for_acc_2_tmp(5)) AND (main_1_for_for_for_acc_4_tmp(5))
      AND or_tmp_2;
  nor_6_nl <= NOT((NOT (main_2_for_for_acc_2_tmp(5))) OR (NOT (main_2_for_for_for_acc_4_tmp(5)))
      OR lfst_exit_main_2_for_lpi_1_dfm_3_0 OR (NOT lfst_exit_main_2_for_lpi_1_dfm_3_1)
      OR exitL_exit_main_2_for_sva);
  nor_7_nl <= NOT(lfst_exit_main_2_for_lpi_1_dfm_3_0 OR (NOT lfst_exit_main_2_for_lpi_1_dfm_3_1)
      OR exitL_exit_main_2_for_sva);
  mux_13_nl <= MUX_s_1_2_2(nor_7_nl, or_tmp, main_1_for_for_for_acc_4_tmp(5));
  mux_14_nl <= MUX_s_1_2_2(and_tmp, mux_13_nl, and_37_cse);
  and_28_nl <= (main_1_for_acc_1_tmp(5)) AND (main_1_for_for_acc_2_tmp(5));
  mux_15_nl <= MUX_s_1_2_2(nor_6_nl, mux_14_nl, and_28_nl);
  mux_16_nl <= MUX_s_1_2_2(and_6_nl, mux_15_nl, main_2_for_acc_1_tmp(5));
  nor_14_nl <= NOT(for_equal_tmp_2_1 OR (NOT(or_tmp_2 AND lfst_exit_main_1_for_for_1_lpi_1_dfm_1)));
  nor_15_nl <= NOT(or_tmp_2 OR (NOT lfst_exit_main_2_for_for_1_lpi_1));
  mux_20_nl <= MUX_s_1_2_2(nor_14_nl, nor_15_nl, for_equal_tmp_1_1);
  and_32_nl <= mux_20_nl AND main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
  mux_31_nl <= MUX_v_32_2_2(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(and_32_nl, 1),32)),
      for_for_sum_1_sva_2, mux_tmp_24);
  for_for_and_9_nl <= lfst_exit_main_2_for_for_1_lpi_1 AND (NOT exit_main_1_for_lpi_1_dfm_2_mx0w0);
  and_35_nl <= lfst_exit_main_2_for_lpi_1_dfm_1_1 AND (NOT mux_21_tmp);
  mux_23_nl <= MUX_v_5_2_2((main_1_for_for_for_acc_4_tmp(4 DOWNTO 0)), (main_2_for_for_for_acc_4_tmp(4
      DOWNTO 0)), and_35_nl);
  not_64_nl <= NOT mux_21_tmp;
  for_for_j_and_nl <= (NOT (main_1_for_for_for_acc_4_tmp(5))) AND and_2_cse;
  for_for_j_and_1_nl <= (main_1_for_for_for_acc_4_tmp(5)) AND and_2_cse;
  for_and_16_nl <= (NOT nand_2_tmp) AND for_equal_tmp_3;
  for_for_j_and_4_nl <= (main_2_for_for_for_acc_4_tmp(5)) AND nand_2_tmp AND for_equal_tmp_3;
  mux_26_nl <= MUX_s_1_2_2(lfst_exit_main_2_for_lpi_1_dfm_3_0, or_tmp_20, and_38_cse);
  mux_27_nl <= MUX_s_1_2_2(or_tmp_20, mux_26_nl, main_2_for_for_for_acc_4_tmp(5));
  and_39_nl <= (and_38_cse OR lfst_exit_main_2_for_lpi_1_dfm_3_0) AND lfst_exit_main_2_for_lpi_1_dfm_3_1;
  mux_25_nl <= MUX_s_1_2_2(lfst_exit_main_2_for_lpi_1_dfm_3_1, and_39_nl, main_2_for_for_for_acc_4_tmp(5));
  mux_28_nl <= MUX_s_1_2_2(mux_27_nl, mux_25_nl, main_1_for_for_for_acc_4_tmp(5));
  for_and_3_nl <= and_37_cse AND for_equal_tmp_3;
  or_32_nl <= lfst_exit_main_2_for_lpi_1_dfm_3_1 OR nand_1_cse;
  or_31_nl <= (main_2_for_acc_1_tmp(5)) OR lfst_exit_main_2_for_lpi_1_dfm_3_0;
  mux_29_nl <= MUX_s_1_2_2(nand_1_cse, or_31_nl, lfst_exit_main_2_for_lpi_1_dfm_3_1);
  mux_30_nl <= MUX_s_1_2_2(or_32_nl, mux_29_nl, and_37_cse);
  nor_2_nl <= NOT((main_2_for_for_acc_2_tmp(5)) OR (NOT (main_2_for_for_for_acc_4_tmp(5))));
  mux_11_nl <= MUX_s_1_2_2(and_tmp, mux_tmp, nor_2_nl);
  nor_8_nl <= NOT((main_2_for_for_acc_2_tmp(5)) OR (NOT (main_2_for_for_for_acc_4_tmp(5)))
      OR lfst_exit_main_2_for_lpi_1_dfm_3_0 OR (NOT lfst_exit_main_2_for_lpi_1_dfm_3_1)
      OR exitL_exit_main_2_for_sva);
END v3;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    A_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsc_we : OUT STD_LOGIC;
    A_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsc_triosy_lz : OUT STD_LOGIC;
    B_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    B_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsc_we : OUT STD_LOGIC;
    B_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsc_triosy_lz : OUT STD_LOGIC;
    C_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    C_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsc_we : OUT STD_LOGIC;
    C_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsc_triosy_lz : OUT STD_LOGIC
  );
END matrix_mul;

ARCHITECTURE v3 OF matrix_mul IS
  -- Default Constants
  CONSTANT PWR : STD_LOGIC := '1';
  CONSTANT GND : STD_LOGIC := '0';

  -- Interconnect Declarations
  SIGNAL A_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff : STD_LOGIC;
  SIGNAL C_rsci_we_d_iff : STD_LOGIC;

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL A_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL B_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL C_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_d_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      A_rsc_triosy_lz : OUT STD_LOGIC;
      B_rsc_triosy_lz : OUT STD_LOGIC;
      C_rsc_triosy_lz : OUT STD_LOGIC;
      A_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      A_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      B_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      B_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      C_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      C_rsci_d_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff : OUT STD_LOGIC;
      C_rsci_we_d_pff : OUT STD_LOGIC
    );
  END COMPONENT;
  SIGNAL matrix_mul_core_inst_A_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_A_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_B_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_B_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_C_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_C_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);

BEGIN
  A_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => A_rsci_q,
      we => A_rsc_we,
      d => A_rsci_d,
      adr => A_rsci_adr,
      adr_d => A_rsci_adr_d_1,
      d_d => A_rsci_d_d,
      we_d => '0',
      q_d => A_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      port_0_rw_ram_ir_internal_WMASK_B_d => '0'
    );
  A_rsci_q <= A_rsc_q;
  A_rsc_d <= A_rsci_d;
  A_rsc_adr <= A_rsci_adr;
  A_rsci_adr_d_1 <= A_rsci_adr_d;
  A_rsci_d_d <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
  A_rsci_q_d <= A_rsci_q_d_1;

  B_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => B_rsci_q,
      we => B_rsc_we,
      d => B_rsci_d,
      adr => B_rsci_adr,
      adr_d => B_rsci_adr_d_1,
      d_d => B_rsci_d_d,
      we_d => '0',
      q_d => B_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      port_0_rw_ram_ir_internal_WMASK_B_d => '0'
    );
  B_rsci_q <= B_rsc_q;
  B_rsc_d <= B_rsci_d;
  B_rsc_adr <= B_rsci_adr;
  B_rsci_adr_d_1 <= B_rsci_adr_d;
  B_rsci_d_d <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
  B_rsci_q_d <= B_rsci_q_d_1;

  C_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => C_rsci_q,
      we => C_rsc_we,
      d => C_rsci_d,
      adr => C_rsci_adr,
      adr_d => C_rsci_adr_d_1,
      d_d => C_rsci_d_d_1,
      we_d => C_rsci_we_d_iff,
      q_d => C_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => '0',
      port_0_rw_ram_ir_internal_WMASK_B_d => C_rsci_we_d_iff
    );
  C_rsci_q <= C_rsc_q;
  C_rsc_d <= C_rsci_d;
  C_rsc_adr <= C_rsci_adr;
  C_rsci_adr_d_1 <= C_rsci_adr_d;
  C_rsci_d_d_1 <= C_rsci_d_d;
  C_rsci_q_d <= C_rsci_q_d_1;

  matrix_mul_core_inst : matrix_mul_core
    PORT MAP(
      clk => clk,
      rst => rst,
      A_rsc_triosy_lz => A_rsc_triosy_lz,
      B_rsc_triosy_lz => B_rsc_triosy_lz,
      C_rsc_triosy_lz => C_rsc_triosy_lz,
      A_rsci_adr_d => matrix_mul_core_inst_A_rsci_adr_d,
      A_rsci_q_d => matrix_mul_core_inst_A_rsci_q_d,
      B_rsci_adr_d => matrix_mul_core_inst_B_rsci_adr_d,
      B_rsci_q_d => matrix_mul_core_inst_B_rsci_q_d,
      C_rsci_adr_d => matrix_mul_core_inst_C_rsci_adr_d,
      C_rsci_d_d => matrix_mul_core_inst_C_rsci_d_d,
      A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      C_rsci_we_d_pff => C_rsci_we_d_iff
    );
  A_rsci_adr_d <= matrix_mul_core_inst_A_rsci_adr_d;
  matrix_mul_core_inst_A_rsci_q_d <= A_rsci_q_d;
  B_rsci_adr_d <= matrix_mul_core_inst_B_rsci_adr_d;
  matrix_mul_core_inst_B_rsci_q_d <= B_rsci_q_d;
  C_rsci_adr_d <= matrix_mul_core_inst_C_rsci_adr_d;
  C_rsci_d_d <= matrix_mul_core_inst_C_rsci_d_d;

END v3;



