directive set /matrix_mul/matrix_mul:core/core/main-1:for:i:slc(for:i(5:0))(4-0)#1.itm.1 REGISTER_NAME main-1:for:i:slc(for:i(5:0))(4-0)#1.itm.1
directive set /matrix_mul/matrix_mul:core/core/main-2:for:i:slc(for:i(5:0))(4-0)#1.itm.1 REGISTER_NAME main-1:for:i:slc(for:i(5:0))(4-0)#1.itm.1
directive set /matrix_mul/matrix_mul:core/core/main-1:for:for:j:slc(for:for:j(5:0))(4-0)#1.itm.1 REGISTER_NAME main-1:for:for:j:slc(for:for:j(5:0))(4-0)#1.itm.1
directive set /matrix_mul/matrix_mul:core/core/main-2:for:for:j:slc(for:for:j(5:0))(4-0)#1.itm.1 REGISTER_NAME main-1:for:for:j:slc(for:for:j(5:0))(4-0)#1.itm.1
directive set /matrix_mul/matrix_mul:core/core/exit:main-1:for.lpi#1.dfm#2.st.1 REGISTER_NAME exit:main-1:for.lpi#1.dfm#2.st.1
directive set /matrix_mul/matrix_mul:core/core/exit:main-2:for.lpi#1.dfm#1.st.1 REGISTER_NAME exit:main-1:for.lpi#1.dfm#2.st.1
directive set /matrix_mul/matrix_mul:core/core/main-1:for:for:for:k:slc(for:for:for:k(5:0))(5)#1.itm.1 REGISTER_NAME main-1:for:for:for:k:slc(for:for:for:k(5:0))(5)#1.itm.1
directive set /matrix_mul/matrix_mul:core/core/main-2:for:for:for:k:slc(for:for:for:k(5:0))(5)#1.itm.1 REGISTER_NAME main-1:for:for:for:k:slc(for:for:for:k(5:0))(5)#1.itm.1
directive set /matrix_mul/matrix_mul:core/core/for:for:for:for:and#4.itm.1 REGISTER_NAME for:for:for:for:and#4.itm.1
directive set /matrix_mul/matrix_mul:core/core/for:for:for:for:and.itm.1 REGISTER_NAME for:for:for:for:and#4.itm.1
directive set /matrix_mul/matrix_mul:core/core/for:for:for:k(5:0)#1.lpi#1(4:0) REGISTER_NAME for:for:for:k(5:0)#1.lpi#1(4:0)
directive set /matrix_mul/matrix_mul:core/core/for:for:for:k(5:0).lpi#1(4:0) REGISTER_NAME for:for:for:k(5:0)#1.lpi#1(4:0)
directive set /matrix_mul/matrix_mul:core/core/for:for:j(5:0)#1.lpi#1(4:0) REGISTER_NAME for:for:j(5:0)#1.lpi#1(4:0)
directive set /matrix_mul/matrix_mul:core/core/for:for:j(5:0).lpi#1(4:0) REGISTER_NAME for:for:j(5:0)#1.lpi#1(4:0)
directive set /matrix_mul/matrix_mul:core/core/for:i(5:0)#1.lpi#1(4:0) REGISTER_NAME for:i(5:0)#1.lpi#1(4:0)
directive set /matrix_mul/matrix_mul:core/core/for:i(5:0).lpi#1(4:0) REGISTER_NAME for:i(5:0)#1.lpi#1(4:0)
directive set /matrix_mul/matrix_mul:core/core/for:for:j:slc(for:for:j(5:0)#1)(5)#2.itm.1 REGISTER_NAME for:for:j:slc(for:for:j(5:0)#1)(5)#2.itm.1
directive set /matrix_mul/matrix_mul:core/core/for:for:j:slc(for:for:j(5:0))(5)#2.itm.1 REGISTER_NAME for:for:j:slc(for:for:j(5:0)#1)(5)#2.itm.1
directive set /matrix_mul/matrix_mul:core/core/main-1:for:for:for:k:slc(for:for:for:k(5:0))(5)#3.itm.1 REGISTER_NAME main-1:for:for:for:k:slc(for:for:for:k(5:0))(5)#3.itm.1
directive set /matrix_mul/matrix_mul:core/core/main-2:for:for:for:k:slc(for:for:for:k(5:0))(5)#3.itm.1 REGISTER_NAME main-1:for:for:for:k:slc(for:for:for:k(5:0))(5)#3.itm.1
