// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4a/835166 Production Release
//  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
// 
//  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
//  Generated date: Thu Nov  6 19:37:57 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_9_7_5_32_32_7_5_gen
// ------------------------------------------------------------------


module test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_9_7_5_32_32_7_5_gen (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [6:0] q;
  output we;
  output [6:0] d;
  output [4:0] adr;
  input [4:0] adr_d;
  input [6:0] d_d;
  input we_d;
  output [6:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_8_7_5_32_32_7_5_gen
// ------------------------------------------------------------------


module test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_8_7_5_32_32_7_5_gen (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [6:0] q;
  output we;
  output [6:0] d;
  output [4:0] adr;
  input [4:0] adr_d;
  input [6:0] d_d;
  input we_d;
  output [6:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_7_7_5_32_32_7_5_gen
// ------------------------------------------------------------------


module test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_7_7_5_32_32_7_5_gen (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [6:0] q;
  output we;
  output [6:0] d;
  output [4:0] adr;
  input [4:0] adr_d;
  input [6:0] d_d;
  input we_d;
  output [6:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_6_7_5_32_32_7_5_gen
// ------------------------------------------------------------------


module test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_6_7_5_32_32_7_5_gen (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [6:0] q;
  output we;
  output [6:0] d;
  output [4:0] adr;
  input [4:0] adr_d;
  input [6:0] d_d;
  input we_d;
  output [6:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module test_core_core_fsm (
  clk, rst, core_wen, fsm_output
);
  input clk;
  input rst;
  input core_wen;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for test_core_core_fsm_1
  parameter
    core_rlp_C_0 = 1'd0,
    main_C_0 = 1'd1;

  reg [0:0] state_var;
  reg [0:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : test_core_core_fsm_1
    case (state_var)
      main_C_0 : begin
        fsm_output = 2'b10;
        state_var_NS = main_C_0;
      end
      // core_rlp_C_0
      default : begin
        fsm_output = 2'b01;
        state_var_NS = main_C_0;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( rst ) begin
      state_var <= core_rlp_C_0;
    end
    else if ( core_wen ) begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_staller
// ------------------------------------------------------------------


module test_core_staller (
  clk, rst, core_wen, core_wten, data_in_rsci_wen_comp, coeff_addr_rsci_wen_comp,
      result_rsci_wen_comp
);
  input clk;
  input rst;
  output core_wen;
  output core_wten;
  input data_in_rsci_wen_comp;
  input coeff_addr_rsci_wen_comp;
  input result_rsci_wen_comp;


  // Interconnect Declarations
  reg core_wten_reg;


  // Interconnect Declarations for Component Instantiations 
  assign core_wen = data_in_rsci_wen_comp & coeff_addr_rsci_wen_comp & result_rsci_wen_comp;
  assign core_wten = core_wten_reg;
  always @(posedge clk) begin
    if ( rst ) begin
      core_wten_reg <= 1'b0;
    end
    else begin
      core_wten_reg <= ~ core_wen;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_triosy_0_0_obj_coeffs_rsc_triosy_0_0_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeffs_rsc_triosy_0_0_obj_coeffs_rsc_triosy_0_0_wait_ctrl (
  core_wten, coeffs_rsc_triosy_0_0_obj_iswt0, coeffs_rsc_triosy_0_0_obj_ld_core_sct
);
  input core_wten;
  input coeffs_rsc_triosy_0_0_obj_iswt0;
  output coeffs_rsc_triosy_0_0_obj_ld_core_sct;



  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_triosy_0_0_obj_ld_core_sct = coeffs_rsc_triosy_0_0_obj_iswt0
      & (~ core_wten);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_triosy_0_1_obj_coeffs_rsc_triosy_0_1_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeffs_rsc_triosy_0_1_obj_coeffs_rsc_triosy_0_1_wait_ctrl (
  core_wten, coeffs_rsc_triosy_0_1_obj_iswt0, coeffs_rsc_triosy_0_1_obj_ld_core_sct
);
  input core_wten;
  input coeffs_rsc_triosy_0_1_obj_iswt0;
  output coeffs_rsc_triosy_0_1_obj_ld_core_sct;



  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_triosy_0_1_obj_ld_core_sct = coeffs_rsc_triosy_0_1_obj_iswt0
      & (~ core_wten);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_triosy_0_2_obj_coeffs_rsc_triosy_0_2_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeffs_rsc_triosy_0_2_obj_coeffs_rsc_triosy_0_2_wait_ctrl (
  core_wten, coeffs_rsc_triosy_0_2_obj_iswt0, coeffs_rsc_triosy_0_2_obj_ld_core_sct
);
  input core_wten;
  input coeffs_rsc_triosy_0_2_obj_iswt0;
  output coeffs_rsc_triosy_0_2_obj_ld_core_sct;



  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_triosy_0_2_obj_ld_core_sct = coeffs_rsc_triosy_0_2_obj_iswt0
      & (~ core_wten);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_triosy_0_3_obj_coeffs_rsc_triosy_0_3_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeffs_rsc_triosy_0_3_obj_coeffs_rsc_triosy_0_3_wait_ctrl (
  core_wten, coeffs_rsc_triosy_0_3_obj_iswt0, coeffs_rsc_triosy_0_3_obj_ld_core_sct
);
  input core_wten;
  input coeffs_rsc_triosy_0_3_obj_iswt0;
  output coeffs_rsc_triosy_0_3_obj_ld_core_sct;



  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_triosy_0_3_obj_ld_core_sct = coeffs_rsc_triosy_0_3_obj_iswt0
      & (~ core_wten);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_3_i_1_coeffs_rsc_0_3_wait_dp
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_3_i_1_coeffs_rsc_0_3_wait_dp (
  clk, rst, coeffs_rsc_0_3_i_q_d, coeffs_rsc_0_3_i_q_d_mxwt, coeffs_rsc_0_3_i_biwt,
      coeffs_rsc_0_3_i_bdwt
);
  input clk;
  input rst;
  input [6:0] coeffs_rsc_0_3_i_q_d;
  output [6:0] coeffs_rsc_0_3_i_q_d_mxwt;
  input coeffs_rsc_0_3_i_biwt;
  input coeffs_rsc_0_3_i_bdwt;


  // Interconnect Declarations
  reg coeffs_rsc_0_3_i_bcwt;
  reg [6:0] coeffs_rsc_0_3_i_q_d_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_0_3_i_q_d_mxwt = MUX_v_7_2_2(coeffs_rsc_0_3_i_q_d, coeffs_rsc_0_3_i_q_d_bfwt,
      coeffs_rsc_0_3_i_bcwt);
  always @(posedge clk) begin
    if ( rst ) begin
      coeffs_rsc_0_3_i_bcwt <= 1'b0;
    end
    else begin
      coeffs_rsc_0_3_i_bcwt <= ~((~(coeffs_rsc_0_3_i_bcwt | coeffs_rsc_0_3_i_biwt))
          | coeffs_rsc_0_3_i_bdwt);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      coeffs_rsc_0_3_i_q_d_bfwt <= 7'b0000000;
    end
    else if ( ~ coeffs_rsc_0_3_i_bcwt ) begin
      coeffs_rsc_0_3_i_q_d_bfwt <= coeffs_rsc_0_3_i_q_d_mxwt;
    end
  end

  function automatic [6:0] MUX_v_7_2_2;
    input [6:0] input_0;
    input [6:0] input_1;
    input [0:0] sel;
    reg [6:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_7_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_3_i_1_coeffs_rsc_0_3_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_3_i_1_coeffs_rsc_0_3_wait_ctrl (
  core_wen, core_wten, coeffs_rsc_0_3_i_oswt, coeffs_rsc_0_3_i_biwt, coeffs_rsc_0_3_i_bdwt,
      coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct, coeffs_rsc_0_3_i_oswt_pff
);
  input core_wen;
  input core_wten;
  input coeffs_rsc_0_3_i_oswt;
  output coeffs_rsc_0_3_i_biwt;
  output coeffs_rsc_0_3_i_bdwt;
  output coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;
  input coeffs_rsc_0_3_i_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_0_3_i_bdwt = coeffs_rsc_0_3_i_oswt & core_wen;
  assign coeffs_rsc_0_3_i_biwt = (~ core_wten) & coeffs_rsc_0_3_i_oswt;
  assign coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct = coeffs_rsc_0_3_i_oswt_pff
      & core_wen;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_2_i_1_coeffs_rsc_0_2_wait_dp
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_2_i_1_coeffs_rsc_0_2_wait_dp (
  clk, rst, coeffs_rsc_0_2_i_q_d, coeffs_rsc_0_2_i_q_d_mxwt, coeffs_rsc_0_2_i_biwt,
      coeffs_rsc_0_2_i_bdwt
);
  input clk;
  input rst;
  input [6:0] coeffs_rsc_0_2_i_q_d;
  output [6:0] coeffs_rsc_0_2_i_q_d_mxwt;
  input coeffs_rsc_0_2_i_biwt;
  input coeffs_rsc_0_2_i_bdwt;


  // Interconnect Declarations
  reg coeffs_rsc_0_2_i_bcwt;
  reg [6:0] coeffs_rsc_0_2_i_q_d_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_0_2_i_q_d_mxwt = MUX_v_7_2_2(coeffs_rsc_0_2_i_q_d, coeffs_rsc_0_2_i_q_d_bfwt,
      coeffs_rsc_0_2_i_bcwt);
  always @(posedge clk) begin
    if ( rst ) begin
      coeffs_rsc_0_2_i_bcwt <= 1'b0;
    end
    else begin
      coeffs_rsc_0_2_i_bcwt <= ~((~(coeffs_rsc_0_2_i_bcwt | coeffs_rsc_0_2_i_biwt))
          | coeffs_rsc_0_2_i_bdwt);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      coeffs_rsc_0_2_i_q_d_bfwt <= 7'b0000000;
    end
    else if ( ~ coeffs_rsc_0_2_i_bcwt ) begin
      coeffs_rsc_0_2_i_q_d_bfwt <= coeffs_rsc_0_2_i_q_d_mxwt;
    end
  end

  function automatic [6:0] MUX_v_7_2_2;
    input [6:0] input_0;
    input [6:0] input_1;
    input [0:0] sel;
    reg [6:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_7_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_2_i_1_coeffs_rsc_0_2_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_2_i_1_coeffs_rsc_0_2_wait_ctrl (
  core_wen, core_wten, coeffs_rsc_0_2_i_oswt, coeffs_rsc_0_2_i_biwt, coeffs_rsc_0_2_i_bdwt,
      coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct, coeffs_rsc_0_2_i_oswt_pff
);
  input core_wen;
  input core_wten;
  input coeffs_rsc_0_2_i_oswt;
  output coeffs_rsc_0_2_i_biwt;
  output coeffs_rsc_0_2_i_bdwt;
  output coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;
  input coeffs_rsc_0_2_i_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_0_2_i_bdwt = coeffs_rsc_0_2_i_oswt & core_wen;
  assign coeffs_rsc_0_2_i_biwt = (~ core_wten) & coeffs_rsc_0_2_i_oswt;
  assign coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct = coeffs_rsc_0_2_i_oswt_pff
      & core_wen;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_1_i_1_coeffs_rsc_0_1_wait_dp
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_1_i_1_coeffs_rsc_0_1_wait_dp (
  clk, rst, coeffs_rsc_0_1_i_q_d, coeffs_rsc_0_1_i_q_d_mxwt, coeffs_rsc_0_1_i_biwt,
      coeffs_rsc_0_1_i_bdwt
);
  input clk;
  input rst;
  input [6:0] coeffs_rsc_0_1_i_q_d;
  output [6:0] coeffs_rsc_0_1_i_q_d_mxwt;
  input coeffs_rsc_0_1_i_biwt;
  input coeffs_rsc_0_1_i_bdwt;


  // Interconnect Declarations
  reg coeffs_rsc_0_1_i_bcwt;
  reg [6:0] coeffs_rsc_0_1_i_q_d_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_0_1_i_q_d_mxwt = MUX_v_7_2_2(coeffs_rsc_0_1_i_q_d, coeffs_rsc_0_1_i_q_d_bfwt,
      coeffs_rsc_0_1_i_bcwt);
  always @(posedge clk) begin
    if ( rst ) begin
      coeffs_rsc_0_1_i_bcwt <= 1'b0;
    end
    else begin
      coeffs_rsc_0_1_i_bcwt <= ~((~(coeffs_rsc_0_1_i_bcwt | coeffs_rsc_0_1_i_biwt))
          | coeffs_rsc_0_1_i_bdwt);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      coeffs_rsc_0_1_i_q_d_bfwt <= 7'b0000000;
    end
    else if ( ~ coeffs_rsc_0_1_i_bcwt ) begin
      coeffs_rsc_0_1_i_q_d_bfwt <= coeffs_rsc_0_1_i_q_d_mxwt;
    end
  end

  function automatic [6:0] MUX_v_7_2_2;
    input [6:0] input_0;
    input [6:0] input_1;
    input [0:0] sel;
    reg [6:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_7_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_1_i_1_coeffs_rsc_0_1_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_1_i_1_coeffs_rsc_0_1_wait_ctrl (
  core_wen, core_wten, coeffs_rsc_0_1_i_oswt, coeffs_rsc_0_1_i_biwt, coeffs_rsc_0_1_i_bdwt,
      coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct, coeffs_rsc_0_1_i_oswt_pff
);
  input core_wen;
  input core_wten;
  input coeffs_rsc_0_1_i_oswt;
  output coeffs_rsc_0_1_i_biwt;
  output coeffs_rsc_0_1_i_bdwt;
  output coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;
  input coeffs_rsc_0_1_i_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_0_1_i_bdwt = coeffs_rsc_0_1_i_oswt & core_wen;
  assign coeffs_rsc_0_1_i_biwt = (~ core_wten) & coeffs_rsc_0_1_i_oswt;
  assign coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct = coeffs_rsc_0_1_i_oswt_pff
      & core_wen;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_0_i_1_coeffs_rsc_0_0_wait_dp
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_0_i_1_coeffs_rsc_0_0_wait_dp (
  clk, rst, coeffs_rsc_0_0_i_q_d, coeffs_rsc_0_0_i_q_d_mxwt, coeffs_rsc_0_0_i_biwt,
      coeffs_rsc_0_0_i_bdwt
);
  input clk;
  input rst;
  input [6:0] coeffs_rsc_0_0_i_q_d;
  output [6:0] coeffs_rsc_0_0_i_q_d_mxwt;
  input coeffs_rsc_0_0_i_biwt;
  input coeffs_rsc_0_0_i_bdwt;


  // Interconnect Declarations
  reg coeffs_rsc_0_0_i_bcwt;
  reg [6:0] coeffs_rsc_0_0_i_q_d_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_0_0_i_q_d_mxwt = MUX_v_7_2_2(coeffs_rsc_0_0_i_q_d, coeffs_rsc_0_0_i_q_d_bfwt,
      coeffs_rsc_0_0_i_bcwt);
  always @(posedge clk) begin
    if ( rst ) begin
      coeffs_rsc_0_0_i_bcwt <= 1'b0;
    end
    else begin
      coeffs_rsc_0_0_i_bcwt <= ~((~(coeffs_rsc_0_0_i_bcwt | coeffs_rsc_0_0_i_biwt))
          | coeffs_rsc_0_0_i_bdwt);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      coeffs_rsc_0_0_i_q_d_bfwt <= 7'b0000000;
    end
    else if ( ~ coeffs_rsc_0_0_i_bcwt ) begin
      coeffs_rsc_0_0_i_q_d_bfwt <= coeffs_rsc_0_0_i_q_d_mxwt;
    end
  end

  function automatic [6:0] MUX_v_7_2_2;
    input [6:0] input_0;
    input [6:0] input_1;
    input [0:0] sel;
    reg [6:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_7_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_0_i_1_coeffs_rsc_0_0_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_0_i_1_coeffs_rsc_0_0_wait_ctrl (
  core_wen, core_wten, coeffs_rsc_0_0_i_oswt, coeffs_rsc_0_0_i_biwt, coeffs_rsc_0_0_i_bdwt,
      coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct, coeffs_rsc_0_0_i_oswt_pff
);
  input core_wen;
  input core_wten;
  input coeffs_rsc_0_0_i_oswt;
  output coeffs_rsc_0_0_i_biwt;
  output coeffs_rsc_0_0_i_bdwt;
  output coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;
  input coeffs_rsc_0_0_i_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign coeffs_rsc_0_0_i_bdwt = coeffs_rsc_0_0_i_oswt & core_wen;
  assign coeffs_rsc_0_0_i_biwt = (~ core_wten) & coeffs_rsc_0_0_i_oswt;
  assign coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct = coeffs_rsc_0_0_i_oswt_pff
      & core_wen;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_result_rsci_result_wait_dp
// ------------------------------------------------------------------


module test_core_result_rsci_result_wait_dp (
  clk, rst, result_rsci_oswt, result_rsci_wen_comp, result_rsci_biwt, result_rsci_bdwt,
      result_rsci_bcwt
);
  input clk;
  input rst;
  input result_rsci_oswt;
  output result_rsci_wen_comp;
  input result_rsci_biwt;
  input result_rsci_bdwt;
  output result_rsci_bcwt;
  reg result_rsci_bcwt;



  // Interconnect Declarations for Component Instantiations 
  assign result_rsci_wen_comp = (~ result_rsci_oswt) | result_rsci_biwt | result_rsci_bcwt;
  always @(posedge clk) begin
    if ( rst ) begin
      result_rsci_bcwt <= 1'b0;
    end
    else begin
      result_rsci_bcwt <= ~((~(result_rsci_bcwt | result_rsci_biwt)) | result_rsci_bdwt);
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_result_rsci_result_wait_ctrl
// ------------------------------------------------------------------


module test_core_result_rsci_result_wait_ctrl (
  core_wen, result_rsci_oswt, result_rsci_irdy, result_rsci_biwt, result_rsci_bdwt,
      result_rsci_bcwt, result_rsci_ivld_core_sct
);
  input core_wen;
  input result_rsci_oswt;
  input result_rsci_irdy;
  output result_rsci_biwt;
  output result_rsci_bdwt;
  input result_rsci_bcwt;
  output result_rsci_ivld_core_sct;


  // Interconnect Declarations
  wire result_rsci_ogwt;


  // Interconnect Declarations for Component Instantiations 
  assign result_rsci_bdwt = result_rsci_oswt & core_wen;
  assign result_rsci_biwt = result_rsci_ogwt & result_rsci_irdy;
  assign result_rsci_ogwt = result_rsci_oswt & (~ result_rsci_bcwt);
  assign result_rsci_ivld_core_sct = result_rsci_ogwt;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeff_addr_rsci_coeff_addr_wait_dp
// ------------------------------------------------------------------


module test_core_coeff_addr_rsci_coeff_addr_wait_dp (
  clk, rst, coeff_addr_rsci_oswt, coeff_addr_rsci_wen_comp, coeff_addr_rsci_idat_mxwt,
      coeff_addr_rsci_biwt, coeff_addr_rsci_bdwt, coeff_addr_rsci_bcwt, coeff_addr_rsci_idat
);
  input clk;
  input rst;
  input coeff_addr_rsci_oswt;
  output coeff_addr_rsci_wen_comp;
  output [4:0] coeff_addr_rsci_idat_mxwt;
  input coeff_addr_rsci_biwt;
  input coeff_addr_rsci_bdwt;
  output coeff_addr_rsci_bcwt;
  reg coeff_addr_rsci_bcwt;
  input [4:0] coeff_addr_rsci_idat;


  // Interconnect Declarations
  reg [4:0] coeff_addr_rsci_idat_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign coeff_addr_rsci_wen_comp = (~ coeff_addr_rsci_oswt) | coeff_addr_rsci_biwt
      | coeff_addr_rsci_bcwt;
  assign coeff_addr_rsci_idat_mxwt = MUX_v_5_2_2(coeff_addr_rsci_idat, coeff_addr_rsci_idat_bfwt,
      coeff_addr_rsci_bcwt);
  always @(posedge clk) begin
    if ( rst ) begin
      coeff_addr_rsci_bcwt <= 1'b0;
    end
    else begin
      coeff_addr_rsci_bcwt <= ~((~(coeff_addr_rsci_bcwt | coeff_addr_rsci_biwt))
          | coeff_addr_rsci_bdwt);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      coeff_addr_rsci_idat_bfwt <= 5'b00000;
    end
    else if ( ~ coeff_addr_rsci_bcwt ) begin
      coeff_addr_rsci_idat_bfwt <= coeff_addr_rsci_idat_mxwt;
    end
  end

  function automatic [4:0] MUX_v_5_2_2;
    input [4:0] input_0;
    input [4:0] input_1;
    input [0:0] sel;
    reg [4:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_5_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeff_addr_rsci_coeff_addr_wait_ctrl
// ------------------------------------------------------------------


module test_core_coeff_addr_rsci_coeff_addr_wait_ctrl (
  core_wen, coeff_addr_rsci_oswt, coeff_addr_rsci_biwt, coeff_addr_rsci_bdwt, coeff_addr_rsci_bcwt,
      coeff_addr_rsci_irdy_core_sct, coeff_addr_rsci_ivld
);
  input core_wen;
  input coeff_addr_rsci_oswt;
  output coeff_addr_rsci_biwt;
  output coeff_addr_rsci_bdwt;
  input coeff_addr_rsci_bcwt;
  output coeff_addr_rsci_irdy_core_sct;
  input coeff_addr_rsci_ivld;


  // Interconnect Declarations
  wire coeff_addr_rsci_ogwt;


  // Interconnect Declarations for Component Instantiations 
  assign coeff_addr_rsci_bdwt = coeff_addr_rsci_oswt & core_wen;
  assign coeff_addr_rsci_biwt = coeff_addr_rsci_ogwt & coeff_addr_rsci_ivld;
  assign coeff_addr_rsci_ogwt = coeff_addr_rsci_oswt & (~ coeff_addr_rsci_bcwt);
  assign coeff_addr_rsci_irdy_core_sct = coeff_addr_rsci_ogwt;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_data_in_rsci_data_in_wait_dp
// ------------------------------------------------------------------


module test_core_data_in_rsci_data_in_wait_dp (
  clk, rst, data_in_rsci_oswt, data_in_rsci_wen_comp, data_in_rsci_idat_mxwt, data_in_rsci_biwt,
      data_in_rsci_bdwt, data_in_rsci_bcwt, data_in_rsci_idat
);
  input clk;
  input rst;
  input data_in_rsci_oswt;
  output data_in_rsci_wen_comp;
  output [9:0] data_in_rsci_idat_mxwt;
  input data_in_rsci_biwt;
  input data_in_rsci_bdwt;
  output data_in_rsci_bcwt;
  reg data_in_rsci_bcwt;
  input [9:0] data_in_rsci_idat;


  // Interconnect Declarations
  reg [9:0] data_in_rsci_idat_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign data_in_rsci_wen_comp = (~ data_in_rsci_oswt) | data_in_rsci_biwt | data_in_rsci_bcwt;
  assign data_in_rsci_idat_mxwt = MUX_v_10_2_2(data_in_rsci_idat, data_in_rsci_idat_bfwt,
      data_in_rsci_bcwt);
  always @(posedge clk) begin
    if ( rst ) begin
      data_in_rsci_bcwt <= 1'b0;
    end
    else begin
      data_in_rsci_bcwt <= ~((~(data_in_rsci_bcwt | data_in_rsci_biwt)) | data_in_rsci_bdwt);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      data_in_rsci_idat_bfwt <= 10'b0000000000;
    end
    else if ( ~ data_in_rsci_bcwt ) begin
      data_in_rsci_idat_bfwt <= data_in_rsci_idat_mxwt;
    end
  end

  function automatic [9:0] MUX_v_10_2_2;
    input [9:0] input_0;
    input [9:0] input_1;
    input [0:0] sel;
    reg [9:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_10_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_data_in_rsci_data_in_wait_ctrl
// ------------------------------------------------------------------


module test_core_data_in_rsci_data_in_wait_ctrl (
  core_wen, data_in_rsci_oswt, data_in_rsci_biwt, data_in_rsci_bdwt, data_in_rsci_bcwt,
      data_in_rsci_irdy_core_sct, data_in_rsci_ivld
);
  input core_wen;
  input data_in_rsci_oswt;
  output data_in_rsci_biwt;
  output data_in_rsci_bdwt;
  input data_in_rsci_bcwt;
  output data_in_rsci_irdy_core_sct;
  input data_in_rsci_ivld;


  // Interconnect Declarations
  wire data_in_rsci_ogwt;


  // Interconnect Declarations for Component Instantiations 
  assign data_in_rsci_bdwt = data_in_rsci_oswt & core_wen;
  assign data_in_rsci_biwt = data_in_rsci_ogwt & data_in_rsci_ivld;
  assign data_in_rsci_ogwt = data_in_rsci_oswt & (~ data_in_rsci_bcwt);
  assign data_in_rsci_irdy_core_sct = data_in_rsci_ogwt;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_triosy_0_0_obj
// ------------------------------------------------------------------


module test_core_coeffs_rsc_triosy_0_0_obj (
  coeffs_rsc_triosy_0_0_lz, core_wten, coeffs_rsc_triosy_0_0_obj_iswt0
);
  output coeffs_rsc_triosy_0_0_lz;
  input core_wten;
  input coeffs_rsc_triosy_0_0_obj_iswt0;


  // Interconnect Declarations
  wire coeffs_rsc_triosy_0_0_obj_ld_core_sct;


  // Interconnect Declarations for Component Instantiations 
  mgc_io_sync_v2 #(.valid(32'sd0)) coeffs_rsc_triosy_0_0_obj (
      .ld(coeffs_rsc_triosy_0_0_obj_ld_core_sct),
      .lz(coeffs_rsc_triosy_0_0_lz)
    );
  test_core_coeffs_rsc_triosy_0_0_obj_coeffs_rsc_triosy_0_0_wait_ctrl test_core_coeffs_rsc_triosy_0_0_obj_coeffs_rsc_triosy_0_0_wait_ctrl_inst
      (
      .core_wten(core_wten),
      .coeffs_rsc_triosy_0_0_obj_iswt0(coeffs_rsc_triosy_0_0_obj_iswt0),
      .coeffs_rsc_triosy_0_0_obj_ld_core_sct(coeffs_rsc_triosy_0_0_obj_ld_core_sct)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_triosy_0_1_obj
// ------------------------------------------------------------------


module test_core_coeffs_rsc_triosy_0_1_obj (
  coeffs_rsc_triosy_0_1_lz, core_wten, coeffs_rsc_triosy_0_1_obj_iswt0
);
  output coeffs_rsc_triosy_0_1_lz;
  input core_wten;
  input coeffs_rsc_triosy_0_1_obj_iswt0;


  // Interconnect Declarations
  wire coeffs_rsc_triosy_0_1_obj_ld_core_sct;


  // Interconnect Declarations for Component Instantiations 
  mgc_io_sync_v2 #(.valid(32'sd0)) coeffs_rsc_triosy_0_1_obj (
      .ld(coeffs_rsc_triosy_0_1_obj_ld_core_sct),
      .lz(coeffs_rsc_triosy_0_1_lz)
    );
  test_core_coeffs_rsc_triosy_0_1_obj_coeffs_rsc_triosy_0_1_wait_ctrl test_core_coeffs_rsc_triosy_0_1_obj_coeffs_rsc_triosy_0_1_wait_ctrl_inst
      (
      .core_wten(core_wten),
      .coeffs_rsc_triosy_0_1_obj_iswt0(coeffs_rsc_triosy_0_1_obj_iswt0),
      .coeffs_rsc_triosy_0_1_obj_ld_core_sct(coeffs_rsc_triosy_0_1_obj_ld_core_sct)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_triosy_0_2_obj
// ------------------------------------------------------------------


module test_core_coeffs_rsc_triosy_0_2_obj (
  coeffs_rsc_triosy_0_2_lz, core_wten, coeffs_rsc_triosy_0_2_obj_iswt0
);
  output coeffs_rsc_triosy_0_2_lz;
  input core_wten;
  input coeffs_rsc_triosy_0_2_obj_iswt0;


  // Interconnect Declarations
  wire coeffs_rsc_triosy_0_2_obj_ld_core_sct;


  // Interconnect Declarations for Component Instantiations 
  mgc_io_sync_v2 #(.valid(32'sd0)) coeffs_rsc_triosy_0_2_obj (
      .ld(coeffs_rsc_triosy_0_2_obj_ld_core_sct),
      .lz(coeffs_rsc_triosy_0_2_lz)
    );
  test_core_coeffs_rsc_triosy_0_2_obj_coeffs_rsc_triosy_0_2_wait_ctrl test_core_coeffs_rsc_triosy_0_2_obj_coeffs_rsc_triosy_0_2_wait_ctrl_inst
      (
      .core_wten(core_wten),
      .coeffs_rsc_triosy_0_2_obj_iswt0(coeffs_rsc_triosy_0_2_obj_iswt0),
      .coeffs_rsc_triosy_0_2_obj_ld_core_sct(coeffs_rsc_triosy_0_2_obj_ld_core_sct)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_triosy_0_3_obj
// ------------------------------------------------------------------


module test_core_coeffs_rsc_triosy_0_3_obj (
  coeffs_rsc_triosy_0_3_lz, core_wten, coeffs_rsc_triosy_0_3_obj_iswt0
);
  output coeffs_rsc_triosy_0_3_lz;
  input core_wten;
  input coeffs_rsc_triosy_0_3_obj_iswt0;


  // Interconnect Declarations
  wire coeffs_rsc_triosy_0_3_obj_ld_core_sct;


  // Interconnect Declarations for Component Instantiations 
  mgc_io_sync_v2 #(.valid(32'sd0)) coeffs_rsc_triosy_0_3_obj (
      .ld(coeffs_rsc_triosy_0_3_obj_ld_core_sct),
      .lz(coeffs_rsc_triosy_0_3_lz)
    );
  test_core_coeffs_rsc_triosy_0_3_obj_coeffs_rsc_triosy_0_3_wait_ctrl test_core_coeffs_rsc_triosy_0_3_obj_coeffs_rsc_triosy_0_3_wait_ctrl_inst
      (
      .core_wten(core_wten),
      .coeffs_rsc_triosy_0_3_obj_iswt0(coeffs_rsc_triosy_0_3_obj_iswt0),
      .coeffs_rsc_triosy_0_3_obj_ld_core_sct(coeffs_rsc_triosy_0_3_obj_ld_core_sct)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_3_i_1
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_3_i_1 (
  clk, rst, coeffs_rsc_0_3_i_q_d, coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d,
      core_wen, core_wten, coeffs_rsc_0_3_i_oswt, coeffs_rsc_0_3_i_q_d_mxwt, coeffs_rsc_0_3_i_oswt_pff
);
  input clk;
  input rst;
  input [6:0] coeffs_rsc_0_3_i_q_d;
  output coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  input core_wen;
  input core_wten;
  input coeffs_rsc_0_3_i_oswt;
  output [6:0] coeffs_rsc_0_3_i_q_d_mxwt;
  input coeffs_rsc_0_3_i_oswt_pff;


  // Interconnect Declarations
  wire coeffs_rsc_0_3_i_biwt;
  wire coeffs_rsc_0_3_i_bdwt;
  wire coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;


  // Interconnect Declarations for Component Instantiations 
  test_core_coeffs_rsc_0_3_i_1_coeffs_rsc_0_3_wait_ctrl test_core_coeffs_rsc_0_3_i_1_coeffs_rsc_0_3_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .core_wten(core_wten),
      .coeffs_rsc_0_3_i_oswt(coeffs_rsc_0_3_i_oswt),
      .coeffs_rsc_0_3_i_biwt(coeffs_rsc_0_3_i_biwt),
      .coeffs_rsc_0_3_i_bdwt(coeffs_rsc_0_3_i_bdwt),
      .coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct(coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct),
      .coeffs_rsc_0_3_i_oswt_pff(coeffs_rsc_0_3_i_oswt_pff)
    );
  test_core_coeffs_rsc_0_3_i_1_coeffs_rsc_0_3_wait_dp test_core_coeffs_rsc_0_3_i_1_coeffs_rsc_0_3_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .coeffs_rsc_0_3_i_q_d(coeffs_rsc_0_3_i_q_d),
      .coeffs_rsc_0_3_i_q_d_mxwt(coeffs_rsc_0_3_i_q_d_mxwt),
      .coeffs_rsc_0_3_i_biwt(coeffs_rsc_0_3_i_biwt),
      .coeffs_rsc_0_3_i_bdwt(coeffs_rsc_0_3_i_bdwt)
    );
  assign coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d = coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_2_i_1
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_2_i_1 (
  clk, rst, coeffs_rsc_0_2_i_q_d, coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d,
      core_wen, core_wten, coeffs_rsc_0_2_i_oswt, coeffs_rsc_0_2_i_q_d_mxwt, coeffs_rsc_0_2_i_oswt_pff
);
  input clk;
  input rst;
  input [6:0] coeffs_rsc_0_2_i_q_d;
  output coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  input core_wen;
  input core_wten;
  input coeffs_rsc_0_2_i_oswt;
  output [6:0] coeffs_rsc_0_2_i_q_d_mxwt;
  input coeffs_rsc_0_2_i_oswt_pff;


  // Interconnect Declarations
  wire coeffs_rsc_0_2_i_biwt;
  wire coeffs_rsc_0_2_i_bdwt;
  wire coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;


  // Interconnect Declarations for Component Instantiations 
  test_core_coeffs_rsc_0_2_i_1_coeffs_rsc_0_2_wait_ctrl test_core_coeffs_rsc_0_2_i_1_coeffs_rsc_0_2_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .core_wten(core_wten),
      .coeffs_rsc_0_2_i_oswt(coeffs_rsc_0_2_i_oswt),
      .coeffs_rsc_0_2_i_biwt(coeffs_rsc_0_2_i_biwt),
      .coeffs_rsc_0_2_i_bdwt(coeffs_rsc_0_2_i_bdwt),
      .coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct(coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct),
      .coeffs_rsc_0_2_i_oswt_pff(coeffs_rsc_0_2_i_oswt_pff)
    );
  test_core_coeffs_rsc_0_2_i_1_coeffs_rsc_0_2_wait_dp test_core_coeffs_rsc_0_2_i_1_coeffs_rsc_0_2_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .coeffs_rsc_0_2_i_q_d(coeffs_rsc_0_2_i_q_d),
      .coeffs_rsc_0_2_i_q_d_mxwt(coeffs_rsc_0_2_i_q_d_mxwt),
      .coeffs_rsc_0_2_i_biwt(coeffs_rsc_0_2_i_biwt),
      .coeffs_rsc_0_2_i_bdwt(coeffs_rsc_0_2_i_bdwt)
    );
  assign coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d = coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_1_i_1
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_1_i_1 (
  clk, rst, coeffs_rsc_0_1_i_q_d, coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d,
      core_wen, core_wten, coeffs_rsc_0_1_i_oswt, coeffs_rsc_0_1_i_q_d_mxwt, coeffs_rsc_0_1_i_oswt_pff
);
  input clk;
  input rst;
  input [6:0] coeffs_rsc_0_1_i_q_d;
  output coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  input core_wen;
  input core_wten;
  input coeffs_rsc_0_1_i_oswt;
  output [6:0] coeffs_rsc_0_1_i_q_d_mxwt;
  input coeffs_rsc_0_1_i_oswt_pff;


  // Interconnect Declarations
  wire coeffs_rsc_0_1_i_biwt;
  wire coeffs_rsc_0_1_i_bdwt;
  wire coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;


  // Interconnect Declarations for Component Instantiations 
  test_core_coeffs_rsc_0_1_i_1_coeffs_rsc_0_1_wait_ctrl test_core_coeffs_rsc_0_1_i_1_coeffs_rsc_0_1_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .core_wten(core_wten),
      .coeffs_rsc_0_1_i_oswt(coeffs_rsc_0_1_i_oswt),
      .coeffs_rsc_0_1_i_biwt(coeffs_rsc_0_1_i_biwt),
      .coeffs_rsc_0_1_i_bdwt(coeffs_rsc_0_1_i_bdwt),
      .coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct(coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct),
      .coeffs_rsc_0_1_i_oswt_pff(coeffs_rsc_0_1_i_oswt_pff)
    );
  test_core_coeffs_rsc_0_1_i_1_coeffs_rsc_0_1_wait_dp test_core_coeffs_rsc_0_1_i_1_coeffs_rsc_0_1_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .coeffs_rsc_0_1_i_q_d(coeffs_rsc_0_1_i_q_d),
      .coeffs_rsc_0_1_i_q_d_mxwt(coeffs_rsc_0_1_i_q_d_mxwt),
      .coeffs_rsc_0_1_i_biwt(coeffs_rsc_0_1_i_biwt),
      .coeffs_rsc_0_1_i_bdwt(coeffs_rsc_0_1_i_bdwt)
    );
  assign coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d = coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeffs_rsc_0_0_i_1
// ------------------------------------------------------------------


module test_core_coeffs_rsc_0_0_i_1 (
  clk, rst, coeffs_rsc_0_0_i_q_d, coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d,
      core_wen, core_wten, coeffs_rsc_0_0_i_oswt, coeffs_rsc_0_0_i_q_d_mxwt, coeffs_rsc_0_0_i_oswt_pff
);
  input clk;
  input rst;
  input [6:0] coeffs_rsc_0_0_i_q_d;
  output coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  input core_wen;
  input core_wten;
  input coeffs_rsc_0_0_i_oswt;
  output [6:0] coeffs_rsc_0_0_i_q_d_mxwt;
  input coeffs_rsc_0_0_i_oswt_pff;


  // Interconnect Declarations
  wire coeffs_rsc_0_0_i_biwt;
  wire coeffs_rsc_0_0_i_bdwt;
  wire coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;


  // Interconnect Declarations for Component Instantiations 
  test_core_coeffs_rsc_0_0_i_1_coeffs_rsc_0_0_wait_ctrl test_core_coeffs_rsc_0_0_i_1_coeffs_rsc_0_0_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .core_wten(core_wten),
      .coeffs_rsc_0_0_i_oswt(coeffs_rsc_0_0_i_oswt),
      .coeffs_rsc_0_0_i_biwt(coeffs_rsc_0_0_i_biwt),
      .coeffs_rsc_0_0_i_bdwt(coeffs_rsc_0_0_i_bdwt),
      .coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct(coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct),
      .coeffs_rsc_0_0_i_oswt_pff(coeffs_rsc_0_0_i_oswt_pff)
    );
  test_core_coeffs_rsc_0_0_i_1_coeffs_rsc_0_0_wait_dp test_core_coeffs_rsc_0_0_i_1_coeffs_rsc_0_0_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .coeffs_rsc_0_0_i_q_d(coeffs_rsc_0_0_i_q_d),
      .coeffs_rsc_0_0_i_q_d_mxwt(coeffs_rsc_0_0_i_q_d_mxwt),
      .coeffs_rsc_0_0_i_biwt(coeffs_rsc_0_0_i_biwt),
      .coeffs_rsc_0_0_i_bdwt(coeffs_rsc_0_0_i_bdwt)
    );
  assign coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d = coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_core_sct;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_result_rsci
// ------------------------------------------------------------------


module test_core_result_rsci (
  clk, rst, result_rsc_dat, result_rsc_vld, result_rsc_rdy, core_wen, result_rsci_oswt,
      result_rsci_wen_comp, result_rsci_idat
);
  input clk;
  input rst;
  output [18:0] result_rsc_dat;
  output result_rsc_vld;
  input result_rsc_rdy;
  input core_wen;
  input result_rsci_oswt;
  output result_rsci_wen_comp;
  input [18:0] result_rsci_idat;


  // Interconnect Declarations
  wire result_rsci_irdy;
  wire result_rsci_biwt;
  wire result_rsci_bdwt;
  wire result_rsci_bcwt;
  wire result_rsci_ivld_core_sct;


  // Interconnect Declarations for Component Instantiations 
  ccs_out_wait_v1 #(.rscid(32'sd4),
  .width(32'sd19)) result_rsci (
      .irdy(result_rsci_irdy),
      .ivld(result_rsci_ivld_core_sct),
      .idat(result_rsci_idat),
      .rdy(result_rsc_rdy),
      .vld(result_rsc_vld),
      .dat(result_rsc_dat)
    );
  test_core_result_rsci_result_wait_ctrl test_core_result_rsci_result_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .result_rsci_oswt(result_rsci_oswt),
      .result_rsci_irdy(result_rsci_irdy),
      .result_rsci_biwt(result_rsci_biwt),
      .result_rsci_bdwt(result_rsci_bdwt),
      .result_rsci_bcwt(result_rsci_bcwt),
      .result_rsci_ivld_core_sct(result_rsci_ivld_core_sct)
    );
  test_core_result_rsci_result_wait_dp test_core_result_rsci_result_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .result_rsci_oswt(result_rsci_oswt),
      .result_rsci_wen_comp(result_rsci_wen_comp),
      .result_rsci_biwt(result_rsci_biwt),
      .result_rsci_bdwt(result_rsci_bdwt),
      .result_rsci_bcwt(result_rsci_bcwt)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_coeff_addr_rsci
// ------------------------------------------------------------------


module test_core_coeff_addr_rsci (
  clk, rst, coeff_addr_rsc_dat, coeff_addr_rsc_vld, coeff_addr_rsc_rdy, core_wen,
      coeff_addr_rsci_oswt, coeff_addr_rsci_wen_comp, coeff_addr_rsci_idat_mxwt
);
  input clk;
  input rst;
  input [4:0] coeff_addr_rsc_dat;
  input coeff_addr_rsc_vld;
  output coeff_addr_rsc_rdy;
  input core_wen;
  input coeff_addr_rsci_oswt;
  output coeff_addr_rsci_wen_comp;
  output [4:0] coeff_addr_rsci_idat_mxwt;


  // Interconnect Declarations
  wire coeff_addr_rsci_biwt;
  wire coeff_addr_rsci_bdwt;
  wire coeff_addr_rsci_bcwt;
  wire coeff_addr_rsci_irdy_core_sct;
  wire coeff_addr_rsci_ivld;
  wire [4:0] coeff_addr_rsci_idat;


  // Interconnect Declarations for Component Instantiations 
  ccs_in_wait_v1 #(.rscid(32'sd3),
  .width(32'sd5)) coeff_addr_rsci (
      .rdy(coeff_addr_rsc_rdy),
      .vld(coeff_addr_rsc_vld),
      .dat(coeff_addr_rsc_dat),
      .irdy(coeff_addr_rsci_irdy_core_sct),
      .ivld(coeff_addr_rsci_ivld),
      .idat(coeff_addr_rsci_idat)
    );
  test_core_coeff_addr_rsci_coeff_addr_wait_ctrl test_core_coeff_addr_rsci_coeff_addr_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .coeff_addr_rsci_oswt(coeff_addr_rsci_oswt),
      .coeff_addr_rsci_biwt(coeff_addr_rsci_biwt),
      .coeff_addr_rsci_bdwt(coeff_addr_rsci_bdwt),
      .coeff_addr_rsci_bcwt(coeff_addr_rsci_bcwt),
      .coeff_addr_rsci_irdy_core_sct(coeff_addr_rsci_irdy_core_sct),
      .coeff_addr_rsci_ivld(coeff_addr_rsci_ivld)
    );
  test_core_coeff_addr_rsci_coeff_addr_wait_dp test_core_coeff_addr_rsci_coeff_addr_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .coeff_addr_rsci_oswt(coeff_addr_rsci_oswt),
      .coeff_addr_rsci_wen_comp(coeff_addr_rsci_wen_comp),
      .coeff_addr_rsci_idat_mxwt(coeff_addr_rsci_idat_mxwt),
      .coeff_addr_rsci_biwt(coeff_addr_rsci_biwt),
      .coeff_addr_rsci_bdwt(coeff_addr_rsci_bdwt),
      .coeff_addr_rsci_bcwt(coeff_addr_rsci_bcwt),
      .coeff_addr_rsci_idat(coeff_addr_rsci_idat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core_data_in_rsci
// ------------------------------------------------------------------


module test_core_data_in_rsci (
  clk, rst, data_in_rsc_dat, data_in_rsc_vld, data_in_rsc_rdy, core_wen, data_in_rsci_oswt,
      data_in_rsci_wen_comp, data_in_rsci_idat_mxwt
);
  input clk;
  input rst;
  input [9:0] data_in_rsc_dat;
  input data_in_rsc_vld;
  output data_in_rsc_rdy;
  input core_wen;
  input data_in_rsci_oswt;
  output data_in_rsci_wen_comp;
  output [9:0] data_in_rsci_idat_mxwt;


  // Interconnect Declarations
  wire data_in_rsci_biwt;
  wire data_in_rsci_bdwt;
  wire data_in_rsci_bcwt;
  wire data_in_rsci_irdy_core_sct;
  wire data_in_rsci_ivld;
  wire [9:0] data_in_rsci_idat;


  // Interconnect Declarations for Component Instantiations 
  ccs_in_wait_v1 #(.rscid(32'sd1),
  .width(32'sd10)) data_in_rsci (
      .rdy(data_in_rsc_rdy),
      .vld(data_in_rsc_vld),
      .dat(data_in_rsc_dat),
      .irdy(data_in_rsci_irdy_core_sct),
      .ivld(data_in_rsci_ivld),
      .idat(data_in_rsci_idat)
    );
  test_core_data_in_rsci_data_in_wait_ctrl test_core_data_in_rsci_data_in_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .data_in_rsci_oswt(data_in_rsci_oswt),
      .data_in_rsci_biwt(data_in_rsci_biwt),
      .data_in_rsci_bdwt(data_in_rsci_bdwt),
      .data_in_rsci_bcwt(data_in_rsci_bcwt),
      .data_in_rsci_irdy_core_sct(data_in_rsci_irdy_core_sct),
      .data_in_rsci_ivld(data_in_rsci_ivld)
    );
  test_core_data_in_rsci_data_in_wait_dp test_core_data_in_rsci_data_in_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .data_in_rsci_oswt(data_in_rsci_oswt),
      .data_in_rsci_wen_comp(data_in_rsci_wen_comp),
      .data_in_rsci_idat_mxwt(data_in_rsci_idat_mxwt),
      .data_in_rsci_biwt(data_in_rsci_biwt),
      .data_in_rsci_bdwt(data_in_rsci_bdwt),
      .data_in_rsci_bcwt(data_in_rsci_bcwt),
      .data_in_rsci_idat(data_in_rsci_idat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    test_core
// ------------------------------------------------------------------


module test_core (
  clk, rst, data_in_rsc_dat, data_in_rsc_vld, data_in_rsc_rdy, coeffs_rsc_triosy_0_0_lz,
      coeffs_rsc_triosy_0_1_lz, coeffs_rsc_triosy_0_2_lz, coeffs_rsc_triosy_0_3_lz,
      coeff_addr_rsc_dat, coeff_addr_rsc_vld, coeff_addr_rsc_rdy, result_rsc_dat,
      result_rsc_vld, result_rsc_rdy, coeffs_rsc_0_0_i_q_d, coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d,
      coeffs_rsc_0_1_i_q_d, coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d,
      coeffs_rsc_0_2_i_q_d, coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d,
      coeffs_rsc_0_3_i_q_d, coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d,
      coeffs_rsc_0_0_i_adr_d_pff
);
  input clk;
  input rst;
  input [9:0] data_in_rsc_dat;
  input data_in_rsc_vld;
  output data_in_rsc_rdy;
  output coeffs_rsc_triosy_0_0_lz;
  output coeffs_rsc_triosy_0_1_lz;
  output coeffs_rsc_triosy_0_2_lz;
  output coeffs_rsc_triosy_0_3_lz;
  input [4:0] coeff_addr_rsc_dat;
  input coeff_addr_rsc_vld;
  output coeff_addr_rsc_rdy;
  output [18:0] result_rsc_dat;
  output result_rsc_vld;
  input result_rsc_rdy;
  input [6:0] coeffs_rsc_0_0_i_q_d;
  output coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  input [6:0] coeffs_rsc_0_1_i_q_d;
  output coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  input [6:0] coeffs_rsc_0_2_i_q_d;
  output coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  input [6:0] coeffs_rsc_0_3_i_q_d;
  output coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  output [4:0] coeffs_rsc_0_0_i_adr_d_pff;


  // Interconnect Declarations
  wire core_wen;
  wire core_wten;
  wire data_in_rsci_wen_comp;
  wire [9:0] data_in_rsci_idat_mxwt;
  wire coeff_addr_rsci_wen_comp;
  wire [4:0] coeff_addr_rsci_idat_mxwt;
  wire result_rsci_wen_comp;
  reg [18:0] result_rsci_idat;
  wire [20:0] nl_result_rsci_idat;
  wire [6:0] coeffs_rsc_0_0_i_q_d_mxwt;
  wire [6:0] coeffs_rsc_0_1_i_q_d_mxwt;
  wire [6:0] coeffs_rsc_0_2_i_q_d_mxwt;
  wire [6:0] coeffs_rsc_0_3_i_q_d_mxwt;
  wire [1:0] fsm_output;
  reg reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse;
  reg reg_result_rsci_ivld_core_psct_cse;
  reg reg_coeff_addr_rsci_irdy_core_psct_cse;
  wire coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg;
  wire coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg;
  wire coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg;
  wire coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg;
  reg [9:0] SHIFT_if_asn_ncse_sva_1;
  reg [9:0] MAC_asn_itm_1;
  reg [9:0] MAC_asn_4_itm_1;
  reg [9:0] MAC_asn_5_itm_1;
  wire MAC_asn_5_itm_1_mx0c1;

  wire[16:0] MAC_3_mul_nl;
  wire[16:0] MAC_4_mul_nl;
  wire[16:0] MAC_1_mul_nl;
  wire[16:0] MAC_2_mul_nl;
  wire[0:0] MAC_not_nl;

  // Interconnect Declarations for Component Instantiations 
  wire [0:0] nl_test_core_coeffs_rsc_0_0_i_1_inst_coeffs_rsc_0_0_i_oswt_pff;
  assign nl_test_core_coeffs_rsc_0_0_i_1_inst_coeffs_rsc_0_0_i_oswt_pff = fsm_output[1];
  wire [0:0] nl_test_core_coeffs_rsc_0_1_i_1_inst_coeffs_rsc_0_1_i_oswt_pff;
  assign nl_test_core_coeffs_rsc_0_1_i_1_inst_coeffs_rsc_0_1_i_oswt_pff = fsm_output[1];
  wire [0:0] nl_test_core_coeffs_rsc_0_2_i_1_inst_coeffs_rsc_0_2_i_oswt_pff;
  assign nl_test_core_coeffs_rsc_0_2_i_1_inst_coeffs_rsc_0_2_i_oswt_pff = fsm_output[1];
  wire [0:0] nl_test_core_coeffs_rsc_0_3_i_1_inst_coeffs_rsc_0_3_i_oswt_pff;
  assign nl_test_core_coeffs_rsc_0_3_i_1_inst_coeffs_rsc_0_3_i_oswt_pff = fsm_output[1];
  test_core_data_in_rsci test_core_data_in_rsci_inst (
      .clk(clk),
      .rst(rst),
      .data_in_rsc_dat(data_in_rsc_dat),
      .data_in_rsc_vld(data_in_rsc_vld),
      .data_in_rsc_rdy(data_in_rsc_rdy),
      .core_wen(core_wen),
      .data_in_rsci_oswt(reg_coeff_addr_rsci_irdy_core_psct_cse),
      .data_in_rsci_wen_comp(data_in_rsci_wen_comp),
      .data_in_rsci_idat_mxwt(data_in_rsci_idat_mxwt)
    );
  test_core_coeff_addr_rsci test_core_coeff_addr_rsci_inst (
      .clk(clk),
      .rst(rst),
      .coeff_addr_rsc_dat(coeff_addr_rsc_dat),
      .coeff_addr_rsc_vld(coeff_addr_rsc_vld),
      .coeff_addr_rsc_rdy(coeff_addr_rsc_rdy),
      .core_wen(core_wen),
      .coeff_addr_rsci_oswt(reg_coeff_addr_rsci_irdy_core_psct_cse),
      .coeff_addr_rsci_wen_comp(coeff_addr_rsci_wen_comp),
      .coeff_addr_rsci_idat_mxwt(coeff_addr_rsci_idat_mxwt)
    );
  test_core_result_rsci test_core_result_rsci_inst (
      .clk(clk),
      .rst(rst),
      .result_rsc_dat(result_rsc_dat),
      .result_rsc_vld(result_rsc_vld),
      .result_rsc_rdy(result_rsc_rdy),
      .core_wen(core_wen),
      .result_rsci_oswt(reg_result_rsci_ivld_core_psct_cse),
      .result_rsci_wen_comp(result_rsci_wen_comp),
      .result_rsci_idat(result_rsci_idat)
    );
  test_core_coeffs_rsc_0_0_i_1 test_core_coeffs_rsc_0_0_i_1_inst (
      .clk(clk),
      .rst(rst),
      .coeffs_rsc_0_0_i_q_d(coeffs_rsc_0_0_i_q_d),
      .coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg),
      .core_wen(core_wen),
      .core_wten(core_wten),
      .coeffs_rsc_0_0_i_oswt(reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse),
      .coeffs_rsc_0_0_i_q_d_mxwt(coeffs_rsc_0_0_i_q_d_mxwt),
      .coeffs_rsc_0_0_i_oswt_pff(nl_test_core_coeffs_rsc_0_0_i_1_inst_coeffs_rsc_0_0_i_oswt_pff[0:0])
    );
  test_core_coeffs_rsc_0_1_i_1 test_core_coeffs_rsc_0_1_i_1_inst (
      .clk(clk),
      .rst(rst),
      .coeffs_rsc_0_1_i_q_d(coeffs_rsc_0_1_i_q_d),
      .coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg),
      .core_wen(core_wen),
      .core_wten(core_wten),
      .coeffs_rsc_0_1_i_oswt(reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse),
      .coeffs_rsc_0_1_i_q_d_mxwt(coeffs_rsc_0_1_i_q_d_mxwt),
      .coeffs_rsc_0_1_i_oswt_pff(nl_test_core_coeffs_rsc_0_1_i_1_inst_coeffs_rsc_0_1_i_oswt_pff[0:0])
    );
  test_core_coeffs_rsc_0_2_i_1 test_core_coeffs_rsc_0_2_i_1_inst (
      .clk(clk),
      .rst(rst),
      .coeffs_rsc_0_2_i_q_d(coeffs_rsc_0_2_i_q_d),
      .coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg),
      .core_wen(core_wen),
      .core_wten(core_wten),
      .coeffs_rsc_0_2_i_oswt(reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse),
      .coeffs_rsc_0_2_i_q_d_mxwt(coeffs_rsc_0_2_i_q_d_mxwt),
      .coeffs_rsc_0_2_i_oswt_pff(nl_test_core_coeffs_rsc_0_2_i_1_inst_coeffs_rsc_0_2_i_oswt_pff[0:0])
    );
  test_core_coeffs_rsc_0_3_i_1 test_core_coeffs_rsc_0_3_i_1_inst (
      .clk(clk),
      .rst(rst),
      .coeffs_rsc_0_3_i_q_d(coeffs_rsc_0_3_i_q_d),
      .coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg),
      .core_wen(core_wen),
      .core_wten(core_wten),
      .coeffs_rsc_0_3_i_oswt(reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse),
      .coeffs_rsc_0_3_i_q_d_mxwt(coeffs_rsc_0_3_i_q_d_mxwt),
      .coeffs_rsc_0_3_i_oswt_pff(nl_test_core_coeffs_rsc_0_3_i_1_inst_coeffs_rsc_0_3_i_oswt_pff[0:0])
    );
  test_core_coeffs_rsc_triosy_0_3_obj test_core_coeffs_rsc_triosy_0_3_obj_inst (
      .coeffs_rsc_triosy_0_3_lz(coeffs_rsc_triosy_0_3_lz),
      .core_wten(core_wten),
      .coeffs_rsc_triosy_0_3_obj_iswt0(reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse)
    );
  test_core_coeffs_rsc_triosy_0_2_obj test_core_coeffs_rsc_triosy_0_2_obj_inst (
      .coeffs_rsc_triosy_0_2_lz(coeffs_rsc_triosy_0_2_lz),
      .core_wten(core_wten),
      .coeffs_rsc_triosy_0_2_obj_iswt0(reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse)
    );
  test_core_coeffs_rsc_triosy_0_1_obj test_core_coeffs_rsc_triosy_0_1_obj_inst (
      .coeffs_rsc_triosy_0_1_lz(coeffs_rsc_triosy_0_1_lz),
      .core_wten(core_wten),
      .coeffs_rsc_triosy_0_1_obj_iswt0(reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse)
    );
  test_core_coeffs_rsc_triosy_0_0_obj test_core_coeffs_rsc_triosy_0_0_obj_inst (
      .coeffs_rsc_triosy_0_0_lz(coeffs_rsc_triosy_0_0_lz),
      .core_wten(core_wten),
      .coeffs_rsc_triosy_0_0_obj_iswt0(reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse)
    );
  test_core_staller test_core_staller_inst (
      .clk(clk),
      .rst(rst),
      .core_wen(core_wen),
      .core_wten(core_wten),
      .data_in_rsci_wen_comp(data_in_rsci_wen_comp),
      .coeff_addr_rsci_wen_comp(coeff_addr_rsci_wen_comp),
      .result_rsci_wen_comp(result_rsci_wen_comp)
    );
  test_core_core_fsm test_core_core_fsm_inst (
      .clk(clk),
      .rst(rst),
      .core_wen(core_wen),
      .fsm_output(fsm_output)
    );
  assign MAC_asn_5_itm_1_mx0c1 = (~ reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse)
      & (fsm_output[1]);
  assign coeffs_rsc_0_0_i_adr_d_pff = coeff_addr_rsci_idat_mxwt;
  assign coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d = coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg;
  assign coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d = coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg;
  assign coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d = coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg;
  assign coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d = coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d_reg;
  always @(posedge clk) begin
    if ( rst ) begin
      reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse <= 1'b0;
      reg_result_rsci_ivld_core_psct_cse <= 1'b0;
      reg_coeff_addr_rsci_irdy_core_psct_cse <= 1'b0;
      MAC_asn_4_itm_1 <= 10'b0000000000;
      SHIFT_if_asn_ncse_sva_1 <= 10'b0000000000;
    end
    else if ( core_wen ) begin
      reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse <= fsm_output[1];
      reg_result_rsci_ivld_core_psct_cse <= reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse;
      reg_coeff_addr_rsci_irdy_core_psct_cse <= 1'b1;
      MAC_asn_4_itm_1 <= MAC_asn_itm_1;
      SHIFT_if_asn_ncse_sva_1 <= data_in_rsci_idat_mxwt;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      result_rsci_idat <= 19'b0000000000000000000;
    end
    else if ( core_wen & reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse ) begin
      result_rsci_idat <= nl_result_rsci_idat[18:0];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      MAC_asn_itm_1 <= 10'b0000000000;
    end
    else if ( core_wen & (~ (fsm_output[0])) ) begin
      MAC_asn_itm_1 <= MAC_asn_5_itm_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      MAC_asn_5_itm_1 <= 10'b0000000000;
    end
    else if ( core_wen & (reg_coeffs_rsc_triosy_0_0_obj_ld_core_psct_cse | MAC_asn_5_itm_1_mx0c1)
        ) begin
      MAC_asn_5_itm_1 <= MUX_v_10_2_2(10'b0000000000, SHIFT_if_asn_ncse_sva_1, (MAC_not_nl));
    end
  end
  assign MAC_3_mul_nl = conv_s2u_17_17($signed(MAC_asn_itm_1) * $signed((coeffs_rsc_0_2_i_q_d_mxwt)));
  assign MAC_4_mul_nl = conv_s2u_17_17($signed(MAC_asn_4_itm_1) * $signed((coeffs_rsc_0_3_i_q_d_mxwt)));
  assign MAC_1_mul_nl = conv_s2u_17_17($signed(SHIFT_if_asn_ncse_sva_1) * $signed((coeffs_rsc_0_0_i_q_d_mxwt)));
  assign MAC_2_mul_nl = conv_s2u_17_17($signed(MAC_asn_5_itm_1) * $signed((coeffs_rsc_0_1_i_q_d_mxwt)));
  assign nl_result_rsci_idat  = conv_s2s_17_19(MAC_3_mul_nl) + conv_s2s_17_19(MAC_4_mul_nl)
      + conv_s2s_17_19(MAC_1_mul_nl) + conv_s2s_17_19(MAC_2_mul_nl);
  assign MAC_not_nl = ~ MAC_asn_5_itm_1_mx0c1;

  function automatic [9:0] MUX_v_10_2_2;
    input [9:0] input_0;
    input [9:0] input_1;
    input [0:0] sel;
    reg [9:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_10_2_2 = result;
  end
  endfunction


  function automatic [18:0] conv_s2s_17_19 ;
    input [16:0]  vector ;
  begin
    conv_s2s_17_19 = {{2{vector[16]}}, vector};
  end
  endfunction


  function automatic [16:0] conv_s2u_17_17 ;
    input [16:0]  vector ;
  begin
    conv_s2u_17_17 = vector;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    test
// ------------------------------------------------------------------


module test (
  clk, rst, data_in_rsc_dat, data_in_rsc_vld, data_in_rsc_rdy, coeffs_rsc_0_0_adr,
      coeffs_rsc_0_0_d, coeffs_rsc_0_0_we, coeffs_rsc_0_0_q, coeffs_rsc_triosy_0_0_lz,
      coeffs_rsc_0_1_adr, coeffs_rsc_0_1_d, coeffs_rsc_0_1_we, coeffs_rsc_0_1_q,
      coeffs_rsc_triosy_0_1_lz, coeffs_rsc_0_2_adr, coeffs_rsc_0_2_d, coeffs_rsc_0_2_we,
      coeffs_rsc_0_2_q, coeffs_rsc_triosy_0_2_lz, coeffs_rsc_0_3_adr, coeffs_rsc_0_3_d,
      coeffs_rsc_0_3_we, coeffs_rsc_0_3_q, coeffs_rsc_triosy_0_3_lz, coeff_addr_rsc_dat,
      coeff_addr_rsc_vld, coeff_addr_rsc_rdy, result_rsc_dat, result_rsc_vld, result_rsc_rdy
);
  input clk;
  input rst;
  input [9:0] data_in_rsc_dat;
  input data_in_rsc_vld;
  output data_in_rsc_rdy;
  output [4:0] coeffs_rsc_0_0_adr;
  output [6:0] coeffs_rsc_0_0_d;
  output coeffs_rsc_0_0_we;
  input [6:0] coeffs_rsc_0_0_q;
  output coeffs_rsc_triosy_0_0_lz;
  output [4:0] coeffs_rsc_0_1_adr;
  output [6:0] coeffs_rsc_0_1_d;
  output coeffs_rsc_0_1_we;
  input [6:0] coeffs_rsc_0_1_q;
  output coeffs_rsc_triosy_0_1_lz;
  output [4:0] coeffs_rsc_0_2_adr;
  output [6:0] coeffs_rsc_0_2_d;
  output coeffs_rsc_0_2_we;
  input [6:0] coeffs_rsc_0_2_q;
  output coeffs_rsc_triosy_0_2_lz;
  output [4:0] coeffs_rsc_0_3_adr;
  output [6:0] coeffs_rsc_0_3_d;
  output coeffs_rsc_0_3_we;
  input [6:0] coeffs_rsc_0_3_q;
  output coeffs_rsc_triosy_0_3_lz;
  input [4:0] coeff_addr_rsc_dat;
  input coeff_addr_rsc_vld;
  output coeff_addr_rsc_rdy;
  output [18:0] result_rsc_dat;
  output result_rsc_vld;
  input result_rsc_rdy;


  // Interconnect Declarations
  wire [6:0] coeffs_rsc_0_0_i_q_d;
  wire coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  wire [6:0] coeffs_rsc_0_1_i_q_d;
  wire coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  wire [6:0] coeffs_rsc_0_2_i_q_d;
  wire coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  wire [6:0] coeffs_rsc_0_3_i_q_d;
  wire coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d;
  wire [4:0] coeffs_rsc_0_0_i_adr_d_iff;


  // Interconnect Declarations for Component Instantiations 
  test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_6_7_5_32_32_7_5_gen coeffs_rsc_0_0_i
      (
      .q(coeffs_rsc_0_0_q),
      .we(coeffs_rsc_0_0_we),
      .d(coeffs_rsc_0_0_d),
      .adr(coeffs_rsc_0_0_adr),
      .adr_d(coeffs_rsc_0_0_i_adr_d_iff),
      .d_d(7'b0000000),
      .we_d(1'b0),
      .q_d(coeffs_rsc_0_0_i_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d),
      .port_0_rw_ram_ir_internal_WMASK_B_d(1'b0)
    );
  test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_7_7_5_32_32_7_5_gen coeffs_rsc_0_1_i
      (
      .q(coeffs_rsc_0_1_q),
      .we(coeffs_rsc_0_1_we),
      .d(coeffs_rsc_0_1_d),
      .adr(coeffs_rsc_0_1_adr),
      .adr_d(coeffs_rsc_0_0_i_adr_d_iff),
      .d_d(7'b0000000),
      .we_d(1'b0),
      .q_d(coeffs_rsc_0_1_i_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d),
      .port_0_rw_ram_ir_internal_WMASK_B_d(1'b0)
    );
  test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_8_7_5_32_32_7_5_gen coeffs_rsc_0_2_i
      (
      .q(coeffs_rsc_0_2_q),
      .we(coeffs_rsc_0_2_we),
      .d(coeffs_rsc_0_2_d),
      .adr(coeffs_rsc_0_2_adr),
      .adr_d(coeffs_rsc_0_0_i_adr_d_iff),
      .d_d(7'b0000000),
      .we_d(1'b0),
      .q_d(coeffs_rsc_0_2_i_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d),
      .port_0_rw_ram_ir_internal_WMASK_B_d(1'b0)
    );
  test_ccs_sample_mem_ccs_ram_sync_singleport_rwport_9_7_5_32_32_7_5_gen coeffs_rsc_0_3_i
      (
      .q(coeffs_rsc_0_3_q),
      .we(coeffs_rsc_0_3_we),
      .d(coeffs_rsc_0_3_d),
      .adr(coeffs_rsc_0_3_adr),
      .adr_d(coeffs_rsc_0_0_i_adr_d_iff),
      .d_d(7'b0000000),
      .we_d(1'b0),
      .q_d(coeffs_rsc_0_3_i_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d),
      .port_0_rw_ram_ir_internal_WMASK_B_d(1'b0)
    );
  test_core test_core_inst (
      .clk(clk),
      .rst(rst),
      .data_in_rsc_dat(data_in_rsc_dat),
      .data_in_rsc_vld(data_in_rsc_vld),
      .data_in_rsc_rdy(data_in_rsc_rdy),
      .coeffs_rsc_triosy_0_0_lz(coeffs_rsc_triosy_0_0_lz),
      .coeffs_rsc_triosy_0_1_lz(coeffs_rsc_triosy_0_1_lz),
      .coeffs_rsc_triosy_0_2_lz(coeffs_rsc_triosy_0_2_lz),
      .coeffs_rsc_triosy_0_3_lz(coeffs_rsc_triosy_0_3_lz),
      .coeff_addr_rsc_dat(coeff_addr_rsc_dat),
      .coeff_addr_rsc_vld(coeff_addr_rsc_vld),
      .coeff_addr_rsc_rdy(coeff_addr_rsc_rdy),
      .result_rsc_dat(result_rsc_dat),
      .result_rsc_vld(result_rsc_vld),
      .result_rsc_rdy(result_rsc_rdy),
      .coeffs_rsc_0_0_i_q_d(coeffs_rsc_0_0_i_q_d),
      .coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_0_i_port_0_rw_ram_ir_internal_RMASK_B_d),
      .coeffs_rsc_0_1_i_q_d(coeffs_rsc_0_1_i_q_d),
      .coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_1_i_port_0_rw_ram_ir_internal_RMASK_B_d),
      .coeffs_rsc_0_2_i_q_d(coeffs_rsc_0_2_i_q_d),
      .coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_2_i_port_0_rw_ram_ir_internal_RMASK_B_d),
      .coeffs_rsc_0_3_i_q_d(coeffs_rsc_0_3_i_q_d),
      .coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d(coeffs_rsc_0_3_i_port_0_rw_ram_ir_internal_RMASK_B_d),
      .coeffs_rsc_0_0_i_adr_d_pff(coeffs_rsc_0_0_i_adr_d_iff)
    );
endmodule



