-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    10.4a/835166 Production Release
--  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
-- 
--  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
--  Generated date: Thu Nov  6 11:26:03 2025
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    test_core_core_fsm
--  FSM Module
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_core_fsm IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    core_wen : IN STD_LOGIC;
    fsm_output : OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
  );
END test_core_core_fsm;

ARCHITECTURE v1 OF test_core_core_fsm IS
  -- Default Constants

  -- FSM State Type Declaration for test_core_core_fsm_1
  TYPE test_core_core_fsm_1_ST IS (core_rlp_C_0, main_C_0);

  SIGNAL state_var : test_core_core_fsm_1_ST;
  SIGNAL state_var_NS : test_core_core_fsm_1_ST;

BEGIN
  test_core_core_fsm_1 : PROCESS (state_var)
  BEGIN
    CASE state_var IS
      WHEN main_C_0 =>
        fsm_output <= STD_LOGIC_VECTOR'( "10");
        state_var_NS <= main_C_0;
      -- core_rlp_C_0
      WHEN OTHERS =>
        fsm_output <= STD_LOGIC_VECTOR'( "01");
        state_var_NS <= main_C_0;
    END CASE;
  END PROCESS test_core_core_fsm_1;

  test_core_core_fsm_1_REG : PROCESS (clk)
  BEGIN
    IF clk'event AND ( clk = '1' ) THEN
      IF ( rst = '1' ) THEN
        state_var <= core_rlp_C_0;
      ELSE
        IF ( core_wen = '1' ) THEN
          state_var <= state_var_NS;
        END IF;
      END IF;
    END IF;
  END PROCESS test_core_core_fsm_1_REG;

END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_staller
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_staller IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    core_wen : OUT STD_LOGIC;
    core_wten : OUT STD_LOGIC;
    a_in_rsci_wen_comp : IN STD_LOGIC;
    b_in_rsci_wen_comp : IN STD_LOGIC;
    result_rsci_wen_comp : IN STD_LOGIC
  );
END test_core_staller;

ARCHITECTURE v1 OF test_core_staller IS
  -- Default Constants

  -- Output Reader Declarations
  SIGNAL core_wen_drv : STD_LOGIC;

BEGIN
  -- Output Reader Assignments
  core_wen <= core_wen_drv;

  core_wen_drv <= a_in_rsci_wen_comp AND b_in_rsci_wen_comp AND result_rsci_wen_comp;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        core_wten <= '0';
      ELSE
        core_wten <= NOT core_wen_drv;
      END IF;
    END IF;
  END PROCESS;
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_valid_in_data_rsc_triosy_obj_valid_in_data_rsc_triosy_wait_ctrl
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_valid_in_data_rsc_triosy_obj_valid_in_data_rsc_triosy_wait_ctrl
    IS
  PORT(
    core_wten : IN STD_LOGIC;
    valid_in_data_rsc_triosy_obj_iswt0 : IN STD_LOGIC;
    valid_in_data_rsc_triosy_obj_ld_core_sct : OUT STD_LOGIC
  );
END test_core_valid_in_data_rsc_triosy_obj_valid_in_data_rsc_triosy_wait_ctrl;

ARCHITECTURE v1 OF test_core_valid_in_data_rsc_triosy_obj_valid_in_data_rsc_triosy_wait_ctrl
    IS
  -- Default Constants

BEGIN
  valid_in_data_rsc_triosy_obj_ld_core_sct <= valid_in_data_rsc_triosy_obj_iswt0
      AND (NOT core_wten);
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_result_rsci_result_wait_dp
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_result_rsci_result_wait_dp IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    result_rsci_oswt : IN STD_LOGIC;
    result_rsci_wen_comp : OUT STD_LOGIC;
    result_rsci_biwt : IN STD_LOGIC;
    result_rsci_bdwt : IN STD_LOGIC;
    result_rsci_bcwt : OUT STD_LOGIC
  );
END test_core_result_rsci_result_wait_dp;

ARCHITECTURE v1 OF test_core_result_rsci_result_wait_dp IS
  -- Default Constants

  -- Output Reader Declarations
  SIGNAL result_rsci_bcwt_drv : STD_LOGIC;

BEGIN
  -- Output Reader Assignments
  result_rsci_bcwt <= result_rsci_bcwt_drv;

  result_rsci_wen_comp <= (NOT result_rsci_oswt) OR result_rsci_biwt OR result_rsci_bcwt_drv;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        result_rsci_bcwt_drv <= '0';
      ELSE
        result_rsci_bcwt_drv <= NOT((NOT(result_rsci_bcwt_drv OR result_rsci_biwt))
            OR result_rsci_bdwt);
      END IF;
    END IF;
  END PROCESS;
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_result_rsci_result_wait_ctrl
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_result_rsci_result_wait_ctrl IS
  PORT(
    core_wen : IN STD_LOGIC;
    result_rsci_oswt : IN STD_LOGIC;
    result_rsci_irdy : IN STD_LOGIC;
    result_rsci_biwt : OUT STD_LOGIC;
    result_rsci_bdwt : OUT STD_LOGIC;
    result_rsci_bcwt : IN STD_LOGIC;
    result_rsci_ivld_core_sct : OUT STD_LOGIC
  );
END test_core_result_rsci_result_wait_ctrl;

ARCHITECTURE v1 OF test_core_result_rsci_result_wait_ctrl IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL result_rsci_ogwt : STD_LOGIC;

BEGIN
  result_rsci_bdwt <= result_rsci_oswt AND core_wen;
  result_rsci_biwt <= result_rsci_ogwt AND result_rsci_irdy;
  result_rsci_ogwt <= result_rsci_oswt AND (NOT result_rsci_bcwt);
  result_rsci_ivld_core_sct <= result_rsci_ogwt;
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_b_in_rsci_b_in_wait_dp
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_b_in_rsci_b_in_wait_dp IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    b_in_rsci_oswt : IN STD_LOGIC;
    b_in_rsci_wen_comp : OUT STD_LOGIC;
    b_in_rsci_idat_mxwt : OUT STD_LOGIC_VECTOR (127 DOWNTO 0);
    b_in_rsci_biwt : IN STD_LOGIC;
    b_in_rsci_bdwt : IN STD_LOGIC;
    b_in_rsci_bcwt : OUT STD_LOGIC;
    b_in_rsci_idat : IN STD_LOGIC_VECTOR (127 DOWNTO 0)
  );
END test_core_b_in_rsci_b_in_wait_dp;

ARCHITECTURE v1 OF test_core_b_in_rsci_b_in_wait_dp IS
  -- Default Constants

  -- Output Reader Declarations
  SIGNAL b_in_rsci_idat_mxwt_drv : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL b_in_rsci_bcwt_drv : STD_LOGIC;

  -- Interconnect Declarations
  SIGNAL b_in_rsci_idat_bfwt : STD_LOGIC_VECTOR (127 DOWNTO 0);

  FUNCTION MUX_v_128_2_2(input_0 : STD_LOGIC_VECTOR(127 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(127 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(127 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

BEGIN
  -- Output Reader Assignments
  b_in_rsci_idat_mxwt <= b_in_rsci_idat_mxwt_drv;
  b_in_rsci_bcwt <= b_in_rsci_bcwt_drv;

  b_in_rsci_wen_comp <= (NOT b_in_rsci_oswt) OR b_in_rsci_biwt OR b_in_rsci_bcwt_drv;
  b_in_rsci_idat_mxwt_drv <= MUX_v_128_2_2(b_in_rsci_idat, b_in_rsci_idat_bfwt, b_in_rsci_bcwt_drv);
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        b_in_rsci_bcwt_drv <= '0';
      ELSE
        b_in_rsci_bcwt_drv <= NOT((NOT(b_in_rsci_bcwt_drv OR b_in_rsci_biwt)) OR
            b_in_rsci_bdwt);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        b_in_rsci_idat_bfwt <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      ELSIF ( b_in_rsci_bcwt_drv = '0' ) THEN
        b_in_rsci_idat_bfwt <= b_in_rsci_idat_mxwt_drv;
      END IF;
    END IF;
  END PROCESS;
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_b_in_rsci_b_in_wait_ctrl
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_b_in_rsci_b_in_wait_ctrl IS
  PORT(
    core_wen : IN STD_LOGIC;
    b_in_rsci_oswt : IN STD_LOGIC;
    b_in_rsci_biwt : OUT STD_LOGIC;
    b_in_rsci_bdwt : OUT STD_LOGIC;
    b_in_rsci_bcwt : IN STD_LOGIC;
    b_in_rsci_irdy_core_sct : OUT STD_LOGIC;
    b_in_rsci_ivld : IN STD_LOGIC
  );
END test_core_b_in_rsci_b_in_wait_ctrl;

ARCHITECTURE v1 OF test_core_b_in_rsci_b_in_wait_ctrl IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL b_in_rsci_ogwt : STD_LOGIC;

BEGIN
  b_in_rsci_bdwt <= b_in_rsci_oswt AND core_wen;
  b_in_rsci_biwt <= b_in_rsci_ogwt AND b_in_rsci_ivld;
  b_in_rsci_ogwt <= b_in_rsci_oswt AND (NOT b_in_rsci_bcwt);
  b_in_rsci_irdy_core_sct <= b_in_rsci_ogwt;
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_a_in_rsci_a_in_wait_dp
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_a_in_rsci_a_in_wait_dp IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    a_in_rsci_oswt : IN STD_LOGIC;
    a_in_rsci_wen_comp : OUT STD_LOGIC;
    a_in_rsci_idat_mxwt : OUT STD_LOGIC_VECTOR (127 DOWNTO 0);
    a_in_rsci_biwt : IN STD_LOGIC;
    a_in_rsci_bdwt : IN STD_LOGIC;
    a_in_rsci_bcwt : OUT STD_LOGIC;
    a_in_rsci_idat : IN STD_LOGIC_VECTOR (127 DOWNTO 0)
  );
END test_core_a_in_rsci_a_in_wait_dp;

ARCHITECTURE v1 OF test_core_a_in_rsci_a_in_wait_dp IS
  -- Default Constants

  -- Output Reader Declarations
  SIGNAL a_in_rsci_idat_mxwt_drv : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL a_in_rsci_bcwt_drv : STD_LOGIC;

  -- Interconnect Declarations
  SIGNAL a_in_rsci_idat_bfwt : STD_LOGIC_VECTOR (127 DOWNTO 0);

  FUNCTION MUX_v_128_2_2(input_0 : STD_LOGIC_VECTOR(127 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(127 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(127 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

BEGIN
  -- Output Reader Assignments
  a_in_rsci_idat_mxwt <= a_in_rsci_idat_mxwt_drv;
  a_in_rsci_bcwt <= a_in_rsci_bcwt_drv;

  a_in_rsci_wen_comp <= (NOT a_in_rsci_oswt) OR a_in_rsci_biwt OR a_in_rsci_bcwt_drv;
  a_in_rsci_idat_mxwt_drv <= MUX_v_128_2_2(a_in_rsci_idat, a_in_rsci_idat_bfwt, a_in_rsci_bcwt_drv);
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        a_in_rsci_bcwt_drv <= '0';
      ELSE
        a_in_rsci_bcwt_drv <= NOT((NOT(a_in_rsci_bcwt_drv OR a_in_rsci_biwt)) OR
            a_in_rsci_bdwt);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        a_in_rsci_idat_bfwt <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      ELSIF ( a_in_rsci_bcwt_drv = '0' ) THEN
        a_in_rsci_idat_bfwt <= a_in_rsci_idat_mxwt_drv;
      END IF;
    END IF;
  END PROCESS;
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_a_in_rsci_a_in_wait_ctrl
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_a_in_rsci_a_in_wait_ctrl IS
  PORT(
    core_wen : IN STD_LOGIC;
    a_in_rsci_oswt : IN STD_LOGIC;
    a_in_rsci_biwt : OUT STD_LOGIC;
    a_in_rsci_bdwt : OUT STD_LOGIC;
    a_in_rsci_bcwt : IN STD_LOGIC;
    a_in_rsci_irdy_core_sct : OUT STD_LOGIC;
    a_in_rsci_ivld : IN STD_LOGIC
  );
END test_core_a_in_rsci_a_in_wait_ctrl;

ARCHITECTURE v1 OF test_core_a_in_rsci_a_in_wait_ctrl IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL a_in_rsci_ogwt : STD_LOGIC;

BEGIN
  a_in_rsci_bdwt <= a_in_rsci_oswt AND core_wen;
  a_in_rsci_biwt <= a_in_rsci_ogwt AND a_in_rsci_ivld;
  a_in_rsci_ogwt <= a_in_rsci_oswt AND (NOT a_in_rsci_bcwt);
  a_in_rsci_irdy_core_sct <= a_in_rsci_ogwt;
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_valid_in_data_rsc_triosy_obj
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_valid_in_data_rsc_triosy_obj IS
  PORT(
    valid_in_data_rsc_triosy_lz : OUT STD_LOGIC;
    core_wten : IN STD_LOGIC;
    valid_in_data_rsc_triosy_obj_iswt0 : IN STD_LOGIC
  );
END test_core_valid_in_data_rsc_triosy_obj;

ARCHITECTURE v1 OF test_core_valid_in_data_rsc_triosy_obj IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL valid_in_data_rsc_triosy_obj_ld_core_sct : STD_LOGIC;

  COMPONENT test_core_valid_in_data_rsc_triosy_obj_valid_in_data_rsc_triosy_wait_ctrl
    PORT(
      core_wten : IN STD_LOGIC;
      valid_in_data_rsc_triosy_obj_iswt0 : IN STD_LOGIC;
      valid_in_data_rsc_triosy_obj_ld_core_sct : OUT STD_LOGIC
    );
  END COMPONENT;
BEGIN
  valid_in_data_rsc_triosy_obj : mgc_hls.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => valid_in_data_rsc_triosy_obj_ld_core_sct,
      lz => valid_in_data_rsc_triosy_lz
    );
  test_core_valid_in_data_rsc_triosy_obj_valid_in_data_rsc_triosy_wait_ctrl_inst
      : test_core_valid_in_data_rsc_triosy_obj_valid_in_data_rsc_triosy_wait_ctrl
    PORT MAP(
      core_wten => core_wten,
      valid_in_data_rsc_triosy_obj_iswt0 => valid_in_data_rsc_triosy_obj_iswt0,
      valid_in_data_rsc_triosy_obj_ld_core_sct => valid_in_data_rsc_triosy_obj_ld_core_sct
    );
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_result_rsci
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_result_rsci IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    result_rsc_dat : OUT STD_LOGIC_VECTOR (19 DOWNTO 0);
    result_rsc_vld : OUT STD_LOGIC;
    result_rsc_rdy : IN STD_LOGIC;
    core_wen : IN STD_LOGIC;
    result_rsci_oswt : IN STD_LOGIC;
    result_rsci_wen_comp : OUT STD_LOGIC;
    result_rsci_idat : IN STD_LOGIC_VECTOR (19 DOWNTO 0)
  );
END test_core_result_rsci;

ARCHITECTURE v1 OF test_core_result_rsci IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL result_rsci_irdy : STD_LOGIC;
  SIGNAL result_rsci_biwt : STD_LOGIC;
  SIGNAL result_rsci_bdwt : STD_LOGIC;
  SIGNAL result_rsci_bcwt : STD_LOGIC;
  SIGNAL result_rsci_ivld_core_sct : STD_LOGIC;

  SIGNAL result_rsci_idat_1 : STD_LOGIC_VECTOR (19 DOWNTO 0);
  SIGNAL result_rsci_dat : STD_LOGIC_VECTOR (19 DOWNTO 0);

  COMPONENT test_core_result_rsci_result_wait_ctrl
    PORT(
      core_wen : IN STD_LOGIC;
      result_rsci_oswt : IN STD_LOGIC;
      result_rsci_irdy : IN STD_LOGIC;
      result_rsci_biwt : OUT STD_LOGIC;
      result_rsci_bdwt : OUT STD_LOGIC;
      result_rsci_bcwt : IN STD_LOGIC;
      result_rsci_ivld_core_sct : OUT STD_LOGIC
    );
  END COMPONENT;
  COMPONENT test_core_result_rsci_result_wait_dp
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      result_rsci_oswt : IN STD_LOGIC;
      result_rsci_wen_comp : OUT STD_LOGIC;
      result_rsci_biwt : IN STD_LOGIC;
      result_rsci_bdwt : IN STD_LOGIC;
      result_rsci_bcwt : OUT STD_LOGIC
    );
  END COMPONENT;
BEGIN
  result_rsci : mgc_hls.ccs_out_wait_pkg_v1.ccs_out_wait_v1
    GENERIC MAP(
      rscid => 4,
      width => 20
      )
    PORT MAP(
      irdy => result_rsci_irdy,
      ivld => result_rsci_ivld_core_sct,
      idat => result_rsci_idat_1,
      rdy => result_rsc_rdy,
      vld => result_rsc_vld,
      dat => result_rsci_dat
    );
  result_rsci_idat_1 <= result_rsci_idat;
  result_rsc_dat <= result_rsci_dat;

  test_core_result_rsci_result_wait_ctrl_inst : test_core_result_rsci_result_wait_ctrl
    PORT MAP(
      core_wen => core_wen,
      result_rsci_oswt => result_rsci_oswt,
      result_rsci_irdy => result_rsci_irdy,
      result_rsci_biwt => result_rsci_biwt,
      result_rsci_bdwt => result_rsci_bdwt,
      result_rsci_bcwt => result_rsci_bcwt,
      result_rsci_ivld_core_sct => result_rsci_ivld_core_sct
    );
  test_core_result_rsci_result_wait_dp_inst : test_core_result_rsci_result_wait_dp
    PORT MAP(
      clk => clk,
      rst => rst,
      result_rsci_oswt => result_rsci_oswt,
      result_rsci_wen_comp => result_rsci_wen_comp,
      result_rsci_biwt => result_rsci_biwt,
      result_rsci_bdwt => result_rsci_bdwt,
      result_rsci_bcwt => result_rsci_bcwt
    );
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_b_in_rsci
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_b_in_rsci IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    b_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
    b_in_rsc_vld : IN STD_LOGIC;
    b_in_rsc_rdy : OUT STD_LOGIC;
    core_wen : IN STD_LOGIC;
    b_in_rsci_oswt : IN STD_LOGIC;
    b_in_rsci_wen_comp : OUT STD_LOGIC;
    b_in_rsci_idat_mxwt : OUT STD_LOGIC_VECTOR (127 DOWNTO 0)
  );
END test_core_b_in_rsci;

ARCHITECTURE v1 OF test_core_b_in_rsci IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL b_in_rsci_biwt : STD_LOGIC;
  SIGNAL b_in_rsci_bdwt : STD_LOGIC;
  SIGNAL b_in_rsci_bcwt : STD_LOGIC;
  SIGNAL b_in_rsci_irdy_core_sct : STD_LOGIC;
  SIGNAL b_in_rsci_ivld : STD_LOGIC;
  SIGNAL b_in_rsci_idat : STD_LOGIC_VECTOR (127 DOWNTO 0);

  SIGNAL b_in_rsci_dat : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL b_in_rsci_idat_1 : STD_LOGIC_VECTOR (127 DOWNTO 0);

  COMPONENT test_core_b_in_rsci_b_in_wait_ctrl
    PORT(
      core_wen : IN STD_LOGIC;
      b_in_rsci_oswt : IN STD_LOGIC;
      b_in_rsci_biwt : OUT STD_LOGIC;
      b_in_rsci_bdwt : OUT STD_LOGIC;
      b_in_rsci_bcwt : IN STD_LOGIC;
      b_in_rsci_irdy_core_sct : OUT STD_LOGIC;
      b_in_rsci_ivld : IN STD_LOGIC
    );
  END COMPONENT;
  COMPONENT test_core_b_in_rsci_b_in_wait_dp
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      b_in_rsci_oswt : IN STD_LOGIC;
      b_in_rsci_wen_comp : OUT STD_LOGIC;
      b_in_rsci_idat_mxwt : OUT STD_LOGIC_VECTOR (127 DOWNTO 0);
      b_in_rsci_biwt : IN STD_LOGIC;
      b_in_rsci_bdwt : IN STD_LOGIC;
      b_in_rsci_bcwt : OUT STD_LOGIC;
      b_in_rsci_idat : IN STD_LOGIC_VECTOR (127 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL test_core_b_in_rsci_b_in_wait_dp_inst_b_in_rsci_idat_mxwt : STD_LOGIC_VECTOR
      (127 DOWNTO 0);
  SIGNAL test_core_b_in_rsci_b_in_wait_dp_inst_b_in_rsci_idat : STD_LOGIC_VECTOR
      (127 DOWNTO 0);

BEGIN
  b_in_rsci : mgc_hls.ccs_in_wait_pkg_v1.ccs_in_wait_v1
    GENERIC MAP(
      rscid => 2,
      width => 128
      )
    PORT MAP(
      rdy => b_in_rsc_rdy,
      vld => b_in_rsc_vld,
      dat => b_in_rsci_dat,
      irdy => b_in_rsci_irdy_core_sct,
      ivld => b_in_rsci_ivld,
      idat => b_in_rsci_idat_1
    );
  b_in_rsci_dat <= b_in_rsc_dat;
  b_in_rsci_idat <= b_in_rsci_idat_1;

  test_core_b_in_rsci_b_in_wait_ctrl_inst : test_core_b_in_rsci_b_in_wait_ctrl
    PORT MAP(
      core_wen => core_wen,
      b_in_rsci_oswt => b_in_rsci_oswt,
      b_in_rsci_biwt => b_in_rsci_biwt,
      b_in_rsci_bdwt => b_in_rsci_bdwt,
      b_in_rsci_bcwt => b_in_rsci_bcwt,
      b_in_rsci_irdy_core_sct => b_in_rsci_irdy_core_sct,
      b_in_rsci_ivld => b_in_rsci_ivld
    );
  test_core_b_in_rsci_b_in_wait_dp_inst : test_core_b_in_rsci_b_in_wait_dp
    PORT MAP(
      clk => clk,
      rst => rst,
      b_in_rsci_oswt => b_in_rsci_oswt,
      b_in_rsci_wen_comp => b_in_rsci_wen_comp,
      b_in_rsci_idat_mxwt => test_core_b_in_rsci_b_in_wait_dp_inst_b_in_rsci_idat_mxwt,
      b_in_rsci_biwt => b_in_rsci_biwt,
      b_in_rsci_bdwt => b_in_rsci_bdwt,
      b_in_rsci_bcwt => b_in_rsci_bcwt,
      b_in_rsci_idat => test_core_b_in_rsci_b_in_wait_dp_inst_b_in_rsci_idat
    );
  b_in_rsci_idat_mxwt <= test_core_b_in_rsci_b_in_wait_dp_inst_b_in_rsci_idat_mxwt;
  test_core_b_in_rsci_b_in_wait_dp_inst_b_in_rsci_idat <= b_in_rsci_idat;

END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core_a_in_rsci
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core_a_in_rsci IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    a_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
    a_in_rsc_vld : IN STD_LOGIC;
    a_in_rsc_rdy : OUT STD_LOGIC;
    core_wen : IN STD_LOGIC;
    a_in_rsci_oswt : IN STD_LOGIC;
    a_in_rsci_wen_comp : OUT STD_LOGIC;
    a_in_rsci_idat_mxwt : OUT STD_LOGIC_VECTOR (127 DOWNTO 0)
  );
END test_core_a_in_rsci;

ARCHITECTURE v1 OF test_core_a_in_rsci IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL a_in_rsci_biwt : STD_LOGIC;
  SIGNAL a_in_rsci_bdwt : STD_LOGIC;
  SIGNAL a_in_rsci_bcwt : STD_LOGIC;
  SIGNAL a_in_rsci_irdy_core_sct : STD_LOGIC;
  SIGNAL a_in_rsci_ivld : STD_LOGIC;
  SIGNAL a_in_rsci_idat : STD_LOGIC_VECTOR (127 DOWNTO 0);

  SIGNAL a_in_rsci_dat : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL a_in_rsci_idat_1 : STD_LOGIC_VECTOR (127 DOWNTO 0);

  COMPONENT test_core_a_in_rsci_a_in_wait_ctrl
    PORT(
      core_wen : IN STD_LOGIC;
      a_in_rsci_oswt : IN STD_LOGIC;
      a_in_rsci_biwt : OUT STD_LOGIC;
      a_in_rsci_bdwt : OUT STD_LOGIC;
      a_in_rsci_bcwt : IN STD_LOGIC;
      a_in_rsci_irdy_core_sct : OUT STD_LOGIC;
      a_in_rsci_ivld : IN STD_LOGIC
    );
  END COMPONENT;
  COMPONENT test_core_a_in_rsci_a_in_wait_dp
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      a_in_rsci_oswt : IN STD_LOGIC;
      a_in_rsci_wen_comp : OUT STD_LOGIC;
      a_in_rsci_idat_mxwt : OUT STD_LOGIC_VECTOR (127 DOWNTO 0);
      a_in_rsci_biwt : IN STD_LOGIC;
      a_in_rsci_bdwt : IN STD_LOGIC;
      a_in_rsci_bcwt : OUT STD_LOGIC;
      a_in_rsci_idat : IN STD_LOGIC_VECTOR (127 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL test_core_a_in_rsci_a_in_wait_dp_inst_a_in_rsci_idat_mxwt : STD_LOGIC_VECTOR
      (127 DOWNTO 0);
  SIGNAL test_core_a_in_rsci_a_in_wait_dp_inst_a_in_rsci_idat : STD_LOGIC_VECTOR
      (127 DOWNTO 0);

BEGIN
  a_in_rsci : mgc_hls.ccs_in_wait_pkg_v1.ccs_in_wait_v1
    GENERIC MAP(
      rscid => 1,
      width => 128
      )
    PORT MAP(
      rdy => a_in_rsc_rdy,
      vld => a_in_rsc_vld,
      dat => a_in_rsci_dat,
      irdy => a_in_rsci_irdy_core_sct,
      ivld => a_in_rsci_ivld,
      idat => a_in_rsci_idat_1
    );
  a_in_rsci_dat <= a_in_rsc_dat;
  a_in_rsci_idat <= a_in_rsci_idat_1;

  test_core_a_in_rsci_a_in_wait_ctrl_inst : test_core_a_in_rsci_a_in_wait_ctrl
    PORT MAP(
      core_wen => core_wen,
      a_in_rsci_oswt => a_in_rsci_oswt,
      a_in_rsci_biwt => a_in_rsci_biwt,
      a_in_rsci_bdwt => a_in_rsci_bdwt,
      a_in_rsci_bcwt => a_in_rsci_bcwt,
      a_in_rsci_irdy_core_sct => a_in_rsci_irdy_core_sct,
      a_in_rsci_ivld => a_in_rsci_ivld
    );
  test_core_a_in_rsci_a_in_wait_dp_inst : test_core_a_in_rsci_a_in_wait_dp
    PORT MAP(
      clk => clk,
      rst => rst,
      a_in_rsci_oswt => a_in_rsci_oswt,
      a_in_rsci_wen_comp => a_in_rsci_wen_comp,
      a_in_rsci_idat_mxwt => test_core_a_in_rsci_a_in_wait_dp_inst_a_in_rsci_idat_mxwt,
      a_in_rsci_biwt => a_in_rsci_biwt,
      a_in_rsci_bdwt => a_in_rsci_bdwt,
      a_in_rsci_bcwt => a_in_rsci_bcwt,
      a_in_rsci_idat => test_core_a_in_rsci_a_in_wait_dp_inst_a_in_rsci_idat
    );
  a_in_rsci_idat_mxwt <= test_core_a_in_rsci_a_in_wait_dp_inst_a_in_rsci_idat_mxwt;
  test_core_a_in_rsci_a_in_wait_dp_inst_a_in_rsci_idat <= a_in_rsci_idat;

END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_core
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    a_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
    a_in_rsc_vld : IN STD_LOGIC;
    a_in_rsc_rdy : OUT STD_LOGIC;
    b_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
    b_in_rsc_vld : IN STD_LOGIC;
    b_in_rsc_rdy : OUT STD_LOGIC;
    valid_in_data_rsc_dat : IN STD_LOGIC_VECTOR (15 DOWNTO 0);
    valid_in_data_rsc_triosy_lz : OUT STD_LOGIC;
    result_rsc_dat : OUT STD_LOGIC_VECTOR (19 DOWNTO 0);
    result_rsc_vld : OUT STD_LOGIC;
    result_rsc_rdy : IN STD_LOGIC
  );
END test_core;

ARCHITECTURE v1 OF test_core IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL core_wen : STD_LOGIC;
  SIGNAL core_wten : STD_LOGIC;
  SIGNAL a_in_rsci_wen_comp : STD_LOGIC;
  SIGNAL a_in_rsci_idat_mxwt : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL b_in_rsci_wen_comp : STD_LOGIC;
  SIGNAL b_in_rsci_idat_mxwt : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL valid_in_data_rsci_idat : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL result_rsci_wen_comp : STD_LOGIC;
  SIGNAL result_rsci_idat : STD_LOGIC_VECTOR (19 DOWNTO 0);
  SIGNAL fsm_output : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL main_stage_0_3 : STD_LOGIC;
  SIGNAL reg_valid_in_data_rsc_triosy_obj_ld_core_psct_cse : STD_LOGIC;
  SIGNAL reg_result_rsci_ivld_core_psct_cse : STD_LOGIC;
  SIGNAL reg_b_in_rsci_irdy_core_psct_cse : STD_LOGIC;
  SIGNAL MAC_MAC_and_14_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_15_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_12_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_13_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_acc_20_itm_1 : STD_LOGIC_VECTOR (17 DOWNTO 0);
  SIGNAL MAC_MAC_and_10_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_11_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_8_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_9_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_acc_19_itm_1 : STD_LOGIC_VECTOR (17 DOWNTO 0);
  SIGNAL MAC_MAC_and_6_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_7_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_4_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_5_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_acc_18_itm_1 : STD_LOGIC_VECTOR (17 DOWNTO 0);
  SIGNAL MAC_MAC_and_2_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_3_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_MAC_and_1_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_acc_21_itm_1 : STD_LOGIC_VECTOR (17 DOWNTO 0);
  SIGNAL MAC_and_cse : STD_LOGIC;

  SIGNAL MAC_3_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_4_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_1_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_2_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_7_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_8_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_5_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_6_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_11_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_12_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_9_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_10_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_15_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_16_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_13_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL MAC_14_qif_mul_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL valid_in_data_rsci_dat : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL valid_in_data_rsci_idat_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);

  COMPONENT test_core_a_in_rsci
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      a_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
      a_in_rsc_vld : IN STD_LOGIC;
      a_in_rsc_rdy : OUT STD_LOGIC;
      core_wen : IN STD_LOGIC;
      a_in_rsci_oswt : IN STD_LOGIC;
      a_in_rsci_wen_comp : OUT STD_LOGIC;
      a_in_rsci_idat_mxwt : OUT STD_LOGIC_VECTOR (127 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL test_core_a_in_rsci_inst_a_in_rsc_dat : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL test_core_a_in_rsci_inst_a_in_rsci_idat_mxwt : STD_LOGIC_VECTOR (127 DOWNTO
      0);

  COMPONENT test_core_b_in_rsci
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      b_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
      b_in_rsc_vld : IN STD_LOGIC;
      b_in_rsc_rdy : OUT STD_LOGIC;
      core_wen : IN STD_LOGIC;
      b_in_rsci_oswt : IN STD_LOGIC;
      b_in_rsci_wen_comp : OUT STD_LOGIC;
      b_in_rsci_idat_mxwt : OUT STD_LOGIC_VECTOR (127 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL test_core_b_in_rsci_inst_b_in_rsc_dat : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL test_core_b_in_rsci_inst_b_in_rsci_idat_mxwt : STD_LOGIC_VECTOR (127 DOWNTO
      0);

  COMPONENT test_core_result_rsci
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      result_rsc_dat : OUT STD_LOGIC_VECTOR (19 DOWNTO 0);
      result_rsc_vld : OUT STD_LOGIC;
      result_rsc_rdy : IN STD_LOGIC;
      core_wen : IN STD_LOGIC;
      result_rsci_oswt : IN STD_LOGIC;
      result_rsci_wen_comp : OUT STD_LOGIC;
      result_rsci_idat : IN STD_LOGIC_VECTOR (19 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL test_core_result_rsci_inst_result_rsc_dat : STD_LOGIC_VECTOR (19 DOWNTO
      0);
  SIGNAL test_core_result_rsci_inst_result_rsci_idat : STD_LOGIC_VECTOR (19 DOWNTO
      0);

  COMPONENT test_core_valid_in_data_rsc_triosy_obj
    PORT(
      valid_in_data_rsc_triosy_lz : OUT STD_LOGIC;
      core_wten : IN STD_LOGIC;
      valid_in_data_rsc_triosy_obj_iswt0 : IN STD_LOGIC
    );
  END COMPONENT;
  COMPONENT test_core_staller
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      core_wen : OUT STD_LOGIC;
      core_wten : OUT STD_LOGIC;
      a_in_rsci_wen_comp : IN STD_LOGIC;
      b_in_rsci_wen_comp : IN STD_LOGIC;
      result_rsci_wen_comp : IN STD_LOGIC
    );
  END COMPONENT;
  COMPONENT test_core_core_fsm
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      core_wen : IN STD_LOGIC;
      fsm_output : OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL test_core_core_fsm_inst_fsm_output : STD_LOGIC_VECTOR (1 DOWNTO 0);

  FUNCTION MUX_v_16_2_2(input_0 : STD_LOGIC_VECTOR(15 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(15 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(15 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

BEGIN
  valid_in_data_rsci : mgc_hls.ccs_in_pkg_v1.ccs_in_v1
    GENERIC MAP(
      rscid => 3,
      width => 16
      )
    PORT MAP(
      dat => valid_in_data_rsci_dat,
      idat => valid_in_data_rsci_idat_1
    );
  valid_in_data_rsci_dat <= valid_in_data_rsc_dat;
  valid_in_data_rsci_idat <= valid_in_data_rsci_idat_1;

  test_core_a_in_rsci_inst : test_core_a_in_rsci
    PORT MAP(
      clk => clk,
      rst => rst,
      a_in_rsc_dat => test_core_a_in_rsci_inst_a_in_rsc_dat,
      a_in_rsc_vld => a_in_rsc_vld,
      a_in_rsc_rdy => a_in_rsc_rdy,
      core_wen => core_wen,
      a_in_rsci_oswt => reg_b_in_rsci_irdy_core_psct_cse,
      a_in_rsci_wen_comp => a_in_rsci_wen_comp,
      a_in_rsci_idat_mxwt => test_core_a_in_rsci_inst_a_in_rsci_idat_mxwt
    );
  test_core_a_in_rsci_inst_a_in_rsc_dat <= a_in_rsc_dat;
  a_in_rsci_idat_mxwt <= test_core_a_in_rsci_inst_a_in_rsci_idat_mxwt;

  test_core_b_in_rsci_inst : test_core_b_in_rsci
    PORT MAP(
      clk => clk,
      rst => rst,
      b_in_rsc_dat => test_core_b_in_rsci_inst_b_in_rsc_dat,
      b_in_rsc_vld => b_in_rsc_vld,
      b_in_rsc_rdy => b_in_rsc_rdy,
      core_wen => core_wen,
      b_in_rsci_oswt => reg_b_in_rsci_irdy_core_psct_cse,
      b_in_rsci_wen_comp => b_in_rsci_wen_comp,
      b_in_rsci_idat_mxwt => test_core_b_in_rsci_inst_b_in_rsci_idat_mxwt
    );
  test_core_b_in_rsci_inst_b_in_rsc_dat <= b_in_rsc_dat;
  b_in_rsci_idat_mxwt <= test_core_b_in_rsci_inst_b_in_rsci_idat_mxwt;

  test_core_result_rsci_inst : test_core_result_rsci
    PORT MAP(
      clk => clk,
      rst => rst,
      result_rsc_dat => test_core_result_rsci_inst_result_rsc_dat,
      result_rsc_vld => result_rsc_vld,
      result_rsc_rdy => result_rsc_rdy,
      core_wen => core_wen,
      result_rsci_oswt => reg_result_rsci_ivld_core_psct_cse,
      result_rsci_wen_comp => result_rsci_wen_comp,
      result_rsci_idat => test_core_result_rsci_inst_result_rsci_idat
    );
  result_rsc_dat <= test_core_result_rsci_inst_result_rsc_dat;
  test_core_result_rsci_inst_result_rsci_idat <= result_rsci_idat;

  test_core_valid_in_data_rsc_triosy_obj_inst : test_core_valid_in_data_rsc_triosy_obj
    PORT MAP(
      valid_in_data_rsc_triosy_lz => valid_in_data_rsc_triosy_lz,
      core_wten => core_wten,
      valid_in_data_rsc_triosy_obj_iswt0 => reg_valid_in_data_rsc_triosy_obj_ld_core_psct_cse
    );
  test_core_staller_inst : test_core_staller
    PORT MAP(
      clk => clk,
      rst => rst,
      core_wen => core_wen,
      core_wten => core_wten,
      a_in_rsci_wen_comp => a_in_rsci_wen_comp,
      b_in_rsci_wen_comp => b_in_rsci_wen_comp,
      result_rsci_wen_comp => result_rsci_wen_comp
    );
  test_core_core_fsm_inst : test_core_core_fsm
    PORT MAP(
      clk => clk,
      rst => rst,
      core_wen => core_wen,
      fsm_output => test_core_core_fsm_inst_fsm_output
    );
  fsm_output <= test_core_core_fsm_inst_fsm_output;

  MAC_and_cse <= core_wen AND reg_valid_in_data_rsc_triosy_obj_ld_core_psct_cse;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        reg_valid_in_data_rsc_triosy_obj_ld_core_psct_cse <= '0';
        reg_result_rsci_ivld_core_psct_cse <= '0';
        reg_b_in_rsci_irdy_core_psct_cse <= '0';
        main_stage_0_3 <= '0';
        MAC_MAC_and_2_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_3_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_1_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_6_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_7_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_4_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_5_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_10_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_11_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_8_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_9_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_14_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_15_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_12_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        MAC_MAC_and_13_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
      ELSIF ( core_wen = '1' ) THEN
        reg_valid_in_data_rsc_triosy_obj_ld_core_psct_cse <= fsm_output(1);
        reg_result_rsci_ivld_core_psct_cse <= main_stage_0_3;
        reg_b_in_rsci_irdy_core_psct_cse <= '1';
        main_stage_0_3 <= reg_valid_in_data_rsc_triosy_obj_ld_core_psct_cse;
        MAC_MAC_and_2_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_3_qif_mul_nl), 16)), (valid_in_data_rsci_idat(2)));
        MAC_MAC_and_3_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_4_qif_mul_nl), 16)), (valid_in_data_rsci_idat(3)));
        MAC_MAC_and_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_1_qif_mul_nl), 16)), (valid_in_data_rsci_idat(0)));
        MAC_MAC_and_1_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_2_qif_mul_nl), 16)), (valid_in_data_rsci_idat(1)));
        MAC_MAC_and_6_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_7_qif_mul_nl), 16)), (valid_in_data_rsci_idat(6)));
        MAC_MAC_and_7_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_8_qif_mul_nl), 16)), (valid_in_data_rsci_idat(7)));
        MAC_MAC_and_4_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_5_qif_mul_nl), 16)), (valid_in_data_rsci_idat(4)));
        MAC_MAC_and_5_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_6_qif_mul_nl), 16)), (valid_in_data_rsci_idat(5)));
        MAC_MAC_and_10_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_11_qif_mul_nl), 16)), (valid_in_data_rsci_idat(10)));
        MAC_MAC_and_11_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_12_qif_mul_nl), 16)), (valid_in_data_rsci_idat(11)));
        MAC_MAC_and_8_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_9_qif_mul_nl), 16)), (valid_in_data_rsci_idat(8)));
        MAC_MAC_and_9_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_10_qif_mul_nl), 16)), (valid_in_data_rsci_idat(9)));
        MAC_MAC_and_14_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_15_qif_mul_nl), 16)), (valid_in_data_rsci_idat(14)));
        MAC_MAC_and_15_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_16_qif_mul_nl), 16)), (valid_in_data_rsci_idat(15)));
        MAC_MAC_and_12_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_13_qif_mul_nl), 16)), (valid_in_data_rsci_idat(12)));
        MAC_MAC_and_13_itm_1 <= MUX_v_16_2_2(STD_LOGIC_VECTOR'("0000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(MAC_14_qif_mul_nl), 16)), (valid_in_data_rsci_idat(13)));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        result_rsci_idat <= STD_LOGIC_VECTOR'( "00000000000000000000");
      ELSIF ( (core_wen AND main_stage_0_3) = '1' ) THEN
        result_rsci_idat <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_acc_20_itm_1),
            18), 20) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_acc_19_itm_1), 18), 20)
            + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_acc_18_itm_1), 18), 20) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_acc_21_itm_1),
            18), 20), 20));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        MAC_acc_20_itm_1 <= STD_LOGIC_VECTOR'( "000000000000000000");
        MAC_acc_19_itm_1 <= STD_LOGIC_VECTOR'( "000000000000000000");
        MAC_acc_18_itm_1 <= STD_LOGIC_VECTOR'( "000000000000000000");
        MAC_acc_21_itm_1 <= STD_LOGIC_VECTOR'( "000000000000000000");
      ELSIF ( MAC_and_cse = '1' ) THEN
        MAC_acc_20_itm_1 <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_14_itm_1),
            16), 18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_15_itm_1), 16),
            18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_12_itm_1), 16), 18)
            + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_13_itm_1), 16), 18), 18));
        MAC_acc_19_itm_1 <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_10_itm_1),
            16), 18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_11_itm_1), 16),
            18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_8_itm_1), 16), 18) +
            CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_9_itm_1), 16), 18), 18));
        MAC_acc_18_itm_1 <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_6_itm_1),
            16), 18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_7_itm_1), 16),
            18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_4_itm_1), 16), 18) +
            CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_5_itm_1), 16), 18), 18));
        MAC_acc_21_itm_1 <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_2_itm_1),
            16), 18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_3_itm_1), 16),
            18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_itm_1), 16), 18) + CONV_SIGNED(CONV_SIGNED(SIGNED(MAC_MAC_and_1_itm_1),
            16), 18), 18));
      END IF;
    END IF;
  END PROCESS;
  MAC_3_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(23
      DOWNTO 16)) * SIGNED(b_in_rsci_idat_mxwt(23 DOWNTO 16))), 16));
  MAC_4_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(31
      DOWNTO 24)) * SIGNED(b_in_rsci_idat_mxwt(31 DOWNTO 24))), 16));
  MAC_1_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(7
      DOWNTO 0)) * SIGNED(b_in_rsci_idat_mxwt(7 DOWNTO 0))), 16));
  MAC_2_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(15
      DOWNTO 8)) * SIGNED(b_in_rsci_idat_mxwt(15 DOWNTO 8))), 16));
  MAC_7_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(55
      DOWNTO 48)) * SIGNED(b_in_rsci_idat_mxwt(55 DOWNTO 48))), 16));
  MAC_8_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(63
      DOWNTO 56)) * SIGNED(b_in_rsci_idat_mxwt(63 DOWNTO 56))), 16));
  MAC_5_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(39
      DOWNTO 32)) * SIGNED(b_in_rsci_idat_mxwt(39 DOWNTO 32))), 16));
  MAC_6_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(47
      DOWNTO 40)) * SIGNED(b_in_rsci_idat_mxwt(47 DOWNTO 40))), 16));
  MAC_11_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(87
      DOWNTO 80)) * SIGNED(b_in_rsci_idat_mxwt(87 DOWNTO 80))), 16));
  MAC_12_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(95
      DOWNTO 88)) * SIGNED(b_in_rsci_idat_mxwt(95 DOWNTO 88))), 16));
  MAC_9_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(71
      DOWNTO 64)) * SIGNED(b_in_rsci_idat_mxwt(71 DOWNTO 64))), 16));
  MAC_10_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(79
      DOWNTO 72)) * SIGNED(b_in_rsci_idat_mxwt(79 DOWNTO 72))), 16));
  MAC_15_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(119
      DOWNTO 112)) * SIGNED(b_in_rsci_idat_mxwt(119 DOWNTO 112))), 16));
  MAC_16_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(127
      DOWNTO 120)) * SIGNED(b_in_rsci_idat_mxwt(127 DOWNTO 120))), 16));
  MAC_13_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(103
      DOWNTO 96)) * SIGNED(b_in_rsci_idat_mxwt(103 DOWNTO 96))), 16));
  MAC_14_qif_mul_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'( SIGNED(a_in_rsci_idat_mxwt(111
      DOWNTO 104)) * SIGNED(b_in_rsci_idat_mxwt(111 DOWNTO 104))), 16));
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test_struct
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test_struct IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    a_in_rsc_dat_data : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
    a_in_rsc_vld : IN STD_LOGIC;
    a_in_rsc_rdy : OUT STD_LOGIC;
    b_in_rsc_dat_data : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
    b_in_rsc_vld : IN STD_LOGIC;
    b_in_rsc_rdy : OUT STD_LOGIC;
    valid_in_data_rsc_dat : IN STD_LOGIC_VECTOR (15 DOWNTO 0);
    valid_in_data_rsc_triosy_lz : OUT STD_LOGIC;
    result_rsc_dat : OUT STD_LOGIC_VECTOR (19 DOWNTO 0);
    result_rsc_vld : OUT STD_LOGIC;
    result_rsc_rdy : IN STD_LOGIC
  );
END test_struct;

ARCHITECTURE v1 OF test_struct IS
  -- Default Constants

  COMPONENT test_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      a_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
      a_in_rsc_vld : IN STD_LOGIC;
      a_in_rsc_rdy : OUT STD_LOGIC;
      b_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
      b_in_rsc_vld : IN STD_LOGIC;
      b_in_rsc_rdy : OUT STD_LOGIC;
      valid_in_data_rsc_dat : IN STD_LOGIC_VECTOR (15 DOWNTO 0);
      valid_in_data_rsc_triosy_lz : OUT STD_LOGIC;
      result_rsc_dat : OUT STD_LOGIC_VECTOR (19 DOWNTO 0);
      result_rsc_vld : OUT STD_LOGIC;
      result_rsc_rdy : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL test_core_inst_a_in_rsc_dat : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL test_core_inst_b_in_rsc_dat : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL test_core_inst_valid_in_data_rsc_dat : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL test_core_inst_result_rsc_dat : STD_LOGIC_VECTOR (19 DOWNTO 0);

BEGIN
  test_core_inst : test_core
    PORT MAP(
      clk => clk,
      rst => rst,
      a_in_rsc_dat => test_core_inst_a_in_rsc_dat,
      a_in_rsc_vld => a_in_rsc_vld,
      a_in_rsc_rdy => a_in_rsc_rdy,
      b_in_rsc_dat => test_core_inst_b_in_rsc_dat,
      b_in_rsc_vld => b_in_rsc_vld,
      b_in_rsc_rdy => b_in_rsc_rdy,
      valid_in_data_rsc_dat => test_core_inst_valid_in_data_rsc_dat,
      valid_in_data_rsc_triosy_lz => valid_in_data_rsc_triosy_lz,
      result_rsc_dat => test_core_inst_result_rsc_dat,
      result_rsc_vld => result_rsc_vld,
      result_rsc_rdy => result_rsc_rdy
    );
  test_core_inst_a_in_rsc_dat <= a_in_rsc_dat_data;
  test_core_inst_b_in_rsc_dat <= b_in_rsc_dat_data;
  test_core_inst_valid_in_data_rsc_dat <= valid_in_data_rsc_dat;
  result_rsc_dat <= test_core_inst_result_rsc_dat;

END v1;

-- ------------------------------------------------------------------
--  Design Unit:    test
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_wait_pkg_v1.ALL;
USE mgc_hls.ccs_out_wait_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;
USE mgc_hls.ccs_in_pkg_v1.ALL;


ENTITY test IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    a_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
    a_in_rsc_vld : IN STD_LOGIC;
    a_in_rsc_rdy : OUT STD_LOGIC;
    b_in_rsc_dat : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
    b_in_rsc_vld : IN STD_LOGIC;
    b_in_rsc_rdy : OUT STD_LOGIC;
    valid_in_data_rsc_dat : IN STD_LOGIC_VECTOR (15 DOWNTO 0);
    valid_in_data_rsc_triosy_lz : OUT STD_LOGIC;
    result_rsc_dat : OUT STD_LOGIC_VECTOR (19 DOWNTO 0);
    result_rsc_vld : OUT STD_LOGIC;
    result_rsc_rdy : IN STD_LOGIC
  );
END test;

ARCHITECTURE v1 OF test IS
  -- Default Constants

  COMPONENT test_struct
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      a_in_rsc_dat_data : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
      a_in_rsc_vld : IN STD_LOGIC;
      a_in_rsc_rdy : OUT STD_LOGIC;
      b_in_rsc_dat_data : IN STD_LOGIC_VECTOR (127 DOWNTO 0);
      b_in_rsc_vld : IN STD_LOGIC;
      b_in_rsc_rdy : OUT STD_LOGIC;
      valid_in_data_rsc_dat : IN STD_LOGIC_VECTOR (15 DOWNTO 0);
      valid_in_data_rsc_triosy_lz : OUT STD_LOGIC;
      result_rsc_dat : OUT STD_LOGIC_VECTOR (19 DOWNTO 0);
      result_rsc_vld : OUT STD_LOGIC;
      result_rsc_rdy : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL test_struct_inst_a_in_rsc_dat_data : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL test_struct_inst_b_in_rsc_dat_data : STD_LOGIC_VECTOR (127 DOWNTO 0);
  SIGNAL test_struct_inst_valid_in_data_rsc_dat : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL test_struct_inst_result_rsc_dat : STD_LOGIC_VECTOR (19 DOWNTO 0);

BEGIN
  test_struct_inst : test_struct
    PORT MAP(
      clk => clk,
      rst => rst,
      a_in_rsc_dat_data => test_struct_inst_a_in_rsc_dat_data,
      a_in_rsc_vld => a_in_rsc_vld,
      a_in_rsc_rdy => a_in_rsc_rdy,
      b_in_rsc_dat_data => test_struct_inst_b_in_rsc_dat_data,
      b_in_rsc_vld => b_in_rsc_vld,
      b_in_rsc_rdy => b_in_rsc_rdy,
      valid_in_data_rsc_dat => test_struct_inst_valid_in_data_rsc_dat,
      valid_in_data_rsc_triosy_lz => valid_in_data_rsc_triosy_lz,
      result_rsc_dat => test_struct_inst_result_rsc_dat,
      result_rsc_vld => result_rsc_vld,
      result_rsc_rdy => result_rsc_rdy
    );
  test_struct_inst_a_in_rsc_dat_data <= a_in_rsc_dat;
  test_struct_inst_b_in_rsc_dat_data <= b_in_rsc_dat;
  test_struct_inst_valid_in_data_rsc_dat <= valid_in_data_rsc_dat;
  result_rsc_dat <= test_struct_inst_result_rsc_dat;

END v1;



