-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    10.4a/835166 Production Release
--  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
-- 
--  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
--  Generated date: Tue Dec  2 09:32:14 2025
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen;

ARCHITECTURE v2 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen;

ARCHITECTURE v2 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen;

ARCHITECTURE v2 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_core_core_fsm
--  FSM Module
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_core_core_fsm IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    fsm_output : OUT STD_LOGIC_VECTOR (37 DOWNTO 0);
    for_for_C_34_tr0 : IN STD_LOGIC;
    for_C_0_tr0 : IN STD_LOGIC
  );
END matrix_mul_core_core_fsm;

ARCHITECTURE v2 OF matrix_mul_core_core_fsm IS
  -- Default Constants

  -- FSM State Type Declaration for matrix_mul_core_core_fsm_1
  TYPE matrix_mul_core_core_fsm_1_ST IS (main_C_0, for_for_C_0, for_for_C_1, for_for_C_2,
      for_for_C_3, for_for_C_4, for_for_C_5, for_for_C_6, for_for_C_7, for_for_C_8,
      for_for_C_9, for_for_C_10, for_for_C_11, for_for_C_12, for_for_C_13, for_for_C_14,
      for_for_C_15, for_for_C_16, for_for_C_17, for_for_C_18, for_for_C_19, for_for_C_20,
      for_for_C_21, for_for_C_22, for_for_C_23, for_for_C_24, for_for_C_25, for_for_C_26,
      for_for_C_27, for_for_C_28, for_for_C_29, for_for_C_30, for_for_C_31, for_for_C_32,
      for_for_C_33, for_for_C_34, for_C_0, main_C_1);

  SIGNAL state_var : matrix_mul_core_core_fsm_1_ST;
  SIGNAL state_var_NS : matrix_mul_core_core_fsm_1_ST;

BEGIN
  matrix_mul_core_core_fsm_1 : PROCESS (for_for_C_34_tr0, for_C_0_tr0, state_var)
  BEGIN
    CASE state_var IS
      WHEN for_for_C_0 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000000010");
        state_var_NS <= for_for_C_1;
      WHEN for_for_C_1 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000000100");
        state_var_NS <= for_for_C_2;
      WHEN for_for_C_2 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000001000");
        state_var_NS <= for_for_C_3;
      WHEN for_for_C_3 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000010000");
        state_var_NS <= for_for_C_4;
      WHEN for_for_C_4 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000100000");
        state_var_NS <= for_for_C_5;
      WHEN for_for_C_5 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000001000000");
        state_var_NS <= for_for_C_6;
      WHEN for_for_C_6 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000010000000");
        state_var_NS <= for_for_C_7;
      WHEN for_for_C_7 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000100000000");
        state_var_NS <= for_for_C_8;
      WHEN for_for_C_8 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000001000000000");
        state_var_NS <= for_for_C_9;
      WHEN for_for_C_9 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000010000000000");
        state_var_NS <= for_for_C_10;
      WHEN for_for_C_10 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000100000000000");
        state_var_NS <= for_for_C_11;
      WHEN for_for_C_11 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000001000000000000");
        state_var_NS <= for_for_C_12;
      WHEN for_for_C_12 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000010000000000000");
        state_var_NS <= for_for_C_13;
      WHEN for_for_C_13 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000100000000000000");
        state_var_NS <= for_for_C_14;
      WHEN for_for_C_14 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000001000000000000000");
        state_var_NS <= for_for_C_15;
      WHEN for_for_C_15 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000010000000000000000");
        state_var_NS <= for_for_C_16;
      WHEN for_for_C_16 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000100000000000000000");
        state_var_NS <= for_for_C_17;
      WHEN for_for_C_17 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000001000000000000000000");
        state_var_NS <= for_for_C_18;
      WHEN for_for_C_18 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000010000000000000000000");
        state_var_NS <= for_for_C_19;
      WHEN for_for_C_19 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000100000000000000000000");
        state_var_NS <= for_for_C_20;
      WHEN for_for_C_20 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000001000000000000000000000");
        state_var_NS <= for_for_C_21;
      WHEN for_for_C_21 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000010000000000000000000000");
        state_var_NS <= for_for_C_22;
      WHEN for_for_C_22 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000100000000000000000000000");
        state_var_NS <= for_for_C_23;
      WHEN for_for_C_23 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000001000000000000000000000000");
        state_var_NS <= for_for_C_24;
      WHEN for_for_C_24 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000010000000000000000000000000");
        state_var_NS <= for_for_C_25;
      WHEN for_for_C_25 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000100000000000000000000000000");
        state_var_NS <= for_for_C_26;
      WHEN for_for_C_26 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000001000000000000000000000000000");
        state_var_NS <= for_for_C_27;
      WHEN for_for_C_27 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000010000000000000000000000000000");
        state_var_NS <= for_for_C_28;
      WHEN for_for_C_28 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000100000000000000000000000000000");
        state_var_NS <= for_for_C_29;
      WHEN for_for_C_29 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000001000000000000000000000000000000");
        state_var_NS <= for_for_C_30;
      WHEN for_for_C_30 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000010000000000000000000000000000000");
        state_var_NS <= for_for_C_31;
      WHEN for_for_C_31 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000100000000000000000000000000000000");
        state_var_NS <= for_for_C_32;
      WHEN for_for_C_32 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00001000000000000000000000000000000000");
        state_var_NS <= for_for_C_33;
      WHEN for_for_C_33 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00010000000000000000000000000000000000");
        state_var_NS <= for_for_C_34;
      WHEN for_for_C_34 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00100000000000000000000000000000000000");
        IF ( for_for_C_34_tr0 = '1' ) THEN
          state_var_NS <= for_C_0;
        ELSE
          state_var_NS <= for_for_C_0;
        END IF;
      WHEN for_C_0 =>
        fsm_output <= STD_LOGIC_VECTOR'( "01000000000000000000000000000000000000");
        IF ( for_C_0_tr0 = '1' ) THEN
          state_var_NS <= main_C_1;
        ELSE
          state_var_NS <= for_for_C_0;
        END IF;
      WHEN main_C_1 =>
        fsm_output <= STD_LOGIC_VECTOR'( "10000000000000000000000000000000000000");
        state_var_NS <= main_C_0;
      -- main_C_0
      WHEN OTHERS =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000000001");
        state_var_NS <= for_for_C_0;
    END CASE;
  END PROCESS matrix_mul_core_core_fsm_1;

  matrix_mul_core_core_fsm_1_REG : PROCESS (clk)
  BEGIN
    IF clk'event AND ( clk = '1' ) THEN
      IF ( rst = '1' ) THEN
        state_var <= main_C_0;
      ELSE
        state_var <= state_var_NS;
      END IF;
    END IF;
  END PROCESS matrix_mul_core_core_fsm_1_REG;

END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_core
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_triosy_lz : OUT STD_LOGIC;
    B_rsc_triosy_lz : OUT STD_LOGIC;
    C_rsc_triosy_lz : OUT STD_LOGIC;
    A_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    A_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    B_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    C_rsci_d_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff : OUT STD_LOGIC;
    C_rsci_we_d_pff : OUT STD_LOGIC
  );
END matrix_mul_core;

ARCHITECTURE v2 OF matrix_mul_core IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL fsm_output : STD_LOGIC_VECTOR (37 DOWNTO 0);
  SIGNAL or_tmp_79 : STD_LOGIC;
  SIGNAL for_for_j_5_0_sva_4_0_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_j_5_0_sva_1 : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL reg_C_rsc_triosy_obj_ld_cse : STD_LOGIC;
  SIGNAL for_for_for_3_and_itm_mx0w2 : STD_LOGIC;
  SIGNAL for_i_5_0_sva_4_0_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL z_out : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL or_tmp_84 : STD_LOGIC;
  SIGNAL z_out_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_for_for_mul_sdt_1_sva : STD_LOGIC_VECTOR (45 DOWNTO 0);
  SIGNAL for_for_for_mul_sdt_2_sva : STD_LOGIC_VECTOR (45 DOWNTO 0);
  SIGNAL for_for_for_acc_7_psp_10_sva : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_for_for_10_and_itm : STD_LOGIC;
  SIGNAL for_for_for_mul_sdt_1_sva_mx0w0 : STD_LOGIC_VECTOR (45 DOWNTO 0);
  SIGNAL for_i_or_cse : STD_LOGIC;

  SIGNAL for_for_j_not_nl : STD_LOGIC;
  SIGNAL for_for_for_1_or_nl : STD_LOGIC;
  SIGNAL for_for_for_2_and_nl : STD_LOGIC;
  SIGNAL A_or_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL A_nor_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL A_mux1h_1_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL B_B_nor_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL B_nor_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL B_mux1h_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_mux_1_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL acc_1_nl : STD_LOGIC_VECTOR (32 DOWNTO 0);
  SIGNAL for_for_for_mux_6_nl : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_for_for_mux_7_nl : STD_LOGIC;
  SIGNAL for_for_for_1_and_1_nl : STD_LOGIC;
  SIGNAL for_for_for_mux_8_nl : STD_LOGIC_VECTOR (31 DOWNTO 0);
  COMPONENT matrix_mul_core_core_fsm
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      fsm_output : OUT STD_LOGIC_VECTOR (37 DOWNTO 0);
      for_for_C_34_tr0 : IN STD_LOGIC;
      for_C_0_tr0 : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL matrix_mul_core_core_fsm_inst_fsm_output : STD_LOGIC_VECTOR (37 DOWNTO 0);
  SIGNAL matrix_mul_core_core_fsm_inst_for_for_C_34_tr0 : STD_LOGIC;
  SIGNAL matrix_mul_core_core_fsm_inst_for_C_0_tr0 : STD_LOGIC;

  FUNCTION CONV_SL_1_1(input:BOOLEAN)
  RETURN STD_LOGIC IS
  BEGIN
    IF input THEN RETURN '1';ELSE RETURN '0';END IF;
  END;

  FUNCTION MUX1HOT_s_1_3_2(input_2 : STD_LOGIC;
  input_1 : STD_LOGIC;
  input_0 : STD_LOGIC;
  sel : STD_LOGIC_VECTOR(2 DOWNTO 0))
  RETURN STD_LOGIC IS
    VARIABLE result : STD_LOGIC;
    VARIABLE tmp : STD_LOGIC;

    BEGIN
      tmp := sel(0);
      result := input_0 and tmp;
      tmp := sel(1);
      result := result or ( input_1 and tmp);
      tmp := sel(2);
      result := result or ( input_2 and tmp);
    RETURN result;
  END;

  FUNCTION MUX1HOT_v_5_30_2(input_29 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_28 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_27 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_26 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_25 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_24 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_23 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_22 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_21 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_20 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_19 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_18 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_17 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_16 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_15 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_14 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_13 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_12 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_11 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_10 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_9 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_8 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_7 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_6 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_5 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_4 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_3 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_2 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC_VECTOR(29 DOWNTO 0))
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);
    VARIABLE tmp : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      tmp := (OTHERS=>sel(0));
      result := input_0 and tmp;
      tmp := (OTHERS=>sel( 1));
      result := result or ( input_1 and tmp);
      tmp := (OTHERS=>sel( 2));
      result := result or ( input_2 and tmp);
      tmp := (OTHERS=>sel( 3));
      result := result or ( input_3 and tmp);
      tmp := (OTHERS=>sel( 4));
      result := result or ( input_4 and tmp);
      tmp := (OTHERS=>sel( 5));
      result := result or ( input_5 and tmp);
      tmp := (OTHERS=>sel( 6));
      result := result or ( input_6 and tmp);
      tmp := (OTHERS=>sel( 7));
      result := result or ( input_7 and tmp);
      tmp := (OTHERS=>sel( 8));
      result := result or ( input_8 and tmp);
      tmp := (OTHERS=>sel( 9));
      result := result or ( input_9 and tmp);
      tmp := (OTHERS=>sel( 10));
      result := result or ( input_10 and tmp);
      tmp := (OTHERS=>sel( 11));
      result := result or ( input_11 and tmp);
      tmp := (OTHERS=>sel( 12));
      result := result or ( input_12 and tmp);
      tmp := (OTHERS=>sel( 13));
      result := result or ( input_13 and tmp);
      tmp := (OTHERS=>sel( 14));
      result := result or ( input_14 and tmp);
      tmp := (OTHERS=>sel( 15));
      result := result or ( input_15 and tmp);
      tmp := (OTHERS=>sel( 16));
      result := result or ( input_16 and tmp);
      tmp := (OTHERS=>sel( 17));
      result := result or ( input_17 and tmp);
      tmp := (OTHERS=>sel( 18));
      result := result or ( input_18 and tmp);
      tmp := (OTHERS=>sel( 19));
      result := result or ( input_19 and tmp);
      tmp := (OTHERS=>sel( 20));
      result := result or ( input_20 and tmp);
      tmp := (OTHERS=>sel( 21));
      result := result or ( input_21 and tmp);
      tmp := (OTHERS=>sel( 22));
      result := result or ( input_22 and tmp);
      tmp := (OTHERS=>sel( 23));
      result := result or ( input_23 and tmp);
      tmp := (OTHERS=>sel( 24));
      result := result or ( input_24 and tmp);
      tmp := (OTHERS=>sel( 25));
      result := result or ( input_25 and tmp);
      tmp := (OTHERS=>sel( 26));
      result := result or ( input_26 and tmp);
      tmp := (OTHERS=>sel( 27));
      result := result or ( input_27 and tmp);
      tmp := (OTHERS=>sel( 28));
      result := result or ( input_28 and tmp);
      tmp := (OTHERS=>sel( 29));
      result := result or ( input_29 and tmp);
    RETURN result;
  END;

  FUNCTION MUX_s_1_2_2(input_0 : STD_LOGIC;
  input_1 : STD_LOGIC;
  sel : STD_LOGIC)
  RETURN STD_LOGIC IS
    VARIABLE result : STD_LOGIC;

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

  FUNCTION MUX_v_32_2_2(input_0 : STD_LOGIC_VECTOR(31 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(31 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(31 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

  FUNCTION MUX_v_5_2_2(input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

BEGIN
  A_rsc_triosy_obj : mgc_hls.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_C_rsc_triosy_obj_ld_cse,
      lz => A_rsc_triosy_lz
    );
  B_rsc_triosy_obj : mgc_hls.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_C_rsc_triosy_obj_ld_cse,
      lz => B_rsc_triosy_lz
    );
  C_rsc_triosy_obj : mgc_hls.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_C_rsc_triosy_obj_ld_cse,
      lz => C_rsc_triosy_lz
    );
  matrix_mul_core_core_fsm_inst : matrix_mul_core_core_fsm
    PORT MAP(
      clk => clk,
      rst => rst,
      fsm_output => matrix_mul_core_core_fsm_inst_fsm_output,
      for_for_C_34_tr0 => matrix_mul_core_core_fsm_inst_for_for_C_34_tr0,
      for_C_0_tr0 => matrix_mul_core_core_fsm_inst_for_C_0_tr0
    );
  fsm_output <= matrix_mul_core_core_fsm_inst_fsm_output;
  matrix_mul_core_core_fsm_inst_for_for_C_34_tr0 <= for_for_j_5_0_sva_1(5);
  matrix_mul_core_core_fsm_inst_for_C_0_tr0 <= z_out(5);

  for_i_or_cse <= (fsm_output(0)) OR (fsm_output(36));
  for_for_for_mul_sdt_1_sva_mx0w0 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(SIGNED'( SIGNED(A_rsci_q_d)
      * SIGNED(B_rsci_q_d)), 46));
  for_for_for_3_and_itm_mx0w2 <= (for_for_for_mul_sdt_1_sva(13)) AND (CONV_SL_1_1(for_for_for_mul_sdt_1_sva(12
      DOWNTO 0)/=STD_LOGIC_VECTOR'("0000000000000")) OR (z_out_1(0)));
  or_tmp_79 <= NOT((fsm_output(1)) OR (fsm_output(37)) OR (fsm_output(34)) OR (fsm_output(35))
      OR (fsm_output(3)) OR (fsm_output(4)) OR (fsm_output(2)) OR (fsm_output(0))
      OR (fsm_output(36)));
  A_mux1h_1_nl <= MUX1HOT_v_5_30_2(STD_LOGIC_VECTOR'( "11110"), STD_LOGIC_VECTOR'(
      "11101"), STD_LOGIC_VECTOR'( "11100"), STD_LOGIC_VECTOR'( "11011"), STD_LOGIC_VECTOR'(
      "11010"), STD_LOGIC_VECTOR'( "11001"), STD_LOGIC_VECTOR'( "11000"), STD_LOGIC_VECTOR'(
      "10111"), STD_LOGIC_VECTOR'( "10110"), STD_LOGIC_VECTOR'( "10101"), STD_LOGIC_VECTOR'(
      "10100"), STD_LOGIC_VECTOR'( "10011"), STD_LOGIC_VECTOR'( "10010"), STD_LOGIC_VECTOR'(
      "10001"), STD_LOGIC_VECTOR'( "10000"), STD_LOGIC_VECTOR'( "01111"), STD_LOGIC_VECTOR'(
      "01110"), STD_LOGIC_VECTOR'( "01101"), STD_LOGIC_VECTOR'( "01100"), STD_LOGIC_VECTOR'(
      "01011"), STD_LOGIC_VECTOR'( "01010"), STD_LOGIC_VECTOR'( "01001"), STD_LOGIC_VECTOR'(
      "01000"), STD_LOGIC_VECTOR'( "00111"), STD_LOGIC_VECTOR'( "00110"), STD_LOGIC_VECTOR'(
      "00101"), STD_LOGIC_VECTOR'( "00100"), STD_LOGIC_VECTOR'( "00011"), STD_LOGIC_VECTOR'(
      "00010"), STD_LOGIC_VECTOR'( "00001"), STD_LOGIC_VECTOR'( (fsm_output(2)) &
      (fsm_output(3)) & (fsm_output(4)) & (fsm_output(5)) & (fsm_output(6)) & (fsm_output(7))
      & (fsm_output(8)) & (fsm_output(9)) & (fsm_output(10)) & (fsm_output(11)) &
      (fsm_output(12)) & (fsm_output(13)) & (fsm_output(14)) & (fsm_output(15)) &
      (fsm_output(16)) & (fsm_output(17)) & (fsm_output(18)) & (fsm_output(19)) &
      (fsm_output(20)) & (fsm_output(21)) & (fsm_output(22)) & (fsm_output(23)) &
      (fsm_output(24)) & (fsm_output(25)) & (fsm_output(26)) & (fsm_output(27)) &
      (fsm_output(28)) & (fsm_output(29)) & (fsm_output(30)) & (fsm_output(31))));
  A_nor_nl <= NOT(MUX_v_5_2_2(A_mux1h_1_nl, STD_LOGIC_VECTOR'("11111"), (fsm_output(1))));
  A_or_nl <= MUX_v_5_2_2(A_nor_nl, STD_LOGIC_VECTOR'("11111"), (fsm_output(32)));
  A_rsci_adr_d <= for_i_5_0_sva_4_0_1 & A_or_nl;
  A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff <= NOT((fsm_output(33)) OR (fsm_output(37))
      OR (fsm_output(34)) OR (fsm_output(35)) OR (fsm_output(0)) OR (fsm_output(36)));
  B_mux1h_nl <= MUX1HOT_v_5_30_2(STD_LOGIC_VECTOR'( "00001"), STD_LOGIC_VECTOR'(
      "00010"), STD_LOGIC_VECTOR'( "00011"), STD_LOGIC_VECTOR'( "00100"), STD_LOGIC_VECTOR'(
      "00101"), STD_LOGIC_VECTOR'( "00110"), STD_LOGIC_VECTOR'( "00111"), STD_LOGIC_VECTOR'(
      "01000"), STD_LOGIC_VECTOR'( "01001"), STD_LOGIC_VECTOR'( "01010"), STD_LOGIC_VECTOR'(
      "01011"), STD_LOGIC_VECTOR'( "01100"), STD_LOGIC_VECTOR'( "01101"), STD_LOGIC_VECTOR'(
      "01110"), STD_LOGIC_VECTOR'( "01111"), STD_LOGIC_VECTOR'( "10000"), STD_LOGIC_VECTOR'(
      "10001"), STD_LOGIC_VECTOR'( "10010"), STD_LOGIC_VECTOR'( "10011"), STD_LOGIC_VECTOR'(
      "10100"), STD_LOGIC_VECTOR'( "10101"), STD_LOGIC_VECTOR'( "10110"), STD_LOGIC_VECTOR'(
      "10111"), STD_LOGIC_VECTOR'( "11000"), STD_LOGIC_VECTOR'( "11001"), STD_LOGIC_VECTOR'(
      "11010"), STD_LOGIC_VECTOR'( "11011"), STD_LOGIC_VECTOR'( "11100"), STD_LOGIC_VECTOR'(
      "11101"), STD_LOGIC_VECTOR'( "11110"), STD_LOGIC_VECTOR'( (fsm_output(2)) &
      (fsm_output(3)) & (fsm_output(4)) & (fsm_output(5)) & (fsm_output(6)) & (fsm_output(7))
      & (fsm_output(8)) & (fsm_output(9)) & (fsm_output(10)) & (fsm_output(11)) &
      (fsm_output(12)) & (fsm_output(13)) & (fsm_output(14)) & (fsm_output(15)) &
      (fsm_output(16)) & (fsm_output(17)) & (fsm_output(18)) & (fsm_output(19)) &
      (fsm_output(20)) & (fsm_output(21)) & (fsm_output(22)) & (fsm_output(23)) &
      (fsm_output(24)) & (fsm_output(25)) & (fsm_output(26)) & (fsm_output(27)) &
      (fsm_output(28)) & (fsm_output(29)) & (fsm_output(30)) & (fsm_output(31))));
  B_nor_nl <= NOT(MUX_v_5_2_2(B_mux1h_nl, STD_LOGIC_VECTOR'("11111"), (fsm_output(32))));
  B_B_nor_nl <= NOT(MUX_v_5_2_2(B_nor_nl, STD_LOGIC_VECTOR'("11111"), (fsm_output(1))));
  B_rsci_adr_d <= B_B_nor_nl & for_for_j_5_0_sva_4_0_1;
  C_rsci_adr_d <= for_i_5_0_sva_4_0_1 & for_for_j_5_0_sva_4_0_1;
  C_rsci_d_d <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(z_out_1) + CONV_UNSIGNED(CONV_UNSIGNED(CONV_UNSIGNED(for_for_for_3_and_itm_mx0w2,
      1), 1), 32), 32));
  C_rsci_we_d_pff <= fsm_output(34);
  or_tmp_84 <= (NOT((fsm_output(37)) OR (fsm_output(35)))) AND (NOT(CONV_SL_1_1(fsm_output(3
      DOWNTO 2)/=STD_LOGIC_VECTOR'("00")))) AND (NOT((fsm_output(0)) OR (fsm_output(4))))
      AND (NOT((fsm_output(36)) OR (fsm_output(1))));
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_i_5_0_sva_4_0_1 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( for_i_or_cse = '1' ) THEN
        for_i_5_0_sva_4_0_1 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), (z_out(4 DOWNTO
            0)), (fsm_output(36)));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_5_0_sva_4_0_1 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( ((fsm_output(35)) OR for_i_or_cse) = '1' ) THEN
        for_for_j_5_0_sva_4_0_1 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), (for_for_j_5_0_sva_1(4
            DOWNTO 0)), for_for_j_not_nl);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        reg_C_rsc_triosy_obj_ld_cse <= '0';
        for_for_for_mul_sdt_2_sva <= STD_LOGIC_VECTOR'( "0000000000000000000000000000000000000000000000");
        for_for_for_acc_7_psp_10_sva <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
      ELSE
        reg_C_rsc_triosy_obj_ld_cse <= (z_out(5)) AND (fsm_output(36));
        for_for_for_mul_sdt_2_sva <= for_for_for_mul_sdt_1_sva_mx0w0;
        for_for_for_acc_7_psp_10_sva <= z_out_1;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_5_0_sva_1 <= STD_LOGIC_VECTOR'( "000000");
      ELSIF ( (fsm_output(1)) = '1' ) THEN
        for_for_j_5_0_sva_1 <= z_out;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_mul_sdt_1_sva <= STD_LOGIC_VECTOR'( "0000000000000000000000000000000000000000000000");
      ELSIF ( (NOT((fsm_output(1)) OR (fsm_output(37)) OR (fsm_output(34)) OR (fsm_output(35))
          OR (fsm_output(3)) OR (fsm_output(0)) OR (fsm_output(36)))) = '1' ) THEN
        for_for_for_mul_sdt_1_sva <= for_for_for_mul_sdt_1_sva_mx0w0;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_10_and_itm <= '0';
      ELSIF ( ((fsm_output(2)) OR (fsm_output(4)) OR or_tmp_79) = '1' ) THEN
        for_for_for_10_and_itm <= MUX1HOT_s_1_3_2(for_for_for_1_or_nl, for_for_for_2_and_nl,
            for_for_for_3_and_itm_mx0w2, STD_LOGIC_VECTOR'( (fsm_output(2)) & (fsm_output(4))
            & or_tmp_79));
      END IF;
    END IF;
  END PROCESS;
  for_for_j_not_nl <= NOT for_i_or_cse;
  for_for_for_1_or_nl <= (for_for_for_mul_sdt_1_sva_mx0w0(0)) OR (for_for_for_mul_sdt_1_sva_mx0w0(1))
      OR (for_for_for_mul_sdt_1_sva_mx0w0(2)) OR (for_for_for_mul_sdt_1_sva_mx0w0(3))
      OR (for_for_for_mul_sdt_1_sva_mx0w0(4)) OR (for_for_for_mul_sdt_1_sva_mx0w0(5))
      OR (for_for_for_mul_sdt_1_sva_mx0w0(6)) OR (for_for_for_mul_sdt_1_sva_mx0w0(7))
      OR (for_for_for_mul_sdt_1_sva_mx0w0(8)) OR (for_for_for_mul_sdt_1_sva_mx0w0(9))
      OR (for_for_for_mul_sdt_1_sva_mx0w0(10)) OR (for_for_for_mul_sdt_1_sva_mx0w0(11))
      OR (for_for_for_mul_sdt_1_sva_mx0w0(12)) OR (for_for_for_mul_sdt_1_sva_mx0w0(14));
  for_for_for_2_and_nl <= (for_for_for_mul_sdt_2_sva(13)) AND (CONV_SL_1_1(for_for_for_mul_sdt_2_sva(12
      DOWNTO 0)/=STD_LOGIC_VECTOR'("0000000000000")) OR (z_out_1(0)));
  for_for_mux_1_nl <= MUX_v_5_2_2(for_for_j_5_0_sva_4_0_1, for_i_5_0_sva_4_0_1, fsm_output(36));
  z_out <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(for_for_mux_1_nl),
      6) + UNSIGNED'( "000001"), 6));
  for_for_for_mux_6_nl <= MUX_v_32_2_2((for_for_for_mul_sdt_1_sva(45 DOWNTO 14)),
      for_for_for_acc_7_psp_10_sva, or_tmp_84);
  for_for_for_1_and_1_nl <= (for_for_for_mul_sdt_1_sva(13)) AND for_for_for_10_and_itm;
  for_for_for_mux_7_nl <= MUX_s_1_2_2(for_for_for_1_and_1_nl, for_for_for_10_and_itm,
      or_tmp_84);
  for_for_for_mux_8_nl <= MUX_v_32_2_2((for_for_for_mul_sdt_2_sva(45 DOWNTO 14)),
      (for_for_for_mul_sdt_1_sva(45 DOWNTO 14)), or_tmp_84);
  acc_1_nl <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(for_for_for_mux_6_nl & for_for_for_mux_7_nl)
      + UNSIGNED(for_for_for_mux_8_nl & '1'), 33));
  z_out_1 <= acc_1_nl(32 DOWNTO 1);
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    A_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsc_we : OUT STD_LOGIC;
    A_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsc_triosy_lz : OUT STD_LOGIC;
    B_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    B_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsc_we : OUT STD_LOGIC;
    B_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsc_triosy_lz : OUT STD_LOGIC;
    C_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    C_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsc_we : OUT STD_LOGIC;
    C_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsc_triosy_lz : OUT STD_LOGIC
  );
END matrix_mul;

ARCHITECTURE v2 OF matrix_mul IS
  -- Default Constants
  CONSTANT PWR : STD_LOGIC := '1';
  CONSTANT GND : STD_LOGIC := '0';

  -- Interconnect Declarations
  SIGNAL A_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff : STD_LOGIC;
  SIGNAL C_rsci_we_d_iff : STD_LOGIC;

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL A_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL B_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL C_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_d_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      A_rsc_triosy_lz : OUT STD_LOGIC;
      B_rsc_triosy_lz : OUT STD_LOGIC;
      C_rsc_triosy_lz : OUT STD_LOGIC;
      A_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      A_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      B_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      B_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      C_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      C_rsci_d_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff : OUT STD_LOGIC;
      C_rsci_we_d_pff : OUT STD_LOGIC
    );
  END COMPONENT;
  SIGNAL matrix_mul_core_inst_A_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_A_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_B_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_B_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_C_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_C_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);

BEGIN
  A_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => A_rsci_q,
      we => A_rsc_we,
      d => A_rsci_d,
      adr => A_rsci_adr,
      adr_d => A_rsci_adr_d_1,
      d_d => A_rsci_d_d,
      we_d => '0',
      q_d => A_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      port_0_rw_ram_ir_internal_WMASK_B_d => '0'
    );
  A_rsci_q <= A_rsc_q;
  A_rsc_d <= A_rsci_d;
  A_rsc_adr <= A_rsci_adr;
  A_rsci_adr_d_1 <= A_rsci_adr_d;
  A_rsci_d_d <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
  A_rsci_q_d <= A_rsci_q_d_1;

  B_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => B_rsci_q,
      we => B_rsc_we,
      d => B_rsci_d,
      adr => B_rsci_adr,
      adr_d => B_rsci_adr_d_1,
      d_d => B_rsci_d_d,
      we_d => '0',
      q_d => B_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      port_0_rw_ram_ir_internal_WMASK_B_d => '0'
    );
  B_rsci_q <= B_rsc_q;
  B_rsc_d <= B_rsci_d;
  B_rsc_adr <= B_rsci_adr;
  B_rsci_adr_d_1 <= B_rsci_adr_d;
  B_rsci_d_d <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
  B_rsci_q_d <= B_rsci_q_d_1;

  C_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => C_rsci_q,
      we => C_rsc_we,
      d => C_rsci_d,
      adr => C_rsci_adr,
      adr_d => C_rsci_adr_d_1,
      d_d => C_rsci_d_d_1,
      we_d => C_rsci_we_d_iff,
      q_d => C_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => '0',
      port_0_rw_ram_ir_internal_WMASK_B_d => C_rsci_we_d_iff
    );
  C_rsci_q <= C_rsc_q;
  C_rsc_d <= C_rsci_d;
  C_rsc_adr <= C_rsci_adr;
  C_rsci_adr_d_1 <= C_rsci_adr_d;
  C_rsci_d_d_1 <= C_rsci_d_d;
  C_rsci_q_d <= C_rsci_q_d_1;

  matrix_mul_core_inst : matrix_mul_core
    PORT MAP(
      clk => clk,
      rst => rst,
      A_rsc_triosy_lz => A_rsc_triosy_lz,
      B_rsc_triosy_lz => B_rsc_triosy_lz,
      C_rsc_triosy_lz => C_rsc_triosy_lz,
      A_rsci_adr_d => matrix_mul_core_inst_A_rsci_adr_d,
      A_rsci_q_d => matrix_mul_core_inst_A_rsci_q_d,
      B_rsci_adr_d => matrix_mul_core_inst_B_rsci_adr_d,
      B_rsci_q_d => matrix_mul_core_inst_B_rsci_q_d,
      C_rsci_adr_d => matrix_mul_core_inst_C_rsci_adr_d,
      C_rsci_d_d => matrix_mul_core_inst_C_rsci_d_d,
      A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      C_rsci_we_d_pff => C_rsci_we_d_iff
    );
  A_rsci_adr_d <= matrix_mul_core_inst_A_rsci_adr_d;
  matrix_mul_core_inst_A_rsci_q_d <= A_rsci_q_d;
  B_rsci_adr_d <= matrix_mul_core_inst_B_rsci_adr_d;
  matrix_mul_core_inst_B_rsci_q_d <= B_rsci_q_d;
  C_rsci_adr_d <= matrix_mul_core_inst_C_rsci_adr_d;
  C_rsci_d_d <= matrix_mul_core_inst_C_rsci_d_d;

END v2;



