
--------> /vol/mentor/Catapult_Synthesis_10.4a/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.vhd 
--------------------------------------------------------------------------------
-- Catapult Synthesis - Sample I/O Port Library
--
-- Copyright (c) 2003-2017 Mentor Graphics Corp.
--       All Rights Reserved
--
-- This document may be used and distributed without restriction provided that
-- this copyright statement is not removed from the file and that any derivative
-- work contains this copyright notice.
--
-- The design information contained in this file is intended to be an example
-- of the functionality which the end user may study in preparation for creating
-- their own custom interfaces. This design does not necessarily present a 
-- complete implementation of the named protocol or standard.
--
--------------------------------------------------------------------------------

LIBRARY ieee;

USE ieee.std_logic_1164.all;
PACKAGE mgc_io_sync_pkg_v2 IS

COMPONENT mgc_io_sync_v2
  GENERIC (
    valid    : INTEGER RANGE 0 TO 1
  );
  PORT (
    ld       : IN    std_logic;
    lz       : OUT   std_logic
  );
END COMPONENT;

END mgc_io_sync_pkg_v2;

LIBRARY ieee;

USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all; -- Prevent STARC 2.1.1.2 violation

ENTITY mgc_io_sync_v2 IS
  GENERIC (
    valid    : INTEGER RANGE 0 TO 1
  );
  PORT (
    ld       : IN    std_logic;
    lz       : OUT   std_logic
  );
END mgc_io_sync_v2;

ARCHITECTURE beh OF mgc_io_sync_v2 IS
BEGIN

  lz <= ld;

END beh;


--------> ./rtl.vhdl 
-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    10.4a/835166 Production Release
--  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
-- 
--  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
--  Generated date: Tue Dec  2 09:31:34 2025
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen;

ARCHITECTURE v1 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen;

ARCHITECTURE v1 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen;

ARCHITECTURE v1 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_core_core_fsm
--  FSM Module
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_core_core_fsm IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    fsm_output : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
    for_for_for_C_2_tr0 : IN STD_LOGIC;
    for_for_C_1_tr0 : IN STD_LOGIC;
    for_C_0_tr0 : IN STD_LOGIC
  );
END matrix_mul_core_core_fsm;

ARCHITECTURE v1 OF matrix_mul_core_core_fsm IS
  -- Default Constants

  -- FSM State Type Declaration for matrix_mul_core_core_fsm_1
  TYPE matrix_mul_core_core_fsm_1_ST IS (main_C_0, for_for_for_C_0, for_for_for_C_1,
      for_for_for_C_2, for_for_C_0, for_for_C_1, for_C_0, main_C_1);

  SIGNAL state_var : matrix_mul_core_core_fsm_1_ST;
  SIGNAL state_var_NS : matrix_mul_core_core_fsm_1_ST;

BEGIN
  matrix_mul_core_core_fsm_1 : PROCESS (for_for_for_C_2_tr0, for_for_C_1_tr0, for_C_0_tr0,
      state_var)
  BEGIN
    CASE state_var IS
      WHEN for_for_for_C_0 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000010");
        state_var_NS <= for_for_for_C_1;
      WHEN for_for_for_C_1 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000100");
        state_var_NS <= for_for_for_C_2;
      WHEN for_for_for_C_2 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00001000");
        IF ( for_for_for_C_2_tr0 = '1' ) THEN
          state_var_NS <= for_for_C_0;
        ELSE
          state_var_NS <= for_for_for_C_0;
        END IF;
      WHEN for_for_C_0 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00010000");
        state_var_NS <= for_for_C_1;
      WHEN for_for_C_1 =>
        fsm_output <= STD_LOGIC_VECTOR'( "00100000");
        IF ( for_for_C_1_tr0 = '1' ) THEN
          state_var_NS <= for_C_0;
        ELSE
          state_var_NS <= for_for_for_C_0;
        END IF;
      WHEN for_C_0 =>
        fsm_output <= STD_LOGIC_VECTOR'( "01000000");
        IF ( for_C_0_tr0 = '1' ) THEN
          state_var_NS <= main_C_1;
        ELSE
          state_var_NS <= for_for_for_C_0;
        END IF;
      WHEN main_C_1 =>
        fsm_output <= STD_LOGIC_VECTOR'( "10000000");
        state_var_NS <= main_C_0;
      -- main_C_0
      WHEN OTHERS =>
        fsm_output <= STD_LOGIC_VECTOR'( "00000001");
        state_var_NS <= for_for_for_C_0;
    END CASE;
  END PROCESS matrix_mul_core_core_fsm_1;

  matrix_mul_core_core_fsm_1_REG : PROCESS (clk)
  BEGIN
    IF clk'event AND ( clk = '1' ) THEN
      IF ( rst = '1' ) THEN
        state_var <= main_C_0;
      ELSE
        state_var <= state_var_NS;
      END IF;
    END IF;
  END PROCESS matrix_mul_core_core_fsm_1_REG;

END v1;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_core
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_triosy_lz : OUT STD_LOGIC;
    B_rsc_triosy_lz : OUT STD_LOGIC;
    C_rsc_triosy_lz : OUT STD_LOGIC;
    A_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    A_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    B_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    C_rsci_d_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff : OUT STD_LOGIC;
    C_rsci_we_d_pff : OUT STD_LOGIC
  );
END matrix_mul_core;

ARCHITECTURE v1 OF matrix_mul_core IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL fsm_output : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL for_for_j_5_0_sva_4_0_2 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL reg_C_rsc_triosy_obj_ld_cse : STD_LOGIC;
  SIGNAL for_for_sum_sva : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_i_5_0_sva_4_0_2 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL z_out : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL for_for_for_mul_sdt_sva : STD_LOGIC_VECTOR (45 DOWNTO 0);
  SIGNAL for_for_for_acc_7_psp_sva_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_i_or_cse : STD_LOGIC;
  SIGNAL for_for_j_or_cse : STD_LOGIC;
  SIGNAL for_for_for_k_for_for_for_k_mux_rgt : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL for_for_for_k_5_0_sva_1_5 : STD_LOGIC;
  SIGNAL for_for_for_k_5_0_sva_1_4_0 : STD_LOGIC_VECTOR (4 DOWNTO 0);

  SIGNAL not_nl : STD_LOGIC;
  SIGNAL for_for_for_acc_3_nl : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_for_for_and_nl : STD_LOGIC;
  SIGNAL for_for_sum_not_nl : STD_LOGIC;
  SIGNAL for_i_for_i_and_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL or_26_nl : STD_LOGIC;
  SIGNAL for_for_for_mux1h_1_nl : STD_LOGIC_VECTOR (4 DOWNTO 0);
  COMPONENT matrix_mul_core_core_fsm
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      fsm_output : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
      for_for_for_C_2_tr0 : IN STD_LOGIC;
      for_for_C_1_tr0 : IN STD_LOGIC;
      for_C_0_tr0 : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL matrix_mul_core_core_fsm_inst_fsm_output : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL matrix_mul_core_core_fsm_inst_for_for_for_C_2_tr0 : STD_LOGIC;
  SIGNAL matrix_mul_core_core_fsm_inst_for_for_C_1_tr0 : STD_LOGIC;
  SIGNAL matrix_mul_core_core_fsm_inst_for_C_0_tr0 : STD_LOGIC;

  FUNCTION CONV_SL_1_1(input:BOOLEAN)
  RETURN STD_LOGIC IS
  BEGIN
    IF input THEN RETURN '1';ELSE RETURN '0';END IF;
  END;

  FUNCTION MUX1HOT_v_5_3_2(input_2 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC_VECTOR(2 DOWNTO 0))
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);
    VARIABLE tmp : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      tmp := (OTHERS=>sel(0));
      result := input_0 and tmp;
      tmp := (OTHERS=>sel( 1));
      result := result or ( input_1 and tmp);
      tmp := (OTHERS=>sel( 2));
      result := result or ( input_2 and tmp);
    RETURN result;
  END;

  FUNCTION MUX_v_32_2_2(input_0 : STD_LOGIC_VECTOR(31 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(31 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(31 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

  FUNCTION MUX_v_5_2_2(input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

  FUNCTION MUX_v_6_2_2(input_0 : STD_LOGIC_VECTOR(5 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(5 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(5 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

BEGIN
  A_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_C_rsc_triosy_obj_ld_cse,
      lz => A_rsc_triosy_lz
    );
  B_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_C_rsc_triosy_obj_ld_cse,
      lz => B_rsc_triosy_lz
    );
  C_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_C_rsc_triosy_obj_ld_cse,
      lz => C_rsc_triosy_lz
    );
  matrix_mul_core_core_fsm_inst : matrix_mul_core_core_fsm
    PORT MAP(
      clk => clk,
      rst => rst,
      fsm_output => matrix_mul_core_core_fsm_inst_fsm_output,
      for_for_for_C_2_tr0 => matrix_mul_core_core_fsm_inst_for_for_for_C_2_tr0,
      for_for_C_1_tr0 => matrix_mul_core_core_fsm_inst_for_for_C_1_tr0,
      for_C_0_tr0 => matrix_mul_core_core_fsm_inst_for_C_0_tr0
    );
  fsm_output <= matrix_mul_core_core_fsm_inst_fsm_output;
  matrix_mul_core_core_fsm_inst_for_for_for_C_2_tr0 <= for_for_for_k_5_0_sva_1_5;
  matrix_mul_core_core_fsm_inst_for_for_C_1_tr0 <= for_for_for_k_5_0_sva_1_5;
  matrix_mul_core_core_fsm_inst_for_C_0_tr0 <= z_out(5);

  for_i_or_cse <= (fsm_output(0)) OR (fsm_output(6));
  for_for_j_or_cse <= (fsm_output(5)) OR for_i_or_cse;
  for_i_for_i_and_nl <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), for_for_for_k_5_0_sva_1_4_0,
      (fsm_output(3)));
  or_26_nl <= for_i_or_cse OR (fsm_output(3)) OR (fsm_output(5));
  for_for_for_k_for_for_for_k_mux_rgt <= MUX_v_6_2_2(z_out, ('0' & for_i_for_i_and_nl),
      or_26_nl);
  for_for_for_acc_7_psp_sva_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(for_for_sum_sva)
      + UNSIGNED(for_for_for_mul_sdt_sva(45 DOWNTO 14)), 32));
  A_rsci_adr_d <= for_i_5_0_sva_4_0_2 & for_for_for_k_5_0_sva_1_4_0;
  A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff <= fsm_output(1);
  B_rsci_adr_d <= for_for_for_k_5_0_sva_1_4_0 & for_for_j_5_0_sva_4_0_2;
  C_rsci_adr_d <= for_i_5_0_sva_4_0_2 & for_for_j_5_0_sva_4_0_2;
  C_rsci_d_d <= for_for_sum_sva;
  C_rsci_we_d_pff <= fsm_output(4);
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_i_5_0_sva_4_0_2 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( for_i_or_cse = '1' ) THEN
        for_i_5_0_sva_4_0_2 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), (z_out(4 DOWNTO
            0)), (fsm_output(6)));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_5_0_sva_4_0_2 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( for_for_j_or_cse = '1' ) THEN
        for_for_j_5_0_sva_4_0_2 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), for_for_for_k_5_0_sva_1_4_0,
            not_nl);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_sum_sva <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
      ELSIF ( ((fsm_output(3)) OR for_for_j_or_cse) = '1' ) THEN
        for_for_sum_sva <= MUX_v_32_2_2(STD_LOGIC_VECTOR'("00000000000000000000000000000000"),
            STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(for_for_for_acc_3_nl), 32)), for_for_sum_not_nl);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        reg_C_rsc_triosy_obj_ld_cse <= '0';
        for_for_for_mul_sdt_sva <= STD_LOGIC_VECTOR'( "0000000000000000000000000000000000000000000000");
      ELSE
        reg_C_rsc_triosy_obj_ld_cse <= (z_out(5)) AND (fsm_output(6));
        for_for_for_mul_sdt_sva <= STD_LOGIC_VECTOR(CONV_UNSIGNED(SIGNED'( SIGNED(A_rsci_q_d)
            * SIGNED(B_rsci_q_d)), 46));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_k_5_0_sva_1_5 <= '0';
      ELSIF ( ((fsm_output(6)) OR (fsm_output(0)) OR (fsm_output(5)) OR (fsm_output(4))
          OR (fsm_output(1)) OR (fsm_output(3))) = '1' ) THEN
        for_for_for_k_5_0_sva_1_5 <= for_for_for_k_for_for_for_k_mux_rgt(5);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_k_5_0_sva_1_4_0 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( ((fsm_output(6)) OR (fsm_output(0)) OR (fsm_output(5)) OR (fsm_output(4))
          OR (fsm_output(1))) = '1' ) THEN
        for_for_for_k_5_0_sva_1_4_0 <= for_for_for_k_for_for_for_k_mux_rgt(4 DOWNTO
            0);
      END IF;
    END IF;
  END PROCESS;
  not_nl <= NOT for_i_or_cse;
  for_for_for_and_nl <= (for_for_for_mul_sdt_sva(13)) AND (CONV_SL_1_1(for_for_for_mul_sdt_sva(12
      DOWNTO 0)/=STD_LOGIC_VECTOR'("0000000000000")) OR (for_for_for_acc_7_psp_sva_1(0)));
  for_for_for_acc_3_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(for_for_for_acc_7_psp_sva_1)
      + CONV_SIGNED(CONV_UNSIGNED(for_for_for_and_nl, 1), 32), 32));
  for_for_sum_not_nl <= NOT for_for_j_or_cse;
  for_for_for_mux1h_1_nl <= MUX1HOT_v_5_3_2(for_for_for_k_5_0_sva_1_4_0, for_for_j_5_0_sva_4_0_2,
      for_i_5_0_sva_4_0_2, STD_LOGIC_VECTOR'( (fsm_output(1)) & (fsm_output(4)) &
      (fsm_output(6))));
  z_out <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(for_for_for_mux1h_1_nl),
      6) + UNSIGNED'( "000001"), 6));
END v1;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    A_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsc_we : OUT STD_LOGIC;
    A_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsc_triosy_lz : OUT STD_LOGIC;
    B_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    B_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsc_we : OUT STD_LOGIC;
    B_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsc_triosy_lz : OUT STD_LOGIC;
    C_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    C_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsc_we : OUT STD_LOGIC;
    C_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsc_triosy_lz : OUT STD_LOGIC
  );
END matrix_mul;

ARCHITECTURE v1 OF matrix_mul IS
  -- Default Constants
  CONSTANT PWR : STD_LOGIC := '1';
  CONSTANT GND : STD_LOGIC := '0';

  -- Interconnect Declarations
  SIGNAL A_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff : STD_LOGIC;
  SIGNAL C_rsci_we_d_iff : STD_LOGIC;

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL A_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL B_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL C_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_d_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      A_rsc_triosy_lz : OUT STD_LOGIC;
      B_rsc_triosy_lz : OUT STD_LOGIC;
      C_rsc_triosy_lz : OUT STD_LOGIC;
      A_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      A_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      B_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      B_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      C_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      C_rsci_d_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff : OUT STD_LOGIC;
      C_rsci_we_d_pff : OUT STD_LOGIC
    );
  END COMPONENT;
  SIGNAL matrix_mul_core_inst_A_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_A_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_B_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_B_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_C_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_C_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);

BEGIN
  A_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => A_rsci_q,
      we => A_rsc_we,
      d => A_rsci_d,
      adr => A_rsci_adr,
      adr_d => A_rsci_adr_d_1,
      d_d => A_rsci_d_d,
      we_d => '0',
      q_d => A_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      port_0_rw_ram_ir_internal_WMASK_B_d => '0'
    );
  A_rsci_q <= A_rsc_q;
  A_rsc_d <= A_rsci_d;
  A_rsc_adr <= A_rsci_adr;
  A_rsci_adr_d_1 <= A_rsci_adr_d;
  A_rsci_d_d <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
  A_rsci_q_d <= A_rsci_q_d_1;

  B_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => B_rsci_q,
      we => B_rsc_we,
      d => B_rsci_d,
      adr => B_rsci_adr,
      adr_d => B_rsci_adr_d_1,
      d_d => B_rsci_d_d,
      we_d => '0',
      q_d => B_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      port_0_rw_ram_ir_internal_WMASK_B_d => '0'
    );
  B_rsci_q <= B_rsc_q;
  B_rsc_d <= B_rsci_d;
  B_rsc_adr <= B_rsci_adr;
  B_rsci_adr_d_1 <= B_rsci_adr_d;
  B_rsci_d_d <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
  B_rsci_q_d <= B_rsci_q_d_1;

  C_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => C_rsci_q,
      we => C_rsc_we,
      d => C_rsci_d,
      adr => C_rsci_adr,
      adr_d => C_rsci_adr_d_1,
      d_d => C_rsci_d_d_1,
      we_d => C_rsci_we_d_iff,
      q_d => C_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => '0',
      port_0_rw_ram_ir_internal_WMASK_B_d => C_rsci_we_d_iff
    );
  C_rsci_q <= C_rsc_q;
  C_rsc_d <= C_rsci_d;
  C_rsc_adr <= C_rsci_adr;
  C_rsci_adr_d_1 <= C_rsci_adr_d;
  C_rsci_d_d_1 <= C_rsci_d_d;
  C_rsci_q_d <= C_rsci_q_d_1;

  matrix_mul_core_inst : matrix_mul_core
    PORT MAP(
      clk => clk,
      rst => rst,
      A_rsc_triosy_lz => A_rsc_triosy_lz,
      B_rsc_triosy_lz => B_rsc_triosy_lz,
      C_rsc_triosy_lz => C_rsc_triosy_lz,
      A_rsci_adr_d => matrix_mul_core_inst_A_rsci_adr_d,
      A_rsci_q_d => matrix_mul_core_inst_A_rsci_q_d,
      B_rsci_adr_d => matrix_mul_core_inst_B_rsci_adr_d,
      B_rsci_q_d => matrix_mul_core_inst_B_rsci_q_d,
      C_rsci_adr_d => matrix_mul_core_inst_C_rsci_adr_d,
      C_rsci_d_d => matrix_mul_core_inst_C_rsci_d_d,
      A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      C_rsci_we_d_pff => C_rsci_we_d_iff
    );
  A_rsci_adr_d <= matrix_mul_core_inst_A_rsci_adr_d;
  matrix_mul_core_inst_A_rsci_q_d <= A_rsci_q_d;
  B_rsci_adr_d <= matrix_mul_core_inst_B_rsci_adr_d;
  matrix_mul_core_inst_B_rsci_q_d <= B_rsci_q_d;
  C_rsci_adr_d <= matrix_mul_core_inst_C_rsci_adr_d;
  C_rsci_d_d <= matrix_mul_core_inst_C_rsci_d_d;

END v1;



