
//------> /vol/mentor/Catapult_Synthesis_10.4a/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module mgc_io_sync_v2 (ld, lz);
    parameter valid = 0;

    input  ld;
    output lz;

    wire   lz;

    assign lz = ld;

endmodule


//------> ./rtl.v 
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4a/835166 Production Release
//  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
// 
//  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
//  Generated date: Tue Dec  2 08:15:20 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
// ------------------------------------------------------------------


module matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [31:0] q;
  output we;
  output [31:0] d;
  output [9:0] adr;
  input [9:0] adr_d;
  input [31:0] d_d;
  input we_d;
  output [31:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
// ------------------------------------------------------------------


module matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [31:0] q;
  output we;
  output [31:0] d;
  output [9:0] adr;
  input [9:0] adr_d;
  input [31:0] d_d;
  input we_d;
  output [31:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
// ------------------------------------------------------------------


module matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [31:0] q;
  output we;
  output [31:0] d;
  output [9:0] adr;
  input [9:0] adr_d;
  input [31:0] d_d;
  input we_d;
  output [31:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module matrix_mul_core_core_fsm (
  clk, rst, fsm_output
);
  input clk;
  input rst;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for matrix_mul_core_core_fsm_1
  parameter
    core_rlp_C_0 = 1'd0,
    main_C_0 = 1'd1;

  reg [0:0] state_var;
  reg [0:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : matrix_mul_core_core_fsm_1
    case (state_var)
      main_C_0 : begin
        fsm_output = 2'b10;
        state_var_NS = main_C_0;
      end
      // core_rlp_C_0
      default : begin
        fsm_output = 2'b01;
        state_var_NS = main_C_0;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( rst ) begin
      state_var <= core_rlp_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_core
// ------------------------------------------------------------------


module matrix_mul_core (
  clk, rst, A_rsc_triosy_lz, B_rsc_triosy_lz, C_rsc_triosy_lz, A_rsci_adr_d, A_rsci_q_d,
      B_rsci_adr_d, B_rsci_q_d, C_rsci_adr_d, C_rsci_d_d, A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff,
      C_rsci_we_d_pff
);
  input clk;
  input rst;
  output A_rsc_triosy_lz;
  output B_rsc_triosy_lz;
  output C_rsc_triosy_lz;
  output [9:0] A_rsci_adr_d;
  input [31:0] A_rsci_q_d;
  output [9:0] B_rsci_adr_d;
  input [31:0] B_rsci_q_d;
  output [9:0] C_rsci_adr_d;
  output [31:0] C_rsci_d_d;
  output A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff;
  output C_rsci_we_d_pff;


  // Interconnect Declarations
  reg C_rsc_triosy_obj_ld;
  wire [1:0] fsm_output;
  wire [5:0] for_acc_1_tmp;
  wire [6:0] nl_for_acc_1_tmp;
  wire [5:0] for_for_acc_2_tmp;
  wire [6:0] nl_for_for_acc_2_tmp;
  wire [5:0] for_for_for_acc_4_tmp;
  wire [6:0] nl_for_for_for_acc_4_tmp;
  wire and_dcpl_1;
  wire or_dcpl;
  wire not_tmp_4;
  wire or_dcpl_1;
  reg exit_for_for_lpi_1_dfm_2;
  wire lfst_exit_for_lpi_1_dfm_1;
  reg exit_for_lpi_1_dfm_2;
  reg exitL_exit_for_sva;
  reg for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1;
  reg for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
  reg main_stage_0_3;
  reg exit_for_lpi_1_dfm_2_st_2;
  reg for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2;
  reg reg_B_rsc_triosy_obj_ld_cse;
  reg reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse;
  reg [4:0] for_i_slc_for_i_5_0_4_0_1_itm_2_1;
  reg [4:0] for_for_j_slc_for_for_j_5_0_4_0_1_itm_2_1;
  wire [4:0] for_for_j_5_0_lpi_1_dfm_4_0_2;
  wire [4:0] for_i_5_0_lpi_1_dfm_4_0_2;
  wire [31:0] for_for_sum_sva_2;
  wire [32:0] nl_for_for_sum_sva_2;
  wire [4:0] for_for_for_k_5_0_lpi_1_dfm_4_0_3;
  wire or_dcpl_4;
  wire and_dcpl_18;
  reg lfst_exit_for_for_1_lpi_1_dfm_1;
  reg [31:0] for_for_for_for_and_itm_1;
  reg for_for_j_slc_for_for_j_5_0_5_3_itm_2;
  reg [45:0] for_for_for_mul_sdt_sva_1;
  wire signed [63:0] nl_for_for_for_mul_sdt_sva_1;
  reg [4:0] for_i_slc_for_i_5_0_4_0_1_itm_1;
  reg [4:0] for_for_j_slc_for_for_j_5_0_4_0_1_itm_1;
  reg for_for_j_slc_for_for_j_5_0_5_3_itm_1;
  reg for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_2;
  reg exit_for_lpi_1_dfm_2_st_1;
  reg [4:0] for_for_for_k_5_0_lpi_1_dfm_2_4_0;
  reg [4:0] for_i_5_0_lpi_1_dfm_1_4_0;
  reg [4:0] for_for_j_5_0_lpi_1_dfm_3_4_0;
  wire exit_for_lpi_1_dfm_2_mx0w0;
  wire lfst_exit_for_for_1_lpi_1_dfm_1_1;
  wire [31:0] for_for_for_acc_7_psp_sva_1;
  wire [32:0] nl_for_for_for_acc_7_psp_sva_1;
  wire and_33_cse;

  wire[0:0] mux_9_nl;
  wire[0:0] or_14_nl;
  wire[0:0] mux_6_nl;
  wire[0:0] for_for_j_and_1_nl;
  wire[0:0] or_13_nl;
  wire[0:0] nand_nl;
  wire[0:0] for_for_for_and_nl;
  wire[0:0] for_not_8_nl;

  // Interconnect Declarations for Component Instantiations 
  mgc_io_sync_v2 #(.valid(32'sd0)) A_rsc_triosy_obj (
      .ld(reg_B_rsc_triosy_obj_ld_cse),
      .lz(A_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) B_rsc_triosy_obj (
      .ld(reg_B_rsc_triosy_obj_ld_cse),
      .lz(B_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) C_rsc_triosy_obj (
      .ld(C_rsc_triosy_obj_ld),
      .lz(C_rsc_triosy_lz)
    );
  matrix_mul_core_core_fsm matrix_mul_core_core_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output)
    );
  assign and_33_cse = (for_for_for_acc_4_tmp[5]) & (for_for_acc_2_tmp[5]);
  assign for_for_for_and_nl = (for_for_for_mul_sdt_sva_1[13]) & ((for_for_for_mul_sdt_sva_1[12:0]!=13'b0000000000000)
      | (for_for_for_acc_7_psp_sva_1[0]));
  assign nl_for_for_sum_sva_2 = for_for_for_acc_7_psp_sva_1 + conv_u2s_1_32(for_for_for_and_nl);
  assign for_for_sum_sva_2 = nl_for_for_sum_sva_2[31:0];
  assign for_for_j_5_0_lpi_1_dfm_4_0_2 = MUX_v_5_2_2(5'b00000, for_for_j_5_0_lpi_1_dfm_3_4_0,
      lfst_exit_for_lpi_1_dfm_1);
  assign for_for_for_k_5_0_lpi_1_dfm_4_0_3 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_lpi_1_dfm_2_4_0,
      lfst_exit_for_for_1_lpi_1_dfm_1_1);
  assign for_not_8_nl = ~ exitL_exit_for_sva;
  assign for_i_5_0_lpi_1_dfm_4_0_2 = MUX_v_5_2_2(5'b00000, for_i_5_0_lpi_1_dfm_1_4_0,
      (for_not_8_nl));
  assign exit_for_lpi_1_dfm_2_mx0w0 = (for_acc_1_tmp[5]) & and_33_cse;
  assign lfst_exit_for_for_1_lpi_1_dfm_1_1 = (~ exit_for_for_lpi_1_dfm_2) & lfst_exit_for_lpi_1_dfm_1;
  assign nl_for_for_for_acc_7_psp_sva_1 = for_for_for_for_and_itm_1 + (for_for_for_mul_sdt_sva_1[45:14]);
  assign for_for_for_acc_7_psp_sva_1 = nl_for_for_for_acc_7_psp_sva_1[31:0];
  assign nl_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_lpi_1_dfm_4_0_2) + 6'b000001;
  assign for_acc_1_tmp = nl_for_acc_1_tmp[5:0];
  assign nl_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_lpi_1_dfm_4_0_2) + 6'b000001;
  assign for_for_acc_2_tmp = nl_for_for_acc_2_tmp[5:0];
  assign nl_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_lpi_1_dfm_4_0_3)
      + 6'b000001;
  assign for_for_for_acc_4_tmp = nl_for_for_for_acc_4_tmp[5:0];
  assign lfst_exit_for_lpi_1_dfm_1 = ~(exit_for_lpi_1_dfm_2 | exitL_exit_for_sva);
  assign and_dcpl_1 = for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 & reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse;
  assign or_dcpl = ((~(exitL_exit_for_sva | exit_for_for_lpi_1_dfm_2)) & (~(exit_for_lpi_1_dfm_2
      | for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1))) | for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
  assign not_tmp_4 = ~(exit_for_lpi_1_dfm_2 | exit_for_for_lpi_1_dfm_2 | exitL_exit_for_sva);
  assign or_dcpl_1 = ~((for_for_for_acc_4_tmp[5]) & (for_for_acc_2_tmp[5]));
  assign A_rsci_adr_d = {for_i_5_0_lpi_1_dfm_4_0_2 , for_for_for_k_5_0_lpi_1_dfm_4_0_3};
  assign A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff = fsm_output[1];
  assign B_rsci_adr_d = {for_for_for_k_5_0_lpi_1_dfm_4_0_3 , for_for_j_5_0_lpi_1_dfm_4_0_2};
  assign C_rsci_adr_d = {for_i_slc_for_i_5_0_4_0_1_itm_2_1 , for_for_j_slc_for_for_j_5_0_4_0_1_itm_2_1};
  assign C_rsci_d_d = for_for_sum_sva_2;
  assign C_rsci_we_d_pff = main_stage_0_3 & for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_2;
  assign or_dcpl_4 = (~ reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse) | lfst_exit_for_for_1_lpi_1_dfm_1;
  assign and_dcpl_18 = or_dcpl_4 & main_stage_0_3 & for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2;
  always @(posedge clk) begin
    if ( rst ) begin
      C_rsc_triosy_obj_ld <= 1'b0;
      reg_B_rsc_triosy_obj_ld_cse <= 1'b0;
      reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse <= 1'b0;
      main_stage_0_3 <= 1'b0;
      lfst_exit_for_for_1_lpi_1_dfm_1 <= 1'b0;
      exit_for_lpi_1_dfm_2_st_1 <= 1'b0;
      for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 <= 1'b0;
    end
    else begin
      C_rsc_triosy_obj_ld <= main_stage_0_3 & exit_for_lpi_1_dfm_2_st_2;
      reg_B_rsc_triosy_obj_ld_cse <= (for_for_for_acc_4_tmp[5]) & (for_for_acc_2_tmp[5])
          & (for_acc_1_tmp[5]) & (fsm_output[1]);
      reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse <= fsm_output[1];
      main_stage_0_3 <= reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse;
      lfst_exit_for_for_1_lpi_1_dfm_1 <= lfst_exit_for_for_1_lpi_1_dfm_1_1;
      exit_for_lpi_1_dfm_2_st_1 <= exit_for_lpi_1_dfm_2_mx0w0;
      for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 <= for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_slc_for_i_5_0_4_0_1_itm_2_1 <= 5'b00000;
      for_for_j_slc_for_for_j_5_0_4_0_1_itm_2_1 <= 5'b00000;
    end
    else if ( and_dcpl_1 ) begin
      for_i_slc_for_i_5_0_4_0_1_itm_2_1 <= for_i_slc_for_i_5_0_4_0_1_itm_1;
      for_for_j_slc_for_for_j_5_0_4_0_1_itm_2_1 <= for_for_j_slc_for_for_j_5_0_4_0_1_itm_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      exit_for_lpi_1_dfm_2_st_2 <= 1'b0;
      for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_2 <= 1'b0;
    end
    else if ( reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse ) begin
      exit_for_lpi_1_dfm_2_st_2 <= exit_for_lpi_1_dfm_2_st_1;
      for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_2 <= for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_mul_sdt_sva_1 <= 46'b0000000000000000000000000000000000000000000000;
    end
    else if ( or_dcpl & reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse ) begin
      for_for_for_mul_sdt_sva_1 <= nl_for_for_for_mul_sdt_sva_1[45:0];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_for_and_itm_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( (mux_6_nl) & (~(or_dcpl_4 & (~ main_stage_0_3))) ) begin
      for_for_for_for_and_itm_1 <= MUX_v_32_2_2((signext_32_1(mux_9_nl)), for_for_sum_sva_2,
          or_14_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      exit_for_lpi_1_dfm_2 <= 1'b0;
    end
    else if ( ~ (fsm_output[0]) ) begin
      exit_for_lpi_1_dfm_2 <= exit_for_lpi_1_dfm_2_mx0w0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      exit_for_for_lpi_1_dfm_2 <= 1'b0;
    end
    else if ( ~ (fsm_output[0]) ) begin
      exit_for_for_lpi_1_dfm_2 <= and_33_cse;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_lpi_1_dfm_2_4_0 <= 5'b00000;
      for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1 <= 1'b0;
    end
    else if ( or_dcpl_1 ) begin
      for_for_for_k_5_0_lpi_1_dfm_2_4_0 <= for_for_for_acc_4_tmp[4:0];
      for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1 <= for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_lpi_1_dfm_3_4_0 <= 5'b00000;
    end
    else if ( MUX_s_1_2_2((or_13_nl), (nand_nl), for_for_for_acc_4_tmp[5]) ) begin
      for_for_j_5_0_lpi_1_dfm_3_4_0 <= MUX1HOT_v_5_3_2((signext_5_1(for_acc_1_tmp[5])),
          for_for_j_5_0_lpi_1_dfm_4_0_2, (for_for_acc_2_tmp[4:0]), {(~ or_dcpl_1)
          , (~ (for_for_for_acc_4_tmp[5])) , (for_for_j_and_1_nl)});
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      exitL_exit_for_sva <= 1'b1;
    end
    else if ( ~ (fsm_output[0]) ) begin
      exitL_exit_for_sva <= exit_for_lpi_1_dfm_2_mx0w0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_lpi_1_dfm_1_4_0 <= 5'b00000;
    end
    else if ( MUX_s_1_2_2(exitL_exit_for_sva, (~ (for_acc_1_tmp[5])), and_33_cse)
        ) begin
      for_i_5_0_lpi_1_dfm_1_4_0 <= MUX_v_5_2_2((for_acc_1_tmp[4:0]), for_i_5_0_lpi_1_dfm_4_0_2,
          or_dcpl_1);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_slc_for_for_j_5_0_5_3_itm_2 <= 1'b0;
    end
    else if ( not_tmp_4 & for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 & for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1
        ) begin
      for_for_j_slc_for_for_j_5_0_5_3_itm_2 <= for_for_j_slc_for_for_j_5_0_5_3_itm_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2 <= 1'b0;
    end
    else if ( not_tmp_4 ) begin
      for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2 <= for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 <= 5'b00000;
    end
    else if ( for_for_for_acc_4_tmp[5] ) begin
      for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 <= for_for_j_5_0_lpi_1_dfm_4_0_2;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_slc_for_i_5_0_4_0_1_itm_1 <= 5'b00000;
    end
    else if ( for_for_for_acc_4_tmp[5] ) begin
      for_i_slc_for_i_5_0_4_0_1_itm_1 <= for_i_5_0_lpi_1_dfm_4_0_2;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_slc_for_for_j_5_0_5_3_itm_1 <= 1'b0;
    end
    else if ( (for_for_for_acc_4_tmp[5]) & (~ (for_for_acc_2_tmp[5])) ) begin
      for_for_j_slc_for_for_j_5_0_5_3_itm_1 <= for_for_acc_2_tmp[5];
    end
  end
  assign nl_for_for_for_mul_sdt_sva_1  = $signed((A_rsci_q_d)) * $signed((B_rsci_q_d));
  assign mux_9_nl = MUX_s_1_2_2(lfst_exit_for_for_1_lpi_1_dfm_1, for_for_j_slc_for_for_j_5_0_5_3_itm_2,
      and_dcpl_18);
  assign or_14_nl = (and_dcpl_18 & for_for_j_slc_for_for_j_5_0_5_3_itm_2) | (or_dcpl_4
      & main_stage_0_3 & (~ for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2));
  assign mux_6_nl = MUX_s_1_2_2(not_tmp_4, or_dcpl, reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse);
  assign for_for_j_and_1_nl = (for_for_for_acc_4_tmp[5]) & or_dcpl_1;
  assign or_13_nl = exit_for_lpi_1_dfm_2 | exitL_exit_for_sva;
  assign nand_nl = ~((for_for_acc_2_tmp[5]) & (for_acc_1_tmp[5]));

  function automatic [4:0] MUX1HOT_v_5_3_2;
    input [4:0] input_2;
    input [4:0] input_1;
    input [4:0] input_0;
    input [2:0] sel;
    reg [4:0] result;
  begin
    result = input_0 & {5{sel[0]}};
    result = result | ( input_1 & {5{sel[1]}});
    result = result | ( input_2 & {5{sel[2]}});
    MUX1HOT_v_5_3_2 = result;
  end
  endfunction


  function automatic [0:0] MUX_s_1_2_2;
    input [0:0] input_0;
    input [0:0] input_1;
    input [0:0] sel;
    reg [0:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [0:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [4:0] MUX_v_5_2_2;
    input [4:0] input_0;
    input [4:0] input_1;
    input [0:0] sel;
    reg [4:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_5_2_2 = result;
  end
  endfunction


  function automatic [31:0] signext_32_1;
    input [0:0] vector;
  begin
    signext_32_1= {{31{vector[0]}}, vector};
  end
  endfunction


  function automatic [4:0] signext_5_1;
    input [0:0] vector;
  begin
    signext_5_1= {{4{vector[0]}}, vector};
  end
  endfunction


  function automatic [31:0] conv_u2s_1_32 ;
    input [0:0]  vector ;
  begin
    conv_u2s_1_32 = {{31{1'b0}}, vector};
  end
  endfunction


  function automatic [5:0] conv_u2s_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2s_5_6 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul
// ------------------------------------------------------------------


module matrix_mul (
  clk, rst, A_rsc_adr, A_rsc_d, A_rsc_we, A_rsc_q, A_rsc_triosy_lz, B_rsc_adr, B_rsc_d,
      B_rsc_we, B_rsc_q, B_rsc_triosy_lz, C_rsc_adr, C_rsc_d, C_rsc_we, C_rsc_q,
      C_rsc_triosy_lz
);
  input clk;
  input rst;
  output [9:0] A_rsc_adr;
  output [31:0] A_rsc_d;
  output A_rsc_we;
  input [31:0] A_rsc_q;
  output A_rsc_triosy_lz;
  output [9:0] B_rsc_adr;
  output [31:0] B_rsc_d;
  output B_rsc_we;
  input [31:0] B_rsc_q;
  output B_rsc_triosy_lz;
  output [9:0] C_rsc_adr;
  output [31:0] C_rsc_d;
  output C_rsc_we;
  input [31:0] C_rsc_q;
  output C_rsc_triosy_lz;


  // Interconnect Declarations
  wire [9:0] A_rsci_adr_d;
  wire [31:0] A_rsci_q_d;
  wire [9:0] B_rsci_adr_d;
  wire [31:0] B_rsci_q_d;
  wire [9:0] C_rsci_adr_d;
  wire [31:0] C_rsci_d_d;
  wire [31:0] C_rsci_q_d;
  wire A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff;
  wire C_rsci_we_d_iff;


  // Interconnect Declarations for Component Instantiations 
  matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
      A_rsci (
      .q(A_rsc_q),
      .we(A_rsc_we),
      .d(A_rsc_d),
      .adr(A_rsc_adr),
      .adr_d(A_rsci_adr_d),
      .d_d(32'b00000000000000000000000000000000),
      .we_d(1'b0),
      .q_d(A_rsci_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff),
      .port_0_rw_ram_ir_internal_WMASK_B_d(1'b0)
    );
  matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
      B_rsci (
      .q(B_rsc_q),
      .we(B_rsc_we),
      .d(B_rsc_d),
      .adr(B_rsc_adr),
      .adr_d(B_rsci_adr_d),
      .d_d(32'b00000000000000000000000000000000),
      .we_d(1'b0),
      .q_d(B_rsci_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff),
      .port_0_rw_ram_ir_internal_WMASK_B_d(1'b0)
    );
  matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
      C_rsci (
      .q(C_rsc_q),
      .we(C_rsc_we),
      .d(C_rsc_d),
      .adr(C_rsc_adr),
      .adr_d(C_rsci_adr_d),
      .d_d(C_rsci_d_d),
      .we_d(C_rsci_we_d_iff),
      .q_d(C_rsci_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(1'b0),
      .port_0_rw_ram_ir_internal_WMASK_B_d(C_rsci_we_d_iff)
    );
  matrix_mul_core matrix_mul_core_inst (
      .clk(clk),
      .rst(rst),
      .A_rsc_triosy_lz(A_rsc_triosy_lz),
      .B_rsc_triosy_lz(B_rsc_triosy_lz),
      .C_rsc_triosy_lz(C_rsc_triosy_lz),
      .A_rsci_adr_d(A_rsci_adr_d),
      .A_rsci_q_d(A_rsci_q_d),
      .B_rsci_adr_d(B_rsci_adr_d),
      .B_rsci_q_d(B_rsci_q_d),
      .C_rsci_adr_d(C_rsci_adr_d),
      .C_rsci_d_d(C_rsci_d_d),
      .A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff(A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff),
      .C_rsci_we_d_pff(C_rsci_we_d_iff)
    );
endmodule



