
--------> /vol/mentor/Catapult_Synthesis_10.4a/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.vhd 
--------------------------------------------------------------------------------
-- Catapult Synthesis - Sample I/O Port Library
--
-- Copyright (c) 2003-2017 Mentor Graphics Corp.
--       All Rights Reserved
--
-- This document may be used and distributed without restriction provided that
-- this copyright statement is not removed from the file and that any derivative
-- work contains this copyright notice.
--
-- The design information contained in this file is intended to be an example
-- of the functionality which the end user may study in preparation for creating
-- their own custom interfaces. This design does not necessarily present a 
-- complete implementation of the named protocol or standard.
--
--------------------------------------------------------------------------------

LIBRARY ieee;

USE ieee.std_logic_1164.all;
PACKAGE mgc_io_sync_pkg_v2 IS

COMPONENT mgc_io_sync_v2
  GENERIC (
    valid    : INTEGER RANGE 0 TO 1
  );
  PORT (
    ld       : IN    std_logic;
    lz       : OUT   std_logic
  );
END COMPONENT;

END mgc_io_sync_pkg_v2;

LIBRARY ieee;

USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all; -- Prevent STARC 2.1.1.2 violation

ENTITY mgc_io_sync_v2 IS
  GENERIC (
    valid    : INTEGER RANGE 0 TO 1
  );
  PORT (
    ld       : IN    std_logic;
    lz       : OUT   std_logic
  );
END mgc_io_sync_v2;

ARCHITECTURE beh OF mgc_io_sync_v2 IS
BEGIN

  lz <= ld;

END beh;


--------> ./rtl.vhdl 
-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    10.4a/835166 Production Release
--  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
-- 
--  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
--  Generated date: Tue Dec  2 08:15:18 2025
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen;

ARCHITECTURE v2 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen;

ARCHITECTURE v2 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    IS
  PORT(
    q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we : OUT STD_LOGIC;
    d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
    d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    we_d : IN STD_LOGIC;
    q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
    port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
  );
END matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen;

ARCHITECTURE v2 OF matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    IS
  -- Default Constants

BEGIN
  q_d <= q;
  we <= (port_0_rw_ram_ir_internal_WMASK_B_d);
  d <= (d_d);
  adr <= (adr_d);
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_core_core_fsm
--  FSM Module
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_core_core_fsm IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    fsm_output : OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
  );
END matrix_mul_core_core_fsm;

ARCHITECTURE v2 OF matrix_mul_core_core_fsm IS
  -- Default Constants

  -- FSM State Type Declaration for matrix_mul_core_core_fsm_1
  TYPE matrix_mul_core_core_fsm_1_ST IS (core_rlp_C_0, main_C_0);

  SIGNAL state_var : matrix_mul_core_core_fsm_1_ST;
  SIGNAL state_var_NS : matrix_mul_core_core_fsm_1_ST;

BEGIN
  matrix_mul_core_core_fsm_1 : PROCESS (state_var)
  BEGIN
    CASE state_var IS
      WHEN main_C_0 =>
        fsm_output <= STD_LOGIC_VECTOR'( "10");
        state_var_NS <= main_C_0;
      -- core_rlp_C_0
      WHEN OTHERS =>
        fsm_output <= STD_LOGIC_VECTOR'( "01");
        state_var_NS <= main_C_0;
    END CASE;
  END PROCESS matrix_mul_core_core_fsm_1;

  matrix_mul_core_core_fsm_1_REG : PROCESS (clk)
  BEGIN
    IF clk'event AND ( clk = '1' ) THEN
      IF ( rst = '1' ) THEN
        state_var <= core_rlp_C_0;
      ELSE
        state_var <= state_var_NS;
      END IF;
    END IF;
  END PROCESS matrix_mul_core_core_fsm_1_REG;

END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul_core
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_triosy_lz : OUT STD_LOGIC;
    B_rsc_triosy_lz : OUT STD_LOGIC;
    C_rsc_triosy_lz : OUT STD_LOGIC;
    A_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    A_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    B_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    C_rsci_d_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff : OUT STD_LOGIC;
    C_rsci_we_d_pff : OUT STD_LOGIC
  );
END matrix_mul_core;

ARCHITECTURE v2 OF matrix_mul_core IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL C_rsc_triosy_obj_ld : STD_LOGIC;
  SIGNAL fsm_output : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL for_acc_1_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL for_for_acc_2_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL for_for_for_acc_4_tmp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL and_dcpl_1 : STD_LOGIC;
  SIGNAL or_dcpl : STD_LOGIC;
  SIGNAL not_tmp_4 : STD_LOGIC;
  SIGNAL or_dcpl_1 : STD_LOGIC;
  SIGNAL exit_for_for_lpi_1_dfm_2 : STD_LOGIC;
  SIGNAL lfst_exit_for_lpi_1_dfm_1 : STD_LOGIC;
  SIGNAL exit_for_lpi_1_dfm_2 : STD_LOGIC;
  SIGNAL exitL_exit_for_sva : STD_LOGIC;
  SIGNAL for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1 : STD_LOGIC;
  SIGNAL for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 : STD_LOGIC;
  SIGNAL main_stage_0_3 : STD_LOGIC;
  SIGNAL exit_for_lpi_1_dfm_2_st_2 : STD_LOGIC;
  SIGNAL for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2 : STD_LOGIC;
  SIGNAL reg_B_rsc_triosy_obj_ld_cse : STD_LOGIC;
  SIGNAL reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse : STD_LOGIC;
  SIGNAL for_i_slc_for_i_5_0_4_0_1_itm_2_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_j_slc_for_for_j_5_0_4_0_1_itm_2_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_j_5_0_lpi_1_dfm_4_0_2 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_i_5_0_lpi_1_dfm_4_0_2 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_sum_sva_2 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_for_for_k_5_0_lpi_1_dfm_4_0_3 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL or_dcpl_4 : STD_LOGIC;
  SIGNAL and_dcpl_18 : STD_LOGIC;
  SIGNAL lfst_exit_for_for_1_lpi_1_dfm_1 : STD_LOGIC;
  SIGNAL for_for_for_for_and_itm_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL for_for_j_slc_for_for_j_5_0_5_3_itm_2 : STD_LOGIC;
  SIGNAL for_for_for_mul_sdt_sva_1 : STD_LOGIC_VECTOR (45 DOWNTO 0);
  SIGNAL for_i_slc_for_i_5_0_4_0_1_itm_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_j_slc_for_for_j_5_0_5_3_itm_1 : STD_LOGIC;
  SIGNAL for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_2 : STD_LOGIC;
  SIGNAL exit_for_lpi_1_dfm_2_st_1 : STD_LOGIC;
  SIGNAL for_for_for_k_5_0_lpi_1_dfm_2_4_0 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_i_5_0_lpi_1_dfm_1_4_0 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL for_for_j_5_0_lpi_1_dfm_3_4_0 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL exit_for_lpi_1_dfm_2_mx0w0 : STD_LOGIC;
  SIGNAL lfst_exit_for_for_1_lpi_1_dfm_1_1 : STD_LOGIC;
  SIGNAL for_for_for_acc_7_psp_sva_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL and_33_cse : STD_LOGIC;

  SIGNAL mux_9_nl : STD_LOGIC;
  SIGNAL or_14_nl : STD_LOGIC;
  SIGNAL mux_6_nl : STD_LOGIC;
  SIGNAL for_for_j_and_1_nl : STD_LOGIC;
  SIGNAL or_13_nl : STD_LOGIC;
  SIGNAL nand_nl : STD_LOGIC;
  SIGNAL for_for_for_and_nl : STD_LOGIC;
  SIGNAL for_not_8_nl : STD_LOGIC;
  COMPONENT matrix_mul_core_core_fsm
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      fsm_output : OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL matrix_mul_core_core_fsm_inst_fsm_output : STD_LOGIC_VECTOR (1 DOWNTO 0);

  FUNCTION CONV_SL_1_1(input:BOOLEAN)
  RETURN STD_LOGIC IS
  BEGIN
    IF input THEN RETURN '1';ELSE RETURN '0';END IF;
  END;

  FUNCTION MUX1HOT_v_5_3_2(input_2 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC_VECTOR(2 DOWNTO 0))
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);
    VARIABLE tmp : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      tmp := (OTHERS=>sel(0));
      result := input_0 and tmp;
      tmp := (OTHERS=>sel( 1));
      result := result or ( input_1 and tmp);
      tmp := (OTHERS=>sel( 2));
      result := result or ( input_2 and tmp);
    RETURN result;
  END;

  FUNCTION MUX_s_1_2_2(input_0 : STD_LOGIC;
  input_1 : STD_LOGIC;
  sel : STD_LOGIC)
  RETURN STD_LOGIC IS
    VARIABLE result : STD_LOGIC;

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

  FUNCTION MUX_v_32_2_2(input_0 : STD_LOGIC_VECTOR(31 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(31 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(31 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

  FUNCTION MUX_v_5_2_2(input_0 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  input_1 : STD_LOGIC_VECTOR(4 DOWNTO 0);
  sel : STD_LOGIC)
  RETURN STD_LOGIC_VECTOR IS
    VARIABLE result : STD_LOGIC_VECTOR(4 DOWNTO 0);

    BEGIN
      CASE sel IS
        WHEN '0' =>
          result := input_0;
        WHEN others =>
          result := input_1;
      END CASE;
    RETURN result;
  END;

BEGIN
  A_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_B_rsc_triosy_obj_ld_cse,
      lz => A_rsc_triosy_lz
    );
  B_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_B_rsc_triosy_obj_ld_cse,
      lz => B_rsc_triosy_lz
    );
  C_rsc_triosy_obj : work.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => C_rsc_triosy_obj_ld,
      lz => C_rsc_triosy_lz
    );
  matrix_mul_core_core_fsm_inst : matrix_mul_core_core_fsm
    PORT MAP(
      clk => clk,
      rst => rst,
      fsm_output => matrix_mul_core_core_fsm_inst_fsm_output
    );
  fsm_output <= matrix_mul_core_core_fsm_inst_fsm_output;

  and_33_cse <= (for_for_for_acc_4_tmp(5)) AND (for_for_acc_2_tmp(5));
  for_for_for_and_nl <= (for_for_for_mul_sdt_sva_1(13)) AND (CONV_SL_1_1(for_for_for_mul_sdt_sva_1(12
      DOWNTO 0)/=STD_LOGIC_VECTOR'("0000000000000")) OR (for_for_for_acc_7_psp_sva_1(0)));
  for_for_sum_sva_2 <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(for_for_for_acc_7_psp_sva_1)
      + CONV_SIGNED(CONV_UNSIGNED(for_for_for_and_nl, 1), 32), 32));
  for_for_j_5_0_lpi_1_dfm_4_0_2 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), for_for_j_5_0_lpi_1_dfm_3_4_0,
      lfst_exit_for_lpi_1_dfm_1);
  for_for_for_k_5_0_lpi_1_dfm_4_0_3 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), for_for_for_k_5_0_lpi_1_dfm_2_4_0,
      lfst_exit_for_for_1_lpi_1_dfm_1_1);
  for_not_8_nl <= NOT exitL_exit_for_sva;
  for_i_5_0_lpi_1_dfm_4_0_2 <= MUX_v_5_2_2(STD_LOGIC_VECTOR'("00000"), for_i_5_0_lpi_1_dfm_1_4_0,
      for_not_8_nl);
  exit_for_lpi_1_dfm_2_mx0w0 <= (for_acc_1_tmp(5)) AND and_33_cse;
  lfst_exit_for_for_1_lpi_1_dfm_1_1 <= (NOT exit_for_for_lpi_1_dfm_2) AND lfst_exit_for_lpi_1_dfm_1;
  for_for_for_acc_7_psp_sva_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(for_for_for_for_and_itm_1)
      + UNSIGNED(for_for_for_mul_sdt_sva_1(45 DOWNTO 14)), 32));
  for_acc_1_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_i_5_0_lpi_1_dfm_4_0_2),
      5), 6) + SIGNED'( "000001"), 6));
  for_for_acc_2_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_for_j_5_0_lpi_1_dfm_4_0_2),
      5), 6) + SIGNED'( "000001"), 6));
  for_for_for_acc_4_tmp <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(for_for_for_k_5_0_lpi_1_dfm_4_0_3),
      5), 6) + SIGNED'( "000001"), 6));
  lfst_exit_for_lpi_1_dfm_1 <= NOT(exit_for_lpi_1_dfm_2 OR exitL_exit_for_sva);
  and_dcpl_1 <= for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 AND reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse;
  or_dcpl <= ((NOT(exitL_exit_for_sva OR exit_for_for_lpi_1_dfm_2)) AND (NOT(exit_for_lpi_1_dfm_2
      OR for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1))) OR for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
  not_tmp_4 <= NOT(exit_for_lpi_1_dfm_2 OR exit_for_for_lpi_1_dfm_2 OR exitL_exit_for_sva);
  or_dcpl_1 <= NOT((for_for_for_acc_4_tmp(5)) AND (for_for_acc_2_tmp(5)));
  A_rsci_adr_d <= for_i_5_0_lpi_1_dfm_4_0_2 & for_for_for_k_5_0_lpi_1_dfm_4_0_3;
  A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff <= fsm_output(1);
  B_rsci_adr_d <= for_for_for_k_5_0_lpi_1_dfm_4_0_3 & for_for_j_5_0_lpi_1_dfm_4_0_2;
  C_rsci_adr_d <= for_i_slc_for_i_5_0_4_0_1_itm_2_1 & for_for_j_slc_for_for_j_5_0_4_0_1_itm_2_1;
  C_rsci_d_d <= for_for_sum_sva_2;
  C_rsci_we_d_pff <= main_stage_0_3 AND for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_2;
  or_dcpl_4 <= (NOT reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse) OR lfst_exit_for_for_1_lpi_1_dfm_1;
  and_dcpl_18 <= or_dcpl_4 AND main_stage_0_3 AND for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        C_rsc_triosy_obj_ld <= '0';
        reg_B_rsc_triosy_obj_ld_cse <= '0';
        reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse <= '0';
        main_stage_0_3 <= '0';
        lfst_exit_for_for_1_lpi_1_dfm_1 <= '0';
        exit_for_lpi_1_dfm_2_st_1 <= '0';
        for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 <= '0';
      ELSE
        C_rsc_triosy_obj_ld <= main_stage_0_3 AND exit_for_lpi_1_dfm_2_st_2;
        reg_B_rsc_triosy_obj_ld_cse <= (for_for_for_acc_4_tmp(5)) AND (for_for_acc_2_tmp(5))
            AND (for_acc_1_tmp(5)) AND (fsm_output(1));
        reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse <= fsm_output(1);
        main_stage_0_3 <= reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse;
        lfst_exit_for_for_1_lpi_1_dfm_1 <= lfst_exit_for_for_1_lpi_1_dfm_1_1;
        exit_for_lpi_1_dfm_2_st_1 <= exit_for_lpi_1_dfm_2_mx0w0;
        for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 <= for_for_for_acc_4_tmp(5);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_i_slc_for_i_5_0_4_0_1_itm_2_1 <= STD_LOGIC_VECTOR'( "00000");
        for_for_j_slc_for_for_j_5_0_4_0_1_itm_2_1 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( and_dcpl_1 = '1' ) THEN
        for_i_slc_for_i_5_0_4_0_1_itm_2_1 <= for_i_slc_for_i_5_0_4_0_1_itm_1;
        for_for_j_slc_for_for_j_5_0_4_0_1_itm_2_1 <= for_for_j_slc_for_for_j_5_0_4_0_1_itm_1;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        exit_for_lpi_1_dfm_2_st_2 <= '0';
        for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_2 <= '0';
      ELSIF ( reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse = '1' ) THEN
        exit_for_lpi_1_dfm_2_st_2 <= exit_for_lpi_1_dfm_2_st_1;
        for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_2 <= for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_mul_sdt_sva_1 <= STD_LOGIC_VECTOR'( "0000000000000000000000000000000000000000000000");
      ELSIF ( (or_dcpl AND reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse) =
          '1' ) THEN
        for_for_for_mul_sdt_sva_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(SIGNED'( SIGNED(A_rsci_q_d)
            * SIGNED(B_rsci_q_d)), 46));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_for_and_itm_1 <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
      ELSIF ( (mux_6_nl AND (NOT(or_dcpl_4 AND (NOT main_stage_0_3)))) = '1' ) THEN
        for_for_for_for_and_itm_1 <= MUX_v_32_2_2(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(mux_9_nl,
            1),32)), for_for_sum_sva_2, or_14_nl);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        exit_for_lpi_1_dfm_2 <= '0';
      ELSIF ( (fsm_output(0)) = '0' ) THEN
        exit_for_lpi_1_dfm_2 <= exit_for_lpi_1_dfm_2_mx0w0;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        exit_for_for_lpi_1_dfm_2 <= '0';
      ELSIF ( (fsm_output(0)) = '0' ) THEN
        exit_for_for_lpi_1_dfm_2 <= and_33_cse;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_k_5_0_lpi_1_dfm_2_4_0 <= STD_LOGIC_VECTOR'( "00000");
        for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1 <= '0';
      ELSIF ( or_dcpl_1 = '1' ) THEN
        for_for_for_k_5_0_lpi_1_dfm_2_4_0 <= for_for_for_acc_4_tmp(4 DOWNTO 0);
        for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1 <= for_for_for_acc_4_tmp(5);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_5_0_lpi_1_dfm_3_4_0 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( (MUX_s_1_2_2(or_13_nl, nand_nl, for_for_for_acc_4_tmp(5))) = '1' )
          THEN
        for_for_j_5_0_lpi_1_dfm_3_4_0 <= MUX1HOT_v_5_3_2(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(for_acc_1_tmp(5),
            1),5)), for_for_j_5_0_lpi_1_dfm_4_0_2, (for_for_acc_2_tmp(4 DOWNTO 0)),
            STD_LOGIC_VECTOR'( (NOT or_dcpl_1) & (NOT (for_for_for_acc_4_tmp(5)))
            & for_for_j_and_1_nl));
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        exitL_exit_for_sva <= '1';
      ELSIF ( (fsm_output(0)) = '0' ) THEN
        exitL_exit_for_sva <= exit_for_lpi_1_dfm_2_mx0w0;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_i_5_0_lpi_1_dfm_1_4_0 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( (MUX_s_1_2_2(exitL_exit_for_sva, (NOT (for_acc_1_tmp(5))), and_33_cse))
          = '1' ) THEN
        for_i_5_0_lpi_1_dfm_1_4_0 <= MUX_v_5_2_2((for_acc_1_tmp(4 DOWNTO 0)), for_i_5_0_lpi_1_dfm_4_0_2,
            or_dcpl_1);
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_slc_for_for_j_5_0_5_3_itm_2 <= '0';
      ELSIF ( (not_tmp_4 AND for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 AND for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1)
          = '1' ) THEN
        for_for_j_slc_for_for_j_5_0_5_3_itm_2 <= for_for_j_slc_for_for_j_5_0_5_3_itm_1;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2 <= '0';
      ELSIF ( not_tmp_4 = '1' ) THEN
        for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2 <= for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( (for_for_for_acc_4_tmp(5)) = '1' ) THEN
        for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 <= for_for_j_5_0_lpi_1_dfm_4_0_2;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_i_slc_for_i_5_0_4_0_1_itm_1 <= STD_LOGIC_VECTOR'( "00000");
      ELSIF ( (for_for_for_acc_4_tmp(5)) = '1' ) THEN
        for_i_slc_for_i_5_0_4_0_1_itm_1 <= for_i_5_0_lpi_1_dfm_4_0_2;
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        for_for_j_slc_for_for_j_5_0_5_3_itm_1 <= '0';
      ELSIF ( ((for_for_for_acc_4_tmp(5)) AND (NOT (for_for_acc_2_tmp(5)))) = '1'
          ) THEN
        for_for_j_slc_for_for_j_5_0_5_3_itm_1 <= for_for_acc_2_tmp(5);
      END IF;
    END IF;
  END PROCESS;
  mux_9_nl <= MUX_s_1_2_2(lfst_exit_for_for_1_lpi_1_dfm_1, for_for_j_slc_for_for_j_5_0_5_3_itm_2,
      and_dcpl_18);
  or_14_nl <= (and_dcpl_18 AND for_for_j_slc_for_for_j_5_0_5_3_itm_2) OR (or_dcpl_4
      AND main_stage_0_3 AND (NOT for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_2));
  mux_6_nl <= MUX_s_1_2_2(not_tmp_4, or_dcpl, reg_B_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_cse);
  for_for_j_and_1_nl <= (for_for_for_acc_4_tmp(5)) AND or_dcpl_1;
  or_13_nl <= exit_for_lpi_1_dfm_2 OR exitL_exit_for_sva;
  nand_nl <= NOT((for_for_acc_2_tmp(5)) AND (for_acc_1_tmp(5)));
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    matrix_mul
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

USE work.mgc_io_sync_pkg_v2.ALL;


ENTITY matrix_mul IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    A_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsc_we : OUT STD_LOGIC;
    A_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    A_rsc_triosy_lz : OUT STD_LOGIC;
    B_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    B_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsc_we : OUT STD_LOGIC;
    B_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    B_rsc_triosy_lz : OUT STD_LOGIC;
    C_rsc_adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
    C_rsc_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsc_we : OUT STD_LOGIC;
    C_rsc_q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
    C_rsc_triosy_lz : OUT STD_LOGIC
  );
END matrix_mul;

ARCHITECTURE v2 OF matrix_mul IS
  -- Default Constants
  CONSTANT PWR : STD_LOGIC := '1';
  CONSTANT GND : STD_LOGIC := '0';

  -- Interconnect Declarations
  SIGNAL A_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff : STD_LOGIC;
  SIGNAL C_rsci_we_d_iff : STD_LOGIC;

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL A_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL A_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL A_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL B_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL B_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL B_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    PORT(
      q : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we : OUT STD_LOGIC;
      d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      adr : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      adr_d : IN STD_LOGIC_VECTOR (9 DOWNTO 0);
      d_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      we_d : IN STD_LOGIC;
      q_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      port_0_rw_ram_ir_internal_RMASK_B_d : IN STD_LOGIC;
      port_0_rw_ram_ir_internal_WMASK_B_d : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL C_rsci_q : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_adr : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_adr_d_1 : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL C_rsci_d_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL C_rsci_q_d_1 : STD_LOGIC_VECTOR (31 DOWNTO 0);

  COMPONENT matrix_mul_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      A_rsc_triosy_lz : OUT STD_LOGIC;
      B_rsc_triosy_lz : OUT STD_LOGIC;
      C_rsc_triosy_lz : OUT STD_LOGIC;
      A_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      A_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      B_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      B_rsci_q_d : IN STD_LOGIC_VECTOR (31 DOWNTO 0);
      C_rsci_adr_d : OUT STD_LOGIC_VECTOR (9 DOWNTO 0);
      C_rsci_d_d : OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
      A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff : OUT STD_LOGIC;
      C_rsci_we_d_pff : OUT STD_LOGIC
    );
  END COMPONENT;
  SIGNAL matrix_mul_core_inst_A_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_A_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_B_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_B_rsci_q_d : STD_LOGIC_VECTOR (31 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_C_rsci_adr_d : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL matrix_mul_core_inst_C_rsci_d_d : STD_LOGIC_VECTOR (31 DOWNTO 0);

BEGIN
  A_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => A_rsci_q,
      we => A_rsc_we,
      d => A_rsci_d,
      adr => A_rsci_adr,
      adr_d => A_rsci_adr_d_1,
      d_d => A_rsci_d_d,
      we_d => '0',
      q_d => A_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      port_0_rw_ram_ir_internal_WMASK_B_d => '0'
    );
  A_rsci_q <= A_rsc_q;
  A_rsc_d <= A_rsci_d;
  A_rsc_adr <= A_rsci_adr;
  A_rsci_adr_d_1 <= A_rsci_adr_d;
  A_rsci_d_d <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
  A_rsci_q_d <= A_rsci_q_d_1;

  B_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => B_rsci_q,
      we => B_rsc_we,
      d => B_rsci_d,
      adr => B_rsci_adr,
      adr_d => B_rsci_adr_d_1,
      d_d => B_rsci_d_d,
      we_d => '0',
      q_d => B_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      port_0_rw_ram_ir_internal_WMASK_B_d => '0'
    );
  B_rsci_q <= B_rsc_q;
  B_rsc_d <= B_rsci_d;
  B_rsc_adr <= B_rsci_adr;
  B_rsci_adr_d_1 <= B_rsci_adr_d;
  B_rsci_d_d <= STD_LOGIC_VECTOR'( "00000000000000000000000000000000");
  B_rsci_q_d <= B_rsci_q_d_1;

  C_rsci : matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    PORT MAP(
      q => C_rsci_q,
      we => C_rsc_we,
      d => C_rsci_d,
      adr => C_rsci_adr,
      adr_d => C_rsci_adr_d_1,
      d_d => C_rsci_d_d_1,
      we_d => C_rsci_we_d_iff,
      q_d => C_rsci_q_d_1,
      port_0_rw_ram_ir_internal_RMASK_B_d => '0',
      port_0_rw_ram_ir_internal_WMASK_B_d => C_rsci_we_d_iff
    );
  C_rsci_q <= C_rsc_q;
  C_rsc_d <= C_rsci_d;
  C_rsc_adr <= C_rsci_adr;
  C_rsci_adr_d_1 <= C_rsci_adr_d;
  C_rsci_d_d_1 <= C_rsci_d_d;
  C_rsci_q_d <= C_rsci_q_d_1;

  matrix_mul_core_inst : matrix_mul_core
    PORT MAP(
      clk => clk,
      rst => rst,
      A_rsc_triosy_lz => A_rsc_triosy_lz,
      B_rsc_triosy_lz => B_rsc_triosy_lz,
      C_rsc_triosy_lz => C_rsc_triosy_lz,
      A_rsci_adr_d => matrix_mul_core_inst_A_rsci_adr_d,
      A_rsci_q_d => matrix_mul_core_inst_A_rsci_q_d,
      B_rsci_adr_d => matrix_mul_core_inst_B_rsci_adr_d,
      B_rsci_q_d => matrix_mul_core_inst_B_rsci_q_d,
      C_rsci_adr_d => matrix_mul_core_inst_C_rsci_adr_d,
      C_rsci_d_d => matrix_mul_core_inst_C_rsci_d_d,
      A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff => A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff,
      C_rsci_we_d_pff => C_rsci_we_d_iff
    );
  A_rsci_adr_d <= matrix_mul_core_inst_A_rsci_adr_d;
  matrix_mul_core_inst_A_rsci_q_d <= A_rsci_q_d;
  B_rsci_adr_d <= matrix_mul_core_inst_B_rsci_adr_d;
  matrix_mul_core_inst_B_rsci_q_d <= B_rsci_q_d;
  C_rsci_adr_d <= matrix_mul_core_inst_C_rsci_adr_d;
  C_rsci_d_d <= matrix_mul_core_inst_C_rsci_d_d;

END v2;



