
//------> /vol/mentor/Catapult_Synthesis_10.4a/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module mgc_io_sync_v2 (ld, lz);
    parameter valid = 0;

    input  ld;
    output lz;

    wire   lz;

    assign lz = ld;

endmodule


//------> ./rtl.v 
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4a/835166 Production Release
//  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
// 
//  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
//  Generated date: Tue Dec  2 09:10:31 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
// ------------------------------------------------------------------


module matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
    (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [31:0] q;
  output we;
  output [31:0] d;
  output [9:0] adr;
  input [9:0] adr_d;
  input [31:0] d_d;
  input we_d;
  output [31:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
// ------------------------------------------------------------------


module matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
    (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [31:0] q;
  output we;
  output [31:0] d;
  output [9:0] adr;
  input [9:0] adr_d;
  input [31:0] d_d;
  input we_d;
  output [31:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
// ------------------------------------------------------------------


module matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
    (
  q, we, d, adr, adr_d, d_d, we_d, q_d, port_0_rw_ram_ir_internal_RMASK_B_d, port_0_rw_ram_ir_internal_WMASK_B_d
);
  input [31:0] q;
  output we;
  output [31:0] d;
  output [9:0] adr;
  input [9:0] adr_d;
  input [31:0] d_d;
  input we_d;
  output [31:0] q_d;
  input port_0_rw_ram_ir_internal_RMASK_B_d;
  input port_0_rw_ram_ir_internal_WMASK_B_d;



  // Interconnect Declarations for Component Instantiations 
  assign q_d = q;
  assign we = (port_0_rw_ram_ir_internal_WMASK_B_d);
  assign d = (d_d);
  assign adr = (adr_d);
endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module matrix_mul_core_core_fsm (
  clk, rst, fsm_output
);
  input clk;
  input rst;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for matrix_mul_core_core_fsm_1
  parameter
    core_rlp_C_0 = 1'd0,
    main_C_0 = 1'd1;

  reg [0:0] state_var;
  reg [0:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : matrix_mul_core_core_fsm_1
    case (state_var)
      main_C_0 : begin
        fsm_output = 2'b10;
        state_var_NS = main_C_0;
      end
      // core_rlp_C_0
      default : begin
        fsm_output = 2'b01;
        state_var_NS = main_C_0;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( rst ) begin
      state_var <= core_rlp_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul_core
// ------------------------------------------------------------------


module matrix_mul_core (
  clk, rst, A_rsc_triosy_lz, B_rsc_triosy_lz, C_rsc_triosy_lz, A_rsci_adr_d, A_rsci_q_d,
      B_rsci_adr_d, B_rsci_q_d, C_rsci_adr_d, C_rsci_d_d, A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff,
      C_rsci_we_d_pff
);
  input clk;
  input rst;
  output A_rsc_triosy_lz;
  output B_rsc_triosy_lz;
  output C_rsc_triosy_lz;
  output [9:0] A_rsci_adr_d;
  input [31:0] A_rsci_q_d;
  output [9:0] B_rsci_adr_d;
  input [31:0] B_rsci_q_d;
  output [9:0] C_rsci_adr_d;
  output [31:0] C_rsci_d_d;
  output A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff;
  output C_rsci_we_d_pff;


  // Interconnect Declarations
  reg C_rsc_triosy_obj_ld;
  wire [1:0] fsm_output;
  wire [5:0] main_1_for_acc_1_tmp;
  wire [6:0] nl_main_1_for_acc_1_tmp;
  wire [5:0] main_1_for_for_acc_2_tmp;
  wire [6:0] nl_main_1_for_for_acc_2_tmp;
  wire [5:0] main_1_for_for_for_acc_4_tmp;
  wire [6:0] nl_main_1_for_for_for_acc_4_tmp;
  wire [5:0] main_2_for_acc_1_tmp;
  wire [6:0] nl_main_2_for_acc_1_tmp;
  wire [5:0] main_2_for_for_acc_2_tmp;
  wire [6:0] nl_main_2_for_for_acc_2_tmp;
  wire [5:0] main_2_for_for_for_acc_4_tmp;
  wire [6:0] nl_main_2_for_for_for_acc_4_tmp;
  wire [5:0] main_3_for_acc_1_tmp;
  wire [6:0] nl_main_3_for_acc_1_tmp;
  wire [5:0] main_3_for_for_acc_2_tmp;
  wire [6:0] nl_main_3_for_for_acc_2_tmp;
  wire [5:0] main_3_for_for_for_acc_4_tmp;
  wire [6:0] nl_main_3_for_for_for_acc_4_tmp;
  wire [5:0] main_4_for_acc_1_tmp;
  wire [6:0] nl_main_4_for_acc_1_tmp;
  wire [5:0] main_4_for_for_acc_2_tmp;
  wire [6:0] nl_main_4_for_for_acc_2_tmp;
  wire [5:0] main_4_for_for_for_acc_4_tmp;
  wire [6:0] nl_main_4_for_for_for_acc_4_tmp;
  wire [5:0] main_5_for_acc_1_tmp;
  wire [6:0] nl_main_5_for_acc_1_tmp;
  wire [5:0] main_5_for_for_acc_2_tmp;
  wire [6:0] nl_main_5_for_for_acc_2_tmp;
  wire [5:0] main_5_for_for_for_acc_4_tmp;
  wire [6:0] nl_main_5_for_for_for_acc_4_tmp;
  wire [5:0] main_6_for_acc_1_tmp;
  wire [6:0] nl_main_6_for_acc_1_tmp;
  wire [5:0] main_6_for_for_acc_2_tmp;
  wire [6:0] nl_main_6_for_for_acc_2_tmp;
  wire [5:0] main_6_for_for_for_acc_4_tmp;
  wire [6:0] nl_main_6_for_for_for_acc_4_tmp;
  wire [5:0] main_7_for_acc_1_tmp;
  wire [6:0] nl_main_7_for_acc_1_tmp;
  wire [5:0] main_7_for_for_acc_2_tmp;
  wire [6:0] nl_main_7_for_for_acc_2_tmp;
  wire [5:0] main_7_for_for_for_acc_4_tmp;
  wire [6:0] nl_main_7_for_for_for_acc_4_tmp;
  wire [5:0] main_8_for_acc_1_tmp;
  wire [6:0] nl_main_8_for_acc_1_tmp;
  wire [5:0] main_8_for_for_acc_2_tmp;
  wire [6:0] nl_main_8_for_for_acc_2_tmp;
  wire [5:0] main_8_for_for_for_acc_4_tmp;
  wire [6:0] nl_main_8_for_for_for_acc_4_tmp;
  wire [2:0] for_mux1h_64_tmp;
  wire for_nor_tmp_2;
  wire mux_tmp_14;
  wire nor_tmp_5;
  wire nor_tmp_7;
  wire mux_tmp_25;
  wire nor_tmp_8;
  wire or_tmp_21;
  wire nor_tmp_27;
  wire mux_tmp_84;
  wire or_dcpl_9;
  wire or_dcpl_12;
  wire and_dcpl_20;
  wire and_dcpl_21;
  wire and_dcpl_22;
  wire and_dcpl_23;
  wire and_dcpl_24;
  wire and_dcpl_25;
  wire and_dcpl_26;
  wire and_dcpl_27;
  wire and_dcpl_29;
  wire and_dcpl_30;
  wire and_dcpl_32;
  wire and_dcpl_36;
  wire or_dcpl_16;
  wire or_dcpl_18;
  wire or_dcpl_23;
  wire or_dcpl_25;
  wire or_dcpl_29;
  wire exit_main_1_for_for_lpi_1_dfm_3;
  reg lfst_exit_main_1_for_for_1_lpi_1;
  wire for_unequal_tmp_1;
  wire lfst_exit_main_8_for_lpi_1_dfm_3_1;
  wire exit_main_2_for_for_lpi_1_dfm_3;
  wire exit_main_4_for_for_lpi_1_dfm_3;
  wire exit_main_6_for_for_lpi_1_dfm_3;
  wire exit_main_8_for_for_lpi_1_dfm_3;
  reg lfst_exit_main_8_for_lpi_1_dfm_9_3;
  reg [2:0] lfst_exit_main_8_for_lpi_1_dfm_9_2_0;
  reg lfst_exit_main_2_for_for_1_lpi_1;
  reg lfst_exit_main_3_for_for_1_lpi_1;
  reg lfst_exit_main_4_for_for_1_lpi_1;
  reg lfst_exit_main_5_for_for_1_lpi_1;
  reg lfst_exit_main_6_for_for_1_lpi_1;
  reg lfst_exit_main_7_for_for_1_lpi_1;
  reg lfst_exit_main_8_for_for_1_lpi_1;
  wire lfst_exit_main_8_for_lpi_1_dfm_9_3_mx0w0;
  wire for_or_tmp_1;
  wire for_equal_tmp_13;
  wire for_equal_tmp_12;
  wire for_equal_tmp_11;
  wire for_equal_tmp_10;
  wire for_equal_tmp_14;
  wire for_equal_tmp_8;
  wire for_equal_tmp_9;
  wire exit_main_8_for_lpi_1_dfm_1_mx0w7;
  wire for_and_11_ssc_1;
  wire exit_main_7_for_lpi_1_dfm_1_mx0w6;
  wire exit_main_6_for_lpi_1_dfm_1_mx0w5;
  wire exit_main_5_for_lpi_1_dfm_1_mx0w4;
  wire exit_main_4_for_lpi_1_dfm_1_mx0w3;
  wire exit_main_3_for_lpi_1_dfm_1_mx0w2;
  wire exit_main_2_for_lpi_1_dfm_1_mx0w1;
  wire for_for_and_cse_1;
  wire for_for_nor_cse_1;
  reg for_equal_tmp_1_1;
  reg for_equal_tmp_2_1;
  reg for_equal_tmp_3_1;
  reg for_equal_tmp_4_1;
  reg for_equal_tmp_5_1;
  reg for_equal_tmp_6_1;
  reg for_equal_tmp_7_1;
  reg for_nor_tmp_1;
  reg exitL_exit_main_8_for_sva;
  reg main_stage_0_2;
  reg exit_main_1_for_lpi_1_dfm_2_st_1;
  reg lfst_exit_main_8_for_lpi_1_dfm_st_1_3;
  reg [2:0] lfst_exit_main_8_for_lpi_1_dfm_st_1_2_0;
  reg main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
  wire exit_main_1_for_lpi_1_dfm_2_mx0w0;
  wire [2:0] lfst_exit_main_8_for_lpi_1_dfm_9_2_0_2;
  wire [2:0] lfst_exit_main_8_for_lpi_1_dfm_2_0_1;
  reg reg_B_rsc_triosy_obj_ld_cse;
  wire and_86_cse;
  reg reg_main_1_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1_cse;
  wire and_85_cse;
  wire or_3_cse;
  wire and_112_cse;
  wire or_4_cse;
  wire nor_71_cse;
  wire or_142_cse;
  wire [4:0] for_for_j_mux1h_1_cse;
  wire [4:0] for_i_mux1h_1_cse;
  wire or_91_cse;
  wire [4:0] B_mux1h_rmff;
  reg [4:0] main_1_for_i_slc_for_i_5_0_4_0_1_itm_1;
  reg [4:0] main_1_for_for_j_slc_for_for_j_5_0_4_0_1_itm_1;
  wire [31:0] for_for_sum_1_sva_2;
  wire [32:0] nl_for_for_sum_1_sva_2;
  wire lfst_exit_main_1_for_for_1_lpi_1_dfm_1;
  wire [31:0] for_for_sum_4_lpi_1_mx0;
  wire [31:0] for_for_sum_5_lpi_1_mx0;
  wire [31:0] for_for_sum_6_lpi_1_mx0;
  wire [31:0] for_for_sum_7_lpi_1_mx0;
  wire [31:0] for_for_sum_lpi_1_mx0;
  wire [31:0] for_for_sum_2_lpi_1_mx0;
  wire [31:0] for_for_sum_3_lpi_1_mx0;
  wire [31:0] for_for_sum_1_lpi_1_mx0;
  wire [4:0] for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0;
  reg [4:0] for_for_j_5_0_2_lpi_1_4_0;
  reg [4:0] for_for_j_5_0_3_lpi_1_4_0;
  reg [4:0] for_for_j_5_0_4_lpi_1_4_0;
  reg [4:0] for_for_j_5_0_5_lpi_1_4_0;
  reg [4:0] for_for_j_5_0_6_lpi_1_4_0;
  reg [4:0] for_for_j_5_0_7_lpi_1_4_0;
  reg [4:0] for_for_j_5_0_lpi_1_4_0;
  wire mux_110_tmp;
  wire or_149_tmp;
  reg [31:0] for_for_sum_1_lpi_1;
  reg [31:0] for_for_sum_2_lpi_1;
  reg [31:0] for_for_sum_3_lpi_1;
  reg [31:0] for_for_sum_4_lpi_1;
  reg [31:0] for_for_sum_5_lpi_1;
  reg [31:0] for_for_sum_6_lpi_1;
  reg [31:0] for_for_sum_7_lpi_1;
  reg [31:0] for_for_sum_lpi_1;
  reg main_2_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm;
  reg main_3_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm;
  reg main_4_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm;
  reg main_5_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm;
  reg main_6_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm;
  reg main_7_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm;
  reg main_8_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm;
  reg for_for_j_slc_for_for_j_5_0_1_5_2_itm_1;
  reg [31:0] for_for_for_for_and_14_itm_1;
  reg [4:0] for_i_5_0_1_lpi_1_4_0;
  reg [4:0] for_for_j_5_0_1_lpi_1_4_0;
  reg [4:0] for_for_for_k_5_0_1_lpi_1_4_0;
  reg [4:0] for_i_5_0_2_lpi_1_4_0;
  reg [4:0] for_for_for_k_5_0_2_lpi_1_4_0;
  reg [4:0] for_i_5_0_3_lpi_1_4_0;
  reg [4:0] for_for_for_k_5_0_3_lpi_1_4_0;
  reg [4:0] for_i_5_0_4_lpi_1_4_0;
  reg [4:0] for_for_for_k_5_0_4_lpi_1_4_0;
  reg [4:0] for_i_5_0_5_lpi_1_4_0;
  reg [4:0] for_for_for_k_5_0_5_lpi_1_4_0;
  reg [4:0] for_i_5_0_6_lpi_1_4_0;
  reg [4:0] for_for_for_k_5_0_6_lpi_1_4_0;
  reg [4:0] for_i_5_0_7_lpi_1_4_0;
  reg [4:0] for_for_for_k_5_0_7_lpi_1_4_0;
  reg [4:0] for_i_5_0_lpi_1_4_0;
  reg [4:0] for_for_for_k_5_0_lpi_1_4_0;
  wire [4:0] for_i_5_0_1_lpi_1_dfm_4_0_mx0w0;
  wire [31:0] for_for_for_acc_7_psp_1_sva_1;
  wire [32:0] nl_for_for_for_acc_7_psp_1_sva_1;
  wire [45:0] for_for_for_mul_sdt_1_sva_1;
  wire signed [63:0] nl_for_for_for_mul_sdt_1_sva_1;
  wire [4:0] for_for_for_k_5_0_1_lpi_1_dfm_4_0_1;
  wire [4:0] for_for_for_k_5_0_2_lpi_1_dfm_4_0_1;
  wire [4:0] for_for_for_k_5_0_3_lpi_1_dfm_4_0_1;
  wire [4:0] for_for_for_k_5_0_4_lpi_1_dfm_4_0_1;
  wire [4:0] for_for_for_k_5_0_5_lpi_1_dfm_4_0_1;
  wire [4:0] for_for_for_k_5_0_6_lpi_1_dfm_4_0_1;
  wire [4:0] for_for_for_k_5_0_7_lpi_1_dfm_4_0_1;
  wire [4:0] for_for_for_k_5_0_lpi_1_dfm_4_0_1;
  wire [31:0] for_for_sum_1_lpi_1_dfm_2;
  wire for_or_7_tmp_1;
  wire mux_tmp_117;
  wire or_dcpl_59;
  wire nand_39_cse;
  wire nor_153_cse;
  wire or_89_cse;
  wire nand_45_cse;
  wire and_67_cse;
  wire nor_149_cse;
  wire nor_158_cse;
  wire nand_43_cse;
  wire and_70_cse;
  wire nor_155_cse;
  wire and_291_cse;
  wire nand_40_cse;
  wire nand_44_cse;
  wire or_167_cse;
  wire or_171_cse;
  wire and_297_cse;
  wire and_295_cse;
  wire and_292_cse;
  wire and_298_cse;
  wire nor_136_cse;
  wire or_195_cse;
  wire and_299_cse;
  wire nand_31_cse;
  wire nand_32_cse;
  wire nand_34_cse;
  wire nand_37_cse;

  wire[0:0] mux_107_nl;
  wire[0:0] mux_106_nl;
  wire[0:0] mux_105_nl;
  wire[0:0] mux_104_nl;
  wire[0:0] and_68_nl;
  wire[0:0] mux_103_nl;
  wire[0:0] mux_102_nl;
  wire[0:0] and_69_nl;
  wire[0:0] mux_101_nl;
  wire[0:0] mux_100_nl;
  wire[0:0] mux_99_nl;
  wire[0:0] mux_98_nl;
  wire[0:0] and_71_nl;
  wire[0:0] mux_97_nl;
  wire[0:0] mux_96_nl;
  wire[0:0] mux_109_nl;
  wire[0:0] and_151_nl;
  wire[0:0] mux_nl;
  wire[0:0] nor_81_nl;
  wire[31:0] mux1h_8_nl;
  wire[0:0] and_153_nl;
  wire[0:0] and_154_nl;
  wire[0:0] and_155_nl;
  wire[0:0] and_156_nl;
  wire[0:0] nor_83_nl;
  wire[0:0] nor_84_nl;
  wire[0:0] and_40_nl;
  wire[0:0] and_157_nl;
  wire[0:0] not_350_nl;
  wire[0:0] mux_22_nl;
  wire[0:0] or_7_nl;
  wire[0:0] mux_21_nl;
  wire[0:0] for_nand_1_nl;
  wire[0:0] mux_88_nl;
  wire[0:0] nor_82_nl;
  wire[4:0] for_for_and_20_nl;
  wire[0:0] for_not_114_nl;
  wire[0:0] for_and_15_nl;
  wire[0:0] mux_127_nl;
  wire[0:0] nor_161_nl;
  wire[0:0] mux_111_nl;
  wire[0:0] or_151_nl;
  wire[0:0] and_121_nl;
  wire[0:0] mux_134_nl;
  wire[0:0] mux_133_nl;
  wire[0:0] mux_132_nl;
  wire[0:0] mux_130_nl;
  wire[0:0] mux_129_nl;
  wire[0:0] nor_102_nl;
  wire[0:0] for_nand_2_nl;
  wire[0:0] for_for_and_22_nl;
  wire[4:0] for_for_and_23_nl;
  wire[0:0] for_not_115_nl;
  wire[0:0] for_and_17_nl;
  wire[0:0] mux_136_nl;
  wire[0:0] mux_112_nl;
  wire[0:0] or_153_nl;
  wire[0:0] and_122_nl;
  wire[0:0] mux_137_nl;
  wire[0:0] for_nand_3_nl;
  wire[0:0] for_for_and_25_nl;
  wire[4:0] for_for_and_26_nl;
  wire[0:0] for_not_116_nl;
  wire[0:0] for_and_19_nl;
  wire[0:0] mux_138_nl;
  wire[0:0] nor_157_nl;
  wire[0:0] mux_113_nl;
  wire[0:0] or_155_nl;
  wire[0:0] and_123_nl;
  wire[0:0] mux_139_nl;
  wire[0:0] nor_145_nl;
  wire[0:0] for_nand_4_nl;
  wire[0:0] for_for_and_28_nl;
  wire[4:0] for_for_and_29_nl;
  wire[0:0] for_not_117_nl;
  wire[0:0] for_and_21_nl;
  wire[0:0] mux_140_nl;
  wire[0:0] mux_114_nl;
  wire[0:0] or_157_nl;
  wire[0:0] and_124_nl;
  wire[0:0] mux_141_nl;
  wire[0:0] for_nand_5_nl;
  wire[0:0] for_for_and_31_nl;
  wire[4:0] for_for_and_32_nl;
  wire[0:0] for_not_118_nl;
  wire[0:0] for_and_23_nl;
  wire[0:0] mux_142_nl;
  wire[0:0] and_293_nl;
  wire[0:0] mux_115_nl;
  wire[0:0] or_159_nl;
  wire[0:0] and_125_nl;
  wire[0:0] mux_143_nl;
  wire[0:0] and_286_nl;
  wire[0:0] for_nand_6_nl;
  wire[0:0] for_for_and_34_nl;
  wire[4:0] for_for_and_35_nl;
  wire[0:0] for_not_119_nl;
  wire[0:0] for_and_25_nl;
  wire[0:0] mux_144_nl;
  wire[0:0] mux_116_nl;
  wire[0:0] or_161_nl;
  wire[0:0] and_126_nl;
  wire[0:0] mux_145_nl;
  wire[0:0] for_nand_7_nl;
  wire[0:0] for_for_and_37_nl;
  wire[4:0] for_for_and_38_nl;
  wire[0:0] for_not_120_nl;
  wire[0:0] for_and_13_nl;
  wire[0:0] mux_146_nl;
  wire[0:0] or_nl;
  wire[0:0] or_231_nl;
  wire[0:0] mux_117_nl;
  wire[0:0] or_163_nl;
  wire[0:0] and_127_nl;
  wire[0:0] mux_147_nl;
  wire[0:0] or_229_nl;
  wire[0:0] or_230_nl;
  wire[0:0] for_nand_nl;
  wire[0:0] for_for_and_40_nl;
  wire[0:0] mux_63_nl;
  wire[0:0] mux_62_nl;
  wire[0:0] mux_61_nl;
  wire[0:0] or_50_nl;
  wire[0:0] or_49_nl;
  wire[0:0] or_48_nl;
  wire[0:0] asn_for_i_5_0_1_lpi_1_4_0_for_nor_nl;
  wire[0:0] mux_148_nl;
  wire[0:0] nand_27_nl;
  wire[0:0] mux_149_nl;
  wire[0:0] or_214_nl;
  wire[0:0] or_213_nl;
  wire[0:0] mux_151_nl;
  wire[0:0] mux_150_nl;
  wire[0:0] nand_24_nl;
  wire[0:0] nand_25_nl;
  wire[0:0] mux_152_nl;
  wire[0:0] or_227_nl;
  wire[0:0] or_226_nl;
  wire[0:0] mux_95_nl;
  wire[0:0] mux_94_nl;
  wire[0:0] mux_93_nl;
  wire[0:0] mux_92_nl;
  wire[0:0] or_86_nl;
  wire[0:0] mux_27_nl;
  wire[0:0] mux_26_nl;
  wire[0:0] mux_25_nl;
  wire[0:0] mux_38_nl;
  wire[0:0] mux_37_nl;
  wire[0:0] mux_36_nl;
  wire[0:0] mux_35_nl;
  wire[0:0] mux_34_nl;
  wire[0:0] mux_33_nl;
  wire[0:0] mux_32_nl;
  wire[0:0] mux_60_nl;
  wire[0:0] mux_59_nl;
  wire[0:0] and_87_nl;
  wire[0:0] mux_58_nl;
  wire[0:0] nand_1_nl;
  wire[0:0] mux_57_nl;
  wire[0:0] mux_56_nl;
  wire[0:0] mux_55_nl;
  wire[0:0] and_88_nl;
  wire[0:0] mux_54_nl;
  wire[0:0] or_42_nl;
  wire[0:0] and_89_nl;
  wire[0:0] and_92_nl;
  wire[0:0] mux_53_nl;
  wire[0:0] mux_52_nl;
  wire[0:0] and_93_nl;
  wire[0:0] mux_51_nl;
  wire[0:0] mux_50_nl;
  wire[0:0] or_37_nl;
  wire[0:0] and_94_nl;
  wire[0:0] and_96_nl;
  wire[0:0] mux_49_nl;
  wire[0:0] mux_48_nl;
  wire[0:0] and_97_nl;
  wire[0:0] or_31_nl;
  wire[0:0] mux_47_nl;
  wire[0:0] or_30_nl;
  wire[0:0] or_29_nl;
  wire[0:0] and_2_nl;
  wire[0:0] mux_46_nl;
  wire[0:0] mux_45_nl;
  wire[0:0] and_99_nl;
  wire[0:0] mux_44_nl;
  wire[0:0] mux_43_nl;
  wire[0:0] or_24_nl;
  wire[0:0] and_100_nl;
  wire[0:0] or_22_nl;
  wire[0:0] and_102_nl;
  wire[0:0] mux_42_nl;
  wire[0:0] mux_41_nl;
  wire[0:0] and_103_nl;
  wire[0:0] mux_40_nl;
  wire[0:0] mux_39_nl;
  wire[0:0] or_18_nl;
  wire[0:0] and_104_nl;
  wire[0:0] and_106_nl;
  wire[0:0] for_not_72_nl;
  wire[0:0] for_not_56_nl;
  wire[0:0] for_mux_43_nl;
  wire[1:0] for_mux_7_nl;
  wire[0:0] for_or_74_nl;
  wire[0:0] for_and_1_nl;
  wire[0:0] for_and_3_nl;
  wire[0:0] for_and_5_nl;
  wire[0:0] for_and_7_nl;
  wire[2:0] for_and_58_nl;
  wire[0:0] for_nor_15_nl;
  wire[0:0] for_and_9_nl;
  wire[0:0] for_for_sum_nand_6_nl;
  wire[0:0] for_and_40_nl;
  wire[0:0] for_and_41_nl;
  wire[0:0] for_for_sum_nand_5_nl;
  wire[0:0] for_and_38_nl;
  wire[0:0] for_and_39_nl;
  wire[0:0] for_for_sum_nand_4_nl;
  wire[0:0] for_and_36_nl;
  wire[0:0] for_and_37_nl;
  wire[0:0] for_for_sum_nand_3_nl;
  wire[0:0] for_and_34_nl;
  wire[0:0] for_and_35_nl;
  wire[0:0] for_for_sum_nand_2_nl;
  wire[0:0] for_and_32_nl;
  wire[0:0] for_and_33_nl;
  wire[0:0] for_for_sum_nand_1_nl;
  wire[0:0] for_and_30_nl;
  wire[0:0] for_and_31_nl;
  wire[0:0] for_for_sum_or_nl;
  wire[0:0] for_for_sum_and_nl;
  wire[0:0] for_and_29_nl;
  wire[0:0] for_for_sum_nand_nl;
  wire[0:0] for_and_26_nl;
  wire[0:0] for_and_27_nl;
  wire[0:0] main_1_for_for_for_and_1_nl;
  wire[0:0] mux_19_nl;
  wire[0:0] mux_18_nl;
  wire[0:0] mux_17_nl;
  wire[0:0] mux_16_nl;
  wire[0:0] mux_15_nl;
  wire[0:0] mux_14_nl;
  wire[0:0] nor_1_nl;
  wire[0:0] mux_13_nl;
  wire[0:0] mux_12_nl;
  wire[0:0] mux_11_nl;
  wire[0:0] mux_10_nl;
  wire[0:0] mux_9_nl;
  wire[0:0] mux_8_nl;
  wire[0:0] mux_7_nl;
  wire[0:0] mux_6_nl;
  wire[0:0] mux_30_nl;
  wire[0:0] mux_29_nl;
  wire[0:0] or_11_nl;
  wire[0:0] or_84_nl;
  wire[0:0] and_114_nl;
  wire[0:0] nor_151_nl;

  // Interconnect Declarations for Component Instantiations 
  mgc_io_sync_v2 #(.valid(32'sd0)) A_rsc_triosy_obj (
      .ld(reg_B_rsc_triosy_obj_ld_cse),
      .lz(A_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) B_rsc_triosy_obj (
      .ld(reg_B_rsc_triosy_obj_ld_cse),
      .lz(B_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) C_rsc_triosy_obj (
      .ld(C_rsc_triosy_obj_ld),
      .lz(C_rsc_triosy_lz)
    );
  matrix_mul_core_core_fsm matrix_mul_core_core_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output)
    );
  assign or_89_cse = (~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1])) | exitL_exit_main_8_for_sva;
  assign and_67_cse = (main_2_for_acc_1_tmp[5]) & (main_2_for_for_acc_2_tmp[5]) &
      (main_2_for_for_for_acc_4_tmp[5]);
  assign and_70_cse = (main_4_for_acc_1_tmp[5]) & (main_4_for_for_acc_2_tmp[5]) &
      (main_4_for_for_for_acc_4_tmp[5]);
  assign or_91_cse = (nor_71_cse & (~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])))
      | exitL_exit_main_8_for_sva | (~ lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign for_i_mux1h_1_cse = MUX1HOT_v_5_8_2(for_i_5_0_1_lpi_1_dfm_4_0_mx0w0, for_i_5_0_2_lpi_1_4_0,
      for_i_5_0_3_lpi_1_4_0, for_i_5_0_4_lpi_1_4_0, for_i_5_0_5_lpi_1_4_0, for_i_5_0_6_lpi_1_4_0,
      for_i_5_0_7_lpi_1_4_0, for_i_5_0_lpi_1_4_0, {or_dcpl_12 , and_dcpl_22 , and_dcpl_24
      , and_dcpl_26 , and_dcpl_27 , and_dcpl_29 , and_dcpl_30 , and_dcpl_32});
  assign for_for_j_mux1h_1_cse = MUX1HOT_v_5_8_2(for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0,
      for_for_j_5_0_2_lpi_1_4_0, for_for_j_5_0_3_lpi_1_4_0, for_for_j_5_0_4_lpi_1_4_0,
      for_for_j_5_0_5_lpi_1_4_0, for_for_j_5_0_6_lpi_1_4_0, for_for_j_5_0_7_lpi_1_4_0,
      for_for_j_5_0_lpi_1_4_0, {or_dcpl_12 , and_dcpl_22 , and_dcpl_24 , and_dcpl_26
      , and_dcpl_27 , and_dcpl_29 , and_dcpl_30 , and_dcpl_32});
  assign or_3_cse = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0!=3'b000);
  assign and_112_cse = exitL_exit_main_8_for_sva & (main_1_for_for_for_acc_4_tmp[5]);
  assign or_4_cse = (~ exitL_exit_main_8_for_sva) | (main_1_for_for_for_acc_4_tmp[5]);
  assign nor_71_cse = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b00));
  assign mux_nl = MUX_s_1_2_2(lfst_exit_main_2_for_for_1_lpi_1, lfst_exit_main_3_for_for_1_lpi_1,
      lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign and_151_nl = and_dcpl_36 & (~ (mux_nl));
  assign nor_81_nl = ~(lfst_exit_main_8_for_for_1_lpi_1 | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])
      | exitL_exit_main_8_for_sva);
  assign mux_109_nl = MUX_s_1_2_2((and_151_nl), (nor_81_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign or_149_tmp = (mux_109_nl) | ((~ lfst_exit_main_1_for_for_1_lpi_1_dfm_1)
      & or_dcpl_12) | ((~ lfst_exit_main_4_for_for_1_lpi_1) & and_dcpl_26) | ((~
      lfst_exit_main_5_for_for_1_lpi_1) & and_dcpl_27) | ((~ lfst_exit_main_6_for_for_1_lpi_1)
      & and_dcpl_29) | ((~ lfst_exit_main_7_for_for_1_lpi_1) & and_dcpl_30);
  assign nand_39_cse = ~((main_1_for_for_acc_2_tmp[5]) & (main_1_for_for_for_acc_4_tmp[5]));
  assign nor_153_cse = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b00) | lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_110_tmp = MUX_s_1_2_2((main_1_for_acc_1_tmp[5]), (main_1_for_for_for_acc_4_tmp[5]),
      nand_39_cse);
  assign nand_45_cse = ~((main_2_for_for_for_acc_4_tmp[5]) & (main_2_for_for_acc_2_tmp[5]));
  assign or_167_cse = lfst_exit_main_8_for_lpi_1_dfm_9_3 | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]);
  assign and_298_cse = (main_1_for_acc_1_tmp[5]) & (main_1_for_for_for_acc_4_tmp[5])
      & (main_1_for_for_acc_2_tmp[5]);
  assign and_299_cse = exitL_exit_main_8_for_sva & (main_1_for_acc_1_tmp[5]) & (main_1_for_for_for_acc_4_tmp[5])
      & (main_1_for_for_acc_2_tmp[5]);
  assign or_171_cse = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b00);
  assign and_297_cse = (main_3_for_for_for_acc_4_tmp[5]) & (main_3_for_for_acc_2_tmp[5]);
  assign nor_149_cse = ~(lfst_exit_main_8_for_lpi_1_dfm_9_3 | exitL_exit_main_8_for_sva);
  assign nand_37_cse = ~((main_3_for_for_acc_2_tmp[5]) & (main_3_for_for_for_acc_4_tmp[5]));
  assign nand_44_cse = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]) & (main_3_for_acc_1_tmp[5])
      & (main_3_for_for_for_acc_4_tmp[5]) & (main_3_for_for_acc_2_tmp[5]));
  assign nor_158_cse = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) | nand_44_cse);
  assign nand_43_cse = ~((main_4_for_for_for_acc_4_tmp[5]) & (main_4_for_for_acc_2_tmp[5]));
  assign and_295_cse = (main_5_for_for_for_acc_4_tmp[5]) & (main_5_for_for_acc_2_tmp[5]);
  assign nand_34_cse = ~((main_5_for_for_for_acc_4_tmp[5]) & (main_5_for_for_acc_2_tmp[5]));
  assign nor_155_cse = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]) | (~((main_5_for_acc_1_tmp[5])
      & (main_5_for_for_for_acc_4_tmp[5]) & (main_5_for_for_acc_2_tmp[5]))));
  assign nand_32_cse = ~((main_6_for_for_acc_2_tmp[5]) & (main_6_for_for_for_acc_4_tmp[5]));
  assign and_291_cse = (main_6_for_acc_1_tmp[5]) & (main_6_for_for_for_acc_4_tmp[5])
      & (main_6_for_for_acc_2_tmp[5]);
  assign and_292_cse = (main_7_for_for_for_acc_4_tmp[5]) & (main_7_for_for_acc_2_tmp[5]);
  assign nand_31_cse = ~((main_7_for_for_acc_2_tmp[5]) & (main_7_for_for_for_acc_4_tmp[5]));
  assign nand_40_cse = ~((main_8_for_for_for_acc_4_tmp[5]) & (main_8_for_for_acc_2_tmp[5]));
  assign nor_136_cse = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0!=3'b000));
  assign and_86_cse = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b11);
  assign and_85_cse = (main_7_for_acc_1_tmp[5]) & (main_7_for_for_acc_2_tmp[5]) &
      (main_7_for_for_for_acc_4_tmp[5]);
  assign or_195_cse = (for_mux1h_64_tmp!=3'b000);
  assign for_not_72_nl = ~ exitL_exit_main_8_for_sva;
  assign for_i_5_0_1_lpi_1_dfm_4_0_mx0w0 = MUX_v_5_2_2(5'b00000, for_i_5_0_1_lpi_1_4_0,
      (for_not_72_nl));
  assign for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0 = MUX_v_5_2_2(5'b00000, for_for_j_5_0_1_lpi_1_4_0,
      for_unequal_tmp_1);
  assign exit_main_1_for_lpi_1_dfm_2_mx0w0 = (main_1_for_acc_1_tmp[5]) & exit_main_1_for_for_lpi_1_dfm_3;
  assign exit_main_2_for_lpi_1_dfm_1_mx0w1 = (main_2_for_acc_1_tmp[5]) & exit_main_2_for_for_lpi_1_dfm_3;
  assign exit_main_3_for_lpi_1_dfm_1_mx0w2 = (main_3_for_acc_1_tmp[5]) & and_297_cse;
  assign exit_main_4_for_lpi_1_dfm_1_mx0w3 = (main_4_for_acc_1_tmp[5]) & exit_main_4_for_for_lpi_1_dfm_3;
  assign exit_main_5_for_lpi_1_dfm_1_mx0w4 = (main_5_for_acc_1_tmp[5]) & and_295_cse;
  assign exit_main_6_for_lpi_1_dfm_1_mx0w5 = (main_6_for_acc_1_tmp[5]) & exit_main_6_for_for_lpi_1_dfm_3;
  assign exit_main_7_for_lpi_1_dfm_1_mx0w6 = (main_7_for_acc_1_tmp[5]) & and_292_cse;
  assign exit_main_8_for_lpi_1_dfm_1_mx0w7 = (main_8_for_acc_1_tmp[5]) & exit_main_8_for_for_lpi_1_dfm_3;
  assign lfst_exit_main_8_for_lpi_1_dfm_3_1 = lfst_exit_main_8_for_lpi_1_dfm_9_3
      & (~ exitL_exit_main_8_for_sva);
  assign for_not_56_nl = ~ exitL_exit_main_8_for_sva;
  assign lfst_exit_main_8_for_lpi_1_dfm_2_0_1 = MUX_v_3_2_2(3'b000, lfst_exit_main_8_for_lpi_1_dfm_9_2_0,
      (for_not_56_nl));
  assign for_mux_43_nl = MUX_s_1_2_2(lfst_exit_main_8_for_lpi_1_dfm_3_1, (~ exit_main_8_for_lpi_1_dfm_1_mx0w7),
      for_equal_tmp_14);
  assign lfst_exit_main_8_for_lpi_1_dfm_9_3_mx0w0 = (for_mux_43_nl) | for_and_11_ssc_1;
  assign for_mux_7_nl = MUX_v_2_2_2(2'b01, 2'b10, exit_main_1_for_lpi_1_dfm_2_mx0w0);
  assign for_or_74_nl = ((~ exit_main_2_for_lpi_1_dfm_1_mx0w1) & for_equal_tmp_13)
      | ((~ exit_main_3_for_lpi_1_dfm_1_mx0w2) & for_equal_tmp_12) | ((~ exit_main_4_for_lpi_1_dfm_1_mx0w3)
      & for_equal_tmp_11) | ((~ exit_main_5_for_lpi_1_dfm_1_mx0w4) & for_equal_tmp_10)
      | ((~ exit_main_6_for_lpi_1_dfm_1_mx0w5) & for_equal_tmp_9) | ((~ exit_main_7_for_lpi_1_dfm_1_mx0w6)
      & for_equal_tmp_8) | for_nor_tmp_2;
  assign for_and_1_nl = exit_main_2_for_lpi_1_dfm_1_mx0w1 & for_equal_tmp_13;
  assign for_and_3_nl = exit_main_3_for_lpi_1_dfm_1_mx0w2 & for_equal_tmp_12;
  assign for_and_5_nl = exit_main_4_for_lpi_1_dfm_1_mx0w3 & for_equal_tmp_11;
  assign for_and_7_nl = exit_main_5_for_lpi_1_dfm_1_mx0w4 & for_equal_tmp_10;
  assign for_mux1h_64_tmp = MUX1HOT_v_3_6_2(({1'b0 , (for_mux_7_nl)}), lfst_exit_main_8_for_lpi_1_dfm_2_0_1,
      3'b011, 3'b100, 3'b101, 3'b110, {for_or_tmp_1 , (for_or_74_nl) , (for_and_1_nl)
      , (for_and_3_nl) , (for_and_5_nl) , (for_and_7_nl)});
  assign for_nor_15_nl = ~(for_and_11_ssc_1 | for_equal_tmp_14);
  assign for_and_58_nl = MUX_v_3_2_2(3'b000, for_mux1h_64_tmp, (for_nor_15_nl));
  assign for_and_9_nl = exit_main_6_for_lpi_1_dfm_1_mx0w5 & for_equal_tmp_9;
  assign lfst_exit_main_8_for_lpi_1_dfm_9_2_0_2 = MUX_v_3_2_2((for_and_58_nl), 3'b111,
      (for_and_9_nl));
  assign for_for_sum_nand_6_nl = ~(main_stage_0_2 & for_equal_tmp_6_1);
  assign for_and_40_nl = (~ main_7_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm) &
      for_equal_tmp_6_1 & main_stage_0_2;
  assign for_and_41_nl = main_7_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm & for_equal_tmp_6_1
      & main_stage_0_2;
  assign for_for_sum_7_lpi_1_mx0 = MUX1HOT_v_32_3_2(for_for_sum_7_lpi_1, for_for_sum_1_sva_2,
      for_for_sum_1_lpi_1_dfm_2, {(for_for_sum_nand_6_nl) , (for_and_40_nl) , (for_and_41_nl)});
  assign for_for_sum_nand_5_nl = ~(main_stage_0_2 & for_equal_tmp_5_1);
  assign for_and_38_nl = (~ main_6_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm) &
      for_equal_tmp_5_1 & main_stage_0_2;
  assign for_and_39_nl = main_6_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm & for_equal_tmp_5_1
      & main_stage_0_2;
  assign for_for_sum_6_lpi_1_mx0 = MUX1HOT_v_32_3_2(for_for_sum_6_lpi_1, for_for_sum_1_sva_2,
      for_for_sum_1_lpi_1_dfm_2, {(for_for_sum_nand_5_nl) , (for_and_38_nl) , (for_and_39_nl)});
  assign for_for_sum_nand_4_nl = ~(main_stage_0_2 & for_equal_tmp_4_1);
  assign for_and_36_nl = (~ main_5_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm) &
      for_equal_tmp_4_1 & main_stage_0_2;
  assign for_and_37_nl = main_5_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm & for_equal_tmp_4_1
      & main_stage_0_2;
  assign for_for_sum_5_lpi_1_mx0 = MUX1HOT_v_32_3_2(for_for_sum_5_lpi_1, for_for_sum_1_sva_2,
      for_for_sum_1_lpi_1_dfm_2, {(for_for_sum_nand_4_nl) , (for_and_36_nl) , (for_and_37_nl)});
  assign for_for_sum_nand_3_nl = ~(main_stage_0_2 & for_equal_tmp_3_1);
  assign for_and_34_nl = (~ main_4_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm) &
      for_equal_tmp_3_1 & main_stage_0_2;
  assign for_and_35_nl = main_4_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm & for_equal_tmp_3_1
      & main_stage_0_2;
  assign for_for_sum_4_lpi_1_mx0 = MUX1HOT_v_32_3_2(for_for_sum_4_lpi_1, for_for_sum_1_sva_2,
      for_for_sum_1_lpi_1_dfm_2, {(for_for_sum_nand_3_nl) , (for_and_34_nl) , (for_and_35_nl)});
  assign for_for_sum_nand_2_nl = ~(main_stage_0_2 & for_equal_tmp_2_1);
  assign for_and_32_nl = (~ main_3_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm) &
      for_equal_tmp_2_1 & main_stage_0_2;
  assign for_and_33_nl = main_3_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm & for_equal_tmp_2_1
      & main_stage_0_2;
  assign for_for_sum_3_lpi_1_mx0 = MUX1HOT_v_32_3_2(for_for_sum_3_lpi_1, for_for_sum_1_sva_2,
      for_for_sum_1_lpi_1_dfm_2, {(for_for_sum_nand_2_nl) , (for_and_32_nl) , (for_and_33_nl)});
  assign for_for_sum_nand_1_nl = ~(main_stage_0_2 & for_equal_tmp_1_1);
  assign for_and_30_nl = (~ main_2_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm) &
      for_equal_tmp_1_1 & main_stage_0_2;
  assign for_and_31_nl = main_2_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm & for_equal_tmp_1_1
      & main_stage_0_2;
  assign for_for_sum_2_lpi_1_mx0 = MUX1HOT_v_32_3_2(for_for_sum_2_lpi_1, for_for_sum_1_sva_2,
      for_for_sum_1_lpi_1_dfm_2, {(for_for_sum_nand_1_nl) , (for_and_30_nl) , (for_and_31_nl)});
  assign for_for_sum_or_nl = (~ main_stage_0_2) | for_or_7_tmp_1;
  assign for_for_sum_and_nl = (~(reg_main_1_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1_cse
      | for_or_7_tmp_1)) & main_stage_0_2;
  assign for_and_29_nl = reg_main_1_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1_cse
      & (~ for_or_7_tmp_1) & main_stage_0_2;
  assign for_for_sum_1_lpi_1_mx0 = MUX1HOT_v_32_3_2(for_for_sum_1_lpi_1, for_for_sum_1_sva_2,
      for_for_sum_1_lpi_1_dfm_2, {(for_for_sum_or_nl) , (for_for_sum_and_nl) , (for_and_29_nl)});
  assign for_for_sum_nand_nl = ~(main_stage_0_2 & for_equal_tmp_7_1);
  assign for_and_26_nl = (~ main_8_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm) &
      for_equal_tmp_7_1 & main_stage_0_2;
  assign for_and_27_nl = main_8_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm & for_equal_tmp_7_1
      & main_stage_0_2;
  assign for_for_sum_lpi_1_mx0 = MUX1HOT_v_32_3_2(for_for_sum_lpi_1, for_for_sum_1_sva_2,
      for_for_sum_1_lpi_1_dfm_2, {(for_for_sum_nand_nl) , (for_and_26_nl) , (for_and_27_nl)});
  assign main_1_for_for_for_and_1_nl = (for_for_for_mul_sdt_1_sva_1[13]) & ((for_for_for_mul_sdt_1_sva_1[12:0]!=13'b0000000000000)
      | (for_for_for_acc_7_psp_1_sva_1[0]));
  assign nl_for_for_sum_1_sva_2 = for_for_for_acc_7_psp_1_sva_1 + conv_u2s_1_32(main_1_for_for_for_and_1_nl);
  assign for_for_sum_1_sva_2 = nl_for_for_sum_1_sva_2[31:0];
  assign for_equal_tmp_8 = (lfst_exit_main_8_for_lpi_1_dfm_2_0_1==3'b111) & (~ lfst_exit_main_8_for_lpi_1_dfm_3_1);
  assign for_equal_tmp_9 = (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[2:1]==2'b11) & (~(lfst_exit_main_8_for_lpi_1_dfm_3_1
      | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[0])));
  assign for_equal_tmp_10 = (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[2]) & (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[0])
      & (~(lfst_exit_main_8_for_lpi_1_dfm_3_1 | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[1])));
  assign for_equal_tmp_11 = (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[2]) & (~(lfst_exit_main_8_for_lpi_1_dfm_3_1
      | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[1:0]!=2'b00)));
  assign for_equal_tmp_12 = (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[1:0]==2'b11) &
      (~(lfst_exit_main_8_for_lpi_1_dfm_3_1 | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[2])));
  assign for_equal_tmp_13 = (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[1]) & (~(lfst_exit_main_8_for_lpi_1_dfm_3_1
      | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[2]) | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[0])));
  assign for_equal_tmp_14 = lfst_exit_main_8_for_lpi_1_dfm_3_1 & (lfst_exit_main_8_for_lpi_1_dfm_2_0_1==3'b000);
  assign for_nor_tmp_2 = ~(for_for_and_cse_1 | for_for_nor_cse_1 | for_equal_tmp_13
      | for_equal_tmp_12 | for_equal_tmp_11 | for_equal_tmp_10 | for_equal_tmp_9
      | for_equal_tmp_8 | for_equal_tmp_14);
  assign nl_main_2_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_2_lpi_1_dfm_4_0_1)
      + 6'b000001;
  assign main_2_for_for_for_acc_4_tmp = nl_main_2_for_for_for_acc_4_tmp[5:0];
  assign nl_main_1_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_1_lpi_1_dfm_4_0_1)
      + 6'b000001;
  assign main_1_for_for_for_acc_4_tmp = nl_main_1_for_for_for_acc_4_tmp[5:0];
  assign nl_main_7_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_7_lpi_1_dfm_4_0_1)
      + 6'b000001;
  assign main_7_for_for_for_acc_4_tmp = nl_main_7_for_for_for_acc_4_tmp[5:0];
  assign nl_main_6_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_6_lpi_1_dfm_4_0_1)
      + 6'b000001;
  assign main_6_for_for_for_acc_4_tmp = nl_main_6_for_for_for_acc_4_tmp[5:0];
  assign nl_main_5_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_5_lpi_1_dfm_4_0_1)
      + 6'b000001;
  assign main_5_for_for_for_acc_4_tmp = nl_main_5_for_for_for_acc_4_tmp[5:0];
  assign nl_main_4_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_4_lpi_1_dfm_4_0_1)
      + 6'b000001;
  assign main_4_for_for_for_acc_4_tmp = nl_main_4_for_for_for_acc_4_tmp[5:0];
  assign nl_main_3_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_3_lpi_1_dfm_4_0_1)
      + 6'b000001;
  assign main_3_for_for_for_acc_4_tmp = nl_main_3_for_for_for_acc_4_tmp[5:0];
  assign nl_main_8_for_for_for_acc_4_tmp = conv_u2s_5_6(for_for_for_k_5_0_lpi_1_dfm_4_0_1)
      + 6'b000001;
  assign main_8_for_for_for_acc_4_tmp = nl_main_8_for_for_for_acc_4_tmp[5:0];
  assign nl_for_for_for_acc_7_psp_1_sva_1 = for_for_for_for_and_14_itm_1 + (for_for_for_mul_sdt_1_sva_1[45:14]);
  assign for_for_for_acc_7_psp_1_sva_1 = nl_for_for_for_acc_7_psp_1_sva_1[31:0];
  assign nl_for_for_for_mul_sdt_1_sva_1 = $signed((A_rsci_q_d)) * $signed((B_rsci_q_d));
  assign for_for_for_mul_sdt_1_sva_1 = nl_for_for_for_mul_sdt_1_sva_1[45:0];
  assign nl_main_1_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_1_lpi_1_dfm_4_0_mx0w0)
      + 6'b000001;
  assign main_1_for_acc_1_tmp = nl_main_1_for_acc_1_tmp[5:0];
  assign nl_main_1_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0)
      + 6'b000001;
  assign main_1_for_for_acc_2_tmp = nl_main_1_for_for_acc_2_tmp[5:0];
  assign exit_main_1_for_for_lpi_1_dfm_3 = (main_1_for_for_acc_2_tmp[5]) & (main_1_for_for_for_acc_4_tmp[5]);
  assign for_for_for_k_5_0_1_lpi_1_dfm_4_0_1 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_1_lpi_1_4_0,
      lfst_exit_main_1_for_for_1_lpi_1_dfm_1);
  assign lfst_exit_main_1_for_for_1_lpi_1_dfm_1 = lfst_exit_main_1_for_for_1_lpi_1
      & for_unequal_tmp_1;
  assign for_unequal_tmp_1 = lfst_exit_main_8_for_lpi_1_dfm_3_1 | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1!=3'b000);
  assign nl_main_2_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_2_lpi_1_4_0) + 6'b000001;
  assign main_2_for_acc_1_tmp = nl_main_2_for_acc_1_tmp[5:0];
  assign nl_main_2_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_2_lpi_1_4_0) +
      6'b000001;
  assign main_2_for_for_acc_2_tmp = nl_main_2_for_for_acc_2_tmp[5:0];
  assign exit_main_2_for_for_lpi_1_dfm_3 = (main_2_for_for_acc_2_tmp[5]) & (main_2_for_for_for_acc_4_tmp[5]);
  assign for_for_for_k_5_0_2_lpi_1_dfm_4_0_1 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_2_lpi_1_4_0,
      lfst_exit_main_2_for_for_1_lpi_1);
  assign nl_main_3_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_3_lpi_1_4_0) + 6'b000001;
  assign main_3_for_acc_1_tmp = nl_main_3_for_acc_1_tmp[5:0];
  assign nl_main_3_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_3_lpi_1_4_0) +
      6'b000001;
  assign main_3_for_for_acc_2_tmp = nl_main_3_for_for_acc_2_tmp[5:0];
  assign for_for_for_k_5_0_3_lpi_1_dfm_4_0_1 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_3_lpi_1_4_0,
      lfst_exit_main_3_for_for_1_lpi_1);
  assign nl_main_4_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_4_lpi_1_4_0) + 6'b000001;
  assign main_4_for_acc_1_tmp = nl_main_4_for_acc_1_tmp[5:0];
  assign nl_main_4_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_4_lpi_1_4_0) +
      6'b000001;
  assign main_4_for_for_acc_2_tmp = nl_main_4_for_for_acc_2_tmp[5:0];
  assign exit_main_4_for_for_lpi_1_dfm_3 = (main_4_for_for_acc_2_tmp[5]) & (main_4_for_for_for_acc_4_tmp[5]);
  assign for_for_for_k_5_0_4_lpi_1_dfm_4_0_1 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_4_lpi_1_4_0,
      lfst_exit_main_4_for_for_1_lpi_1);
  assign nl_main_5_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_5_lpi_1_4_0) + 6'b000001;
  assign main_5_for_acc_1_tmp = nl_main_5_for_acc_1_tmp[5:0];
  assign nl_main_5_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_5_lpi_1_4_0) +
      6'b000001;
  assign main_5_for_for_acc_2_tmp = nl_main_5_for_for_acc_2_tmp[5:0];
  assign for_for_for_k_5_0_5_lpi_1_dfm_4_0_1 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_5_lpi_1_4_0,
      lfst_exit_main_5_for_for_1_lpi_1);
  assign nl_main_6_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_6_lpi_1_4_0) + 6'b000001;
  assign main_6_for_acc_1_tmp = nl_main_6_for_acc_1_tmp[5:0];
  assign nl_main_6_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_6_lpi_1_4_0) +
      6'b000001;
  assign main_6_for_for_acc_2_tmp = nl_main_6_for_for_acc_2_tmp[5:0];
  assign exit_main_6_for_for_lpi_1_dfm_3 = (main_6_for_for_acc_2_tmp[5]) & (main_6_for_for_for_acc_4_tmp[5]);
  assign for_for_for_k_5_0_6_lpi_1_dfm_4_0_1 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_6_lpi_1_4_0,
      lfst_exit_main_6_for_for_1_lpi_1);
  assign nl_main_7_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_7_lpi_1_4_0) + 6'b000001;
  assign main_7_for_acc_1_tmp = nl_main_7_for_acc_1_tmp[5:0];
  assign nl_main_7_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_7_lpi_1_4_0) +
      6'b000001;
  assign main_7_for_for_acc_2_tmp = nl_main_7_for_for_acc_2_tmp[5:0];
  assign for_for_for_k_5_0_7_lpi_1_dfm_4_0_1 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_7_lpi_1_4_0,
      lfst_exit_main_7_for_for_1_lpi_1);
  assign nl_main_8_for_acc_1_tmp = conv_u2s_5_6(for_i_5_0_lpi_1_4_0) + 6'b000001;
  assign main_8_for_acc_1_tmp = nl_main_8_for_acc_1_tmp[5:0];
  assign nl_main_8_for_for_acc_2_tmp = conv_u2s_5_6(for_for_j_5_0_lpi_1_4_0) + 6'b000001;
  assign main_8_for_for_acc_2_tmp = nl_main_8_for_for_acc_2_tmp[5:0];
  assign exit_main_8_for_for_lpi_1_dfm_3 = (main_8_for_for_acc_2_tmp[5]) & (main_8_for_for_for_acc_4_tmp[5]);
  assign for_for_for_k_5_0_lpi_1_dfm_4_0_1 = MUX_v_5_2_2(5'b00000, for_for_for_k_5_0_lpi_1_4_0,
      lfst_exit_main_8_for_for_1_lpi_1);
  assign for_for_sum_1_lpi_1_dfm_2 = MUX_v_32_2_2(32'b00000000000000000000000000000000,
      for_for_sum_1_sva_2, for_for_j_slc_for_for_j_5_0_1_5_2_itm_1);
  assign for_or_7_tmp_1 = for_equal_tmp_1_1 | for_equal_tmp_2_1 | for_equal_tmp_3_1
      | for_equal_tmp_4_1 | for_equal_tmp_5_1 | for_equal_tmp_6_1 | for_equal_tmp_7_1
      | for_nor_tmp_1;
  assign for_or_tmp_1 = for_for_and_cse_1 | for_for_nor_cse_1;
  assign for_and_11_ssc_1 = exit_main_7_for_lpi_1_dfm_1_mx0w6 & for_equal_tmp_8;
  assign for_for_and_cse_1 = (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[0]) & (~(lfst_exit_main_8_for_lpi_1_dfm_3_1
      | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1[2:1]!=2'b00)));
  assign for_for_nor_cse_1 = ~(lfst_exit_main_8_for_lpi_1_dfm_3_1 | (lfst_exit_main_8_for_lpi_1_dfm_2_0_1!=3'b000));
  assign mux_16_nl = MUX_s_1_2_2(and_112_cse, or_4_cse, main_2_for_for_for_acc_4_tmp[5]);
  assign mux_15_nl = MUX_s_1_2_2(and_112_cse, or_4_cse, main_3_for_for_for_acc_4_tmp[5]);
  assign mux_17_nl = MUX_s_1_2_2((mux_16_nl), (mux_15_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_18_nl = MUX_s_1_2_2((main_1_for_for_for_acc_4_tmp[5]), (mux_17_nl),
      lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign nor_1_nl = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1:0]!=2'b00) | (~ (main_8_for_for_for_acc_4_tmp[5])));
  assign mux_14_nl = MUX_s_1_2_2(and_112_cse, or_4_cse, nor_1_nl);
  assign mux_19_nl = MUX_s_1_2_2((mux_18_nl), (mux_14_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_10_nl = MUX_s_1_2_2(and_112_cse, or_4_cse, main_4_for_for_for_acc_4_tmp[5]);
  assign mux_9_nl = MUX_s_1_2_2(and_112_cse, or_4_cse, main_5_for_for_for_acc_4_tmp[5]);
  assign mux_11_nl = MUX_s_1_2_2((mux_10_nl), (mux_9_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_7_nl = MUX_s_1_2_2(and_112_cse, or_4_cse, main_6_for_for_for_acc_4_tmp[5]);
  assign mux_6_nl = MUX_s_1_2_2(and_112_cse, or_4_cse, main_7_for_for_for_acc_4_tmp[5]);
  assign mux_8_nl = MUX_s_1_2_2((mux_7_nl), (mux_6_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_12_nl = MUX_s_1_2_2((mux_11_nl), (mux_8_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign mux_13_nl = MUX_s_1_2_2((mux_12_nl), and_112_cse, lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_tmp_14 = MUX_s_1_2_2((mux_19_nl), (mux_13_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]);
  assign nor_tmp_5 = for_nor_tmp_2 & lfst_exit_main_2_for_for_1_lpi_1;
  assign nor_tmp_7 = ((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) | for_nor_tmp_2)
      & lfst_exit_main_2_for_for_1_lpi_1;
  assign or_11_nl = (~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])) | lfst_exit_main_2_for_for_1_lpi_1;
  assign mux_29_nl = MUX_s_1_2_2((or_11_nl), nor_tmp_7, exit_main_2_for_for_lpi_1_dfm_3);
  assign mux_30_nl = MUX_s_1_2_2((mux_29_nl), lfst_exit_main_2_for_for_1_lpi_1, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_tmp_25 = MUX_s_1_2_2((mux_30_nl), nor_tmp_5, lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign nor_tmp_8 = ((~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])))
      | for_nor_tmp_2) & lfst_exit_main_2_for_for_1_lpi_1;
  assign or_142_cse = nor_136_cse | for_nor_tmp_2 | exitL_exit_main_8_for_sva;
  assign or_tmp_21 = for_nor_tmp_2 | exitL_exit_main_8_for_sva;
  assign nor_tmp_27 = for_nor_tmp_2 & lfst_exit_main_8_for_for_1_lpi_1;
  assign or_84_nl = (~ for_nor_tmp_2) | lfst_exit_main_1_for_for_1_lpi_1;
  assign and_114_nl = for_nor_tmp_2 & lfst_exit_main_1_for_for_1_lpi_1;
  assign mux_tmp_84 = MUX_s_1_2_2((or_84_nl), (and_114_nl), exit_main_1_for_for_lpi_1_dfm_3);
  assign or_dcpl_9 = ~(((lfst_exit_main_8_for_lpi_1_dfm_st_1_2_0!=3'b000)) & lfst_exit_main_8_for_lpi_1_dfm_st_1_3);
  assign or_dcpl_12 = (nor_71_cse & (~ lfst_exit_main_8_for_lpi_1_dfm_9_3)) | exitL_exit_main_8_for_sva;
  assign and_dcpl_20 = ~(exitL_exit_main_8_for_sva | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]));
  assign and_dcpl_21 = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b01);
  assign and_dcpl_22 = and_dcpl_21 & and_dcpl_20;
  assign and_dcpl_23 = (~ exitL_exit_main_8_for_sva) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign and_dcpl_24 = and_dcpl_21 & and_dcpl_23;
  assign and_dcpl_25 = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b10);
  assign and_dcpl_26 = and_dcpl_25 & and_dcpl_20;
  assign and_dcpl_27 = and_dcpl_25 & and_dcpl_23;
  assign and_dcpl_29 = and_86_cse & and_dcpl_20;
  assign and_dcpl_30 = and_86_cse & and_dcpl_23;
  assign and_dcpl_32 = nor_71_cse & (~ exitL_exit_main_8_for_sva) & lfst_exit_main_8_for_lpi_1_dfm_9_3;
  assign and_dcpl_36 = and_dcpl_21 & (~ exitL_exit_main_8_for_sva);
  assign or_dcpl_16 = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) | lfst_exit_main_8_for_lpi_1_dfm_9_3;
  assign or_dcpl_18 = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b01) | exitL_exit_main_8_for_sva;
  assign or_dcpl_23 = (~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])) | lfst_exit_main_8_for_lpi_1_dfm_9_3;
  assign or_dcpl_25 = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b11) | exitL_exit_main_8_for_sva;
  assign or_dcpl_29 = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b10) | exitL_exit_main_8_for_sva;
  assign B_mux1h_rmff = MUX1HOT_v_5_8_2(for_for_for_k_5_0_1_lpi_1_dfm_4_0_1, for_for_for_k_5_0_2_lpi_1_dfm_4_0_1,
      for_for_for_k_5_0_3_lpi_1_dfm_4_0_1, for_for_for_k_5_0_4_lpi_1_dfm_4_0_1, for_for_for_k_5_0_5_lpi_1_dfm_4_0_1,
      for_for_for_k_5_0_6_lpi_1_dfm_4_0_1, for_for_for_k_5_0_7_lpi_1_dfm_4_0_1, for_for_for_k_5_0_lpi_1_dfm_4_0_1,
      {or_dcpl_12 , and_dcpl_22 , and_dcpl_24 , and_dcpl_26 , and_dcpl_27 , and_dcpl_29
      , and_dcpl_30 , and_dcpl_32});
  assign A_rsci_adr_d = {for_i_mux1h_1_cse , B_mux1h_rmff};
  assign A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff = or_91_cse & (fsm_output[1]);
  assign B_rsci_adr_d = {B_mux1h_rmff , for_for_j_mux1h_1_cse};
  assign C_rsci_adr_d = {main_1_for_i_slc_for_i_5_0_4_0_1_itm_1 , main_1_for_for_j_slc_for_for_j_5_0_4_0_1_itm_1};
  assign C_rsci_d_d = for_for_sum_1_sva_2;
  assign C_rsci_we_d_pff = or_dcpl_9 & main_stage_0_2 & main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1;
  assign nor_151_nl = ~(lfst_exit_main_8_for_lpi_1_dfm_9_3 | (~ and_298_cse));
  assign mux_tmp_117 = MUX_s_1_2_2((nor_151_nl), and_298_cse, exitL_exit_main_8_for_sva);
  assign or_dcpl_59 = lfst_exit_main_8_for_lpi_1_dfm_9_3 | exitL_exit_main_8_for_sva;
  always @(posedge clk) begin
    if ( rst ) begin
      C_rsc_triosy_obj_ld <= 1'b0;
      reg_B_rsc_triosy_obj_ld_cse <= 1'b0;
      lfst_exit_main_8_for_lpi_1_dfm_st_1_3 <= 1'b0;
      lfst_exit_main_8_for_lpi_1_dfm_st_1_2_0 <= 3'b000;
      main_stage_0_2 <= 1'b0;
      for_for_j_slc_for_for_j_5_0_1_5_2_itm_1 <= 1'b0;
      for_equal_tmp_6_1 <= 1'b0;
      for_equal_tmp_5_1 <= 1'b0;
      for_equal_tmp_4_1 <= 1'b0;
      for_equal_tmp_3_1 <= 1'b0;
      for_equal_tmp_2_1 <= 1'b0;
      for_equal_tmp_1_1 <= 1'b0;
      for_equal_tmp_7_1 <= 1'b0;
    end
    else begin
      C_rsc_triosy_obj_ld <= or_dcpl_9 & main_stage_0_2 & exit_main_1_for_lpi_1_dfm_2_st_1;
      reg_B_rsc_triosy_obj_ld_cse <= (mux_107_nl) & (fsm_output[1]);
      lfst_exit_main_8_for_lpi_1_dfm_st_1_3 <= lfst_exit_main_8_for_lpi_1_dfm_3_1;
      lfst_exit_main_8_for_lpi_1_dfm_st_1_2_0 <= lfst_exit_main_8_for_lpi_1_dfm_2_0_1;
      main_stage_0_2 <= fsm_output[1];
      for_for_j_slc_for_for_j_5_0_1_5_2_itm_1 <= MUX1HOT_s_1_8_2((main_1_for_for_acc_2_tmp[5]),
          (main_2_for_for_acc_2_tmp[5]), (main_3_for_for_acc_2_tmp[5]), (main_4_for_for_acc_2_tmp[5]),
          (main_5_for_for_acc_2_tmp[5]), (main_6_for_for_acc_2_tmp[5]), (main_7_for_for_acc_2_tmp[5]),
          (main_8_for_for_acc_2_tmp[5]), {or_dcpl_12 , and_dcpl_22 , and_dcpl_24
          , and_dcpl_26 , and_dcpl_27 , and_dcpl_29 , and_dcpl_30 , and_dcpl_32});
      for_equal_tmp_6_1 <= for_equal_tmp_8;
      for_equal_tmp_5_1 <= for_equal_tmp_9;
      for_equal_tmp_4_1 <= for_equal_tmp_10;
      for_equal_tmp_3_1 <= for_equal_tmp_11;
      for_equal_tmp_2_1 <= for_equal_tmp_12;
      for_equal_tmp_1_1 <= for_equal_tmp_13;
      for_equal_tmp_7_1 <= for_equal_tmp_14;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      main_1_for_i_slc_for_i_5_0_4_0_1_itm_1 <= 5'b00000;
      main_1_for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 <= 5'b00000;
    end
    else if ( mux_tmp_14 ) begin
      main_1_for_i_slc_for_i_5_0_4_0_1_itm_1 <= for_i_mux1h_1_cse;
      main_1_for_for_j_slc_for_for_j_5_0_4_0_1_itm_1 <= for_for_j_mux1h_1_cse;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      exit_main_1_for_lpi_1_dfm_2_st_1 <= 1'b0;
      main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 <= 1'b0;
    end
    else if ( or_91_cse ) begin
      exit_main_1_for_lpi_1_dfm_2_st_1 <= MUX1HOT_s_1_8_2(exit_main_1_for_lpi_1_dfm_2_mx0w0,
          exit_main_2_for_lpi_1_dfm_1_mx0w1, exit_main_3_for_lpi_1_dfm_1_mx0w2, exit_main_4_for_lpi_1_dfm_1_mx0w3,
          exit_main_5_for_lpi_1_dfm_1_mx0w4, exit_main_6_for_lpi_1_dfm_1_mx0w5, exit_main_7_for_lpi_1_dfm_1_mx0w6,
          exit_main_8_for_lpi_1_dfm_1_mx0w7, {or_dcpl_12 , and_dcpl_22 , and_dcpl_24
          , and_dcpl_26 , and_dcpl_27 , and_dcpl_29 , and_dcpl_30 , and_dcpl_32});
      main_1_for_for_for_k_slc_for_for_for_k_5_0_5_1_itm_1 <= MUX1HOT_s_1_8_2((main_1_for_for_for_acc_4_tmp[5]),
          (main_2_for_for_for_acc_4_tmp[5]), (main_3_for_for_for_acc_4_tmp[5]), (main_4_for_for_for_acc_4_tmp[5]),
          (main_5_for_for_for_acc_4_tmp[5]), (main_6_for_for_for_acc_4_tmp[5]), (main_7_for_for_for_acc_4_tmp[5]),
          (main_8_for_for_for_acc_4_tmp[5]), {or_dcpl_12 , and_dcpl_22 , and_dcpl_24
          , and_dcpl_26 , and_dcpl_27 , and_dcpl_29 , and_dcpl_30 , and_dcpl_32});
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_for_and_14_itm_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( MUX_s_1_2_2(or_91_cse, (mux_22_nl), for_nor_tmp_2) ) begin
      for_for_for_for_and_14_itm_1 <= MUX_v_32_2_2(32'b00000000000000000000000000000000,
          (mux1h_8_nl), (not_350_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_1_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (nor_153_cse | exitL_exit_main_8_for_sva) & nand_39_cse ) begin
      for_for_for_k_5_0_1_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_1_for_for_for_acc_4_tmp[4:0]),
          (for_nand_1_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_1_for_for_1_lpi_1 <= 1'b0;
    end
    else if ( ~((~((mux_88_nl) | exitL_exit_main_8_for_sva)) | for_nor_tmp_2) ) begin
      lfst_exit_main_1_for_for_1_lpi_1 <= ~ exit_main_1_for_for_lpi_1_dfm_3;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_1_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (nor_153_cse & ((~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])) | (main_1_for_for_for_acc_4_tmp[5])))
        | exitL_exit_main_8_for_sva ) begin
      for_for_j_5_0_1_lpi_1_4_0 <= MUX1HOT_v_5_3_2((signext_5_1(main_1_for_acc_1_tmp[5])),
          for_for_j_5_0_1_lpi_1_dfm_4_0_mx0w0, (main_1_for_for_acc_2_tmp[4:0]), {(nor_82_nl)
          , (~ (main_1_for_for_for_acc_4_tmp[5])) , mux_110_tmp});
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_2_lpi_1_4_0 <= 5'b00000;
    end
    else if ( MUX_s_1_2_2((mux_127_nl), and_299_cse, or_167_cse) ) begin
      for_i_5_0_2_lpi_1_4_0 <= MUX_v_5_2_2((for_for_and_20_nl), (main_2_for_acc_1_tmp[4:0]),
          for_and_15_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_2_lpi_1_4_0 <= 5'b00000;
    end
    else if ( MUX_s_1_2_2((mux_134_nl), (mux_133_nl), nor_102_nl) ) begin
      for_for_j_5_0_2_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_2_for_for_acc_2_tmp[4:0]),
          (mux_111_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_2_lpi_1_4_0 <= 5'b00000;
    end
    else if ( nand_45_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1:0]==2'b10) &
        (~(exitL_exit_main_8_for_sva | lfst_exit_main_8_for_lpi_1_dfm_9_3 | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])))
        ) begin
      for_for_for_k_5_0_2_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_2_for_for_for_acc_4_tmp[4:0]),
          (for_nand_2_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_2_for_for_1_lpi_1 <= 1'b0;
    end
    else if ( for_or_tmp_1 | for_equal_tmp_13 ) begin
      lfst_exit_main_2_for_for_1_lpi_1 <= MUX_s_1_2_2((for_for_and_22_nl), (~ exit_main_2_for_for_lpi_1_dfm_3),
          for_equal_tmp_13);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_3_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_136_nl) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]) & (~ exitL_exit_main_8_for_sva)
        & (~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) | lfst_exit_main_8_for_lpi_1_dfm_9_3))
        ) begin
      for_i_5_0_3_lpi_1_4_0 <= MUX_v_5_2_2((for_for_and_23_nl), (main_3_for_acc_1_tmp[4:0]),
          for_and_17_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_3_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_137_nl) & nor_149_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b01)
        ) begin
      for_for_j_5_0_3_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_3_for_for_acc_2_tmp[4:0]),
          (mux_112_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_3_lpi_1_4_0 <= 5'b00000;
    end
    else if ( nand_37_cse & nor_149_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0==3'b011)
        ) begin
      for_for_for_k_5_0_3_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_3_for_for_for_acc_4_tmp[4:0]),
          (for_nand_3_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_3_for_for_1_lpi_1 <= 1'b0;
    end
    else if ( for_equal_tmp_13 | for_equal_tmp_12 ) begin
      lfst_exit_main_3_for_for_1_lpi_1 <= MUX_s_1_2_2((for_for_and_25_nl), (~ and_297_cse),
          for_equal_tmp_12);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_4_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_138_nl) & nor_149_cse ) begin
      for_i_5_0_4_lpi_1_4_0 <= MUX_v_5_2_2((for_for_and_26_nl), (main_4_for_acc_1_tmp[4:0]),
          for_and_19_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_4_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_139_nl) & nor_149_cse ) begin
      for_for_j_5_0_4_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_4_for_for_acc_2_tmp[4:0]),
          (mux_113_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_4_lpi_1_4_0 <= 5'b00000;
    end
    else if ( nand_43_cse & (~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]) | exitL_exit_main_8_for_sva))
        & (~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])
        & (~ lfst_exit_main_8_for_lpi_1_dfm_9_3) ) begin
      for_for_for_k_5_0_4_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_4_for_for_for_acc_4_tmp[4:0]),
          (for_nand_4_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_4_for_for_1_lpi_1 <= 1'b0;
    end
    else if ( for_equal_tmp_12 | for_equal_tmp_11 ) begin
      lfst_exit_main_4_for_for_1_lpi_1 <= MUX_s_1_2_2((for_for_and_28_nl), (~ exit_main_4_for_for_lpi_1_dfm_3),
          for_equal_tmp_11);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_5_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_140_nl) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) & (~ exitL_exit_main_8_for_sva)
        & (~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]) | lfst_exit_main_8_for_lpi_1_dfm_9_3))
        ) begin
      for_i_5_0_5_lpi_1_4_0 <= MUX_v_5_2_2((for_for_and_29_nl), (main_5_for_acc_1_tmp[4:0]),
          for_and_21_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_5_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_141_nl) & nor_149_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b10)
        ) begin
      for_for_j_5_0_5_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_5_for_for_acc_2_tmp[4:0]),
          (mux_114_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_5_lpi_1_4_0 <= 5'b00000;
    end
    else if ( nor_149_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b10) &
        nand_34_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) ) begin
      for_for_for_k_5_0_5_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_5_for_for_for_acc_4_tmp[4:0]),
          (for_nand_5_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_5_for_for_1_lpi_1 <= 1'b0;
    end
    else if ( for_equal_tmp_11 | for_equal_tmp_10 ) begin
      lfst_exit_main_5_for_for_1_lpi_1 <= MUX_s_1_2_2((for_for_and_31_nl), (~ and_295_cse),
          for_equal_tmp_10);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_6_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_142_nl) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) & (~ exitL_exit_main_8_for_sva)
        & (~ lfst_exit_main_8_for_lpi_1_dfm_9_3) ) begin
      for_i_5_0_6_lpi_1_4_0 <= MUX_v_5_2_2((for_for_and_32_nl), (main_6_for_acc_1_tmp[4:0]),
          for_and_23_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_6_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_143_nl) & nor_149_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])
        ) begin
      for_for_j_5_0_6_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_6_for_for_acc_2_tmp[4:0]),
          (mux_115_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_6_lpi_1_4_0 <= 5'b00000;
    end
    else if ( nand_32_cse & nor_149_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0==3'b110)
        ) begin
      for_for_for_k_5_0_6_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_6_for_for_for_acc_4_tmp[4:0]),
          (for_nand_6_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_6_for_for_1_lpi_1 <= 1'b0;
    end
    else if ( for_equal_tmp_10 | for_equal_tmp_9 ) begin
      lfst_exit_main_6_for_for_1_lpi_1 <= MUX_s_1_2_2((for_for_and_34_nl), (~ exit_main_6_for_for_lpi_1_dfm_3),
          for_equal_tmp_9);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_7_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_144_nl) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) & (~ exitL_exit_main_8_for_sva)
        & (~ lfst_exit_main_8_for_lpi_1_dfm_9_3) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1])
        ) begin
      for_i_5_0_7_lpi_1_4_0 <= MUX_v_5_2_2((for_for_and_35_nl), (main_7_for_acc_1_tmp[4:0]),
          for_and_25_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_7_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (mux_145_nl) & nor_149_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b11)
        ) begin
      for_for_j_5_0_7_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_7_for_for_acc_2_tmp[4:0]),
          (mux_116_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_7_lpi_1_4_0 <= 5'b00000;
    end
    else if ( nand_31_cse & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) & (~ exitL_exit_main_8_for_sva)
        & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1:0]==2'b11) & (~ lfst_exit_main_8_for_lpi_1_dfm_9_3)
        ) begin
      for_for_for_k_5_0_7_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_7_for_for_for_acc_4_tmp[4:0]),
          (for_nand_7_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_7_for_for_1_lpi_1 <= 1'b0;
    end
    else if ( for_equal_tmp_9 | for_equal_tmp_8 ) begin
      lfst_exit_main_7_for_for_1_lpi_1 <= MUX_s_1_2_2((for_for_and_37_nl), (~ and_292_cse),
          for_equal_tmp_8);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_lpi_1_4_0 <= 5'b00000;
    end
    else if ( ~((mux_146_nl) | exitL_exit_main_8_for_sva) ) begin
      for_i_5_0_lpi_1_4_0 <= MUX_v_5_2_2((for_for_and_38_nl), (main_8_for_acc_1_tmp[4:0]),
          for_and_13_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_j_5_0_lpi_1_4_0 <= 5'b00000;
    end
    else if ( ~((mux_147_nl) | exitL_exit_main_8_for_sva) ) begin
      for_for_j_5_0_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_8_for_for_acc_2_tmp[4:0]),
          (mux_117_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_for_k_5_0_lpi_1_4_0 <= 5'b00000;
    end
    else if ( nand_40_cse & lfst_exit_main_8_for_lpi_1_dfm_9_3 & (~ exitL_exit_main_8_for_sva)
        & nor_136_cse ) begin
      for_for_for_k_5_0_lpi_1_4_0 <= MUX_v_5_2_2(5'b00000, (main_8_for_for_for_acc_4_tmp[4:0]),
          (for_nand_nl));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_8_for_for_1_lpi_1 <= 1'b0;
    end
    else if ( for_equal_tmp_8 | for_equal_tmp_14 ) begin
      lfst_exit_main_8_for_for_1_lpi_1 <= MUX_s_1_2_2((for_for_and_40_nl), (~ exit_main_8_for_for_lpi_1_dfm_3),
          for_equal_tmp_14);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_8_for_lpi_1_dfm_9_3 <= 1'b0;
    end
    else if ( ~ (fsm_output[0]) ) begin
      lfst_exit_main_8_for_lpi_1_dfm_9_3 <= lfst_exit_main_8_for_lpi_1_dfm_9_3_mx0w0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      exitL_exit_main_8_for_sva <= 1'b1;
    end
    else if ( ~ (fsm_output[0]) ) begin
      exitL_exit_main_8_for_sva <= ~(lfst_exit_main_8_for_lpi_1_dfm_9_3_mx0w0 | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0_2!=3'b000));
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      lfst_exit_main_8_for_lpi_1_dfm_9_2_0 <= 3'b000;
    end
    else if ( MUX_s_1_2_2((mux_63_nl), or_195_cse, exitL_exit_main_8_for_sva) ) begin
      lfst_exit_main_8_for_lpi_1_dfm_9_2_0 <= lfst_exit_main_8_for_lpi_1_dfm_9_2_0_2;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_i_5_0_1_lpi_1_4_0 <= 5'b00000;
    end
    else if ( (((main_1_for_for_acc_2_tmp[5]) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b00)
        & (~ lfst_exit_main_8_for_lpi_1_dfm_9_3) & (main_1_for_for_for_acc_4_tmp[5]))
        | exitL_exit_main_8_for_sva) & or_195_cse ) begin
      for_i_5_0_1_lpi_1_4_0 <= MUX_v_5_2_2(for_i_5_0_1_lpi_1_dfm_4_0_mx0w0, (main_1_for_acc_1_tmp[4:0]),
          asn_for_i_5_0_1_lpi_1_4_0_for_nor_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_sum_7_lpi_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ((~(and_291_cse | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]))) | or_dcpl_59
        | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b11)) & lfst_exit_main_7_for_for_1_lpi_1
        & main_stage_0_2 & for_equal_tmp_6_1 ) begin
      for_for_sum_7_lpi_1 <= for_for_sum_7_lpi_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_sum_6_lpi_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ((mux_148_nl) | or_dcpl_59 | (~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])))
        & lfst_exit_main_6_for_for_1_lpi_1 & main_stage_0_2 & for_equal_tmp_5_1 )
        begin
      for_for_sum_6_lpi_1 <= for_for_sum_6_lpi_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_sum_5_lpi_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ((~(and_70_cse | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]))) | or_dcpl_59
        | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b10)) & lfst_exit_main_5_for_for_1_lpi_1
        & main_stage_0_2 & for_equal_tmp_4_1 ) begin
      for_for_sum_5_lpi_1 <= for_for_sum_5_lpi_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_sum_4_lpi_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ((mux_149_nl) | or_dcpl_59) & lfst_exit_main_4_for_for_1_lpi_1 & main_stage_0_2
        & for_equal_tmp_3_1 ) begin
      for_for_sum_4_lpi_1 <= for_for_sum_4_lpi_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_sum_3_lpi_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ((~(and_67_cse | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]))) | or_dcpl_59
        | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b01)) & lfst_exit_main_3_for_for_1_lpi_1
        & main_stage_0_2 & for_equal_tmp_2_1 ) begin
      for_for_sum_3_lpi_1 <= for_for_sum_3_lpi_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_sum_2_lpi_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( (mux_151_nl) & lfst_exit_main_2_for_for_1_lpi_1 & main_stage_0_2 &
        for_equal_tmp_1_1 ) begin
      for_for_sum_2_lpi_1 <= for_for_sum_2_lpi_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_sum_1_lpi_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( (~(for_nor_tmp_1 | for_equal_tmp_7_1)) & (~(for_equal_tmp_6_1 | for_equal_tmp_5_1))
        & ((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) | lfst_exit_main_8_for_lpi_1_dfm_9_3
        | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1])) & (~(for_equal_tmp_4_1 | for_equal_tmp_3_1))
        & (~(for_equal_tmp_2_1 | for_equal_tmp_1_1)) & main_stage_0_2 & (~ exitL_exit_main_8_for_sva)
        & lfst_exit_main_1_for_for_1_lpi_1 ) begin
      for_for_sum_1_lpi_1 <= for_for_sum_1_lpi_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_for_sum_lpi_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ((mux_152_nl) | exitL_exit_main_8_for_sva) & lfst_exit_main_8_for_for_1_lpi_1
        & main_stage_0_2 & for_equal_tmp_7_1 ) begin
      for_for_sum_lpi_1 <= for_for_sum_lpi_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      reg_main_1_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1_cse <= 1'b0;
    end
    else if ( (mux_95_nl) & ((~(or_171_cse | lfst_exit_main_8_for_lpi_1_dfm_9_3))
        | exitL_exit_main_8_for_sva) ) begin
      reg_main_1_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm_1_cse <= main_1_for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      for_nor_tmp_1 <= 1'b0;
    end
    else if ( MUX_s_1_2_2((~ (mux_27_nl)), lfst_exit_main_1_for_for_1_lpi_1, for_nor_tmp_2)
        ) begin
      for_nor_tmp_1 <= for_nor_tmp_2;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      main_2_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= 1'b0;
    end
    else if ( (mux_38_nl) & (~(or_dcpl_18 | or_dcpl_16)) ) begin
      main_2_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= main_2_for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      main_8_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= 1'b0;
    end
    else if ( (mux_60_nl) & (~(or_171_cse | exitL_exit_main_8_for_sva | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])
        | (~ lfst_exit_main_8_for_lpi_1_dfm_9_3))) ) begin
      main_8_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= main_8_for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      main_7_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= 1'b0;
    end
    else if ( (mux_57_nl) & (~(or_dcpl_25 | or_dcpl_23)) ) begin
      main_7_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= main_7_for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      main_6_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= 1'b0;
    end
    else if ( (mux_53_nl) & (~(or_dcpl_25 | or_dcpl_16)) ) begin
      main_6_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= main_6_for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      main_5_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= 1'b0;
    end
    else if ( (mux_49_nl) & (~(or_dcpl_29 | or_dcpl_23)) ) begin
      main_5_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= main_5_for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      main_4_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= 1'b0;
    end
    else if ( (mux_46_nl) & (~(or_dcpl_29 | or_dcpl_16)) ) begin
      main_4_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= main_4_for_for_for_acc_4_tmp[5];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      main_3_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= 1'b0;
    end
    else if ( (mux_42_nl) & (~(or_dcpl_18 | or_dcpl_23)) ) begin
      main_3_for_for_for_k_slc_for_for_for_k_5_0_5_3_itm <= main_3_for_for_for_acc_4_tmp[5];
    end
  end
  assign and_68_nl = (main_3_for_acc_1_tmp[5]) & (main_3_for_for_acc_2_tmp[5]) &
      (main_3_for_for_for_acc_4_tmp[5]);
  assign mux_104_nl = MUX_s_1_2_2(and_67_cse, (and_68_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_105_nl = MUX_s_1_2_2((mux_104_nl), and_298_cse, or_89_cse);
  assign mux_102_nl = MUX_s_1_2_2((~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])),
      and_298_cse, exitL_exit_main_8_for_sva);
  assign and_69_nl = (~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1])) & (main_8_for_acc_1_tmp[5])
      & (main_8_for_for_acc_2_tmp[5]) & (main_8_for_for_for_acc_4_tmp[5]);
  assign mux_103_nl = MUX_s_1_2_2(and_299_cse, (mux_102_nl), and_69_nl);
  assign mux_106_nl = MUX_s_1_2_2((mux_105_nl), (mux_103_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign and_71_nl = (main_5_for_acc_1_tmp[5]) & (main_5_for_for_acc_2_tmp[5]) &
      (main_5_for_for_for_acc_4_tmp[5]);
  assign mux_98_nl = MUX_s_1_2_2(and_70_cse, (and_71_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_99_nl = MUX_s_1_2_2((mux_98_nl), and_298_cse, exitL_exit_main_8_for_sva);
  assign mux_96_nl = MUX_s_1_2_2(and_291_cse, and_85_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_97_nl = MUX_s_1_2_2((mux_96_nl), and_298_cse, exitL_exit_main_8_for_sva);
  assign mux_100_nl = MUX_s_1_2_2((mux_99_nl), (mux_97_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign mux_101_nl = MUX_s_1_2_2((mux_100_nl), and_299_cse, lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_107_nl = MUX_s_1_2_2((mux_106_nl), (mux_101_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]);
  assign and_153_nl = and_dcpl_26 & (~ or_149_tmp);
  assign and_154_nl = and_dcpl_27 & (~ or_149_tmp);
  assign and_155_nl = and_dcpl_29 & (~ or_149_tmp);
  assign and_156_nl = and_dcpl_30 & (~ or_149_tmp);
  assign nor_83_nl = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) | exitL_exit_main_8_for_sva
      | (~ lfst_exit_main_8_for_lpi_1_dfm_9_3) | or_149_tmp);
  assign nor_84_nl = ~((~ and_dcpl_36) | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])
      | lfst_exit_main_8_for_lpi_1_dfm_9_3 | or_149_tmp);
  assign and_40_nl = and_dcpl_36 & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) & (~
      lfst_exit_main_8_for_lpi_1_dfm_9_3) & (~ or_149_tmp);
  assign and_157_nl = or_dcpl_12 & (~ or_149_tmp);
  assign mux1h_8_nl = MUX1HOT_v_32_8_2(for_for_sum_4_lpi_1_mx0, for_for_sum_5_lpi_1_mx0,
      for_for_sum_6_lpi_1_mx0, for_for_sum_7_lpi_1_mx0, for_for_sum_lpi_1_mx0, for_for_sum_2_lpi_1_mx0,
      for_for_sum_3_lpi_1_mx0, for_for_sum_1_lpi_1_mx0, {(and_153_nl) , (and_154_nl)
      , (and_155_nl) , (and_156_nl) , (nor_83_nl) , (nor_84_nl) , (and_40_nl) , (and_157_nl)});
  assign not_350_nl = ~ or_149_tmp;
  assign or_7_nl = (~(nor_71_cse | exitL_exit_main_8_for_sva)) | (main_1_for_for_for_acc_4_tmp[5]);
  assign mux_21_nl = MUX_s_1_2_2(or_4_cse, and_112_cse, or_3_cse);
  assign mux_22_nl = MUX_s_1_2_2((or_7_nl), (mux_21_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign for_nand_1_nl = ~((main_1_for_for_for_acc_4_tmp[5]) & (~(for_equal_tmp_13
      | for_equal_tmp_12 | for_equal_tmp_11 | for_equal_tmp_10 | for_equal_tmp_9
      | for_equal_tmp_8 | for_equal_tmp_14 | for_nor_tmp_2)));
  assign mux_88_nl = MUX_s_1_2_2(nor_71_cse, or_3_cse, lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign nor_82_nl = ~((~ (main_1_for_for_for_acc_4_tmp[5])) | mux_110_tmp);
  assign for_not_114_nl = ~ exit_main_1_for_lpi_1_dfm_2_mx0w0;
  assign for_for_and_20_nl = MUX_v_5_2_2(5'b00000, for_i_5_0_2_lpi_1_4_0, (for_not_114_nl));
  assign for_and_15_nl = exit_main_2_for_for_lpi_1_dfm_3 & for_equal_tmp_13;
  assign nor_161_nl = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) | nand_45_cse);
  assign mux_127_nl = MUX_s_1_2_2((nor_161_nl), and_298_cse, or_89_cse);
  assign or_151_nl = (~ for_equal_tmp_13) | (main_2_for_acc_1_tmp[5]) | nand_45_cse;
  assign and_121_nl = for_equal_tmp_13 & ((main_2_for_acc_1_tmp[5]) | nand_45_cse);
  assign mux_111_nl = MUX_s_1_2_2((or_151_nl), (and_121_nl), exit_main_1_for_lpi_1_dfm_2_mx0w0);
  assign mux_134_nl = MUX_s_1_2_2(mux_tmp_117, and_299_cse, or_171_cse);
  assign mux_132_nl = MUX_s_1_2_2(mux_tmp_117, and_299_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]);
  assign mux_129_nl = MUX_s_1_2_2((~ lfst_exit_main_8_for_lpi_1_dfm_9_3), and_298_cse,
      exitL_exit_main_8_for_sva);
  assign mux_130_nl = MUX_s_1_2_2((mux_129_nl), and_299_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]);
  assign mux_133_nl = MUX_s_1_2_2((mux_132_nl), (mux_130_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign nor_102_nl = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) | (~ (main_2_for_for_for_acc_4_tmp[5])));
  assign for_nand_2_nl = ~((main_2_for_for_for_acc_4_tmp[5]) & for_equal_tmp_13);
  assign for_for_and_22_nl = lfst_exit_main_2_for_for_1_lpi_1 & (~ exit_main_1_for_lpi_1_dfm_2_mx0w0);
  assign for_not_115_nl = ~ exit_main_2_for_lpi_1_dfm_1_mx0w1;
  assign for_for_and_23_nl = MUX_v_5_2_2(5'b00000, for_i_5_0_3_lpi_1_4_0, (for_not_115_nl));
  assign for_and_17_nl = and_297_cse & for_equal_tmp_12;
  assign mux_136_nl = MUX_s_1_2_2(and_67_cse, and_297_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign or_153_nl = (~ for_equal_tmp_12) | (main_3_for_acc_1_tmp[5]) | nand_37_cse;
  assign and_122_nl = for_equal_tmp_12 & ((main_3_for_acc_1_tmp[5]) | nand_37_cse);
  assign mux_112_nl = MUX_s_1_2_2((or_153_nl), (and_122_nl), exit_main_2_for_lpi_1_dfm_1_mx0w1);
  assign mux_137_nl = MUX_s_1_2_2(and_67_cse, (main_3_for_for_for_acc_4_tmp[5]),
      lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign for_nand_3_nl = ~((main_3_for_for_for_acc_4_tmp[5]) & for_equal_tmp_12);
  assign for_for_and_25_nl = lfst_exit_main_3_for_for_1_lpi_1 & (~ exit_main_2_for_lpi_1_dfm_1_mx0w1);
  assign for_not_116_nl = ~ exit_main_3_for_lpi_1_dfm_1_mx0w2;
  assign for_for_and_26_nl = MUX_v_5_2_2(5'b00000, for_i_5_0_4_lpi_1_4_0, (for_not_116_nl));
  assign for_and_19_nl = exit_main_4_for_for_lpi_1_dfm_3 & for_equal_tmp_11;
  assign nor_157_nl = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b10) | nand_43_cse);
  assign mux_138_nl = MUX_s_1_2_2((nor_157_nl), nor_158_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign or_155_nl = (~ for_equal_tmp_11) | (main_4_for_acc_1_tmp[5]) | nand_43_cse;
  assign and_123_nl = for_equal_tmp_11 & ((main_4_for_acc_1_tmp[5]) | nand_43_cse);
  assign mux_113_nl = MUX_s_1_2_2((or_155_nl), (and_123_nl), exit_main_3_for_lpi_1_dfm_1_mx0w2);
  assign nor_145_nl = ~((~ (main_4_for_for_for_acc_4_tmp[5])) | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b10));
  assign mux_139_nl = MUX_s_1_2_2((nor_145_nl), nor_158_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign for_nand_4_nl = ~((main_4_for_for_for_acc_4_tmp[5]) & for_equal_tmp_11);
  assign for_for_and_28_nl = lfst_exit_main_4_for_for_1_lpi_1 & (~ exit_main_3_for_lpi_1_dfm_1_mx0w2);
  assign for_not_117_nl = ~ exit_main_4_for_lpi_1_dfm_1_mx0w3;
  assign for_for_and_29_nl = MUX_v_5_2_2(5'b00000, for_i_5_0_5_lpi_1_4_0, (for_not_117_nl));
  assign for_and_21_nl = and_295_cse & for_equal_tmp_10;
  assign mux_140_nl = MUX_s_1_2_2(and_70_cse, and_295_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign or_157_nl = (~ for_equal_tmp_10) | (main_5_for_acc_1_tmp[5]) | nand_34_cse;
  assign and_124_nl = for_equal_tmp_10 & ((main_5_for_acc_1_tmp[5]) | nand_34_cse);
  assign mux_114_nl = MUX_s_1_2_2((or_157_nl), (and_124_nl), exit_main_4_for_lpi_1_dfm_1_mx0w3);
  assign mux_141_nl = MUX_s_1_2_2(and_70_cse, (main_5_for_for_for_acc_4_tmp[5]),
      lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign for_nand_5_nl = ~((main_5_for_for_for_acc_4_tmp[5]) & for_equal_tmp_10);
  assign for_for_and_31_nl = lfst_exit_main_5_for_for_1_lpi_1 & (~ exit_main_4_for_lpi_1_dfm_1_mx0w3);
  assign for_not_118_nl = ~ exit_main_5_for_lpi_1_dfm_1_mx0w4;
  assign for_for_and_32_nl = MUX_v_5_2_2(5'b00000, for_i_5_0_6_lpi_1_4_0, (for_not_118_nl));
  assign for_and_23_nl = exit_main_6_for_for_lpi_1_dfm_3 & for_equal_tmp_9;
  assign and_293_nl = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]) & (main_6_for_for_for_acc_4_tmp[5])
      & (main_6_for_for_acc_2_tmp[5]);
  assign mux_142_nl = MUX_s_1_2_2((and_293_nl), nor_155_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign or_159_nl = (~ for_equal_tmp_9) | (main_6_for_acc_1_tmp[5]) | nand_32_cse;
  assign and_125_nl = for_equal_tmp_9 & ((main_6_for_acc_1_tmp[5]) | nand_32_cse);
  assign mux_115_nl = MUX_s_1_2_2((or_159_nl), (and_125_nl), exit_main_5_for_lpi_1_dfm_1_mx0w4);
  assign and_286_nl = (main_6_for_for_for_acc_4_tmp[5]) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign mux_143_nl = MUX_s_1_2_2((and_286_nl), nor_155_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign for_nand_6_nl = ~((main_6_for_for_for_acc_4_tmp[5]) & for_equal_tmp_9);
  assign for_for_and_34_nl = lfst_exit_main_6_for_for_1_lpi_1 & (~ exit_main_5_for_lpi_1_dfm_1_mx0w4);
  assign for_not_119_nl = ~ exit_main_6_for_lpi_1_dfm_1_mx0w5;
  assign for_for_and_35_nl = MUX_v_5_2_2(5'b00000, for_i_5_0_7_lpi_1_4_0, (for_not_119_nl));
  assign for_and_25_nl = and_292_cse & for_equal_tmp_8;
  assign mux_144_nl = MUX_s_1_2_2(and_291_cse, and_292_cse, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign or_161_nl = (~ for_equal_tmp_8) | (main_7_for_acc_1_tmp[5]) | nand_31_cse;
  assign and_126_nl = for_equal_tmp_8 & ((main_7_for_acc_1_tmp[5]) | nand_31_cse);
  assign mux_116_nl = MUX_s_1_2_2((or_161_nl), (and_126_nl), exit_main_6_for_lpi_1_dfm_1_mx0w5);
  assign mux_145_nl = MUX_s_1_2_2(and_291_cse, (main_7_for_for_for_acc_4_tmp[5]),
      lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign for_nand_7_nl = ~((main_7_for_for_for_acc_4_tmp[5]) & for_equal_tmp_8);
  assign for_for_and_37_nl = lfst_exit_main_7_for_for_1_lpi_1 & (~ exit_main_6_for_lpi_1_dfm_1_mx0w5);
  assign for_not_120_nl = ~ exit_main_7_for_lpi_1_dfm_1_mx0w6;
  assign for_for_and_38_nl = MUX_v_5_2_2(5'b00000, for_i_5_0_lpi_1_4_0, (for_not_120_nl));
  assign for_and_13_nl = exit_main_8_for_for_lpi_1_dfm_3 & for_equal_tmp_14;
  assign or_nl = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) | (~ lfst_exit_main_8_for_lpi_1_dfm_9_3)
      | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) | nand_40_cse;
  assign or_231_nl = (~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])) | lfst_exit_main_8_for_lpi_1_dfm_9_3
      | (~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) & (main_7_for_acc_1_tmp[5])
      & (main_7_for_for_for_acc_4_tmp[5]) & (main_7_for_for_acc_2_tmp[5])));
  assign mux_146_nl = MUX_s_1_2_2((or_nl), (or_231_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign or_163_nl = (~ for_equal_tmp_14) | (main_8_for_acc_1_tmp[5]) | nand_40_cse;
  assign and_127_nl = for_equal_tmp_14 & ((main_8_for_acc_1_tmp[5]) | nand_40_cse);
  assign mux_117_nl = MUX_s_1_2_2((or_163_nl), (and_127_nl), exit_main_7_for_lpi_1_dfm_1_mx0w6);
  assign or_229_nl = (~ (main_8_for_for_for_acc_4_tmp[5])) | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b00)
      | (~ lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign or_230_nl = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b11) | lfst_exit_main_8_for_lpi_1_dfm_9_3
      | (~((main_7_for_acc_1_tmp[5]) & (main_7_for_for_for_acc_4_tmp[5]) & (main_7_for_for_acc_2_tmp[5])));
  assign mux_147_nl = MUX_s_1_2_2((or_229_nl), (or_230_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign for_nand_nl = ~((main_8_for_for_for_acc_4_tmp[5]) & for_equal_tmp_14);
  assign for_for_and_40_nl = lfst_exit_main_8_for_for_1_lpi_1 & (~ exit_main_7_for_lpi_1_dfm_1_mx0w6);
  assign or_50_nl = and_291_cse | (for_mux1h_64_tmp!=3'b000);
  assign or_49_nl = and_85_cse | (for_mux1h_64_tmp!=3'b000);
  assign mux_61_nl = MUX_s_1_2_2((or_50_nl), (or_49_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_62_nl = MUX_s_1_2_2(or_195_cse, (mux_61_nl), and_86_cse);
  assign or_48_nl = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0!=3'b000) | (~((main_8_for_acc_1_tmp[5])
      & (main_8_for_for_acc_2_tmp[5]) & (main_8_for_for_for_acc_4_tmp[5])));
  assign mux_63_nl = MUX_s_1_2_2((mux_62_nl), (or_48_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign asn_for_i_5_0_1_lpi_1_4_0_for_nor_nl = ~((~ exit_main_1_for_for_lpi_1_dfm_3)
      | for_equal_tmp_13 | for_equal_tmp_12 | for_equal_tmp_11 | for_equal_tmp_10
      | for_equal_tmp_9 | for_equal_tmp_8 | for_equal_tmp_14 | for_nor_tmp_2);
  assign nand_27_nl = ~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) & (main_5_for_acc_1_tmp[5])
      & (main_5_for_for_acc_2_tmp[5]) & (main_5_for_for_for_acc_4_tmp[5]));
  assign mux_148_nl = MUX_s_1_2_2((nand_27_nl), (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]),
      lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign or_214_nl = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b10);
  assign or_213_nl = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) | nand_44_cse;
  assign mux_149_nl = MUX_s_1_2_2((or_214_nl), (or_213_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign nand_24_nl = ~((main_1_for_acc_1_tmp[5]) & (main_1_for_for_acc_2_tmp[5])
      & (main_1_for_for_for_acc_4_tmp[5]));
  assign mux_150_nl = MUX_s_1_2_2((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]), (nand_24_nl),
      or_89_cse);
  assign nand_25_nl = ~(exitL_exit_main_8_for_sva & (main_1_for_acc_1_tmp[5]) & (main_1_for_for_acc_2_tmp[5])
      & (main_1_for_for_for_acc_4_tmp[5]));
  assign mux_151_nl = MUX_s_1_2_2((mux_150_nl), (nand_25_nl), or_167_cse);
  assign or_227_nl = (~ lfst_exit_main_8_for_lpi_1_dfm_9_3) | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b00);
  assign or_226_nl = lfst_exit_main_8_for_lpi_1_dfm_9_3 | (~((lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]==2'b11)
      & (main_7_for_acc_1_tmp[5]) & (main_7_for_for_acc_2_tmp[5]) & (main_7_for_for_for_acc_4_tmp[5])));
  assign mux_152_nl = MUX_s_1_2_2((or_227_nl), (or_226_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_93_nl = MUX_s_1_2_2(mux_tmp_84, lfst_exit_main_1_for_for_1_lpi_1, or_171_cse);
  assign or_86_nl = (for_mux1h_64_tmp!=3'b000) | (~ for_nor_tmp_2) | lfst_exit_main_1_for_for_1_lpi_1;
  assign mux_92_nl = MUX_s_1_2_2(lfst_exit_main_1_for_for_1_lpi_1, (or_86_nl), or_3_cse);
  assign mux_94_nl = MUX_s_1_2_2((mux_93_nl), (mux_92_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_95_nl = MUX_s_1_2_2((mux_94_nl), mux_tmp_84, exitL_exit_main_8_for_sva);
  assign mux_25_nl = MUX_s_1_2_2(exit_main_1_for_for_lpi_1_dfm_3, (~ lfst_exit_main_1_for_for_1_lpi_1),
      or_171_cse);
  assign mux_26_nl = MUX_s_1_2_2((mux_25_nl), (~ lfst_exit_main_1_for_for_1_lpi_1),
      lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_27_nl = MUX_s_1_2_2((mux_26_nl), exit_main_1_for_for_lpi_1_dfm_3, exitL_exit_main_8_for_sva);
  assign mux_35_nl = MUX_s_1_2_2(lfst_exit_main_2_for_for_1_lpi_1, nor_tmp_8, lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_36_nl = MUX_s_1_2_2((mux_35_nl), mux_tmp_25, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign mux_37_nl = MUX_s_1_2_2((mux_36_nl), lfst_exit_main_2_for_for_1_lpi_1, exitL_exit_main_8_for_sva);
  assign mux_32_nl = MUX_s_1_2_2(nor_tmp_7, nor_tmp_8, lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_33_nl = MUX_s_1_2_2((mux_32_nl), mux_tmp_25, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign mux_34_nl = MUX_s_1_2_2((mux_33_nl), nor_tmp_5, exitL_exit_main_8_for_sva);
  assign mux_38_nl = MUX_s_1_2_2((mux_37_nl), (mux_34_nl), and_298_cse);
  assign and_87_nl = (~((main_7_for_acc_1_tmp[5]) & (main_7_for_for_acc_2_tmp[5])
      & (main_7_for_for_for_acc_4_tmp[5]) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0==3'b111)
      & (~ for_nor_tmp_2))) & lfst_exit_main_8_for_for_1_lpi_1;
  assign nand_1_nl = ~((main_8_for_for_acc_2_tmp[5]) & (main_8_for_for_for_acc_4_tmp[5])
      & (~ nor_tmp_27));
  assign mux_58_nl = MUX_s_1_2_2((nand_1_nl), nor_tmp_27, or_3_cse);
  assign mux_59_nl = MUX_s_1_2_2((and_87_nl), (mux_58_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign mux_60_nl = MUX_s_1_2_2((mux_59_nl), lfst_exit_main_8_for_for_1_lpi_1, exitL_exit_main_8_for_sva);
  assign and_88_nl = ((~ (main_6_for_acc_1_tmp[5])) | (~ (main_6_for_for_acc_2_tmp[5]))
      | (~ (main_6_for_for_for_acc_4_tmp[5])) | for_nor_tmp_2 | exitL_exit_main_8_for_sva)
      & lfst_exit_main_7_for_for_1_lpi_1;
  assign or_42_nl = (~ exitL_exit_main_8_for_sva) | lfst_exit_main_7_for_for_1_lpi_1;
  assign and_89_nl = or_tmp_21 & lfst_exit_main_7_for_for_1_lpi_1;
  assign mux_54_nl = MUX_s_1_2_2((or_42_nl), (and_89_nl), and_292_cse);
  assign mux_55_nl = MUX_s_1_2_2((and_88_nl), (mux_54_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_56_nl = MUX_s_1_2_2(lfst_exit_main_7_for_for_1_lpi_1, (mux_55_nl), and_86_cse);
  assign and_92_nl = or_142_cse & lfst_exit_main_7_for_for_1_lpi_1;
  assign mux_57_nl = MUX_s_1_2_2((mux_56_nl), (and_92_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign and_93_nl = (~((main_5_for_acc_1_tmp[5]) & (main_5_for_for_acc_2_tmp[5])
      & (main_5_for_for_for_acc_4_tmp[5]) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0])
      & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]) & (~ for_nor_tmp_2) & (~ exitL_exit_main_8_for_sva)))
      & lfst_exit_main_6_for_for_1_lpi_1;
  assign or_37_nl = (~((~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])) | exitL_exit_main_8_for_sva))
      | lfst_exit_main_6_for_for_1_lpi_1;
  assign and_94_nl = ((~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2])) | for_nor_tmp_2
      | exitL_exit_main_8_for_sva) & lfst_exit_main_6_for_for_1_lpi_1;
  assign mux_50_nl = MUX_s_1_2_2((or_37_nl), (and_94_nl), exit_main_6_for_for_lpi_1_dfm_3);
  assign mux_51_nl = MUX_s_1_2_2((mux_50_nl), lfst_exit_main_6_for_for_1_lpi_1, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign mux_52_nl = MUX_s_1_2_2((and_93_nl), (mux_51_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1]);
  assign and_96_nl = or_142_cse & lfst_exit_main_6_for_for_1_lpi_1;
  assign mux_53_nl = MUX_s_1_2_2((mux_52_nl), (and_96_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign and_97_nl = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]) & (~(and_295_cse |
      (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b10) | exitL_exit_main_8_for_sva));
  assign or_30_nl = (~ (main_4_for_acc_1_tmp[5])) | (~ (main_4_for_for_acc_2_tmp[5]))
      | (~ (main_4_for_for_for_acc_4_tmp[5])) | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b10)
      | exitL_exit_main_8_for_sva;
  assign or_29_nl = (~ (main_5_for_for_acc_2_tmp[5])) | (~ (main_5_for_for_for_acc_4_tmp[5]))
      | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b10) | exitL_exit_main_8_for_sva;
  assign mux_47_nl = MUX_s_1_2_2((or_30_nl), (or_29_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign or_31_nl = for_nor_tmp_2 | (mux_47_nl);
  assign mux_48_nl = MUX_s_1_2_2((and_97_nl), (or_31_nl), lfst_exit_main_5_for_for_1_lpi_1);
  assign and_2_nl = lfst_exit_main_5_for_for_1_lpi_1 & or_142_cse;
  assign mux_49_nl = MUX_s_1_2_2((mux_48_nl), (and_2_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign and_99_nl = (~((main_3_for_acc_1_tmp[5]) & (main_3_for_for_acc_2_tmp[5])
      & (main_3_for_for_for_acc_4_tmp[5]) & (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1:0]==2'b11)
      & (~ for_nor_tmp_2) & (~ exitL_exit_main_8_for_sva))) & lfst_exit_main_4_for_for_1_lpi_1;
  assign or_24_nl = (~ exitL_exit_main_8_for_sva) | lfst_exit_main_4_for_for_1_lpi_1;
  assign and_100_nl = or_tmp_21 & lfst_exit_main_4_for_for_1_lpi_1;
  assign mux_43_nl = MUX_s_1_2_2((or_24_nl), (and_100_nl), exit_main_4_for_for_lpi_1_dfm_3);
  assign or_22_nl = (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1:0]!=2'b00);
  assign mux_44_nl = MUX_s_1_2_2((mux_43_nl), lfst_exit_main_4_for_for_1_lpi_1, or_22_nl);
  assign mux_45_nl = MUX_s_1_2_2((and_99_nl), (mux_44_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]);
  assign and_102_nl = or_142_cse & lfst_exit_main_4_for_for_1_lpi_1;
  assign mux_46_nl = MUX_s_1_2_2((mux_45_nl), (and_102_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);
  assign and_103_nl = ((~ (main_2_for_acc_1_tmp[5])) | (~ (main_2_for_for_acc_2_tmp[5]))
      | (~ (main_2_for_for_for_acc_4_tmp[5])) | (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2:1]!=2'b01)
      | for_nor_tmp_2 | exitL_exit_main_8_for_sva) & lfst_exit_main_3_for_for_1_lpi_1;
  assign or_18_nl = (~((~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1])) | exitL_exit_main_8_for_sva))
      | lfst_exit_main_3_for_for_1_lpi_1;
  assign and_104_nl = ((~ (lfst_exit_main_8_for_lpi_1_dfm_9_2_0[1])) | for_nor_tmp_2
      | exitL_exit_main_8_for_sva) & lfst_exit_main_3_for_for_1_lpi_1;
  assign mux_39_nl = MUX_s_1_2_2((or_18_nl), (and_104_nl), and_297_cse);
  assign mux_40_nl = MUX_s_1_2_2((mux_39_nl), lfst_exit_main_3_for_for_1_lpi_1, lfst_exit_main_8_for_lpi_1_dfm_9_2_0[2]);
  assign mux_41_nl = MUX_s_1_2_2((and_103_nl), (mux_40_nl), lfst_exit_main_8_for_lpi_1_dfm_9_2_0[0]);
  assign and_106_nl = or_142_cse & lfst_exit_main_3_for_for_1_lpi_1;
  assign mux_42_nl = MUX_s_1_2_2((mux_41_nl), (and_106_nl), lfst_exit_main_8_for_lpi_1_dfm_9_3);

  function automatic [0:0] MUX1HOT_s_1_8_2;
    input [0:0] input_7;
    input [0:0] input_6;
    input [0:0] input_5;
    input [0:0] input_4;
    input [0:0] input_3;
    input [0:0] input_2;
    input [0:0] input_1;
    input [0:0] input_0;
    input [7:0] sel;
    reg [0:0] result;
  begin
    result = input_0 & {1{sel[0]}};
    result = result | ( input_1 & {1{sel[1]}});
    result = result | ( input_2 & {1{sel[2]}});
    result = result | ( input_3 & {1{sel[3]}});
    result = result | ( input_4 & {1{sel[4]}});
    result = result | ( input_5 & {1{sel[5]}});
    result = result | ( input_6 & {1{sel[6]}});
    result = result | ( input_7 & {1{sel[7]}});
    MUX1HOT_s_1_8_2 = result;
  end
  endfunction


  function automatic [31:0] MUX1HOT_v_32_3_2;
    input [31:0] input_2;
    input [31:0] input_1;
    input [31:0] input_0;
    input [2:0] sel;
    reg [31:0] result;
  begin
    result = input_0 & {32{sel[0]}};
    result = result | ( input_1 & {32{sel[1]}});
    result = result | ( input_2 & {32{sel[2]}});
    MUX1HOT_v_32_3_2 = result;
  end
  endfunction


  function automatic [31:0] MUX1HOT_v_32_8_2;
    input [31:0] input_7;
    input [31:0] input_6;
    input [31:0] input_5;
    input [31:0] input_4;
    input [31:0] input_3;
    input [31:0] input_2;
    input [31:0] input_1;
    input [31:0] input_0;
    input [7:0] sel;
    reg [31:0] result;
  begin
    result = input_0 & {32{sel[0]}};
    result = result | ( input_1 & {32{sel[1]}});
    result = result | ( input_2 & {32{sel[2]}});
    result = result | ( input_3 & {32{sel[3]}});
    result = result | ( input_4 & {32{sel[4]}});
    result = result | ( input_5 & {32{sel[5]}});
    result = result | ( input_6 & {32{sel[6]}});
    result = result | ( input_7 & {32{sel[7]}});
    MUX1HOT_v_32_8_2 = result;
  end
  endfunction


  function automatic [2:0] MUX1HOT_v_3_6_2;
    input [2:0] input_5;
    input [2:0] input_4;
    input [2:0] input_3;
    input [2:0] input_2;
    input [2:0] input_1;
    input [2:0] input_0;
    input [5:0] sel;
    reg [2:0] result;
  begin
    result = input_0 & {3{sel[0]}};
    result = result | ( input_1 & {3{sel[1]}});
    result = result | ( input_2 & {3{sel[2]}});
    result = result | ( input_3 & {3{sel[3]}});
    result = result | ( input_4 & {3{sel[4]}});
    result = result | ( input_5 & {3{sel[5]}});
    MUX1HOT_v_3_6_2 = result;
  end
  endfunction


  function automatic [4:0] MUX1HOT_v_5_3_2;
    input [4:0] input_2;
    input [4:0] input_1;
    input [4:0] input_0;
    input [2:0] sel;
    reg [4:0] result;
  begin
    result = input_0 & {5{sel[0]}};
    result = result | ( input_1 & {5{sel[1]}});
    result = result | ( input_2 & {5{sel[2]}});
    MUX1HOT_v_5_3_2 = result;
  end
  endfunction


  function automatic [4:0] MUX1HOT_v_5_8_2;
    input [4:0] input_7;
    input [4:0] input_6;
    input [4:0] input_5;
    input [4:0] input_4;
    input [4:0] input_3;
    input [4:0] input_2;
    input [4:0] input_1;
    input [4:0] input_0;
    input [7:0] sel;
    reg [4:0] result;
  begin
    result = input_0 & {5{sel[0]}};
    result = result | ( input_1 & {5{sel[1]}});
    result = result | ( input_2 & {5{sel[2]}});
    result = result | ( input_3 & {5{sel[3]}});
    result = result | ( input_4 & {5{sel[4]}});
    result = result | ( input_5 & {5{sel[5]}});
    result = result | ( input_6 & {5{sel[6]}});
    result = result | ( input_7 & {5{sel[7]}});
    MUX1HOT_v_5_8_2 = result;
  end
  endfunction


  function automatic [0:0] MUX_s_1_2_2;
    input [0:0] input_0;
    input [0:0] input_1;
    input [0:0] sel;
    reg [0:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [1:0] MUX_v_2_2_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input [0:0] sel;
    reg [1:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_2_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [0:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [2:0] MUX_v_3_2_2;
    input [2:0] input_0;
    input [2:0] input_1;
    input [0:0] sel;
    reg [2:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_3_2_2 = result;
  end
  endfunction


  function automatic [4:0] MUX_v_5_2_2;
    input [4:0] input_0;
    input [4:0] input_1;
    input [0:0] sel;
    reg [4:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_5_2_2 = result;
  end
  endfunction


  function automatic [4:0] signext_5_1;
    input [0:0] vector;
  begin
    signext_5_1= {{4{vector[0]}}, vector};
  end
  endfunction


  function automatic [31:0] conv_u2s_1_32 ;
    input [0:0]  vector ;
  begin
    conv_u2s_1_32 = {{31{1'b0}}, vector};
  end
  endfunction


  function automatic [5:0] conv_u2s_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2s_5_6 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    matrix_mul
// ------------------------------------------------------------------


module matrix_mul (
  clk, rst, A_rsc_adr, A_rsc_d, A_rsc_we, A_rsc_q, A_rsc_triosy_lz, B_rsc_adr, B_rsc_d,
      B_rsc_we, B_rsc_q, B_rsc_triosy_lz, C_rsc_adr, C_rsc_d, C_rsc_we, C_rsc_q,
      C_rsc_triosy_lz
);
  input clk;
  input rst;
  output [9:0] A_rsc_adr;
  output [31:0] A_rsc_d;
  output A_rsc_we;
  input [31:0] A_rsc_q;
  output A_rsc_triosy_lz;
  output [9:0] B_rsc_adr;
  output [31:0] B_rsc_d;
  output B_rsc_we;
  input [31:0] B_rsc_q;
  output B_rsc_triosy_lz;
  output [9:0] C_rsc_adr;
  output [31:0] C_rsc_d;
  output C_rsc_we;
  input [31:0] C_rsc_q;
  output C_rsc_triosy_lz;


  // Interconnect Declarations
  wire [9:0] A_rsci_adr_d;
  wire [31:0] A_rsci_q_d;
  wire [9:0] B_rsci_adr_d;
  wire [31:0] B_rsci_q_d;
  wire [9:0] C_rsci_adr_d;
  wire [31:0] C_rsci_d_d;
  wire [31:0] C_rsci_q_d;
  wire A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff;
  wire C_rsci_we_d_iff;


  // Interconnect Declarations for Component Instantiations 
  matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_1_32_10_1024_1024_32_5_gen
      A_rsci (
      .q(A_rsc_q),
      .we(A_rsc_we),
      .d(A_rsc_d),
      .adr(A_rsc_adr),
      .adr_d(A_rsci_adr_d),
      .d_d(32'b00000000000000000000000000000000),
      .we_d(1'b0),
      .q_d(A_rsci_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff),
      .port_0_rw_ram_ir_internal_WMASK_B_d(1'b0)
    );
  matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_2_32_10_1024_1024_32_5_gen
      B_rsci (
      .q(B_rsc_q),
      .we(B_rsc_we),
      .d(B_rsc_d),
      .adr(B_rsc_adr),
      .adr_d(B_rsci_adr_d),
      .d_d(32'b00000000000000000000000000000000),
      .we_d(1'b0),
      .q_d(B_rsci_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff),
      .port_0_rw_ram_ir_internal_WMASK_B_d(1'b0)
    );
  matrix_mul_ccs_sample_mem_ccs_ram_sync_singleport_rwport_3_32_10_1024_1024_32_5_gen
      C_rsci (
      .q(C_rsc_q),
      .we(C_rsc_we),
      .d(C_rsc_d),
      .adr(C_rsc_adr),
      .adr_d(C_rsci_adr_d),
      .d_d(C_rsci_d_d),
      .we_d(C_rsci_we_d_iff),
      .q_d(C_rsci_q_d),
      .port_0_rw_ram_ir_internal_RMASK_B_d(1'b0),
      .port_0_rw_ram_ir_internal_WMASK_B_d(C_rsci_we_d_iff)
    );
  matrix_mul_core matrix_mul_core_inst (
      .clk(clk),
      .rst(rst),
      .A_rsc_triosy_lz(A_rsc_triosy_lz),
      .B_rsc_triosy_lz(B_rsc_triosy_lz),
      .C_rsc_triosy_lz(C_rsc_triosy_lz),
      .A_rsci_adr_d(A_rsci_adr_d),
      .A_rsci_q_d(A_rsci_q_d),
      .B_rsci_adr_d(B_rsci_adr_d),
      .B_rsci_q_d(B_rsci_q_d),
      .C_rsci_adr_d(C_rsci_adr_d),
      .C_rsci_d_d(C_rsci_d_d),
      .A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_pff(A_rsci_port_0_rw_ram_ir_internal_RMASK_B_d_iff),
      .C_rsci_we_d_pff(C_rsci_we_d_iff)
    );
endmodule



