// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4a/835166 Production Release
//  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
// 
//  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
//  Generated date: Mon Dec  1 01:44:24 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    conv_fixed_core
// ------------------------------------------------------------------


module conv_fixed_core (
  clk, rst, input_rsc_dat, input_rsc_triosy_lz, output_rsc_dat, output_rsc_triosy_lz,
      filter_rsc_dat, filter_rsc_triosy_lz
);
  input clk;
  input rst;
  input [143:0] input_rsc_dat;
  output input_rsc_triosy_lz;
  output [15:0] output_rsc_dat;
  output output_rsc_triosy_lz;
  input [143:0] filter_rsc_dat;
  output filter_rsc_triosy_lz;


  // Interconnect Declarations
  wire [143:0] input_rsci_idat;
  reg [15:0] output_rsci_idat;
  wire [19:0] nl_output_rsci_idat;
  wire [143:0] filter_rsci_idat;
  wire [3:0] sum_acc_tmp;
  wire [4:0] nl_sum_acc_tmp;
  wire or_dcpl_20;
  wire or_dcpl_21;
  wire or_dcpl_22;
  wire or_dcpl_24;
  wire or_dcpl_27;
  wire or_dcpl_28;
  wire or_dcpl_30;
  reg [3:0] sum_i_3_0_sva_1;
  reg exitL_exit_sum_sva;
  reg reg_input_rsc_triosy_obj_ld_cse;
  reg [15:0] temp_4_sva_1;
  reg [15:0] temp_3_sva_1;
  reg [15:0] temp_5_sva_1;
  reg [15:0] temp_2_sva_1;
  reg [15:0] temp_6_sva_1;
  reg [15:0] temp_1_sva_1;
  reg [15:0] temp_7_sva_1;
  reg [15:0] temp_0_sva_1;
  wire [15:0] temp_7_sva_1_mx0;
  wire [15:0] temp_0_sva_1_mx0;
  wire [15:0] temp_1_sva_1_mx0;
  wire [15:0] temp_2_sva_1_mx0;
  wire [15:0] temp_3_sva_1_mx0;
  wire [15:0] temp_4_sva_1_mx0;
  wire [15:0] temp_5_sva_1_mx0;
  wire [15:0] temp_6_sva_1_mx0;
  wire [3:0] sum_i_3_0_lpi_1_dfm_1;
  wire nor_12_cse;
  wire nand_3_cse;
  wire nor_8_cse;
  wire or_16_cse;
  wire [15:0] sum_mul_itm_23_8;

  wire[0:0] mux_2_nl;
  wire[0:0] mux_1_nl;
  wire[0:0] nor_13_nl;
  wire[0:0] nor_14_nl;
  wire[0:0] nor_15_nl;
  wire[0:0] or_40_nl;
  wire[0:0] or_39_nl;
  wire[0:0] mux_nl;
  wire[0:0] or_23_nl;
  wire[23:0] sum_mul_nl;
  wire signed [31:0] nl_sum_mul_nl;
  wire[15:0] sum_mux_19_nl;
  wire[15:0] sum_mux_20_nl;
  wire[0:0] asn_temp_0_sva_1_nor_nl;
  wire[0:0] or_29_nl;
  wire[0:0] or_31_nl;
  wire[0:0] or_32_nl;
  wire[0:0] or_33_nl;
  wire[0:0] or_34_nl;
  wire[0:0] or_35_nl;
  wire[0:0] sum_not_nl;

  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd144)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd16)) output_rsci (
      .idat(output_rsci_idat),
      .dat(output_rsc_dat)
    );
  ccs_in_v1 #(.rscid(32'sd3),
  .width(32'sd144)) filter_rsci (
      .dat(filter_rsc_dat),
      .idat(filter_rsci_idat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_rsc_triosy_obj (
      .ld(reg_input_rsc_triosy_obj_ld_cse),
      .lz(input_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) output_rsc_triosy_obj (
      .ld(reg_input_rsc_triosy_obj_ld_cse),
      .lz(output_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) filter_rsc_triosy_obj (
      .ld(reg_input_rsc_triosy_obj_ld_cse),
      .lz(filter_rsc_triosy_lz)
    );
  assign nand_3_cse = ~((sum_acc_tmp[1:0]==2'b11));
  assign nor_12_cse = ~(exitL_exit_sum_sva | (sum_i_3_0_sva_1[2]));
  assign nor_8_cse = ~((sum_i_3_0_sva_1[0]) | (sum_i_3_0_sva_1[3]));
  assign or_16_cse = (sum_acc_tmp!=4'b1001);
  assign or_23_nl = or_dcpl_22 | or_dcpl_20;
  assign temp_7_sva_1_mx0 = MUX_v_16_2_2(sum_mul_itm_23_8, temp_7_sva_1, or_23_nl);
  assign sum_mux_19_nl = MUX_v_16_9_2((filter_rsci_idat[15:0]), (filter_rsci_idat[31:16]),
      (filter_rsci_idat[47:32]), (filter_rsci_idat[63:48]), (filter_rsci_idat[79:64]),
      (filter_rsci_idat[95:80]), (filter_rsci_idat[111:96]), (filter_rsci_idat[127:112]),
      (filter_rsci_idat[143:128]), sum_i_3_0_lpi_1_dfm_1);
  assign sum_mux_20_nl = MUX_v_16_9_2((input_rsci_idat[15:0]), (input_rsci_idat[31:16]),
      (input_rsci_idat[47:32]), (input_rsci_idat[63:48]), (input_rsci_idat[79:64]),
      (input_rsci_idat[95:80]), (input_rsci_idat[111:96]), (input_rsci_idat[127:112]),
      (input_rsci_idat[143:128]), sum_i_3_0_lpi_1_dfm_1);
  assign nl_sum_mul_nl = $signed((sum_mux_19_nl)) * $signed((sum_mux_20_nl));
  assign sum_mul_nl = nl_sum_mul_nl[23:0];
  assign sum_mul_itm_23_8 = readslicef_24_16_8((sum_mul_nl));
  assign asn_temp_0_sva_1_nor_nl = ~((~((sum_i_3_0_sva_1[3:2]!=2'b00) | or_dcpl_24))
      | exitL_exit_sum_sva);
  assign temp_0_sva_1_mx0 = MUX_v_16_2_2(sum_mul_itm_23_8, temp_0_sva_1, asn_temp_0_sva_1_nor_nl);
  assign or_29_nl = or_dcpl_28 | or_dcpl_27;
  assign temp_1_sva_1_mx0 = MUX_v_16_2_2(sum_mul_itm_23_8, temp_1_sva_1, or_29_nl);
  assign or_31_nl = or_dcpl_28 | or_dcpl_30;
  assign temp_2_sva_1_mx0 = MUX_v_16_2_2(sum_mul_itm_23_8, temp_2_sva_1, or_31_nl);
  assign or_32_nl = or_dcpl_28 | or_dcpl_20;
  assign temp_3_sva_1_mx0 = MUX_v_16_2_2(sum_mul_itm_23_8, temp_3_sva_1, or_32_nl);
  assign or_33_nl = or_dcpl_22 | or_dcpl_24;
  assign temp_4_sva_1_mx0 = MUX_v_16_2_2(sum_mul_itm_23_8, temp_4_sva_1, or_33_nl);
  assign or_34_nl = or_dcpl_22 | or_dcpl_27;
  assign temp_5_sva_1_mx0 = MUX_v_16_2_2(sum_mul_itm_23_8, temp_5_sva_1, or_34_nl);
  assign or_35_nl = or_dcpl_22 | or_dcpl_30;
  assign temp_6_sva_1_mx0 = MUX_v_16_2_2(sum_mul_itm_23_8, temp_6_sva_1, or_35_nl);
  assign nl_sum_acc_tmp = sum_i_3_0_lpi_1_dfm_1 + 4'b0001;
  assign sum_acc_tmp = nl_sum_acc_tmp[3:0];
  assign sum_not_nl = ~ exitL_exit_sum_sva;
  assign sum_i_3_0_lpi_1_dfm_1 = MUX_v_4_2_2(4'b0000, sum_i_3_0_sva_1, (sum_not_nl));
  assign or_dcpl_20 = ~((sum_i_3_0_sva_1[1:0]==2'b11));
  assign or_dcpl_21 = exitL_exit_sum_sva | (sum_i_3_0_sva_1[3]);
  assign or_dcpl_22 = or_dcpl_21 | (~ (sum_i_3_0_sva_1[2]));
  assign or_dcpl_24 = (sum_i_3_0_sva_1[1:0]!=2'b00);
  assign or_dcpl_27 = (sum_i_3_0_sva_1[1:0]!=2'b01);
  assign or_dcpl_28 = or_dcpl_21 | (sum_i_3_0_sva_1[2]);
  assign or_dcpl_30 = (sum_i_3_0_sva_1[1:0]!=2'b10);
  always @(posedge clk) begin
    if ( rst ) begin
      reg_input_rsc_triosy_obj_ld_cse <= 1'b0;
      exitL_exit_sum_sva <= 1'b1;
    end
    else begin
      reg_input_rsc_triosy_obj_ld_cse <= ~ or_16_cse;
      exitL_exit_sum_sva <= (sum_acc_tmp==4'b1001);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      output_rsci_idat <= 16'b0000000000000000;
    end
    else if ( ~ or_16_cse ) begin
      output_rsci_idat <= nl_output_rsci_idat[15:0];
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_7_sva_1 <= 16'b0000000000000000;
    end
    else if ( (nand_3_cse | (sum_acc_tmp[3:2]!=2'b01)) & (sum_i_3_0_sva_1[1]) & (sum_i_3_0_sva_1[0])
        & (~ (sum_i_3_0_sva_1[3])) & (~ exitL_exit_sum_sva) & (sum_i_3_0_sva_1[2])
        ) begin
      temp_7_sva_1 <= temp_7_sva_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_0_sva_1 <= 16'b0000000000000000;
    end
    else if ( MUX_s_1_2_2((mux_2_nl), (or_39_nl), exitL_exit_sum_sva) ) begin
      temp_0_sva_1 <= temp_0_sva_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_1_sva_1 <= 16'b0000000000000000;
    end
    else if ( (~((~((sum_acc_tmp!=4'b0001))) | (sum_i_3_0_sva_1[1]))) & (sum_i_3_0_sva_1[0])
        & (~ (sum_i_3_0_sva_1[3])) & nor_12_cse ) begin
      temp_1_sva_1 <= temp_1_sva_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_2_sva_1 <= 16'b0000000000000000;
    end
    else if ( ((sum_acc_tmp!=4'b0010)) & (sum_i_3_0_sva_1[1]) & nor_8_cse & nor_12_cse
        ) begin
      temp_2_sva_1 <= temp_2_sva_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_3_sva_1 <= 16'b0000000000000000;
    end
    else if ( (nand_3_cse | (sum_acc_tmp[3:2]!=2'b00)) & (sum_i_3_0_sva_1[1]) & (sum_i_3_0_sva_1[0])
        & (~ (sum_i_3_0_sva_1[3])) & nor_12_cse ) begin
      temp_3_sva_1 <= temp_3_sva_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_4_sva_1 <= 16'b0000000000000000;
    end
    else if ( (~((~((sum_acc_tmp!=4'b0100))) | (sum_i_3_0_sva_1[1]))) & nor_8_cse
        & (~ exitL_exit_sum_sva) & (sum_i_3_0_sva_1[2]) ) begin
      temp_4_sva_1 <= temp_4_sva_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_5_sva_1 <= 16'b0000000000000000;
    end
    else if ( (~((~((sum_acc_tmp!=4'b0101))) | (sum_i_3_0_sva_1[1]))) & (sum_i_3_0_sva_1[0])
        & (~ (sum_i_3_0_sva_1[3])) & (~ exitL_exit_sum_sva) & (sum_i_3_0_sva_1[2])
        ) begin
      temp_5_sva_1 <= temp_5_sva_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      temp_6_sva_1 <= 16'b0000000000000000;
    end
    else if ( ((sum_acc_tmp!=4'b0110)) & (sum_i_3_0_sva_1[1]) & nor_8_cse & (~ exitL_exit_sum_sva)
        & (sum_i_3_0_sva_1[2]) ) begin
      temp_6_sva_1 <= temp_6_sva_1_mx0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      sum_i_3_0_sva_1 <= 4'b0000;
    end
    else if ( or_16_cse ) begin
      sum_i_3_0_sva_1 <= sum_acc_tmp;
    end
  end
  assign nl_output_rsci_idat  = temp_3_sva_1_mx0 + temp_4_sva_1_mx0 + temp_0_sva_1_mx0
      + temp_7_sva_1_mx0 + sum_mul_itm_23_8 + temp_1_sva_1_mx0 + temp_2_sva_1_mx0
      + temp_5_sva_1_mx0 + temp_6_sva_1_mx0;
  assign nor_13_nl = ~((~ (sum_acc_tmp[0])) | (sum_i_3_0_sva_1!=4'b0000));
  assign nor_14_nl = ~((sum_acc_tmp[0]) | (sum_i_3_0_sva_1!=4'b0000));
  assign mux_1_nl = MUX_s_1_2_2((nor_13_nl), (nor_14_nl), sum_acc_tmp[3]);
  assign nor_15_nl = ~((sum_i_3_0_sva_1!=4'b0000));
  assign or_40_nl = (sum_acc_tmp[2:1]!=2'b00);
  assign mux_2_nl = MUX_s_1_2_2((mux_1_nl), (nor_15_nl), or_40_nl);
  assign mux_nl = MUX_s_1_2_2((sum_acc_tmp[0]), (~ (sum_acc_tmp[0])), sum_acc_tmp[3]);
  assign or_39_nl = (sum_acc_tmp[2:1]!=2'b00) | (mux_nl);

  function automatic [0:0] MUX_s_1_2_2;
    input [0:0] input_0;
    input [0:0] input_1;
    input [0:0] sel;
    reg [0:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [15:0] MUX_v_16_2_2;
    input [15:0] input_0;
    input [15:0] input_1;
    input [0:0] sel;
    reg [15:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_16_2_2 = result;
  end
  endfunction


  function automatic [15:0] MUX_v_16_9_2;
    input [15:0] input_0;
    input [15:0] input_1;
    input [15:0] input_2;
    input [15:0] input_3;
    input [15:0] input_4;
    input [15:0] input_5;
    input [15:0] input_6;
    input [15:0] input_7;
    input [15:0] input_8;
    input [3:0] sel;
    reg [15:0] result;
  begin
    case (sel)
      4'b0000 : begin
        result = input_0;
      end
      4'b0001 : begin
        result = input_1;
      end
      4'b0010 : begin
        result = input_2;
      end
      4'b0011 : begin
        result = input_3;
      end
      4'b0100 : begin
        result = input_4;
      end
      4'b0101 : begin
        result = input_5;
      end
      4'b0110 : begin
        result = input_6;
      end
      4'b0111 : begin
        result = input_7;
      end
      default : begin
        result = input_8;
      end
    endcase
    MUX_v_16_9_2 = result;
  end
  endfunction


  function automatic [3:0] MUX_v_4_2_2;
    input [3:0] input_0;
    input [3:0] input_1;
    input [0:0] sel;
    reg [3:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_4_2_2 = result;
  end
  endfunction


  function automatic [15:0] readslicef_24_16_8;
    input [23:0] vector;
    reg [23:0] tmp;
  begin
    tmp = vector >> 8;
    readslicef_24_16_8 = tmp[15:0];
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    conv_fixed
// ------------------------------------------------------------------


module conv_fixed (
  clk, rst, input_rsc_dat, input_rsc_triosy_lz, output_rsc_dat, output_rsc_triosy_lz,
      filter_rsc_dat, filter_rsc_triosy_lz
);
  input clk;
  input rst;
  input [143:0] input_rsc_dat;
  output input_rsc_triosy_lz;
  output [15:0] output_rsc_dat;
  output output_rsc_triosy_lz;
  input [143:0] filter_rsc_dat;
  output filter_rsc_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  conv_fixed_core conv_fixed_core_inst (
      .clk(clk),
      .rst(rst),
      .input_rsc_dat(input_rsc_dat),
      .input_rsc_triosy_lz(input_rsc_triosy_lz),
      .output_rsc_dat(output_rsc_dat),
      .output_rsc_triosy_lz(output_rsc_triosy_lz),
      .filter_rsc_dat(filter_rsc_dat),
      .filter_rsc_triosy_lz(filter_rsc_triosy_lz)
    );
endmodule



