// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4a/835166 Production Release
//  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
// 
//  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
//  Generated date: Mon Dec  1 01:39:50 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    conv_core
// ------------------------------------------------------------------


module conv_core (
  clk, rst, input_rsc_dat, input_rsc_triosy_lz, output_rsc_dat, output_rsc_triosy_lz,
      filter_rsc_dat, filter_rsc_triosy_lz
);
  input clk;
  input rst;
  input [143:0] input_rsc_dat;
  output input_rsc_triosy_lz;
  output [15:0] output_rsc_dat;
  output output_rsc_triosy_lz;
  input [143:0] filter_rsc_dat;
  output filter_rsc_triosy_lz;


  // Interconnect Declarations
  wire [143:0] input_rsci_idat;
  reg [15:0] output_rsci_idat;
  wire [17:0] nl_output_rsci_idat;
  wire [143:0] filter_rsci_idat;
  reg output_rsc_triosy_obj_ld;
  reg reg_filter_rsc_triosy_obj_ld_cse;
  reg [15:0] acc_13_itm_1;
  wire [17:0] nl_acc_13_itm_1;
  reg [15:0] acc_12_itm_1;
  wire [16:0] nl_acc_12_itm_1;
  reg [15:0] acc_14_itm_1;
  wire [17:0] nl_acc_14_itm_1;

  wire[15:0] sum_1_sum_mul_1_nl;
  wire[31:0] nl_sum_1_sum_mul_1_nl;
  wire[15:0] sum_8_sum_mul_1_nl;
  wire[31:0] nl_sum_8_sum_mul_1_nl;
  wire[15:0] sum_9_sum_mul_1_nl;
  wire[31:0] nl_sum_9_sum_mul_1_nl;
  wire[15:0] sum_2_sum_mul_1_nl;
  wire[31:0] nl_sum_2_sum_mul_1_nl;
  wire[15:0] sum_3_sum_mul_1_nl;
  wire[31:0] nl_sum_3_sum_mul_1_nl;
  wire[15:0] sum_4_sum_mul_1_nl;
  wire[31:0] nl_sum_4_sum_mul_1_nl;
  wire[15:0] sum_5_sum_mul_1_nl;
  wire[31:0] nl_sum_5_sum_mul_1_nl;
  wire[15:0] sum_6_sum_mul_1_nl;
  wire[31:0] nl_sum_6_sum_mul_1_nl;
  wire[15:0] sum_7_sum_mul_1_nl;
  wire[31:0] nl_sum_7_sum_mul_1_nl;

  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd144)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd16)) output_rsci (
      .idat(output_rsci_idat),
      .dat(output_rsc_dat)
    );
  ccs_in_v1 #(.rscid(32'sd3),
  .width(32'sd144)) filter_rsci (
      .dat(filter_rsc_dat),
      .idat(filter_rsci_idat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_rsc_triosy_obj (
      .ld(reg_filter_rsc_triosy_obj_ld_cse),
      .lz(input_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) output_rsc_triosy_obj (
      .ld(output_rsc_triosy_obj_ld),
      .lz(output_rsc_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) filter_rsc_triosy_obj (
      .ld(reg_filter_rsc_triosy_obj_ld_cse),
      .lz(filter_rsc_triosy_lz)
    );
  always @(posedge clk) begin
    if ( rst ) begin
      output_rsc_triosy_obj_ld <= 1'b0;
      acc_13_itm_1 <= 16'b0000000000000000;
      acc_12_itm_1 <= 16'b0000000000000000;
      acc_14_itm_1 <= 16'b0000000000000000;
      reg_filter_rsc_triosy_obj_ld_cse <= 1'b0;
    end
    else begin
      output_rsc_triosy_obj_ld <= reg_filter_rsc_triosy_obj_ld_cse;
      acc_13_itm_1 <= nl_acc_13_itm_1[15:0];
      acc_12_itm_1 <= nl_acc_12_itm_1[15:0];
      acc_14_itm_1 <= nl_acc_14_itm_1[15:0];
      reg_filter_rsc_triosy_obj_ld_cse <= 1'b1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      output_rsci_idat <= 16'b0000000000000000;
    end
    else if ( reg_filter_rsc_triosy_obj_ld_cse ) begin
      output_rsci_idat <= nl_output_rsci_idat[15:0];
    end
  end
  assign nl_sum_1_sum_mul_1_nl = (filter_rsci_idat[15:0]) * (input_rsci_idat[15:0]);
  assign sum_1_sum_mul_1_nl = nl_sum_1_sum_mul_1_nl[15:0];
  assign nl_sum_8_sum_mul_1_nl = (filter_rsci_idat[127:112]) * (input_rsci_idat[127:112]);
  assign sum_8_sum_mul_1_nl = nl_sum_8_sum_mul_1_nl[15:0];
  assign nl_sum_9_sum_mul_1_nl = (filter_rsci_idat[143:128]) * (input_rsci_idat[143:128]);
  assign sum_9_sum_mul_1_nl = nl_sum_9_sum_mul_1_nl[15:0];
  assign nl_acc_13_itm_1  = (sum_1_sum_mul_1_nl) + (sum_8_sum_mul_1_nl) + (sum_9_sum_mul_1_nl);
  assign nl_sum_2_sum_mul_1_nl = (filter_rsci_idat[31:16]) * (input_rsci_idat[31:16]);
  assign sum_2_sum_mul_1_nl = nl_sum_2_sum_mul_1_nl[15:0];
  assign nl_sum_3_sum_mul_1_nl = (filter_rsci_idat[47:32]) * (input_rsci_idat[47:32]);
  assign sum_3_sum_mul_1_nl = nl_sum_3_sum_mul_1_nl[15:0];
  assign nl_acc_12_itm_1  = (sum_2_sum_mul_1_nl) + (sum_3_sum_mul_1_nl);
  assign nl_sum_4_sum_mul_1_nl = (filter_rsci_idat[63:48]) * (input_rsci_idat[63:48]);
  assign sum_4_sum_mul_1_nl = nl_sum_4_sum_mul_1_nl[15:0];
  assign nl_sum_5_sum_mul_1_nl = (filter_rsci_idat[79:64]) * (input_rsci_idat[79:64]);
  assign sum_5_sum_mul_1_nl = nl_sum_5_sum_mul_1_nl[15:0];
  assign nl_sum_6_sum_mul_1_nl = (filter_rsci_idat[95:80]) * (input_rsci_idat[95:80]);
  assign sum_6_sum_mul_1_nl = nl_sum_6_sum_mul_1_nl[15:0];
  assign nl_sum_7_sum_mul_1_nl = (filter_rsci_idat[111:96]) * (input_rsci_idat[111:96]);
  assign sum_7_sum_mul_1_nl = nl_sum_7_sum_mul_1_nl[15:0];
  assign nl_acc_14_itm_1  = (sum_4_sum_mul_1_nl) + (sum_5_sum_mul_1_nl) + (sum_6_sum_mul_1_nl)
      + (sum_7_sum_mul_1_nl);
  assign nl_output_rsci_idat  = acc_14_itm_1 + acc_13_itm_1 + acc_12_itm_1;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    conv
// ------------------------------------------------------------------


module conv (
  clk, rst, input_rsc_dat, input_rsc_triosy_lz, output_rsc_dat, output_rsc_triosy_lz,
      filter_rsc_dat, filter_rsc_triosy_lz
);
  input clk;
  input rst;
  input [143:0] input_rsc_dat;
  output input_rsc_triosy_lz;
  output [15:0] output_rsc_dat;
  output output_rsc_triosy_lz;
  input [143:0] filter_rsc_dat;
  output filter_rsc_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  conv_core conv_core_inst (
      .clk(clk),
      .rst(rst),
      .input_rsc_dat(input_rsc_dat),
      .input_rsc_triosy_lz(input_rsc_triosy_lz),
      .output_rsc_dat(output_rsc_dat),
      .output_rsc_triosy_lz(output_rsc_triosy_lz),
      .filter_rsc_dat(filter_rsc_dat),
      .filter_rsc_triosy_lz(filter_rsc_triosy_lz)
    );
endmodule



