-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    10.4a/835166 Production Release
--  HLS Date:       Thu Sep  5 21:35:46 PDT 2019
-- 
--  Generated by:   gel8580@finagle.wot.ece.northwestern.edu
--  Generated date: Mon Dec  1 01:39:50 2025
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    conv_core
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_pkg_v1.ALL;
USE mgc_hls.ccs_out_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;


ENTITY conv_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    input_rsc_dat : IN STD_LOGIC_VECTOR (143 DOWNTO 0);
    input_rsc_triosy_lz : OUT STD_LOGIC;
    output_rsc_dat : OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
    output_rsc_triosy_lz : OUT STD_LOGIC;
    filter_rsc_dat : IN STD_LOGIC_VECTOR (143 DOWNTO 0);
    filter_rsc_triosy_lz : OUT STD_LOGIC
  );
END conv_core;

ARCHITECTURE v3 OF conv_core IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL input_rsci_idat : STD_LOGIC_VECTOR (143 DOWNTO 0);
  SIGNAL output_rsci_idat : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL filter_rsci_idat : STD_LOGIC_VECTOR (143 DOWNTO 0);
  SIGNAL output_rsc_triosy_obj_ld : STD_LOGIC;
  SIGNAL reg_filter_rsc_triosy_obj_ld_cse : STD_LOGIC;
  SIGNAL acc_13_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL acc_12_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL acc_14_itm_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);

  SIGNAL sum_1_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL sum_8_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL sum_9_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL sum_2_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL sum_3_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL sum_4_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL sum_5_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL sum_6_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL sum_7_sum_mul_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL input_rsci_dat : STD_LOGIC_VECTOR (143 DOWNTO 0);
  SIGNAL input_rsci_idat_1 : STD_LOGIC_VECTOR (143 DOWNTO 0);

  SIGNAL output_rsci_idat_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL output_rsci_dat : STD_LOGIC_VECTOR (15 DOWNTO 0);

  SIGNAL filter_rsci_dat : STD_LOGIC_VECTOR (143 DOWNTO 0);
  SIGNAL filter_rsci_idat_1 : STD_LOGIC_VECTOR (143 DOWNTO 0);

BEGIN
  input_rsci : mgc_hls.ccs_in_pkg_v1.ccs_in_v1
    GENERIC MAP(
      rscid => 1,
      width => 144
      )
    PORT MAP(
      dat => input_rsci_dat,
      idat => input_rsci_idat_1
    );
  input_rsci_dat <= input_rsc_dat;
  input_rsci_idat <= input_rsci_idat_1;

  output_rsci : mgc_hls.ccs_out_pkg_v1.ccs_out_v1
    GENERIC MAP(
      rscid => 2,
      width => 16
      )
    PORT MAP(
      idat => output_rsci_idat_1,
      dat => output_rsci_dat
    );
  output_rsci_idat_1 <= output_rsci_idat;
  output_rsc_dat <= output_rsci_dat;

  filter_rsci : mgc_hls.ccs_in_pkg_v1.ccs_in_v1
    GENERIC MAP(
      rscid => 3,
      width => 144
      )
    PORT MAP(
      dat => filter_rsci_dat,
      idat => filter_rsci_idat_1
    );
  filter_rsci_dat <= filter_rsc_dat;
  filter_rsci_idat <= filter_rsci_idat_1;

  input_rsc_triosy_obj : mgc_hls.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_filter_rsc_triosy_obj_ld_cse,
      lz => input_rsc_triosy_lz
    );
  output_rsc_triosy_obj : mgc_hls.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => output_rsc_triosy_obj_ld,
      lz => output_rsc_triosy_lz
    );
  filter_rsc_triosy_obj : mgc_hls.mgc_io_sync_pkg_v2.mgc_io_sync_v2
    GENERIC MAP(
      valid => 0
      )
    PORT MAP(
      ld => reg_filter_rsc_triosy_obj_ld_cse,
      lz => filter_rsc_triosy_lz
    );
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        output_rsc_triosy_obj_ld <= '0';
        acc_13_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        acc_12_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        acc_14_itm_1 <= STD_LOGIC_VECTOR'( "0000000000000000");
        reg_filter_rsc_triosy_obj_ld_cse <= '0';
      ELSE
        output_rsc_triosy_obj_ld <= reg_filter_rsc_triosy_obj_ld_cse;
        acc_13_itm_1 <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(SIGNED(sum_1_sum_mul_1_nl),
            16) + CONV_SIGNED(SIGNED(sum_8_sum_mul_1_nl), 16) + CONV_SIGNED(SIGNED(sum_9_sum_mul_1_nl),
            16), 16));
        acc_12_itm_1 <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(SIGNED(sum_2_sum_mul_1_nl),
            16) + CONV_SIGNED(SIGNED(sum_3_sum_mul_1_nl), 16), 16));
        acc_14_itm_1 <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(SIGNED(sum_4_sum_mul_1_nl),
            16) + CONV_SIGNED(SIGNED(sum_5_sum_mul_1_nl), 16) + CONV_SIGNED(SIGNED(sum_6_sum_mul_1_nl),
            16) + CONV_SIGNED(SIGNED(sum_7_sum_mul_1_nl), 16), 16));
        reg_filter_rsc_triosy_obj_ld_cse <= '1';
      END IF;
    END IF;
  END PROCESS;
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        output_rsci_idat <= STD_LOGIC_VECTOR'( "0000000000000000");
      ELSIF ( reg_filter_rsc_triosy_obj_ld_cse = '1' ) THEN
        output_rsci_idat <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(acc_14_itm_1) + SIGNED(acc_13_itm_1)
            + SIGNED(acc_12_itm_1), 16));
      END IF;
    END IF;
  END PROCESS;
  sum_1_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(15
      DOWNTO 0)) * UNSIGNED(input_rsci_idat(15 DOWNTO 0))), 16));
  sum_8_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(127
      DOWNTO 112)) * UNSIGNED(input_rsci_idat(127 DOWNTO 112))), 16));
  sum_9_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(143
      DOWNTO 128)) * UNSIGNED(input_rsci_idat(143 DOWNTO 128))), 16));
  sum_2_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(31
      DOWNTO 16)) * UNSIGNED(input_rsci_idat(31 DOWNTO 16))), 16));
  sum_3_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(47
      DOWNTO 32)) * UNSIGNED(input_rsci_idat(47 DOWNTO 32))), 16));
  sum_4_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(63
      DOWNTO 48)) * UNSIGNED(input_rsci_idat(63 DOWNTO 48))), 16));
  sum_5_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(79
      DOWNTO 64)) * UNSIGNED(input_rsci_idat(79 DOWNTO 64))), 16));
  sum_6_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(95
      DOWNTO 80)) * UNSIGNED(input_rsci_idat(95 DOWNTO 80))), 16));
  sum_7_sum_mul_1_nl <= STD_LOGIC_VECTOR(CONV_SIGNED(UNSIGNED'( UNSIGNED(filter_rsci_idat(111
      DOWNTO 96)) * UNSIGNED(input_rsci_idat(111 DOWNTO 96))), 16));
END v3;

-- ------------------------------------------------------------------
--  Design Unit:    conv
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.ccs_in_pkg_v1.ALL;
USE mgc_hls.ccs_out_pkg_v1.ALL;
USE mgc_hls.mgc_io_sync_pkg_v2.ALL;


ENTITY conv IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    input_rsc_dat : IN STD_LOGIC_VECTOR (143 DOWNTO 0);
    input_rsc_triosy_lz : OUT STD_LOGIC;
    output_rsc_dat : OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
    output_rsc_triosy_lz : OUT STD_LOGIC;
    filter_rsc_dat : IN STD_LOGIC_VECTOR (143 DOWNTO 0);
    filter_rsc_triosy_lz : OUT STD_LOGIC
  );
END conv;

ARCHITECTURE v3 OF conv IS
  -- Default Constants

  COMPONENT conv_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      input_rsc_dat : IN STD_LOGIC_VECTOR (143 DOWNTO 0);
      input_rsc_triosy_lz : OUT STD_LOGIC;
      output_rsc_dat : OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
      output_rsc_triosy_lz : OUT STD_LOGIC;
      filter_rsc_dat : IN STD_LOGIC_VECTOR (143 DOWNTO 0);
      filter_rsc_triosy_lz : OUT STD_LOGIC
    );
  END COMPONENT;
  SIGNAL conv_core_inst_input_rsc_dat : STD_LOGIC_VECTOR (143 DOWNTO 0);
  SIGNAL conv_core_inst_output_rsc_dat : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL conv_core_inst_filter_rsc_dat : STD_LOGIC_VECTOR (143 DOWNTO 0);

BEGIN
  conv_core_inst : conv_core
    PORT MAP(
      clk => clk,
      rst => rst,
      input_rsc_dat => conv_core_inst_input_rsc_dat,
      input_rsc_triosy_lz => input_rsc_triosy_lz,
      output_rsc_dat => conv_core_inst_output_rsc_dat,
      output_rsc_triosy_lz => output_rsc_triosy_lz,
      filter_rsc_dat => conv_core_inst_filter_rsc_dat,
      filter_rsc_triosy_lz => filter_rsc_triosy_lz
    );
  conv_core_inst_input_rsc_dat <= input_rsc_dat;
  output_rsc_dat <= conv_core_inst_output_rsc_dat;
  conv_core_inst_filter_rsc_dat <= filter_rsc_dat;

END v3;



